import type { MCQ } from "@/lib/mcqBank";

export const discreteMathsMcqBank: MCQ[] = [
  {
    id: "dm-mcq-1",
    question: "What is the truth value of (p ∨ ¬q) → q when p is false and q is false?",
    options: ["True", "False", "Undefined", "It depends on r"],
    correctIndex: 1,
    explanation: "¬q = true, so p∨¬q = false∨true = true. The whole expression is true → q = true → false, which is FALSE.",
  },
  {
    id: "dm-mcq-2",
    question: "Which of these is the contrapositive of \"if it rains, then the ground is wet\"?",
    options: [
      "If the ground is wet, then it rains.",
      "If it doesn't rain, then the ground isn't wet.",
      "If the ground isn't wet, then it doesn't rain.",
      "It rains if and only if the ground is wet.",
    ],
    correctIndex: 2,
    explanation: "The contrapositive of p→q is ¬q→¬p: swap AND negate both sides. Only the contrapositive is guaranteed logically equivalent to the original.",
  },
  {
    id: "dm-mcq-3",
    question: "For the statement ∀x∃y (x+y=0) over the integers, which best describes why it's true?",
    options: [
      "Every x has some y (namely -x) that makes it true",
      "Some single y works for every x",
      "It's true only when x=0",
      "It's never true since it depends on y",
    ],
    correctIndex: 0,
    explanation: "∀x∃y means: for every x, we get to pick a NEW y. Picking y=-x always works, so the statement is true. Swapping to ∃y∀x would be false.",
  },
  {
    id: "dm-mcq-4",
    question: "In a proof by contradiction, what do you assume at the start?",
    options: [
      "The hypothesis of the theorem",
      "The negation of what you're trying to prove",
      "The contrapositive of the conclusion",
      "Nothing — you work forward from axioms only",
    ],
    correctIndex: 1,
    explanation: "Proof by contradiction assumes the OPPOSITE of the desired conclusion, then derives a logical impossibility, which forces the original assumption (the negation) to be false — so the real conclusion must be true.",
  },
  {
    id: "dm-mcq-5",
    question: "What is |P({1,2,3})| — the size of the power set of a 3-element set?",
    options: ["3", "6", "8", "9"],
    correctIndex: 2,
    explanation: "A set with n elements has 2ⁿ subsets. Here n=3, so 2³=8 (including ∅ and the full set itself).",
  },
  {
    id: "dm-mcq-6",
    question: "A function is bijective when it is:",
    options: [
      "Injective only",
      "Surjective only",
      "Both injective and surjective",
      "Neither, but total",
    ],
    correctIndex: 2,
    explanation: "Bijective = injective (one-to-one, no two inputs share an output) AND surjective (onto, every possible output is hit) — this is exactly the condition needed for an inverse function to exist.",
  },
  {
    id: "dm-mcq-7",
    question: "What is the worst-case time complexity of binary search on a sorted array of n elements?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 1,
    explanation: "Binary search discards half the remaining search window with each comparison, so it needs about log₂(n) comparisons in the worst case.",
  },
  {
    id: "dm-mcq-8",
    question: "Which sorting algorithm repeatedly swaps adjacent out-of-order elements, letting the largest value 'bubble' to the end each pass?",
    options: ["Insertion sort", "Merge sort", "Bubble sort", "Binary search"],
    correctIndex: 2,
    explanation: "That's the defining behavior of bubble sort — insertion sort instead grows a sorted prefix, and merge sort divides and conquers rather than doing adjacent swaps.",
  },
  {
    id: "dm-mcq-9",
    question: "In the inductive step of a proof by mathematical induction, what do you assume?",
    options: [
      "P(1) is true",
      "P(k) is true for an arbitrary k, then show P(k+1) follows",
      "P(n) is true for all n simultaneously",
      "Nothing — you just check the basis step",
    ],
    correctIndex: 1,
    explanation: "The inductive hypothesis assumes P(k) holds for some arbitrary k, and the inductive step then proves P(k) ⟹ P(k+1) — together with the basis step, this proves P(n) for all n.",
  },
  {
    id: "dm-mcq-10",
    question: "If you place 10 pigeons into 3 holes, the pigeonhole principle guarantees at least one hole has at least how many pigeons?",
    options: ["2", "3", "4", "10"],
    correctIndex: 2,
    explanation: "The generalized pigeonhole principle guarantees at least ⌈P/H⌉ pigeons in some hole. ⌈10/3⌉ = ⌈3.33⌉ = 4.",
  },
  {
    id: "dm-mcq-11",
    question: "C(5,2), the number of ways to choose 2 items from 5 without regard to order, equals:",
    options: ["10", "20", "5", "25"],
    correctIndex: 0,
    explanation: "C(5,2) = 5!/(2!×3!) = 120/(2×6) = 10.",
  },
  {
    id: "dm-mcq-12",
    question: "A relation R is antisymmetric when:",
    options: [
      "(a,b)∈R always implies (b,a)∈R",
      "(a,a)∈R for every a",
      "(a,b)∈R and (b,a)∈R together force a=b",
      "R contains no pairs at all",
    ],
    correctIndex: 2,
    explanation: "Antisymmetric means you can never have both (a,b) and (b,a) in R unless a=b — it's the opposite spirit of symmetric.",
  },
  {
    id: "dm-mcq-13",
    question: "Which condition guarantees a connected graph has an Euler circuit?",
    options: [
      "Every vertex has even degree",
      "Every vertex has odd degree",
      "The graph is a tree",
      "The graph has exactly one cycle",
    ],
    correctIndex: 0,
    explanation: "A connected graph has an Euler circuit if and only if every vertex has even degree — this is why the Königsberg bridges problem (with odd-degree vertices) has no solution.",
  },
  {
    id: "dm-mcq-14",
    question: "Dijkstra's algorithm, at each step, finalizes the distance to:",
    options: [
      "A random unvisited vertex",
      "The unvisited vertex with the smallest current known distance",
      "The vertex furthest from the start",
      "Every vertex simultaneously",
    ],
    correctIndex: 1,
    explanation: "Dijkstra's greedy step always locks in the closest unvisited vertex next, since its distance can never be improved by any path found later.",
  },
  {
    id: "dm-mcq-15",
    question: "In a binary search tree, where does a new value smaller than the current node go?",
    options: ["Left subtree", "Right subtree", "Becomes the new root", "It can't be inserted"],
    correctIndex: 0,
    explanation: "The BST invariant: smaller values always go left, larger values always go right, at every node in the tree.",
  },
  {
    id: "dm-mcq-16",
    question: "Huffman coding assigns the shortest binary codes to which symbols?",
    options: [
      "The alphabetically first symbols",
      "The most frequent symbols",
      "The least frequent symbols",
      "All symbols get equal-length codes",
    ],
    correctIndex: 1,
    explanation: "Huffman coding merges the least-frequent symbols first, which pushes frequent symbols near the root of the tree — meaning they end up with the shortest codes.",
  },
  {
    id: "dm-mcq-17",
    question: "Prim's and Kruskal's algorithms, run on the same connected weighted graph, always produce:",
    options: [
      "The exact same set of edges",
      "Spanning trees with the same total weight",
      "Completely unrelated results",
      "A cycle, not a tree",
    ],
    correctIndex: 1,
    explanation: "Both are correct minimum spanning tree algorithms, so they're guaranteed to find the SAME minimum total weight — though the specific edges chosen along the way can differ, especially when there are weight ties.",
  },
];
