import type { MCQ } from "@/lib/mcqBank";

export const discreteMathsMcqBank: MCQ[] = [
  {
    id: "dm-mcq-1",
    question: "What is the truth value of (p ∨ ¬q) → q when p is false and q is false?",
    options: ["True", "False", "Undefined", "It depends on r"],
    correctIndex: 1,
    explanation: "¬q = true, so p∨¬q = false∨true = true. The whole expression is true → q = true → false, which is FALSE.",
  },
  {
    id: "dm-mcq-2",
    question: "Which of these is the contrapositive of \"if it rains, then the ground is wet\"?",
    options: [
      "If the ground is wet, then it rains.",
      "If it doesn't rain, then the ground isn't wet.",
      "If the ground isn't wet, then it doesn't rain.",
      "It rains if and only if the ground is wet.",
    ],
    correctIndex: 2,
    explanation: "The contrapositive of p→q is ¬q→¬p: swap AND negate both sides. Only the contrapositive is guaranteed logically equivalent to the original.",
  },
  {
    id: "dm-mcq-3",
    question: "For the statement ∀x∃y (x+y=0) over the integers, which best describes why it's true?",
    options: [
      "Every x has some y (namely -x) that makes it true",
      "Some single y works for every x",
      "It's true only when x=0",
      "It's never true since it depends on y",
    ],
    correctIndex: 0,
    explanation: "∀x∃y means: for every x, we get to pick a NEW y. Picking y=-x always works, so the statement is true. Swapping to ∃y∀x would be false.",
  },
  {
    id: "dm-mcq-4",
    question: "In a proof by contradiction, what do you assume at the start?",
    options: [
      "The hypothesis of the theorem",
      "The negation of what you're trying to prove",
      "The contrapositive of the conclusion",
      "Nothing — you work forward from axioms only",
    ],
    correctIndex: 1,
    explanation: "Proof by contradiction assumes the OPPOSITE of the desired conclusion, then derives a logical impossibility, which forces the original assumption (the negation) to be false — so the real conclusion must be true.",
  },
  {
    id: "dm-mcq-5",
    question: "What is |P({1,2,3})| — the size of the power set of a 3-element set?",
    options: ["3", "6", "8", "9"],
    correctIndex: 2,
    explanation: "A set with n elements has 2ⁿ subsets. Here n=3, so 2³=8 (including ∅ and the full set itself).",
  },
  {
    id: "dm-mcq-6",
    question: "A function is bijective when it is:",
    options: [
      "Injective only",
      "Surjective only",
      "Both injective and surjective",
      "Neither, but total",
    ],
    correctIndex: 2,
    explanation: "Bijective = injective (one-to-one, no two inputs share an output) AND surjective (onto, every possible output is hit) — this is exactly the condition needed for an inverse function to exist.",
  },
  {
    id: "dm-mcq-7",
    question: "What is the worst-case time complexity of binary search on a sorted array of n elements?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 1,
    explanation: "Binary search discards half the remaining search window with each comparison, so it needs about log₂(n) comparisons in the worst case.",
  },
  {
    id: "dm-mcq-8",
    question: "Which sorting algorithm repeatedly swaps adjacent out-of-order elements, letting the largest value 'bubble' to the end each pass?",
    options: ["Insertion sort", "Merge sort", "Bubble sort", "Binary search"],
    correctIndex: 2,
    explanation: "That's the defining behavior of bubble sort — insertion sort instead grows a sorted prefix, and merge sort divides and conquers rather than doing adjacent swaps.",
  },
  {
    id: "dm-mcq-9",
    question: "In the inductive step of a proof by mathematical induction, what do you assume?",
    options: [
      "P(1) is true",
      "P(k) is true for an arbitrary k, then show P(k+1) follows",
      "P(n) is true for all n simultaneously",
      "Nothing — you just check the basis step",
    ],
    correctIndex: 1,
    explanation: "The inductive hypothesis assumes P(k) holds for some arbitrary k, and the inductive step then proves P(k) ⟹ P(k+1) — together with the basis step, this proves P(n) for all n.",
  },
  {
    id: "dm-mcq-10",
    question: "If you place 10 pigeons into 3 holes, the pigeonhole principle guarantees at least one hole has at least how many pigeons?",
    options: ["2", "3", "4", "10"],
    correctIndex: 2,
    explanation: "The generalized pigeonhole principle guarantees at least ⌈P/H⌉ pigeons in some hole. ⌈10/3⌉ = ⌈3.33⌉ = 4.",
  },
  {
    id: "dm-mcq-11",
    question: "C(5,2), the number of ways to choose 2 items from 5 without regard to order, equals:",
    options: ["10", "20", "5", "25"],
    correctIndex: 0,
    explanation: "C(5,2) = 5!/(2!×3!) = 120/(2×6) = 10.",
  },
  {
    id: "dm-mcq-12",
    question: "A relation R is antisymmetric when:",
    options: [
      "(a,b)∈R always implies (b,a)∈R",
      "(a,a)∈R for every a",
      "(a,b)∈R and (b,a)∈R together force a=b",
      "R contains no pairs at all",
    ],
    correctIndex: 2,
    explanation: "Antisymmetric means you can never have both (a,b) and (b,a) in R unless a=b — it's the opposite spirit of symmetric.",
  },
  {
    id: "dm-mcq-13",
    question: "Which condition guarantees a connected graph has an Euler circuit?",
    options: [
      "Every vertex has even degree",
      "Every vertex has odd degree",
      "The graph is a tree",
      "The graph has exactly one cycle",
    ],
    correctIndex: 0,
    explanation: "A connected graph has an Euler circuit if and only if every vertex has even degree — this is why the Königsberg bridges problem (with odd-degree vertices) has no solution.",
  },
  {
    id: "dm-mcq-14",
    question: "Dijkstra's algorithm, at each step, finalizes the distance to:",
    options: [
      "A random unvisited vertex",
      "The unvisited vertex with the smallest current known distance",
      "The vertex furthest from the start",
      "Every vertex simultaneously",
    ],
    correctIndex: 1,
    explanation: "Dijkstra's greedy step always locks in the closest unvisited vertex next, since its distance can never be improved by any path found later.",
  },
  {
    id: "dm-mcq-15",
    question: "In a binary search tree, where does a new value smaller than the current node go?",
    options: ["Left subtree", "Right subtree", "Becomes the new root", "It can't be inserted"],
    correctIndex: 0,
    explanation: "The BST invariant: smaller values always go left, larger values always go right, at every node in the tree.",
  },
  {
    id: "dm-mcq-16",
    question: "Huffman coding assigns the shortest binary codes to which symbols?",
    options: [
      "The alphabetically first symbols",
      "The most frequent symbols",
      "The least frequent symbols",
      "All symbols get equal-length codes",
    ],
    correctIndex: 1,
    explanation: "Huffman coding merges the least-frequent symbols first, which pushes frequent symbols near the root of the tree — meaning they end up with the shortest codes.",
  },
  {
    id: "dm-mcq-17",
    question: "Prim's and Kruskal's algorithms, run on the same connected weighted graph, always produce:",
    options: [
      "The exact same set of edges",
      "Spanning trees with the same total weight",
      "Completely unrelated results",
      "A cycle, not a tree",
    ],
    correctIndex: 1,
    explanation: "Both are correct minimum spanning tree algorithms, so they're guaranteed to find the SAME minimum total weight — though the specific edges chosen along the way can differ, especially when there are weight ties.",
  },

  // ---------- Computer Science Foundations (discrete math as the theory behind CS) ----------
  {
    id: "dm-mcq-cs-1",
    question: "Boolean algebra (AND, OR, NOT) is the mathematical foundation directly used to design:",
    options: ["Digital logic circuits and computer hardware", "Sorting algorithms only", "Wireless signal modulation", "Compiler syntax highlighting"],
    correctIndex: 0,
    explanation: "Every logic gate in a CPU — AND gates, OR gates, NOT gates, and everything built from them — is a direct physical implementation of Boolean algebra.",
  },
  {
    id: "dm-mcq-cs-2",
    question: "How many distinct Boolean functions exist on 3 input variables (i.e., how many different 3-variable truth tables are possible)?",
    options: ["256", "8", "64", "512"],
    correctIndex: 0,
    explanation: "A function on n variables has 2ⁿ input rows, and each row can independently be assigned True or False, giving 2^(2ⁿ) possible functions. For n=3: 2^(2³) = 2⁸ = 256.",
  },
  {
    id: "dm-mcq-cs-3",
    question: "A finite-state automaton (used to recognize regular languages, and the basis of regex engines) is fundamentally which discrete-math structure with labelled transitions?",
    options: ["A directed graph — states as nodes, transitions as labelled edges", "An unordered set with no structure", "A continuous function", "A matrix of real numbers only"],
    correctIndex: 0,
    explanation: "A finite automaton's states and transitions map directly onto a directed graph: each state is a node, and each transition (on a given input symbol) is a labelled directed edge to the next state.",
  },
  {
    id: "dm-mcq-cs-4",
    question: "Solving the recurrence T(n) = 2T(n/2) + n — the running time of merge sort — gives:",
    options: ["O(n log n)", "O(n²)", "O(n)", "O(2ⁿ)"],
    correctIndex: 0,
    explanation: "This recurrence splits the problem into 2 halves (2T(n/2)) and does O(n) extra work to merge — the classic divide-and-conquer pattern that the Master Theorem resolves to O(n log n).",
  },
  {
    id: "dm-mcq-cs-5",
    question: "Solving the recurrence T(n) = T(n/2) + O(1) — the running time of binary search — gives:",
    options: ["O(log n)", "O(n)", "O(n log n)", "O(1)"],
    correctIndex: 0,
    explanation: "Each step does constant work and shrinks the problem to half its size; the number of halvings needed to reduce n down to 1 is log₂(n) — hence O(log n).",
  },
  {
    id: "dm-mcq-cs-6",
    question: "If you insert 13 items into a hash table with only 12 buckets, the pigeonhole principle guarantees:",
    options: ["At least one bucket contains two or more items — a collision", "Every bucket contains exactly one item", "No collisions are possible", "The hash table automatically resizes itself"],
    correctIndex: 0,
    explanation: "The pigeonhole principle: if you place more items (13 pigeons) than there are containers (12 holes), at least one container must hold more than one item — exactly why hash tables must have a collision-resolution strategy.",
  },
  {
    id: "dm-mcq-cs-7",
    question: "RSA public-key encryption, one of the most widely used cryptosystems, is built directly on discrete-math concepts from:",
    options: ["Modular arithmetic and number theory (primes, Euler's totient function)", "Graph theory only", "Boolean algebra only", "Set theory only"],
    correctIndex: 0,
    explanation: "RSA's security and correctness both rest on number theory: choosing large primes, computing Euler's totient φ(n), and using modular exponentiation for encryption/decryption.",
  },
  {
    id: "dm-mcq-cs-8",
    question: "In a tiny RSA example with primes p=3, q=11 (so n=33, φ(n)=20), if the public exponent is e=3, which of these is a valid private exponent d satisfying e·d ≡ 1 (mod φ(n))?",
    options: ["7", "3", "11", "20"],
    correctIndex: 0,
    explanation: "3 × 7 = 21, and 21 mod 20 = 1, so d=7 satisfies e·d ≡ 1 (mod φ(n)) — exactly the modular-inverse condition RSA's key generation relies on.",
  },
  {
    id: "dm-mcq-cs-9",
    question: "Mathematical induction is the direct theoretical basis for which common technique used to verify an algorithm (e.g., a loop) is correct?",
    options: ["Proving a loop invariant holds before the loop, after each iteration, and implies correctness once the loop ends", "Testing the code on a few sample inputs only", "Measuring the program's execution time", "Reading the code's comments"],
    correctIndex: 0,
    explanation: "Loop-invariant proofs mirror induction exactly: establish the invariant before the first iteration (base case), show each iteration preserves it (inductive step), then argue that the invariant plus the loop's exit condition implies correctness.",
  },
  {
    id: "dm-mcq-cs-10",
    question: "Kruskal's and Prim's algorithms both solve the same discrete-math graph problem. Which one?",
    options: ["Finding a minimum spanning tree", "Finding the chromatic number of a graph", "Determining if a graph is bipartite", "Finding an Eulerian circuit"],
    correctIndex: 0,
    explanation: "Both are classic greedy algorithms for the minimum spanning tree problem: connecting all vertices with the least total edge weight and no cycles.",
  },
  {
    id: "dm-mcq-cs-11",
    question: "Graph colouring (assigning colours to vertices so adjacent vertices differ) has a well-known application in compiler design:",
    options: ["Register allocation — assigning a limited number of CPU registers so that no two variables \"live\" at the same time share one", "Sorting an array", "Parsing regular expressions", "Rendering 3D graphics"],
    correctIndex: 0,
    explanation: "Compilers model variables that are simultaneously in use as a graph (an edge means \"these two are live at the same time\") and colour it with as many colours as there are registers — adjacent (conflicting) variables can never get the same register.",
  },
  {
    id: "dm-mcq-cs-12",
    question: "How many structurally distinct binary search trees can be built from 3 distinct keys?",
    options: ["5", "3", "6", "8"],
    correctIndex: 0,
    explanation: "The number of distinct BST shapes on n keys is the nth Catalan number. For n=3, C₃ = 5 — you can verify this by actually enumerating all the shapes with each key as the root.",
  },
  {
    id: "dm-mcq-cs-13",
    question: "The relational database model (as in SQL) is directly built on which discrete-math structure?",
    options: ["Relations (subsets of a Cartesian product) from set theory", "Boolean circuits", "Graph colourings", "Recurrence relations"],
    correctIndex: 0,
    explanation: "A database \"relation\" (table) is literally a mathematical relation: a subset of the Cartesian product of its columns' domains — the term isn't a coincidence, it's where the model gets its name.",
  },
  {
    id: "dm-mcq-cs-14",
    question: "For an encryption function to be reversible (decryptable), it must be, in discrete-math terms:",
    options: ["A bijection (one-to-one and onto) — every plaintext maps to a unique ciphertext and back", "Any function at all", "A function that is undefined for some inputs", "A many-to-one function"],
    correctIndex: 0,
    explanation: "If two different plaintexts ever mapped to the same ciphertext (not injective), decryption would be ambiguous. If some ciphertext had no corresponding plaintext (not surjective onto the ciphertext space), decryption could fail — reversibility requires a true bijection.",
  },
  {
    id: "dm-mcq-cs-15",
    question: "An 8-character password using only lowercase letters (26 choices per character, repetition allowed) has how many possible combinations, by the multiplication principle?",
    options: ["26⁸", "26 × 8", "8!", "C(26, 8)"],
    correctIndex: 0,
    explanation: "Each of the 8 positions independently has 26 choices, and positions are distinguishable with repetition allowed, so the multiplication principle gives 26 × 26 × ... (8 times) = 26⁸ — not a combination, since order matters and repeats are allowed.",
  },
  {
    id: "dm-mcq-cs-16",
    question: "Brute-force search through all possible n-character passwords over an alphabet of size k has time complexity:",
    options: ["O(kⁿ) — exponential in n", "O(n) — linear", "O(log n)", "O(n²)"],
    correctIndex: 0,
    explanation: "There are kⁿ possible strings to try, and checking each one takes at least constant time, so brute force is O(kⁿ) — exponential growth in the password length is exactly why longer passwords are so much harder to crack.",
  },
  {
    id: "dm-mcq-cs-17",
    question: "The Boolean Satisfiability Problem (SAT) — deciding whether some assignment of truth values makes a propositional logic formula true — is significant in computer science because it was the first problem proven to be:",
    options: ["NP-complete", "Solvable in constant time", "Undecidable", "Always false"],
    correctIndex: 0,
    explanation: "The Cook-Levin theorem (1971) proved SAT is NP-complete — every problem in NP can be reduced to it — making SAT the foundational problem for the entire theory of NP-completeness.",
  },
  {
    id: "dm-mcq-cs-18",
    question: "In SQL, the UNION and INTERSECT operators directly correspond to which discrete-math set operations?",
    options: ["Set union (∪) and set intersection (∩)", "Set complement and power set", "Cartesian product and function composition", "Symmetric difference only"],
    correctIndex: 0,
    explanation: "SQL's set operators are named after — and behave exactly like — the set-theory operations of union and intersection applied to the rows of two result sets.",
  },
  {
    id: "dm-mcq-cs-19",
    question: "The Union-Find (disjoint-set) data structure, used in Kruskal's algorithm and cycle detection, directly implements which discrete-math concept?",
    options: ["Equivalence relations partitioning a set into disjoint equivalence classes", "Boolean algebra only", "A single linear order", "A continuous function"],
    correctIndex: 0,
    explanation: "Union-Find maintains a partition of elements into disjoint groups (\"which set am I in?\"), exactly mirroring how an equivalence relation partitions a set into disjoint equivalence classes.",
  },
  {
    id: "dm-mcq-cs-20",
    question: "Breadth-first search (BFS) on a graph explores vertices in order of:",
    options: ["Increasing distance (number of edges) from the starting vertex", "Alphabetical order of vertex labels", "Random order", "Decreasing degree of each vertex"],
    correctIndex: 0,
    explanation: "BFS processes vertices level by level using a queue, so it visits all vertices at distance 1 from the start before any at distance 2, and so on — which is exactly why BFS finds shortest paths in unweighted graphs.",
  },
  {
    id: "dm-mcq-cs-21",
    question: "A tree with n vertices always has exactly how many edges?",
    options: ["n − 1", "n", "n + 1", "2n"],
    correctIndex: 0,
    explanation: "A tree is defined as a connected, acyclic graph. Adding any edge beyond n−1 to a connected graph on n vertices necessarily creates a cycle, and fewer than n−1 edges can't keep it connected — so n−1 is exact, and CS algorithms use this to sanity-check tree structures.",
  },
  {
    id: "dm-mcq-cs-22",
    question: "Checking every row of the truth table for a Boolean formula with n variables to determine satisfiability takes time:",
    options: ["O(2ⁿ) — exponential, since there are 2ⁿ possible truth assignments", "O(n) — linear", "O(n log n)", "O(1)"],
    correctIndex: 0,
    explanation: "A truth table has one row per possible assignment of the n variables, and there are 2ⁿ such assignments — brute-force satisfiability checking is exponential, which is exactly why SAT solvers rely on much cleverer techniques in practice.",
  },
  {
    id: "dm-mcq-cs-23",
    question: "The pigeonhole principle guarantees that any hash function mapping a very large input space to a fixed-size output (like a 256-bit hash) must have:",
    options: ["Collisions — distinct inputs mapping to the same output — even if finding one is computationally hard", "No collisions ever", "At least one input with no valid hash", "Output values that grow with the input size"],
    correctIndex: 0,
    explanation: "If the input space is larger than the (fixed) output space, pigeonhole guarantees collisions must exist mathematically. Cryptographic hash security doesn't rely on collisions being impossible — only on them being computationally infeasible to find.",
  },
  {
    id: "dm-mcq-cs-24",
    question: "A common algorithmic trick to enumerate all subsets of an n-element set is to loop through every integer from 0 to 2ⁿ−1 and treat each bit as \"included/excluded.\" This works because:",
    options: ["There are exactly 2ⁿ subsets of an n-element set, matching exactly the 2ⁿ possible n-bit binary numbers", "There are only n subsets of an n-element set", "Bits can only represent even numbers", "Subsets must always be sorted first"],
    correctIndex: 0,
    explanation: "The power set of an n-element set has 2ⁿ elements (each element is either in or out — 2 choices, n times). That's exactly the count of n-bit binary numbers, giving a clean one-to-one correspondence between bit patterns and subsets.",
  },
  {
    id: "dm-mcq-cs-25",
    question: "A recursively defined sequence like the Fibonacci numbers directly parallels which fundamental programming technique?",
    options: ["A recursive function that calls itself with a smaller input, plus one or more base cases", "An iterative loop that never terminates", "A sorting algorithm", "A hash table lookup"],
    correctIndex: 0,
    explanation: "A recursive definition (base case(s) plus a rule building larger values from smaller ones) translates almost line-for-line into a recursive function — the mathematical and programming ideas are the same structure.",
  },
  {
    id: "dm-mcq-cs-26",
    question: "A connected graph has an Eulerian circuit (a walk using every edge exactly once, returning to the start) if and only if:",
    options: ["Every vertex has even degree", "Every vertex has odd degree", "The graph has exactly one vertex", "The graph is a tree"],
    correctIndex: 0,
    explanation: "Euler's theorem: a connected graph has an Eulerian circuit exactly when every vertex has even degree — each visit to a vertex uses one edge in and one edge out, so an odd-degree vertex would leave one edge unmatched.",
  },
  {
    id: "dm-mcq-cs-27",
    question: "The proven lower bound of Ω(n log n) comparisons for any comparison-based sorting algorithm comes from a counting argument: there are n! possible orderings of n elements, and:",
    options: ["A binary decision tree distinguishing all n! outcomes needs at least log₂(n!) ≈ n log n levels (comparisons)", "There are only n possible orderings, so 1 comparison always suffices", "Sorting always requires exactly n² comparisons", "The bound applies only to already-sorted arrays"],
    correctIndex: 0,
    explanation: "Model any comparison sort as a binary decision tree: each comparison is one branch, and the tree must have at least n! leaves (one per possible ordering). A binary tree with n! leaves needs depth at least log₂(n!), which by Stirling's approximation is Θ(n log n).",
  },
  {
    id: "dm-mcq-cs-28",
    question: "In code, negating the condition !(a && b) is equivalent to !a || !b — this is a direct application of:",
    options: ["De Morgan's laws", "The Pythagorean theorem", "The pigeonhole principle", "L'Hôpital's rule"],
    correctIndex: 0,
    explanation: "De Morgan's laws state ¬(p∧q) ≡ ¬p∨¬q and ¬(p∨q) ≡ ¬p∧¬q — exactly the identity programmers use (often without realizing it) every time they negate a compound boolean condition.",
  },
  {
    id: "dm-mcq-cs-29",
    question: "Topological sorting (used e.g. to order compilation of files with dependencies, or task scheduling) is only possible on a graph that is:",
    options: ["A directed acyclic graph (DAG)", "Any undirected graph", "A complete graph", "A tree with exactly one leaf"],
    correctIndex: 0,
    explanation: "A topological order requires that every dependency comes before what depends on it. A cycle would create a contradiction (A must come before B, which must come before A), so a valid topological ordering only exists for directed acyclic graphs.",
  },
  {
    id: "dm-mcq-cs-30",
    question: "The precise mathematical definitions behind P vs NP — arguably computer science's most famous open problem — rest on discrete-math foundations from:",
    options: ["Set theory, logic, and the formal theory of computation (automata/complexity theory)", "Calculus and continuous functions", "Statistics and probability distributions alone", "Linear algebra matrix decompositions"],
    correctIndex: 0,
    explanation: "P vs NP is formalized using discrete structures: languages as sets of strings, Turing machines as formal automata, and reductions defined via logic — the entire theory of computation is built on discrete, not continuous, mathematics.",
  },
];
