export interface QuizStep {
  statement: string;
  reason: string;
}

export type QuizDifficulty = "hard" | "medium" | "easy";
export type QuizType = "mcq" | "fill-in";

export interface QuizQuestion {
  id: string;
  concept: string;
  difficulty: QuizDifficulty;
  type: QuizType;
  question: string;
  code?: string;
  options?: string[];
  correctIndex?: number;
  acceptableAnswers?: string[];
  steps?: QuizStep[];
  explanation: string;
}

export const quizConcepts: { id: string; label: string }[] = [
  { id: "propositional-logic", label: "Propositional Logic" },
  { id: "quantifiers-inference", label: "Quantifiers & Inference" },
  { id: "proof-techniques", label: "Proof Techniques" },
  { id: "sets", label: "Sets & Set Operations" },
  { id: "functions-sequences", label: "Functions & Sequences" },
  { id: "algorithms", label: "Algorithms" },
  { id: "induction-recursion", label: "Induction & Recursion" },
  { id: "counting", label: "Counting" },
  { id: "relations", label: "Relations" },
  { id: "graphs", label: "Graphs" },
  { id: "trees", label: "Trees" },
];

export const discreteMathsQuizBank: QuizQuestion[] = [
  // Propositional Logic
  {
    id: "pl-1",
    concept: "propositional-logic",
    difficulty: "hard",
    type: "mcq",
    question: "Which expression is logically equivalent to p → q?",
    options: ["¬p ∨ q", "¬p ∧ q", "p ∧ ¬q", "¬q → p"],
    correctIndex: 0,
    steps: [
      { statement: "p → q is only FALSE in exactly one case: p=T, q=F.", reason: "Definition of the conditional" },
      { statement: "¬p ∨ q is FALSE only when ¬p=F and q=F, i.e. p=T and q=F.", reason: "Definition of OR — false only when both sides are false" },
      { statement: "Both expressions are false in exactly the same single case (p=T, q=F), and true everywhere else.", reason: "Matching truth tables means logical equivalence" },
    ],
    explanation: "p → q ≡ ¬p ∨ q is one of the most useful equivalences in discrete math — it lets you rewrite any conditional using only ∨ and ¬.",
  },
  {
    id: "pl-2",
    concept: "propositional-logic",
    difficulty: "hard",
    type: "fill-in",
    question: "Is (p ∧ q) → (p ∨ q) a tautology, a contradiction, or a contingency? Type one word.",
    acceptableAnswers: ["tautology"],
    steps: [
      { statement: "Suppose p ∧ q is true. Then both p and q are true, so p ∨ q must also be true.", reason: "If both p and q hold, either one alone certainly holds" },
      { statement: "So whenever the hypothesis (p ∧ q) is true, the conclusion (p ∨ q) is also true.", reason: "The only way a conditional is false is a true hypothesis with a false conclusion — that never happens here" },
      { statement: "When p ∧ q is false, the conditional is automatically true regardless of p ∨ q.", reason: "A false hypothesis makes any conditional true" },
    ],
    explanation: "The expression is true for every possible combination of p and q, so it's a tautology.",
  },
  {
    id: "pl-6",
    concept: "propositional-logic",
    difficulty: "hard",
    type: "mcq",
    question: "Which of these correctly applies the distributive law to p ∧ (q ∨ r)?",
    options: ["(p ∧ q) ∨ (p ∧ r)", "(p ∨ q) ∧ (p ∨ r)", "p ∧ q ∨ r", "¬(p ∨ q) ∧ r"],
    correctIndex: 0,
    steps: [
      { statement: "Distribute the ∧ over each term inside the parentheses individually.", reason: "Apply the pattern a ∧ (b ∨ c) = (a ∧ b) ∨ (a ∧ c)" },
      { statement: "This produces p ∧ q for the first term and p ∧ r for the second, joined by ∨.", reason: "Write out the fully distributed form" },
    ],
    explanation: "p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r) — the mirror image of the more familiar p ∨ (q ∧ r) ≡ (p ∨ q) ∧ (p ∨ r).",
  },
  {
    id: "pl-3",
    concept: "propositional-logic",
    difficulty: "medium",
    type: "mcq",
    question: "¬(p → q) is logically equivalent to:",
    options: ["p ∧ ¬q", "¬p ∨ q", "¬p ∧ ¬q", "p ∨ ¬q"],
    correctIndex: 0,
    steps: [
      { statement: "p → q ≡ ¬p ∨ q, so ¬(p → q) ≡ ¬(¬p ∨ q).", reason: "Start from the known equivalence for the conditional" },
      { statement: "By De Morgan's law, ¬(¬p ∨ q) = ¬¬p ∧ ¬q = p ∧ ¬q.", reason: "Apply De Morgan's law, then cancel the double negation" },
    ],
    explanation: "Since p → q ≡ ¬p ∨ q, negating both sides gives ¬(¬p ∨ q) ≡ p ∧ ¬q by De Morgan's law.",
  },
  {
    id: "pl-7",
    concept: "propositional-logic",
    difficulty: "medium",
    type: "fill-in",
    question: "Evaluate p ↔ q when p = False and q = False. Type True or False.",
    acceptableAnswers: ["true", "t"],
    steps: [
      { statement: "↔ is true exactly when both sides have the same truth value.", reason: "Definition of the biconditional" },
      { statement: "p = False and q = False — both sides match.", reason: "Compare the two given values" },
    ],
    explanation: "Both sides are false, and ↔ is true whenever the two sides agree — so the result is True.",
  },
  {
    id: "pl-8",
    concept: "propositional-logic",
    difficulty: "medium",
    type: "mcq",
    question: "Which pair matches De Morgan's law exactly?",
    options: [
      "¬(p ∨ q) and ¬p ∧ ¬q",
      "¬(p ∨ q) and ¬p ∨ ¬q",
      "p ∨ q and ¬p ∧ ¬q",
      "¬(p ∧ q) and ¬p ∧ ¬q",
    ],
    correctIndex: 0,
    steps: [
      { statement: "De Morgan's law states ¬(p ∨ q) ≡ ¬p ∧ ¬q (and symmetrically ¬(p ∧ q) ≡ ¬p ∨ ¬q).", reason: "Recall the law directly" },
      { statement: "None of the other three pairings match either version of the law exactly.", reason: "Eliminate the distractors by checking each" },
    ],
    explanation: "¬(p ∨ q) ≡ ¬p ∧ ¬q is the correct De Morgan's pairing — negating an OR flips it into an AND of negations.",
  },
  {
    id: "pl-4",
    concept: "propositional-logic",
    difficulty: "easy",
    type: "fill-in",
    question: "Evaluate ¬(T ∧ F). Type True or False.",
    acceptableAnswers: ["true", "t"],
    steps: [
      { statement: "T ∧ F = F.", reason: "AND is true only when both sides are true" },
      { statement: "¬F = True.", reason: "Negating false gives true" },
    ],
    explanation: "T ∧ F = F, and ¬F = True.",
  },
  {
    id: "pl-5",
    concept: "propositional-logic",
    difficulty: "easy",
    type: "mcq",
    question: "Which symbol represents logical OR?",
    options: ["∧", "∨", "¬", "→"],
    correctIndex: 1,
    steps: [
      { statement: "∧ is AND, ¬ is NOT, and → is the conditional — none of those mean OR.", reason: "Eliminate the other three by their known meanings" },
      { statement: "∨ is the one remaining symbol, and it is indeed OR.", reason: "Confirm by elimination" },
    ],
    explanation: "∨ is OR (true if either or both sides are true), ∧ is AND, ¬ is NOT, and → is the conditional.",
  },

  // Quantifiers & Inference
  {
    id: "qi-1",
    concept: "quantifiers-inference",
    difficulty: "hard",
    type: "mcq",
    question: "What is the correct negation of ∀x P(x)?",
    options: ["∃x ¬P(x)", "∀x ¬P(x)", "¬∃x P(x)", "∃x P(x)"],
    correctIndex: 0,
    steps: [
      { statement: "∀x P(x) says every x satisfies P.", reason: "Definition of the universal quantifier" },
      { statement: "For this to be FALSE, at least one x must fail to satisfy P — that's exactly ∃x ¬P(x).", reason: "Negating 'every x works' means 'some x doesn't work'" },
    ],
    explanation: "Negating a quantifier flips it AND negates the predicate: ¬∀x P(x) ≡ ∃x ¬P(x) (and symmetrically ¬∃x P(x) ≡ ∀x ¬P(x)).",
  },
  {
    id: "qi-2",
    concept: "quantifiers-inference",
    difficulty: "hard",
    type: "fill-in",
    question: "Given premises p → q and ¬q, what can you validly conclude by modus tollens? (type using ¬ or 'not p')",
    acceptableAnswers: ["¬p", "not p", "-p", "!p"],
    steps: [
      { statement: "Modus tollens: from p→q and ¬q, conclude ¬p.", reason: "If q were false, then p can't be true, since p→q would be violated" },
    ],
    explanation: "Modus tollens is the 'contrapositive in action' rule — it's exactly why disproving the consequent disproves the hypothesis.",
  },
  {
    id: "qi-6",
    concept: "quantifiers-inference",
    difficulty: "hard",
    type: "mcq",
    question: "Why is 'some cats are black; some black things are cars; therefore some cats are cars' an invalid argument?",
    options: [
      "Each ∃ statement may refer to a different example — nothing forces the same black thing to be both a cat and a car",
      "It's valid by hypothetical syllogism",
      "It's valid by universal instantiation",
      "It's valid by modus ponens",
    ],
    correctIndex: 0,
    steps: [
      { statement: "'Some cats are black' and 'some black things are cars' each only guarantee ONE example exists — possibly a different one each time.", reason: "Unpack exactly what ∃ guarantees" },
      { statement: "Nothing forces the same black thing to be both a cat and a car.", reason: "Identify the missing link in the argument" },
      { statement: "So the conclusion doesn't follow — this is an invalid chaining of existential statements.", reason: "State the fallacy" },
    ],
    explanation: "Existential statements can't be chained together like universal ones — each ∃ might be talking about a completely different witness.",
  },
  {
    id: "qi-3",
    concept: "quantifiers-inference",
    difficulty: "medium",
    type: "mcq",
    question: "Which inference rule concludes q directly from p and p → q?",
    options: ["Modus ponens", "Modus tollens", "Hypothetical syllogism", "Disjunctive syllogism"],
    correctIndex: 0,
    steps: [
      { statement: "p is given true, and p → q is given true.", reason: "State the two premises" },
      { statement: "Modus ponens directly concludes q from exactly these two premises.", reason: "Apply the rule's definition" },
    ],
    explanation: "Modus ponens: p is true, p→q is true, so q must be true — the most commonly used rule of inference.",
  },
  {
    id: "qi-4",
    concept: "quantifiers-inference",
    difficulty: "medium",
    type: "fill-in",
    question: "Over the integers, is ∃x (x² = 4) true or false? Type True or False.",
    acceptableAnswers: ["true", "t"],
    steps: [{ statement: "Try x = 2: 2² = 4. A working value exists.", reason: "∃ just needs ONE example to succeed" }],
    explanation: "x=2 (or x=-2) satisfies x²=4, so the existential statement is true — only one witness is needed.",
  },
  {
    id: "qi-7",
    concept: "quantifiers-inference",
    difficulty: "medium",
    type: "fill-in",
    question: "Over the positive integers, is ∀x (x + 1 > x) true or false? Type True or False.",
    acceptableAnswers: ["true", "t"],
    steps: [
      { statement: "For any positive integer x, adding 1 always makes it strictly bigger.", reason: "Reason about the general case" },
      { statement: "This holds for every single x with no exceptions.", reason: "Confirm the statement is universal" },
    ],
    explanation: "There's no positive integer for which x+1 fails to exceed x, so the universal statement is true.",
  },
  {
    id: "qi-8",
    concept: "quantifiers-inference",
    difficulty: "medium",
    type: "mcq",
    question: "Hypothetical syllogism concludes p → r from which two premises?",
    options: ["p → q and q → r", "p → q and r → q", "q → p and q → r", "p → q and ¬q"],
    correctIndex: 0,
    steps: [
      { statement: "Hypothetical syllogism chains two conditionals that share a middle term (q).", reason: "Recall the rule's pattern" },
      { statement: "p → q and q → r chain directly into p → r.", reason: "Apply the chaining" },
    ],
    explanation: "Hypothetical syllogism links two conditionals through their shared middle term, like a domino chain.",
  },
  {
    id: "qi-5",
    concept: "quantifiers-inference",
    difficulty: "easy",
    type: "mcq",
    question: "What does ∃ mean?",
    options: ["For all", "There exists", "Not", "And"],
    correctIndex: 1,
    steps: [
      { statement: "∀ means 'for all' — that's a different symbol.", reason: "Eliminate by definition" },
      { statement: "∃ is the remaining quantifier, meaning 'there exists'.", reason: "Confirm by elimination" },
    ],
    explanation: "∃ is the existential quantifier — 'there exists at least one'. ∀ is 'for all'.",
  },

  // Proof Techniques
  {
    id: "pt-1",
    concept: "proof-techniques",
    difficulty: "hard",
    type: "mcq",
    question: "A proof that assumes the negation of the conclusion and derives an impossibility is called:",
    options: ["Direct proof", "Proof by contradiction", "Proof by induction", "Proof by cases"],
    correctIndex: 1,
    steps: [
      { statement: "Direct proof assumes the hypothesis and derives the conclusion directly — that's not this.", reason: "Eliminate direct proof" },
      { statement: "Induction and cases don't involve assuming the negation of the conclusion.", reason: "Eliminate the other two distractors" },
      { statement: "Only 'proof by contradiction' matches assuming ¬conclusion and deriving an impossibility.", reason: "Confirm the correct technique" },
    ],
    explanation: "Proof by contradiction: assume ¬conclusion, show it leads somewhere impossible, so the conclusion must actually be true — the classic proof of √2's irrationality uses this technique.",
  },
  {
    id: "pt-2",
    concept: "proof-techniques",
    difficulty: "hard",
    type: "mcq",
    question: "To prove 'if n² is even then n is even' using the contrapositive, what must you show instead?",
    options: [
      "If n is odd, then n² is odd",
      "If n is even, then n² is odd",
      "n² is odd implies n is even",
      "n is even implies n² is even",
    ],
    correctIndex: 0,
    steps: [
      { statement: "The contrapositive of p → q is ¬q → ¬p.", reason: "Definition of contrapositive" },
      { statement: "Here p = 'n² is even', q = 'n is even'. So ¬q → ¬p is 'n is odd → n² is odd'.", reason: "Substitute the negations" },
    ],
    explanation: "Proving the contrapositive is always logically equivalent to proving the original statement, and is often easier algebraically.",
  },
  {
    id: "pt-6",
    concept: "proof-techniques",
    difficulty: "hard",
    type: "mcq",
    question: "A proof that two irrational numbers a, b exist with a^b rational, WITHOUT identifying which specific case works, is called:",
    options: ["A nonconstructive existence proof", "A proof by induction", "A proof by contraposition", "A direct proof"],
    correctIndex: 0,
    steps: [
      { statement: "This kind of proof shows something exists without necessarily pinning down which specific case is the working one.", reason: "Describe what a nonconstructive proof does" },
      { statement: "The classic version considers √2^√2 and splits into cases on whether it's rational or irrational, without ever settling which case is true.", reason: "Recall the standard example's structure" },
    ],
    explanation: "Nonconstructive existence proofs are a genuinely strange but valid technique — they prove 'a working example exists' without ever producing one explicitly.",
  },
  {
    id: "pt-3",
    concept: "proof-techniques",
    difficulty: "medium",
    type: "fill-in",
    question: "Direct proof step: if n is odd, n = 2k+1. Expand n² in terms of k (as a polynomial, no parentheses, e.g. 'ak^2+bk+c').",
    acceptableAnswers: ["4k^2+4k+1", "4k^2 + 4k + 1"],
    steps: [
      { statement: "n = 2k+1, so n² = (2k+1)².", reason: "Substitute the odd-number form" },
      { statement: "(2k+1)² = 4k² + 4k + 1 by expanding the binomial.", reason: "Apply (a+b)² = a² + 2ab + b²" },
    ],
    explanation: "(2k+1)² = 4k² + 4k + 1 — grouping the first two terms as 2(2k²+2k) shows the whole thing is 2×(integer)+1, i.e. odd.",
  },
  {
    id: "pt-7",
    concept: "proof-techniques",
    difficulty: "medium",
    type: "fill-in",
    question: "To prove by contradiction that no smallest positive rational number exists, you assume one exists (call it r), then construct what smaller rational? (answer as a simple expression in r)",
    acceptableAnswers: ["r/2", "half of r", "r / 2"],
    steps: [
      { statement: "Assume r is the smallest positive rational number.", reason: "State the contradiction assumption" },
      { statement: "r/2 is also rational (rationals are closed under division by 2), and it's strictly smaller than r since r > 0.", reason: "Construct a smaller candidate" },
      { statement: "This contradicts r being the smallest — so no smallest positive rational can exist.", reason: "State the resulting contradiction" },
    ],
    explanation: "r/2 is always a smaller positive rational than r, so assuming a 'smallest' one always self-destructs.",
  },
  {
    id: "pt-4",
    concept: "proof-techniques",
    difficulty: "medium",
    type: "mcq",
    question: "What must a proof of 'p if and only if q' establish?",
    options: ["Both p → q and q → p", "Only p → q", "Only q → p", "Neither direction, just a truth table"],
    correctIndex: 0,
    steps: [
      { statement: "p ↔ q is defined as (p→q) ∧ (q→p).", reason: "Recall the definition of the biconditional" },
      { statement: "Proving a conjunction requires proving both halves.", reason: "Apply the definition of AND" },
    ],
    explanation: "p ↔ q is the conjunction of both conditionals — an iff proof always needs two separate directions.",
  },
  {
    id: "pt-8",
    concept: "proof-techniques",
    difficulty: "medium",
    type: "mcq",
    question: "What does the abbreviation 'WLOG' mean inside a proof?",
    options: [
      "Without loss of generality",
      "With limited outcomes given",
      "Without listing options generally",
      "Weak logical outcome guarantee",
    ],
    correctIndex: 0,
    steps: [
      { statement: "This phrase signals the proof picked one symmetric case to focus on, since every other case works identically by the same argument.", reason: "Explain the purpose of the phrase" },
    ],
    explanation: "'WLOG' lets a proof skip re-deriving symmetric cases, since the same reasoning applies to each of them.",
  },
  {
    id: "pt-5",
    concept: "proof-techniques",
    difficulty: "easy",
    type: "mcq",
    question: "What's used to disprove a universal statement 'for all x, P(x)'?",
    options: ["A counterexample", "A direct proof", "Proof by contradiction", "Induction"],
    correctIndex: 0,
    steps: [
      { statement: "¬∀x P(x) ≡ ∃x ¬P(x).", reason: "Recall the quantifier negation law" },
      { statement: "So disproving 'for all x' only needs ONE x where P(x) fails — a counterexample.", reason: "Interpret the existential result" },
    ],
    explanation: "Since ¬∀x P(x) ≡ ∃x ¬P(x), finding just one x where P(x) fails is enough to disprove the universal claim.",
  },

  // Sets & Set Operations
  {
    id: "st-1",
    concept: "sets",
    difficulty: "hard",
    type: "fill-in",
    question: "If |S| = 5, how many elements does the power set P(S) have?",
    acceptableAnswers: ["32"],
    steps: [{ statement: "A set with n elements has 2ⁿ subsets.", reason: "Each element is independently in or out of a given subset" }, { statement: "2⁵ = 32.", reason: "Direct computation" }],
    explanation: "|P(S)| = 2^|S| always — here 2⁵ = 32.",
  },
  {
    id: "st-6",
    concept: "sets",
    difficulty: "hard",
    type: "fill-in",
    question: "|A| = 3 and |B| = 4. Find |A × B|, the number of ordered pairs in the Cartesian product.",
    acceptableAnswers: ["12"],
    steps: [
      { statement: "|A × B| = |A| × |B|.", reason: "Recall the Cartesian product size formula" },
      { statement: "3 × 4 = 12.", reason: "Arithmetic" },
    ],
    explanation: "Every element of A pairs with every element of B, giving |A|×|B| = 12 total ordered pairs.",
  },
  {
    id: "st-2",
    concept: "sets",
    difficulty: "hard",
    type: "mcq",
    question: "Which of these is always true for any set A?",
    options: ["A ∪ ∅ = A", "A ∩ ∅ = A", "A − ∅ = ∅", "A ⊕ ∅ = ∅"],
    correctIndex: 0,
    steps: [
      { statement: "∅ has no elements to add to A.", reason: "Definition of the empty set" },
      { statement: "So A ∪ ∅ can only contain exactly what was already in A.", reason: "Apply the definition of union" },
    ],
    explanation: "∅ contributes nothing to a union, so A ∪ ∅ = A always. (A ∩ ∅ = ∅, A − ∅ = A, and A ⊕ ∅ = A — all the other options are wrong.)",
  },
  {
    id: "st-3",
    concept: "sets",
    difficulty: "medium",
    type: "fill-in",
    question: "A = {1,2,3}, B = {2,3,4}. Find |A ∪ B|.",
    acceptableAnswers: ["4"],
    steps: [{ statement: "A ∪ B = {1,2,3,4} — merge both lists, drop the repeated 2 and 3.", reason: "Definition of union" }],
    explanation: "A ∪ B = {1,2,3,4}, so |A ∪ B| = 4.",
  },
  {
    id: "st-7",
    concept: "sets",
    difficulty: "medium",
    type: "mcq",
    question: "A ⊕ B (symmetric difference) represents:",
    options: ["Elements in exactly one of A or B", "Elements in both A and B", "Elements in neither A nor B", "Elements only in A"],
    correctIndex: 0,
    steps: [
      { statement: "⊕ explicitly EXCLUDES elements found in both sets.", reason: "Recall the definition of symmetric difference" },
      { statement: "That leaves only elements found in exactly one of A or B.", reason: "State the resulting set" },
    ],
    explanation: "Symmetric difference is like an 'exclusive or' for sets — shared elements are deliberately left out.",
  },
  {
    id: "st-8",
    concept: "sets",
    difficulty: "medium",
    type: "fill-in",
    question: "A ⊆ B, |A| = 3, |B| = 7. Find |B − A|.",
    acceptableAnswers: ["4"],
    steps: [
      { statement: "Since A ⊆ B, every element of A is also in B.", reason: "Use the subset relationship" },
      { statement: "B − A removes exactly A's 3 elements from B's 7.", reason: "Set up the subtraction" },
      { statement: "7 − 3 = 4.", reason: "Arithmetic" },
    ],
    explanation: "When A is a subset of B, |B − A| = |B| − |A| always holds.",
  },
  {
    id: "st-4",
    concept: "sets",
    difficulty: "easy",
    type: "mcq",
    question: "A ∩ B represents:",
    options: ["Elements in both A and B", "Elements in either A or B", "Elements only in A", "Elements not in A"],
    correctIndex: 0,
    steps: [
      { statement: "∩ requires membership in BOTH sets simultaneously.", reason: "Definition of intersection" },
      { statement: "That directly matches 'elements in both A and B'.", reason: "Match to the correct option" },
    ],
    explanation: "∩ is intersection — only elements shared by both sets.",
  },
  {
    id: "st-5",
    concept: "sets",
    difficulty: "easy",
    type: "fill-in",
    question: "How many elements are in the empty set ∅?",
    acceptableAnswers: ["0", "zero"],
    steps: [
      { statement: "∅ is defined as the set containing no elements.", reason: "Definition of the empty set" },
      { statement: "So its cardinality is 0.", reason: "Count the elements" },
    ],
    explanation: "By definition, ∅ contains no elements at all.",
  },

  // Functions & Sequences
  {
    id: "fs-1",
    concept: "functions-sequences",
    difficulty: "hard",
    type: "mcq",
    question: "f: Z → Z defined by f(x) = x² is:",
    options: ["Neither injective nor surjective", "Injective only", "Surjective only", "Bijective"],
    correctIndex: 0,
    steps: [
      { statement: "f(2) = 4 and f(-2) = 4 — two different inputs give the same output.", reason: "Squaring destroys the sign" },
      { statement: "Not injective. Also, -1 is never hit since no integer squares to a negative number.", reason: "Negative outputs are impossible, so f isn't surjective onto Z either" },
    ],
    explanation: "Squaring on the integers is neither one-to-one (loses sign information) nor onto (misses all negative numbers).",
  },
  {
    id: "fs-6",
    concept: "functions-sequences",
    difficulty: "hard",
    type: "mcq",
    question: "Which of these functions ℝ → ℝ is bijective?",
    options: ["f(x) = x³", "f(x) = x²", "f(x) = |x|", "f(x) = sin(x)"],
    correctIndex: 0,
    steps: [
      { statement: "x² and |x| both map +a and −a to the same output — neither is injective.", reason: "Eliminate x² and |x|" },
      { statement: "sin(x) repeats output values and never exceeds [-1,1] — neither injective nor surjective on ℝ.", reason: "Eliminate sin(x)" },
      { statement: "x³ is strictly increasing (injective) and covers every real number as x ranges over ℝ (surjective).", reason: "Confirm x³ is bijective" },
    ],
    explanation: "x³ is the only option here that's both one-to-one and onto across all of ℝ.",
  },
  {
    id: "fs-2",
    concept: "functions-sequences",
    difficulty: "hard",
    type: "fill-in",
    question: "A sequence is defined by aₙ = 3n − 1. Find a₅.",
    acceptableAnswers: ["14"],
    steps: [{ statement: "a₅ = 3(5) − 1 = 15 − 1", reason: "Substitute n=5" }, { statement: "= 14", reason: "Arithmetic" }],
    explanation: "a₅ = 3(5) − 1 = 14.",
  },
  {
    id: "fs-3",
    concept: "functions-sequences",
    difficulty: "medium",
    type: "mcq",
    question: "A function that is both injective and surjective is called:",
    options: ["Bijective", "Constant", "Identity", "Partial"],
    correctIndex: 0,
    steps: [
      { statement: "Injective alone only rules out repeated outputs.", reason: "Consider the injective-only case" },
      { statement: "Surjective alone only guarantees every output is hit.", reason: "Consider the surjective-only case" },
      { statement: "Only when BOTH hold together do we call it bijective.", reason: "Combine both conditions" },
    ],
    explanation: "Bijective = one-to-one AND onto — exactly the condition needed for an inverse function to exist.",
  },
  {
    id: "fs-7",
    concept: "functions-sequences",
    difficulty: "medium",
    type: "fill-in",
    question: "Geometric sequence: aₙ = 3 · 2ⁿ. Find a₃.",
    acceptableAnswers: ["24"],
    steps: [
      { statement: "Substitute n=3: a₃ = 3 × 2³.", reason: "Set up the substitution" },
      { statement: "2³ = 8, so a₃ = 3 × 8 = 24.", reason: "Arithmetic" },
    ],
    explanation: "a₃ = 3 × 2³ = 24.",
  },
  {
    id: "fs-8",
    concept: "functions-sequences",
    difficulty: "medium",
    type: "mcq",
    question: "In (f ∘ g)(x), which function is applied first?",
    options: ["g, then f", "f, then g", "Both simultaneously", "Neither — it's undefined"],
    correctIndex: 0,
    steps: [
      { statement: "(f∘g)(x) is read as f(g(x)).", reason: "Recall the notation" },
      { statement: "The innermost function (g) is evaluated first, then its output feeds into f.", reason: "Trace the order of evaluation" },
    ],
    explanation: "Composition applies right-to-left: the function closest to x runs first.",
  },
  {
    id: "fs-4",
    concept: "functions-sequences",
    difficulty: "easy",
    type: "fill-in",
    question: "Evaluate Σ (k=1 to 4) k.",
    acceptableAnswers: ["10"],
    steps: [{ statement: "1 + 2 + 3 + 4", reason: "Expand the summation" }, { statement: "= 10", reason: "Add them up" }],
    explanation: "1+2+3+4 = 10.",
  },
  {
    id: "fs-5",
    concept: "functions-sequences",
    difficulty: "easy",
    type: "mcq",
    question: "f(x) = x + 1 maps 3 to:",
    options: ["4", "3", "2", "5"],
    correctIndex: 0,
    steps: [
      { statement: "f(x) = x+1, substitute x=3.", reason: "Set up the substitution" },
      { statement: "f(3) = 3+1 = 4.", reason: "Arithmetic" },
    ],
    explanation: "f(3) = 3 + 1 = 4.",
  },

  // Algorithms
  {
    id: "al-1",
    concept: "algorithms",
    difficulty: "hard",
    type: "mcq",
    question: "What is the worst-case time complexity of bubble sort on n elements?",
    options: ["O(n²)", "O(n log n)", "O(log n)", "O(n)"],
    correctIndex: 0,
    steps: [
      { statement: "Bubble sort makes up to n−1 passes.", reason: "Count the passes" },
      { statement: "Each pass does up to n−1 comparisons.", reason: "Count comparisons per pass" },
      { statement: "(n−1)×(n−1) is on the order of n² — matching O(n²).", reason: "Combine into a growth rate" },
    ],
    explanation: "Bubble sort compares adjacent pairs across up to n passes, each doing up to n comparisons — O(n²) in the worst case.",
  },
  {
    id: "al-6",
    concept: "algorithms",
    difficulty: "hard",
    type: "fill-in",
    question: "Insertion sort's worst case (a completely reverse-sorted array) on n=5 elements takes how many comparisons?",
    acceptableAnswers: ["10"],
    steps: [
      { statement: "Worst case for insertion sort is a reverse-sorted array, forcing every new element to compare against ALL previously placed elements.", reason: "Identify the worst-case scenario" },
      { statement: "Total comparisons = 1+2+3+4 = n(n-1)/2 = 5×4/2.", reason: "Sum the comparisons across each insertion" },
      { statement: "= 10.", reason: "Arithmetic" },
    ],
    explanation: "Insertion sort's worst case needs n(n−1)/2 comparisons — here, 10.",
  },
  {
    id: "al-2",
    concept: "algorithms",
    difficulty: "medium",
    type: "fill-in",
    question: "What is the maximum number of comparisons binary search needs on a sorted list of 16 elements?",
    acceptableAnswers: ["4"],
    steps: [
      { statement: "Binary search needs about log₂(n) comparisons in the worst case.", reason: "Each comparison halves the remaining search window" },
      { statement: "log₂(16) = 4, since 2⁴ = 16.", reason: "Direct computation" },
    ],
    explanation: "⌈log₂ 16⌉ = 4 comparisons in the worst case.",
  },
  {
    id: "al-3",
    concept: "algorithms",
    difficulty: "medium",
    type: "mcq",
    question: "Which of these grows fastest as n → ∞?",
    options: ["n!", "2ⁿ", "n²", "n log n"],
    correctIndex: 0,
    steps: [
      { statement: "n! multiplies by a growing factor (n, n-1, n-2, ...) each step.", reason: "Compare growth mechanisms" },
      { statement: "2ⁿ multiplies by a FIXED factor (2) each step — always slower long-term than a growing multiplier.", reason: "Compare to exponential growth" },
      { statement: "n² and n log n are polynomial/near-linear, far slower than either.", reason: "Eliminate the remaining options" },
    ],
    explanation: "Factorial growth outpaces exponential, which outpaces polynomial, which outpaces n log n.",
  },
  {
    id: "al-7",
    concept: "algorithms",
    difficulty: "medium",
    type: "mcq",
    question: "Which search algorithm REQUIRES the array to be sorted first?",
    options: ["Binary search", "Linear search", "Both require it", "Neither requires it"],
    correctIndex: 0,
    steps: [
      { statement: "Binary search relies on comparing against a midpoint and discarding half the range.", reason: "Recall how binary search works" },
      { statement: "That only works correctly if the array is already sorted.", reason: "State the requirement" },
    ],
    explanation: "Linear search works on any order; binary search's entire logic depends on the array being sorted.",
  },
  {
    id: "al-4",
    concept: "algorithms",
    difficulty: "medium",
    type: "fill-in",
    question: "Using greedy coin change with quarters(25), dimes(10), nickels(5), pennies(1), how many coins minimum for 41 cents?",
    acceptableAnswers: ["4"],
    steps: [
      { statement: "41 ≥ 25: take a quarter → 16 left.", reason: "Greedy: always take the largest coin that fits" },
      { statement: "16 ≥ 10: take a dime → 6 left.", reason: "Continue greedily" },
      { statement: "6 ≥ 5: take a nickel → 1 left.", reason: "Continue greedily" },
      { statement: "1 ≥ 1: take a penny → 0 left.", reason: "Done" },
    ],
    explanation: "1 quarter + 1 dime + 1 nickel + 1 penny = 4 coins.",
  },
  {
    id: "al-8",
    concept: "algorithms",
    difficulty: "easy",
    type: "fill-in",
    question: "Using greedy coin change with quarters(25), dimes(10), nickels(5), pennies(1), how many coins minimum for 63 cents?",
    acceptableAnswers: ["6"],
    steps: [
      { statement: "63 ≥ 25: take 2 quarters (50) → 13 left.", reason: "Greedy: take the largest coin that fits, repeatedly" },
      { statement: "13 ≥ 10: take 1 dime → 3 left.", reason: "Continue greedily" },
      { statement: "3 < 5: take 3 pennies → 0 left.", reason: "Finish with pennies since 3 < 5" },
      { statement: "Total coins: 2 + 1 + 3 = 6.", reason: "Add up all coins used" },
    ],
    explanation: "2 quarters + 1 dime + 3 pennies = 6 coins.",
  },
  {
    id: "al-5",
    concept: "algorithms",
    difficulty: "easy",
    type: "mcq",
    question: "What is the time complexity of linear search on n elements?",
    options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
    correctIndex: 0,
    steps: [
      { statement: "Linear search checks elements one at a time from the start.", reason: "Describe the algorithm" },
      { statement: "Worst case (element missing, or last), it checks all n elements.", reason: "Count the worst case" },
    ],
    explanation: "Linear search may need to check every one of the n elements in the worst case.",
  },

  // Induction & Recursion
  {
    id: "ir-1",
    concept: "induction-recursion",
    difficulty: "hard",
    type: "mcq",
    question: "In a proof by induction, the inductive hypothesis assumes:",
    options: ["P(k) is true for an arbitrary k", "P(1) is true", "P(n) is true for all n", "P(k+1) is true"],
    correctIndex: 0,
    steps: [
      { statement: "The basis step handles P(1) (or the smallest case) separately.", reason: "Eliminate the basis-step option" },
      { statement: "The inductive step's job is to assume P(k) and PROVE P(k+1) — you don't get to assume P(k+1) itself.", reason: "Eliminate the wrong assumption options" },
      { statement: "So the hypothesis you're allowed to assume is P(k) for an arbitrary k.", reason: "Confirm the correct answer" },
    ],
    explanation: "The inductive hypothesis assumes P(k) for an arbitrary (but fixed) k, then the inductive step must show P(k) ⟹ P(k+1).",
  },
  {
    id: "ir-6",
    concept: "induction-recursion",
    difficulty: "hard",
    type: "mcq",
    question: "The classic 'all horses are the same color' induction fallacy breaks down specifically because:",
    options: [
      "The inductive step's overlap argument requires k≥2, so it's never verified for the k=1 → k=2 case",
      "The basis step itself is false",
      "The inductive hypothesis is circular",
      "There's actually no flaw — the conclusion is correct",
    ],
    correctIndex: 0,
    steps: [
      { statement: "The inductive step relies on two overlapping (k-horse) subgroups sharing a common horse to link their colors.", reason: "Recall the flawed argument's mechanism" },
      { statement: "That overlap only exists when k≥2 — it fails exactly at k=1 (going from 1 horse to 2 horses).", reason: "Identify where the overlap breaks down" },
      { statement: "So the inductive step was never actually verified for the smallest case, invalidating the whole chain.", reason: "State the conclusion" },
    ],
    explanation: "The flaw hides in a step that looks fine 'in general' but silently assumes k≥2 — a great reminder to always check the smallest case explicitly.",
  },
  {
    id: "ir-2",
    concept: "induction-recursion",
    difficulty: "hard",
    type: "fill-in",
    question: "f(n) = f(n-1) + 2, f(0) = 5. Find f(3).",
    acceptableAnswers: ["11"],
    steps: [
      { statement: "f(1) = f(0)+2 = 5+2 = 7", reason: "Apply the rule with n=1" },
      { statement: "f(2) = f(1)+2 = 7+2 = 9", reason: "Apply the rule with n=2" },
      { statement: "f(3) = f(2)+2 = 9+2 = 11", reason: "Apply the rule with n=3" },
    ],
    explanation: "Unwinding the recurrence three times from f(0)=5 gives f(3) = 11.",
  },
  {
    id: "ir-7",
    concept: "induction-recursion",
    difficulty: "medium",
    type: "fill-in",
    question: "aₙ = aₙ₋₁ × 2, a₁ = 3. Find a₄.",
    acceptableAnswers: ["24"],
    steps: [
      { statement: "a₂ = a₁ × 2 = 3 × 2 = 6", reason: "Apply the rule once" },
      { statement: "a₃ = a₂ × 2 = 6 × 2 = 12", reason: "Apply again" },
      { statement: "a₄ = a₃ × 2 = 12 × 2 = 24", reason: "Apply a third time" },
    ],
    explanation: "Unwinding three times from a₁=3 gives a₄ = 24.",
  },
  {
    id: "ir-3",
    concept: "induction-recursion",
    difficulty: "medium",
    type: "mcq",
    question: "What must the basis step of an induction proof establish?",
    options: ["P is true for the smallest case", "P is true for all n", "The inductive step", "Nothing — it's optional"],
    correctIndex: 0,
    steps: [
      { statement: "Induction is a two-part structure: basis step + inductive step.", reason: "Recall the overall structure" },
      { statement: "The basis step's specific job is verifying the smallest/starting case directly.", reason: "Define its role" },
    ],
    explanation: "The basis step checks the starting case (often n=0 or n=1) directly — without it, the inductive chain has nothing to start from.",
  },
  {
    id: "ir-8",
    concept: "induction-recursion",
    difficulty: "medium",
    type: "mcq",
    question: "How does strong induction differ from regular (weak) induction?",
    options: [
      "It lets you assume P is true for every value up to k, not just P(k) itself",
      "It skips the basis step entirely",
      "It only proves the basis step",
      "It only works for even n",
    ],
    correctIndex: 0,
    steps: [
      { statement: "Regular induction only assumes P(k) itself.", reason: "Recall standard induction's hypothesis" },
      { statement: "Strong induction instead lets you assume P holds for EVERY value from the base case up through k.", reason: "State the key difference" },
    ],
    explanation: "Strong induction hands you a much bigger toolbox in the inductive step — every earlier case, not just the one immediately before k.",
  },
  {
    id: "ir-4",
    concept: "induction-recursion",
    difficulty: "easy",
    type: "fill-in",
    question: "The recursive definition of factorial has its base case at n = ?",
    acceptableAnswers: ["0", "n=0"],
    steps: [
      { statement: "Recursive factorial: n! = n × (n−1)! for n>0.", reason: "Recall the recursive rule" },
      { statement: "That rule needs a stopping point — defined directly as 0! = 1.", reason: "Identify the base case" },
    ],
    explanation: "0! = 1 is the base case; every other value unwinds via n! = n × (n-1)!.",
  },
  {
    id: "ir-5",
    concept: "induction-recursion",
    difficulty: "easy",
    type: "mcq",
    question: "What essential component does recursion need to terminate?",
    options: ["A base case", "A loop", "A pointer", "A global variable"],
    correctIndex: 0,
    steps: [
      { statement: "Without a stopping condition, a recursive call would call itself forever.", reason: "Consider what happens without one" },
      { statement: "The base case is exactly what halts the chain of calls.", reason: "Confirm the necessary component" },
    ],
    explanation: "Without a base case, a recursive function calls itself forever — the base case is what lets the recursion actually stop.",
  },

  // Counting
  {
    id: "ct-1",
    concept: "counting",
    difficulty: "hard",
    type: "fill-in",
    question: "How many 4-digit PINs are possible using digits 0-9 (repetition allowed)?",
    acceptableAnswers: ["10000", "10,000"],
    steps: [{ statement: "Each of the 4 digit positions independently has 10 choices.", reason: "Product rule" }, { statement: "10 × 10 × 10 × 10 = 10,000", reason: "Multiply the choices" }],
    explanation: "10⁴ = 10,000 possible PINs.",
  },
  {
    id: "ct-6",
    concept: "counting",
    difficulty: "hard",
    type: "fill-in",
    question: "How many distinct arrangements are there of the letters in the word BANANA?",
    acceptableAnswers: ["60"],
    steps: [
      { statement: "BANANA has 6 letters total, with A repeated 3 times and N repeated 2 times.", reason: "Identify the letter counts" },
      { statement: "Arrangements of items with repetition: 6!/(3!×2!).", reason: "Apply the permutations-with-repetition formula" },
      { statement: "720/(6×2) = 720/12 = 60.", reason: "Arithmetic" },
    ],
    explanation: "Dividing by the repeated letters' factorials corrects for the arrangements that look identical.",
  },
  {
    id: "ct-2",
    concept: "counting",
    difficulty: "hard",
    type: "mcq",
    question: "With 13 people, the pigeonhole principle guarantees at least 2 share a birth month because:",
    options: ["13 people > 12 months", "13 is a prime number", "Months always repeat", "Birthdays are random"],
    correctIndex: 0,
    steps: [
      { statement: "There are only 12 possible months (the 'holes').", reason: "Count the categories" },
      { statement: "With 13 people (the 'pigeons'), one more person than categories exist.", reason: "Compare the counts" },
      { statement: "By the pigeonhole principle, at least one month must be shared.", reason: "Apply the principle" },
    ],
    explanation: "13 pigeons (people) into 12 holes (months) forces at least one hole to hold ≥2 pigeons — the basic pigeonhole principle.",
  },
  {
    id: "ct-3",
    concept: "counting",
    difficulty: "medium",
    type: "fill-in",
    question: "Compute C(6,2), the number of ways to choose 2 items from 6 (order doesn't matter).",
    acceptableAnswers: ["15"],
    steps: [{ statement: "C(6,2) = 6!/(2!×4!) = 720/(2×24)", reason: "Combination formula" }, { statement: "= 720/48 = 15", reason: "Arithmetic" }],
    explanation: "C(6,2) = 15.",
  },
  {
    id: "ct-7",
    concept: "counting",
    difficulty: "medium",
    type: "fill-in",
    question: "How many subsets of size 3 can be chosen from a 7-element set?",
    acceptableAnswers: ["35"],
    steps: [
      { statement: "C(7,3) = 7!/(3!×4!).", reason: "Combination formula" },
      { statement: "= 5040/(6×24) = 5040/144.", reason: "Arithmetic" },
      { statement: "= 35.", reason: "Final division" },
    ],
    explanation: "C(7,3) = 35 — choosing a subset never cares about order.",
  },
  {
    id: "ct-4",
    concept: "counting",
    difficulty: "medium",
    type: "mcq",
    question: "The product rule applies when a sequence of choices is made:",
    options: ["Together, each independent of the others", "As mutually exclusive alternatives", "Impossible to do together", "Unrelated to counting at all"],
    correctIndex: 0,
    steps: [
      { statement: "The sum rule instead applies to mutually exclusive alternatives — not this.", reason: "Eliminate the sum-rule description" },
      { statement: "The product rule applies when choices are made together, each independent of the others.", reason: "State the correct condition" },
    ],
    explanation: "Product rule = AND (choices made together); sum rule = OR (mutually exclusive alternatives).",
  },
  {
    id: "ct-5",
    concept: "counting",
    difficulty: "easy",
    type: "fill-in",
    question: "Compute P(4,2), the number of ways to arrange 2 items chosen from 4 (order matters).",
    acceptableAnswers: ["12"],
    steps: [{ statement: "P(4,2) = 4!/(4-2)! = 4!/2! = 24/2", reason: "Permutation formula" }, { statement: "= 12", reason: "Arithmetic" }],
    explanation: "P(4,2) = 4 × 3 = 12.",
  },
  {
    id: "ct-8",
    concept: "counting",
    difficulty: "easy",
    type: "mcq",
    question: "Choosing r items from n where order DOES matter is called a:",
    options: ["Permutation", "Combination", "Partition", "Subset"],
    correctIndex: 0,
    steps: [
      { statement: "A combination doesn't care about order — {a,b} = {b,a}.", reason: "Recall the definition of combination" },
      { statement: "A permutation treats different orders as different outcomes.", reason: "Recall the definition of permutation" },
    ],
    explanation: "Permutations count ordered arrangements; combinations count unordered selections.",
  },

  // Relations
  {
    id: "rl-1",
    concept: "relations",
    difficulty: "hard",
    type: "mcq",
    question: "A relation that is reflexive, symmetric, AND transitive is called:",
    options: ["An equivalence relation", "A partial order", "A function", "Antisymmetric"],
    correctIndex: 0,
    steps: [
      { statement: "A partial order requires antisymmetric, not symmetric — that's different from what's described.", reason: "Eliminate partial order" },
      { statement: "A function isn't defined by these three properties at all.", reason: "Eliminate function" },
      { statement: "Reflexive + symmetric + transitive together is the exact definition of an equivalence relation.", reason: "Confirm the match" },
    ],
    explanation: "That exact combination of three properties defines an equivalence relation, which always partitions a set into equivalence classes.",
  },
  {
    id: "rl-2",
    concept: "relations",
    difficulty: "hard",
    type: "fill-in",
    question: "R = {(1,1),(2,2),(3,3),(1,2),(2,1)} on {1,2,3}. Is R transitive? Type Yes or No.",
    acceptableAnswers: ["yes", "y", "true"],
    steps: [
      { statement: "Check (1,2) and (2,1): need (1,1) — present ✓.", reason: "Transitivity check for this pair" },
      { statement: "Check (2,1) and (1,2): need (2,2) — present ✓.", reason: "Transitivity check for the reverse pair" },
      { statement: "No other combinations of pairs need checking.", reason: "All chained pairs have been covered" },
    ],
    explanation: "Every chain of related pairs also has its shortcut pair present, so R is transitive.",
  },
  {
    id: "rl-6",
    concept: "relations",
    difficulty: "hard",
    type: "fill-in",
    question: "How many elements of {0,1,...,9} belong to the equivalence class [2] under congruence mod 5?",
    acceptableAnswers: ["2"],
    steps: [
      { statement: "Find every number in {0,...,9} that leaves remainder 2 when divided by 5.", reason: "Apply the definition of the equivalence class" },
      { statement: "2÷5 remainder 2 ✓, 7÷5 remainder 2 ✓ — checking the rest (0,1,3,4,5,6,8,9) all give different remainders.", reason: "Test each candidate" },
      { statement: "Only 2 and 7 qualify.", reason: "Count the matches" },
    ],
    explanation: "[2] mod 5 restricted to {0,...,9} contains exactly {2, 7} — 2 elements.",
  },
  {
    id: "rl-3",
    concept: "relations",
    difficulty: "medium",
    type: "mcq",
    question: "A relation is antisymmetric when:",
    options: [
      "(a,b) and (b,a) both in R forces a=b",
      "a=b implies (a,b) is in R",
      "R contains no pairs at all",
      "R is automatically symmetric too",
    ],
    correctIndex: 0,
    steps: [
      { statement: "Symmetric would require (a,b)→(b,a) always — that's a different property.", reason: "Eliminate the symmetric-flavored distractor" },
      { statement: "Antisymmetric instead FORBIDS having both (a,b) and (b,a) unless a=b.", reason: "State the actual definition" },
    ],
    explanation: "Antisymmetric forbids two DIFFERENT elements from relating to each other in both directions.",
  },
  {
    id: "rl-7",
    concept: "relations",
    difficulty: "medium",
    type: "fill-in",
    question: "How many total relations exist on a 2-element set?",
    acceptableAnswers: ["16"],
    steps: [
      { statement: "A 2-element set has |A×A| = 4 possible ordered pairs.", reason: "Count the pairs in A×A" },
      { statement: "A relation is ANY subset of those 4 pairs, so there are 2⁴ possible relations.", reason: "Apply the subset-counting formula" },
      { statement: "2⁴ = 16.", reason: "Arithmetic" },
    ],
    explanation: "Every one of the 4 ordered pairs is independently either in or out of the relation, giving 2⁴ = 16 possible relations.",
  },
  {
    id: "rl-4",
    concept: "relations",
    difficulty: "medium",
    type: "fill-in",
    question: "How many ordered pairs (a,b) satisfy a ≤ b on the set {1,2,3}?",
    acceptableAnswers: ["6"],
    steps: [{ statement: "List them: (1,1),(1,2),(1,3),(2,2),(2,3),(3,3).", reason: "Every pair where the first is ≤ the second" }],
    explanation: "There are 6 such pairs.",
  },
  {
    id: "rl-5",
    concept: "relations",
    difficulty: "easy",
    type: "mcq",
    question: "A relation on set A is formally a subset of:",
    options: ["A × A", "A", "P(A)", "A ∪ A"],
    correctIndex: 0,
    steps: [
      { statement: "A × A is the set of ALL possible ordered pairs from A.", reason: "Recall the Cartesian product" },
      { statement: "Any relation on A is simply some collection of those pairs — a subset of A × A.", reason: "Apply the definition of a relation" },
    ],
    explanation: "A relation on A is any set of ordered pairs (a,b) with a,b ∈ A — i.e. a subset of the Cartesian product A × A.",
  },

  // Graphs
  {
    id: "gr-1",
    concept: "graphs",
    difficulty: "hard",
    type: "mcq",
    question: "A connected graph has an Euler circuit if and only if:",
    options: ["Every vertex has even degree", "Every vertex has odd degree", "It's a tree", "It has no cycles"],
    correctIndex: 0,
    steps: [
      { statement: "An Euler circuit must enter and leave every vertex the same number of times.", reason: "Think about how a circuit traverses a vertex" },
      { statement: "Entering and leaving in matched pairs means every vertex needs an even number of edges.", reason: "Translate that into a degree condition" },
    ],
    explanation: "Euler circuit theorem: every vertex must have even degree so the circuit can enter and leave through paired-up edges every time.",
  },
  {
    id: "gr-6",
    concept: "graphs",
    difficulty: "hard",
    type: "fill-in",
    question: "What is the minimum number of colors needed to properly color the cycle graph C₅ (so no two adjacent vertices share a color)?",
    acceptableAnswers: ["3"],
    steps: [
      { statement: "A cycle needs only 2 colors if its length is even (alternate colors around the loop).", reason: "Consider the even-cycle case first" },
      { statement: "C₅ has an ODD number of vertices, so alternating 2 colors fails to close the loop consistently.", reason: "Explain why 2 colors aren't enough for odd cycles" },
      { statement: "A third color resolves the conflict at the final vertex.", reason: "State the minimum needed" },
    ],
    explanation: "Odd cycles always need exactly 3 colors; even cycles only need 2.",
  },
  {
    id: "gr-2",
    concept: "graphs",
    difficulty: "medium",
    type: "fill-in",
    question: "How many edges does the complete graph K₆ have?",
    acceptableAnswers: ["15"],
    steps: [{ statement: "Every pair of the 6 vertices is connected: C(6,2) = 6!/(2!×4!)", reason: "Complete graph definition" }, { statement: "= 15", reason: "Arithmetic" }],
    explanation: "K₆ has C(6,2) = 15 edges.",
  },
  {
    id: "gr-3",
    concept: "graphs",
    difficulty: "medium",
    type: "mcq",
    question: "Dijkstra's algorithm requires edge weights to be:",
    options: ["Non-negative", "All equal", "Negative", "Irrelevant"],
    correctIndex: 0,
    steps: [
      { statement: "Dijkstra finalizes a vertex's distance once it's the smallest unvisited value.", reason: "Recall the greedy step" },
      { statement: "A later negative edge could undercut an already-finalized distance, breaking that guarantee.", reason: "Show why negative weights break the greedy assumption" },
    ],
    explanation: "Dijkstra's greedy approach breaks down with negative weights, since a 'finalized' shortest distance could later be undercut by a negative edge.",
  },
  {
    id: "gr-7",
    concept: "graphs",
    difficulty: "medium",
    type: "mcq",
    question: "A tree is a graph that is:",
    options: ["Connected and acyclic", "Connected and has cycles", "Disconnected and acyclic", "Complete"],
    correctIndex: 0,
    steps: [
      { statement: "A graph with cycles wouldn't be a tree by definition.", reason: "Eliminate the cycle option" },
      { statement: "A disconnected graph also isn't a single tree.", reason: "Eliminate the disconnected option" },
      { statement: "Connected AND acyclic together is the exact definition of a tree.", reason: "Confirm the definition" },
    ],
    explanation: "Both conditions are required together — connectivity alone (or acyclicity alone) isn't enough to define a tree.",
  },
  {
    id: "gr-4",
    concept: "graphs",
    difficulty: "medium",
    type: "fill-in",
    question: "A graph has 8 edges. What is the sum of all vertex degrees?",
    acceptableAnswers: ["16"],
    steps: [{ statement: "The Handshake Theorem: sum of degrees = 2 × number of edges.", reason: "Every edge contributes exactly 2 to the total degree count" }, { statement: "2 × 8 = 16", reason: "Arithmetic" }],
    explanation: "Sum of degrees = 2 × 8 = 16.",
  },
  {
    id: "gr-8",
    concept: "graphs",
    difficulty: "easy",
    type: "fill-in",
    question: "How many total vertices does the complete bipartite graph K₃,₄ have?",
    acceptableAnswers: ["7"],
    steps: [
      { statement: "K_{m,n} has m vertices on one side and n on the other.", reason: "Recall the complete bipartite graph structure" },
      { statement: "3 + 4 = 7.", reason: "Add the two sides" },
    ],
    explanation: "K₃,₄ has 3+4 = 7 vertices total, split into two sides with every cross-edge present.",
  },
  {
    id: "gr-5",
    concept: "graphs",
    difficulty: "easy",
    type: "mcq",
    question: "An edge connecting a vertex to itself is called a:",
    options: ["Loop", "Bridge", "Cycle", "Path"],
    correctIndex: 0,
    steps: [
      { statement: "A bridge is a single edge whose removal disconnects the graph — not this.", reason: "Eliminate bridge" },
      { statement: "A cycle and a path both involve multiple distinct vertices — not this either.", reason: "Eliminate cycle and path" },
      { statement: "An edge from a vertex to itself is specifically called a loop.", reason: "Confirm by elimination" },
    ],
    explanation: "A loop is a self-connecting edge — most simple-graph definitions exclude them, but multigraphs allow them.",
  },

  // Trees
  {
    id: "tr-1",
    concept: "trees",
    difficulty: "hard",
    type: "fill-in",
    question: "A full binary tree (every node has 0 or 2 children) has 15 total nodes. How many are leaves?",
    acceptableAnswers: ["8"],
    steps: [
      { statement: "For a full binary tree, leaves = internal nodes + 1.", reason: "Property of full binary trees" },
      { statement: "Total = internal + leaves = internal + (internal+1) = 2×internal + 1 = 15, so internal = 7.", reason: "Solve for internal nodes" },
      { statement: "Leaves = internal + 1 = 8.", reason: "Substitute back" },
    ],
    explanation: "A full binary tree with 15 nodes has 8 leaves and 7 internal nodes.",
  },
  {
    id: "tr-6",
    concept: "trees",
    difficulty: "hard",
    type: "fill-in",
    question: "What is the MAXIMUM number of nodes possible in a binary tree of height 3?",
    acceptableAnswers: ["15"],
    steps: [
      { statement: "A binary tree of height h has at most 2^(h+1) − 1 nodes when every level is completely full.", reason: "Recall the maximum-nodes formula" },
      { statement: "2^(3+1) − 1 = 2⁴ − 1 = 16 − 1.", reason: "Substitute h=3" },
      { statement: "= 15.", reason: "Arithmetic" },
    ],
    explanation: "A perfectly full binary tree of height 3 has 15 nodes — the same shape as the full binary tree in the question above.",
  },
  {
    id: "tr-2",
    concept: "trees",
    difficulty: "hard",
    type: "mcq",
    question: "Huffman coding assigns the SHORTEST codes to:",
    options: ["The most frequent symbols", "The least frequent symbols", "Alphabetically first symbols", "The longest symbols"],
    correctIndex: 0,
    steps: [
      { statement: "Huffman repeatedly merges the two LEAST frequent nodes first.", reason: "Recall the algorithm's merge order" },
      { statement: "Merging least-frequent nodes first pushes them deep into the tree, leaving frequent symbols near the top.", reason: "Trace the consequence" },
      { statement: "Being near the root means a SHORT path — a short code.", reason: "Connect tree depth to code length" },
    ],
    explanation: "Huffman merges the least-frequent symbols first, pushing frequent symbols near the root — closer to the root means a shorter code.",
  },
  {
    id: "tr-3",
    concept: "trees",
    difficulty: "medium",
    type: "mcq",
    question: "In a binary search tree, where do values LARGER than a node go?",
    options: ["Right subtree", "Left subtree", "The root", "It doesn't matter"],
    correctIndex: 0,
    steps: [
      { statement: "The BST invariant is: smaller values left, larger values right, at every node.", reason: "Recall the invariant" },
      { statement: "So a value larger than the current node always goes into its right subtree.", reason: "Apply directly" },
    ],
    explanation: "BST invariant: smaller goes left, larger goes right — at every single node in the tree.",
  },
  {
    id: "tr-7",
    concept: "trees",
    difficulty: "medium",
    type: "mcq",
    question: "In a PREORDER traversal, when is the root visited?",
    options: ["First, before its subtrees", "Last, after both subtrees", "Between the left and right subtree", "Never — only leaves are visited"],
    correctIndex: 0,
    steps: [
      { statement: "Preorder is defined as: visit root, then left subtree, then right subtree.", reason: "Recall the definition" },
      { statement: "So the root is always visited before either subtree — first.", reason: "State directly" },
    ],
    explanation: "'Pre' in preorder literally means the root comes before its subtrees are explored.",
  },
  {
    id: "tr-8",
    concept: "trees",
    difficulty: "medium",
    type: "fill-in",
    question: "A complete binary tree with 7 nodes has how many leaves?",
    acceptableAnswers: ["4"],
    steps: [
      { statement: "A perfect/complete binary tree with 7 nodes has 3 levels (2³−1=7).", reason: "Identify the tree's shape" },
      { statement: "The bottom (last) level holds all the leaves: level 3 has 2² = 4 nodes.", reason: "Count the bottom level" },
    ],
    explanation: "In a perfectly full 7-node binary tree, the bottom level alone accounts for exactly 4 leaves.",
  },
  {
    id: "tr-4",
    concept: "trees",
    difficulty: "easy",
    type: "fill-in",
    question: "A tree has 10 vertices. How many edges does it have?",
    acceptableAnswers: ["9"],
    steps: [{ statement: "A tree with n vertices always has exactly n-1 edges.", reason: "Defining property of a tree — connected and acyclic" }, { statement: "10 - 1 = 9", reason: "Arithmetic" }],
    explanation: "Every tree has exactly (vertices − 1) edges — here, 9.",
  },
  {
    id: "tr-5",
    concept: "trees",
    difficulty: "easy",
    type: "mcq",
    question: "The topmost node of a rooted tree is called the:",
    options: ["Root", "Leaf", "Child", "Edge"],
    correctIndex: 0,
    steps: [
      { statement: "A leaf has no children — the opposite of the topmost node.", reason: "Eliminate leaf" },
      { statement: "A child and an edge describe relationships, not the topmost position.", reason: "Eliminate the remaining distractors" },
      { statement: "The single node with no parent, at the very top, is the root.", reason: "Confirm by elimination" },
    ],
    explanation: "The root is the single topmost node that every other node descends from.",
  },
];
