export interface QuizStep {
  statement: string;
  reason: string;
}

export type QuizDifficulty = "hard" | "medium" | "easy";
export type QuizType = "mcq" | "fill-in";

export interface QuizQuestion {
  id: string;
  concept: string;
  difficulty: QuizDifficulty;
  type: QuizType;
  question: string;
  code?: string;
  options?: string[];
  correctIndex?: number;
  acceptableAnswers?: string[];
  steps?: QuizStep[];
  explanation: string;
}

export const quizConcepts: { id: string; label: string }[] = [
  { id: "propositional-logic", label: "Propositional Logic" },
  { id: "quantifiers-inference", label: "Quantifiers & Inference" },
  { id: "proof-techniques", label: "Proof Techniques" },
  { id: "sets", label: "Sets & Set Operations" },
  { id: "functions-sequences", label: "Functions & Sequences" },
  { id: "algorithms", label: "Algorithms" },
  { id: "induction-recursion", label: "Induction & Recursion" },
  { id: "counting", label: "Counting" },
  { id: "relations", label: "Relations" },
  { id: "graphs", label: "Graphs" },
  { id: "trees", label: "Trees" },
];

export const discreteMathsQuizBank: QuizQuestion[] = [
  // Propositional Logic
  {
    id: "pl-1",
    concept: "propositional-logic",
    difficulty: "hard",
    type: "mcq",
    question: "Which expression is logically equivalent to p → q?",
    options: ["¬p ∨ q", "¬p ∧ q", "p ∧ ¬q", "¬q → p"],
    correctIndex: 0,
    steps: [
      { statement: "p → q is only FALSE in exactly one case: p=T, q=F.", reason: "Definition of the conditional" },
      { statement: "¬p ∨ q is FALSE only when ¬p=F and q=F, i.e. p=T and q=F.", reason: "Definition of OR — false only when both sides are false" },
      { statement: "Both expressions are false in exactly the same single case (p=T, q=F), and true everywhere else.", reason: "Matching truth tables means logical equivalence" },
    ],
    explanation: "p → q ≡ ¬p ∨ q is one of the most useful equivalences in discrete math — it lets you rewrite any conditional using only ∨ and ¬.",
  },
  {
    id: "pl-2",
    concept: "propositional-logic",
    difficulty: "hard",
    type: "fill-in",
    question: "Is (p ∧ q) → (p ∨ q) a tautology, a contradiction, or a contingency? Type one word.",
    acceptableAnswers: ["tautology"],
    steps: [
      { statement: "Suppose p ∧ q is true. Then both p and q are true, so p ∨ q must also be true.", reason: "If both p and q hold, either one alone certainly holds" },
      { statement: "So whenever the hypothesis (p ∧ q) is true, the conclusion (p ∨ q) is also true.", reason: "The only way a conditional is false is a true hypothesis with a false conclusion — that never happens here" },
      { statement: "When p ∧ q is false, the conditional is automatically true regardless of p ∨ q.", reason: "A false hypothesis makes any conditional true" },
    ],
    explanation: "The expression is true for every possible combination of p and q, so it's a tautology.",
  },
  {
    id: "pl-3",
    concept: "propositional-logic",
    difficulty: "medium",
    type: "mcq",
    question: "¬(p → q) is logically equivalent to:",
    options: ["p ∧ ¬q", "¬p ∨ q", "¬p ∧ ¬q", "p ∨ ¬q"],
    correctIndex: 0,
    explanation: "Since p → q ≡ ¬p ∨ q, negating both sides gives ¬(¬p ∨ q) ≡ p ∧ ¬q by De Morgan's law.",
  },
  {
    id: "pl-4",
    concept: "propositional-logic",
    difficulty: "medium",
    type: "fill-in",
    question: "Evaluate ¬(T ∧ F). Type True or False.",
    acceptableAnswers: ["true", "t"],
    explanation: "T ∧ F = F, and ¬F = True.",
  },
  {
    id: "pl-5",
    concept: "propositional-logic",
    difficulty: "easy",
    type: "mcq",
    question: "Which symbol represents logical OR?",
    options: ["∧", "∨", "¬", "→"],
    correctIndex: 1,
    explanation: "∨ is OR (true if either or both sides are true), ∧ is AND, ¬ is NOT, and → is the conditional.",
  },

  // Quantifiers & Inference
  {
    id: "qi-1",
    concept: "quantifiers-inference",
    difficulty: "hard",
    type: "mcq",
    question: "What is the correct negation of ∀x P(x)?",
    options: ["∃x ¬P(x)", "∀x ¬P(x)", "¬∃x P(x)", "∃x P(x)"],
    correctIndex: 0,
    steps: [
      { statement: "∀x P(x) says every x satisfies P.", reason: "Definition of the universal quantifier" },
      { statement: "For this to be FALSE, at least one x must fail to satisfy P — that's exactly ∃x ¬P(x).", reason: "Negating 'every x works' means 'some x doesn't work'" },
    ],
    explanation: "Negating a quantifier flips it AND negates the predicate: ¬∀x P(x) ≡ ∃x ¬P(x) (and symmetrically ¬∃x P(x) ≡ ∀x ¬P(x)).",
  },
  {
    id: "qi-2",
    concept: "quantifiers-inference",
    difficulty: "hard",
    type: "fill-in",
    question: "Given premises p → q and ¬q, what can you validly conclude by modus tollens? (type using ¬ or 'not p')",
    acceptableAnswers: ["¬p", "not p", "-p", "!p"],
    steps: [
      { statement: "Modus tollens: from p→q and ¬q, conclude ¬p.", reason: "If q were false, then p can't be true, since p→q would be violated" },
    ],
    explanation: "Modus tollens is the 'contrapositive in action' rule — it's exactly why disproving the consequent disproves the hypothesis.",
  },
  {
    id: "qi-3",
    concept: "quantifiers-inference",
    difficulty: "medium",
    type: "mcq",
    question: "Which inference rule concludes q directly from p and p → q?",
    options: ["Modus ponens", "Modus tollens", "Hypothetical syllogism", "Disjunctive syllogism"],
    correctIndex: 0,
    explanation: "Modus ponens: p is true, p→q is true, so q must be true — the most commonly used rule of inference.",
  },
  {
    id: "qi-4",
    concept: "quantifiers-inference",
    difficulty: "medium",
    type: "fill-in",
    question: "Over the integers, is ∃x (x² = 4) true or false? Type True or False.",
    acceptableAnswers: ["true", "t"],
    steps: [{ statement: "Try x = 2: 2² = 4. A working value exists.", reason: "∃ just needs ONE example to succeed" }],
    explanation: "x=2 (or x=-2) satisfies x²=4, so the existential statement is true — only one witness is needed.",
  },
  {
    id: "qi-5",
    concept: "quantifiers-inference",
    difficulty: "easy",
    type: "mcq",
    question: "What does ∃ mean?",
    options: ["For all", "There exists", "Not", "And"],
    correctIndex: 1,
    explanation: "∃ is the existential quantifier — 'there exists at least one'. ∀ is 'for all'.",
  },

  // Proof Techniques
  {
    id: "pt-1",
    concept: "proof-techniques",
    difficulty: "hard",
    type: "mcq",
    question: "A proof that assumes the negation of the conclusion and derives an impossibility is called:",
    options: ["Direct proof", "Proof by contradiction", "Proof by induction", "Proof by cases"],
    correctIndex: 1,
    explanation: "Proof by contradiction: assume ¬conclusion, show it leads somewhere impossible, so the conclusion must actually be true — the classic proof of √2's irrationality uses this technique.",
  },
  {
    id: "pt-2",
    concept: "proof-techniques",
    difficulty: "hard",
    type: "mcq",
    question: "To prove 'if n² is even then n is even' using the contrapositive, what must you show instead?",
    options: [
      "If n is odd, then n² is odd",
      "If n is even, then n² is odd",
      "n² is odd implies n is even",
      "n is even implies n² is even",
    ],
    correctIndex: 0,
    steps: [
      { statement: "The contrapositive of p → q is ¬q → ¬p.", reason: "Definition of contrapositive" },
      { statement: "Here p = 'n² is even', q = 'n is even'. So ¬q → ¬p is 'n is odd → n² is odd'.", reason: "Substitute the negations" },
    ],
    explanation: "Proving the contrapositive is always logically equivalent to proving the original statement, and is often easier algebraically.",
  },
  {
    id: "pt-3",
    concept: "proof-techniques",
    difficulty: "medium",
    type: "fill-in",
    question: "Direct proof step: if n is odd, n = 2k+1. Expand n² in terms of k (as a polynomial, no parentheses, e.g. 'ak^2+bk+c').",
    acceptableAnswers: ["4k^2+4k+1", "4k^2 + 4k + 1"],
    explanation: "(2k+1)² = 4k² + 4k + 1 — grouping the first two terms as 2(2k²+2k) shows the whole thing is 2×(integer)+1, i.e. odd.",
  },
  {
    id: "pt-4",
    concept: "proof-techniques",
    difficulty: "medium",
    type: "mcq",
    question: "What must a proof of 'p if and only if q' establish?",
    options: ["Both p → q and q → p", "Only p → q", "Only q → p", "Neither direction, just a truth table"],
    correctIndex: 0,
    explanation: "p ↔ q is the conjunction of both conditionals — an iff proof always needs two separate directions.",
  },
  {
    id: "pt-5",
    concept: "proof-techniques",
    difficulty: "easy",
    type: "mcq",
    question: "What's used to disprove a universal statement 'for all x, P(x)'?",
    options: ["A counterexample", "A direct proof", "Proof by contradiction", "Induction"],
    correctIndex: 0,
    explanation: "Since ¬∀x P(x) ≡ ∃x ¬P(x), finding just one x where P(x) fails is enough to disprove the universal claim.",
  },

  // Sets & Set Operations
  {
    id: "st-1",
    concept: "sets",
    difficulty: "hard",
    type: "fill-in",
    question: "If |S| = 5, how many elements does the power set P(S) have?",
    acceptableAnswers: ["32"],
    steps: [{ statement: "A set with n elements has 2ⁿ subsets.", reason: "Each element is independently in or out of a given subset" }, { statement: "2⁵ = 32.", reason: "Direct computation" }],
    explanation: "|P(S)| = 2^|S| always — here 2⁵ = 32.",
  },
  {
    id: "st-2",
    concept: "sets",
    difficulty: "hard",
    type: "mcq",
    question: "Which of these is always true for any set A?",
    options: ["A ∪ ∅ = A", "A ∩ ∅ = A", "A − ∅ = ∅", "A ⊕ ∅ = ∅"],
    correctIndex: 0,
    explanation: "∅ contributes nothing to a union, so A ∪ ∅ = A always. (A ∩ ∅ = ∅, A − ∅ = A, and A ⊕ ∅ = A — all the other options are wrong.)",
  },
  {
    id: "st-3",
    concept: "sets",
    difficulty: "medium",
    type: "fill-in",
    question: "A = {1,2,3}, B = {2,3,4}. Find |A ∪ B|.",
    acceptableAnswers: ["4"],
    steps: [{ statement: "A ∪ B = {1,2,3,4} — merge both lists, drop the repeated 2 and 3.", reason: "Definition of union" }],
    explanation: "A ∪ B = {1,2,3,4}, so |A ∪ B| = 4.",
  },
  {
    id: "st-4",
    concept: "sets",
    difficulty: "medium",
    type: "mcq",
    question: "A ∩ B represents:",
    options: ["Elements in both A and B", "Elements in either A or B", "Elements only in A", "Elements not in A"],
    correctIndex: 0,
    explanation: "∩ is intersection — only elements shared by both sets.",
  },
  {
    id: "st-5",
    concept: "sets",
    difficulty: "easy",
    type: "fill-in",
    question: "How many elements are in the empty set ∅?",
    acceptableAnswers: ["0", "zero"],
    explanation: "By definition, ∅ contains no elements at all.",
  },

  // Functions & Sequences
  {
    id: "fs-1",
    concept: "functions-sequences",
    difficulty: "hard",
    type: "mcq",
    question: "f: Z → Z defined by f(x) = x² is:",
    options: ["Neither injective nor surjective", "Injective only", "Surjective only", "Bijective"],
    correctIndex: 0,
    steps: [
      { statement: "f(2) = 4 and f(-2) = 4 — two different inputs give the same output.", reason: "Squaring destroys the sign" },
      { statement: "Not injective. Also, -1 is never hit since no integer squares to a negative number.", reason: "Negative outputs are impossible, so f isn't surjective onto Z either" },
    ],
    explanation: "Squaring on the integers is neither one-to-one (loses sign information) nor onto (misses all negative numbers).",
  },
  {
    id: "fs-2",
    concept: "functions-sequences",
    difficulty: "hard",
    type: "fill-in",
    question: "A sequence is defined by aₙ = 3n − 1. Find a₅.",
    acceptableAnswers: ["14"],
    steps: [{ statement: "a₅ = 3(5) − 1 = 15 − 1", reason: "Substitute n=5" }, { statement: "= 14", reason: "Arithmetic" }],
    explanation: "a₅ = 3(5) − 1 = 14.",
  },
  {
    id: "fs-3",
    concept: "functions-sequences",
    difficulty: "medium",
    type: "mcq",
    question: "A function that is both injective and surjective is called:",
    options: ["Bijective", "Constant", "Identity", "Partial"],
    correctIndex: 0,
    explanation: "Bijective = one-to-one AND onto — exactly the condition needed for an inverse function to exist.",
  },
  {
    id: "fs-4",
    concept: "functions-sequences",
    difficulty: "medium",
    type: "fill-in",
    question: "Evaluate Σ (k=1 to 4) k.",
    acceptableAnswers: ["10"],
    steps: [{ statement: "1 + 2 + 3 + 4", reason: "Expand the summation" }, { statement: "= 10", reason: "Add them up" }],
    explanation: "1+2+3+4 = 10.",
  },
  {
    id: "fs-5",
    concept: "functions-sequences",
    difficulty: "easy",
    type: "mcq",
    question: "f(x) = x + 1 maps 3 to:",
    options: ["4", "3", "2", "5"],
    correctIndex: 0,
    explanation: "f(3) = 3 + 1 = 4.",
  },

  // Algorithms
  {
    id: "al-1",
    concept: "algorithms",
    difficulty: "hard",
    type: "mcq",
    question: "What is the worst-case time complexity of bubble sort on n elements?",
    options: ["O(n²)", "O(n log n)", "O(log n)", "O(n)"],
    correctIndex: 0,
    explanation: "Bubble sort compares adjacent pairs across up to n passes, each doing up to n comparisons — O(n²) in the worst case.",
  },
  {
    id: "al-2",
    concept: "algorithms",
    difficulty: "hard",
    type: "fill-in",
    question: "What is the maximum number of comparisons binary search needs on a sorted list of 16 elements?",
    acceptableAnswers: ["4"],
    steps: [
      { statement: "Binary search needs about log₂(n) comparisons in the worst case.", reason: "Each comparison halves the remaining search window" },
      { statement: "log₂(16) = 4, since 2⁴ = 16.", reason: "Direct computation" },
    ],
    explanation: "⌈log₂ 16⌉ = 4 comparisons in the worst case.",
  },
  {
    id: "al-3",
    concept: "algorithms",
    difficulty: "medium",
    type: "mcq",
    question: "Which of these grows fastest as n → ∞?",
    options: ["n!", "2ⁿ", "n²", "n log n"],
    correctIndex: 0,
    explanation: "Factorial growth outpaces exponential, which outpaces polynomial, which outpaces n log n.",
  },
  {
    id: "al-4",
    concept: "algorithms",
    difficulty: "medium",
    type: "fill-in",
    question: "Using greedy coin change with quarters(25), dimes(10), nickels(5), pennies(1), how many coins minimum for 41 cents?",
    acceptableAnswers: ["4"],
    steps: [
      { statement: "41 ≥ 25: take a quarter → 16 left.", reason: "Greedy: always take the largest coin that fits" },
      { statement: "16 ≥ 10: take a dime → 6 left.", reason: "Continue greedily" },
      { statement: "6 ≥ 5: take a nickel → 1 left.", reason: "Continue greedily" },
      { statement: "1 ≥ 1: take a penny → 0 left.", reason: "Done" },
    ],
    explanation: "1 quarter + 1 dime + 1 nickel + 1 penny = 4 coins.",
  },
  {
    id: "al-5",
    concept: "algorithms",
    difficulty: "easy",
    type: "mcq",
    question: "What is the time complexity of linear search on n elements?",
    options: ["O(n)", "O(log n)", "O(1)", "O(n²)"],
    correctIndex: 0,
    explanation: "Linear search may need to check every one of the n elements in the worst case.",
  },

  // Induction & Recursion
  {
    id: "ir-1",
    concept: "induction-recursion",
    difficulty: "hard",
    type: "mcq",
    question: "In a proof by induction, the inductive hypothesis assumes:",
    options: ["P(k) is true for an arbitrary k", "P(1) is true", "P(n) is true for all n", "P(k+1) is true"],
    correctIndex: 0,
    explanation: "The inductive hypothesis assumes P(k) for an arbitrary (but fixed) k, then the inductive step must show P(k) ⟹ P(k+1).",
  },
  {
    id: "ir-2",
    concept: "induction-recursion",
    difficulty: "hard",
    type: "fill-in",
    question: "f(n) = f(n-1) + 2, f(0) = 5. Find f(3).",
    acceptableAnswers: ["11"],
    steps: [
      { statement: "f(1) = f(0)+2 = 5+2 = 7", reason: "Apply the rule with n=1" },
      { statement: "f(2) = f(1)+2 = 7+2 = 9", reason: "Apply the rule with n=2" },
      { statement: "f(3) = f(2)+2 = 9+2 = 11", reason: "Apply the rule with n=3" },
    ],
    explanation: "Unwinding the recurrence three times from f(0)=5 gives f(3) = 11.",
  },
  {
    id: "ir-3",
    concept: "induction-recursion",
    difficulty: "medium",
    type: "mcq",
    question: "What must the basis step of an induction proof establish?",
    options: ["P is true for the smallest case", "P is true for all n", "The inductive step", "Nothing — it's optional"],
    correctIndex: 0,
    explanation: "The basis step checks the starting case (often n=0 or n=1) directly — without it, the inductive chain has nothing to start from.",
  },
  {
    id: "ir-4",
    concept: "induction-recursion",
    difficulty: "medium",
    type: "fill-in",
    question: "The recursive definition of factorial has its base case at n = ?",
    acceptableAnswers: ["0", "n=0"],
    explanation: "0! = 1 is the base case; every other value unwinds via n! = n × (n-1)!.",
  },
  {
    id: "ir-5",
    concept: "induction-recursion",
    difficulty: "easy",
    type: "mcq",
    question: "What essential component does recursion need to terminate?",
    options: ["A base case", "A loop", "A pointer", "A global variable"],
    correctIndex: 0,
    explanation: "Without a base case, a recursive function calls itself forever — the base case is what lets the recursion actually stop.",
  },

  // Counting
  {
    id: "ct-1",
    concept: "counting",
    difficulty: "hard",
    type: "fill-in",
    question: "How many 4-digit PINs are possible using digits 0-9 (repetition allowed)?",
    acceptableAnswers: ["10000", "10,000"],
    steps: [{ statement: "Each of the 4 digit positions independently has 10 choices.", reason: "Product rule" }, { statement: "10 × 10 × 10 × 10 = 10,000", reason: "Multiply the choices" }],
    explanation: "10⁴ = 10,000 possible PINs.",
  },
  {
    id: "ct-2",
    concept: "counting",
    difficulty: "hard",
    type: "mcq",
    question: "With 13 people, the pigeonhole principle guarantees at least 2 share a birth month because:",
    options: ["13 people > 12 months", "13 is a prime number", "Months always repeat", "Birthdays are random"],
    correctIndex: 0,
    explanation: "13 pigeons (people) into 12 holes (months) forces at least one hole to hold ≥2 pigeons — the basic pigeonhole principle.",
  },
  {
    id: "ct-3",
    concept: "counting",
    difficulty: "medium",
    type: "fill-in",
    question: "Compute C(6,2), the number of ways to choose 2 items from 6 (order doesn't matter).",
    acceptableAnswers: ["15"],
    steps: [{ statement: "C(6,2) = 6!/(2!×4!) = 720/(2×24)", reason: "Combination formula" }, { statement: "= 720/48 = 15", reason: "Arithmetic" }],
    explanation: "C(6,2) = 15.",
  },
  {
    id: "ct-4",
    concept: "counting",
    difficulty: "medium",
    type: "mcq",
    question: "Choosing r items from n where order DOES matter is called a:",
    options: ["Permutation", "Combination", "Partition", "Subset"],
    correctIndex: 0,
    explanation: "Permutations count ordered arrangements; combinations count unordered selections.",
  },
  {
    id: "ct-5",
    concept: "counting",
    difficulty: "easy",
    type: "fill-in",
    question: "Compute P(4,2), the number of ways to arrange 2 items chosen from 4 (order matters).",
    acceptableAnswers: ["12"],
    steps: [{ statement: "P(4,2) = 4!/(4-2)! = 4!/2! = 24/2", reason: "Permutation formula" }, { statement: "= 12", reason: "Arithmetic" }],
    explanation: "P(4,2) = 4 × 3 = 12.",
  },

  // Relations
  {
    id: "rl-1",
    concept: "relations",
    difficulty: "hard",
    type: "mcq",
    question: "A relation that is reflexive, symmetric, AND transitive is called:",
    options: ["An equivalence relation", "A partial order", "A function", "Antisymmetric"],
    correctIndex: 0,
    explanation: "That exact combination of three properties defines an equivalence relation, which always partitions a set into equivalence classes.",
  },
  {
    id: "rl-2",
    concept: "relations",
    difficulty: "hard",
    type: "fill-in",
    question: "R = {(1,1),(2,2),(3,3),(1,2),(2,1)} on {1,2,3}. Is R transitive? Type Yes or No.",
    acceptableAnswers: ["yes", "y", "true"],
    steps: [
      { statement: "Check (1,2) and (2,1): need (1,1) — present ✓.", reason: "Transitivity check for this pair" },
      { statement: "Check (2,1) and (1,2): need (2,2) — present ✓.", reason: "Transitivity check for the reverse pair" },
      { statement: "No other combinations of pairs need checking.", reason: "All chained pairs have been covered" },
    ],
    explanation: "Every chain of related pairs also has its shortcut pair present, so R is transitive.",
  },
  {
    id: "rl-3",
    concept: "relations",
    difficulty: "medium",
    type: "mcq",
    question: "A relation is antisymmetric when:",
    options: [
      "(a,b) and (b,a) both in R forces a=b",
      "a=b implies (a,b) is in R",
      "R contains no pairs at all",
      "R is automatically symmetric too",
    ],
    correctIndex: 0,
    explanation: "Antisymmetric forbids two DIFFERENT elements from relating to each other in both directions.",
  },
  {
    id: "rl-4",
    concept: "relations",
    difficulty: "medium",
    type: "fill-in",
    question: "How many ordered pairs (a,b) satisfy a ≤ b on the set {1,2,3}?",
    acceptableAnswers: ["6"],
    steps: [{ statement: "List them: (1,1),(1,2),(1,3),(2,2),(2,3),(3,3).", reason: "Every pair where the first is ≤ the second" }],
    explanation: "There are 6 such pairs.",
  },
  {
    id: "rl-5",
    concept: "relations",
    difficulty: "easy",
    type: "mcq",
    question: "A relation on set A is formally a subset of:",
    options: ["A × A", "A", "P(A)", "A ∪ A"],
    correctIndex: 0,
    explanation: "A relation on A is any set of ordered pairs (a,b) with a,b ∈ A — i.e. a subset of the Cartesian product A × A.",
  },

  // Graphs
  {
    id: "gr-1",
    concept: "graphs",
    difficulty: "hard",
    type: "mcq",
    question: "A connected graph has an Euler circuit if and only if:",
    options: ["Every vertex has even degree", "Every vertex has odd degree", "It's a tree", "It has no cycles"],
    correctIndex: 0,
    explanation: "Euler circuit theorem: every vertex must have even degree so the circuit can enter and leave through paired-up edges every time.",
  },
  {
    id: "gr-2",
    concept: "graphs",
    difficulty: "hard",
    type: "fill-in",
    question: "How many edges does the complete graph K₆ have?",
    acceptableAnswers: ["15"],
    steps: [{ statement: "Every pair of the 6 vertices is connected: C(6,2) = 6!/(2!×4!)", reason: "Complete graph definition" }, { statement: "= 15", reason: "Arithmetic" }],
    explanation: "K₆ has C(6,2) = 15 edges.",
  },
  {
    id: "gr-3",
    concept: "graphs",
    difficulty: "medium",
    type: "mcq",
    question: "Dijkstra's algorithm requires edge weights to be:",
    options: ["Non-negative", "All equal", "Negative", "Irrelevant"],
    correctIndex: 0,
    explanation: "Dijkstra's greedy approach breaks down with negative weights, since a 'finalized' shortest distance could later be undercut by a negative edge.",
  },
  {
    id: "gr-4",
    concept: "graphs",
    difficulty: "medium",
    type: "fill-in",
    question: "A graph has 8 edges. What is the sum of all vertex degrees?",
    acceptableAnswers: ["16"],
    steps: [{ statement: "The Handshake Theorem: sum of degrees = 2 × number of edges.", reason: "Every edge contributes exactly 2 to the total degree count" }, { statement: "2 × 8 = 16", reason: "Arithmetic" }],
    explanation: "Sum of degrees = 2 × 8 = 16.",
  },
  {
    id: "gr-5",
    concept: "graphs",
    difficulty: "easy",
    type: "mcq",
    question: "An edge connecting a vertex to itself is called a:",
    options: ["Loop", "Bridge", "Cycle", "Path"],
    correctIndex: 0,
    explanation: "A loop is a self-connecting edge — most simple-graph definitions exclude them, but multigraphs allow them.",
  },

  // Trees
  {
    id: "tr-1",
    concept: "trees",
    difficulty: "hard",
    type: "fill-in",
    question: "A full binary tree (every node has 0 or 2 children) has 15 total nodes. How many are leaves?",
    acceptableAnswers: ["8"],
    steps: [
      { statement: "For a full binary tree, leaves = internal nodes + 1.", reason: "Property of full binary trees" },
      { statement: "Total = internal + leaves = internal + (internal+1) = 2×internal + 1 = 15, so internal = 7.", reason: "Solve for internal nodes" },
      { statement: "Leaves = internal + 1 = 8.", reason: "Substitute back" },
    ],
    explanation: "A full binary tree with 15 nodes has 8 leaves and 7 internal nodes.",
  },
  {
    id: "tr-2",
    concept: "trees",
    difficulty: "hard",
    type: "mcq",
    question: "Huffman coding assigns the SHORTEST codes to:",
    options: ["The most frequent symbols", "The least frequent symbols", "Alphabetically first symbols", "The longest symbols"],
    correctIndex: 0,
    explanation: "Huffman merges the least-frequent symbols first, pushing frequent symbols near the root — closer to the root means a shorter code.",
  },
  {
    id: "tr-3",
    concept: "trees",
    difficulty: "medium",
    type: "mcq",
    question: "In a binary search tree, where do values LARGER than a node go?",
    options: ["Right subtree", "Left subtree", "The root", "It doesn't matter"],
    correctIndex: 0,
    explanation: "BST invariant: smaller goes left, larger goes right — at every single node in the tree.",
  },
  {
    id: "tr-4",
    concept: "trees",
    difficulty: "medium",
    type: "fill-in",
    question: "A tree has 10 vertices. How many edges does it have?",
    acceptableAnswers: ["9"],
    steps: [{ statement: "A tree with n vertices always has exactly n-1 edges.", reason: "Defining property of a tree — connected and acyclic" }, { statement: "10 - 1 = 9", reason: "Arithmetic" }],
    explanation: "Every tree has exactly (vertices − 1) edges — here, 9.",
  },
  {
    id: "tr-5",
    concept: "trees",
    difficulty: "easy",
    type: "mcq",
    question: "The topmost node of a rooted tree is called the:",
    options: ["Root", "Leaf", "Child", "Edge"],
    correctIndex: 0,
    explanation: "The root is the single topmost node that every other node descends from.",
  },
];
