export interface WorkedProblem {
  id: string;
  label: string;
  given?: string;
  goal: string;
  steps: { statement: string; reason: string }[];
  conclusion: string;
}

export const part1WorkedProblems: WorkedProblem[] = [
  {
    id: "1.1-ex1",
    label: "Section 1.1, Exercise 1 — is it a proposition?",
    given:
      "a) Miami is the capital of Florida.\nb) 2 + 3 = 5\nc) 5 + 7 = 10\nd) x + 2 = 11\ne) Answer this question.",
    goal: "Decide which of a-e are propositions (declarative sentences that are definitely true or definitely false), and give the truth value of the ones that are.",
    steps: [
      { statement: "(a) is a declarative sentence with a fixed, checkable truth value.", reason: "It claims a specific fact about the world" },
      { statement: "(a) is a proposition, and it is FALSE — Tallahassee is Florida's capital, not Miami.", reason: "Verifiable fact" },
      { statement: "(b) is a declarative sentence with a fixed truth value.", reason: "It's a closed arithmetic claim" },
      { statement: "(b) is a proposition, and it is TRUE.", reason: "2 + 3 does equal 5" },
      { statement: "(c) is a declarative sentence with a fixed truth value.", reason: "Same reasoning as (b)" },
      { statement: "(c) is a proposition, and it is FALSE — 5 + 7 = 12, not 10.", reason: "Arithmetic check" },
      { statement: "(d) contains a variable x, so its truth depends on what x is — it isn't fixed.", reason: "\"x + 2 = 11\" is true for x=9 and false for every other x" },
      { statement: "(d) is NOT a proposition — it's a predicate/open sentence, not a proposition.", reason: "No fixed truth value until x is specified" },
      { statement: "(e) is a command/question, not a declarative sentence at all.", reason: "It has no truth value — it's an instruction" },
      { statement: "(e) is NOT a proposition.", reason: "Questions and commands are never propositions" },
    ],
    conclusion: "Propositions: (a) false, (b) true, (c) false. Not propositions: (d) (a predicate — depends on x) and (e) (a command).",
  },
  {
    id: "1.1-ex9",
    label: "Section 1.1, Exercise 9 — translating compound propositions",
    given: "p: \"I bought a lottery ticket this week.\"\nq: \"I won the million dollar jackpot.\"",
    goal: "Translate ¬p, p ∨ q, p → q, p ∧ q, p ↔ q, and ¬p ∧ ¬q into plain English.",
    steps: [
      { statement: "¬p  →  \"I did not buy a lottery ticket this week.\"", reason: "¬ just negates the sentence" },
      { statement: "p ∨ q  →  \"I bought a lottery ticket this week, or I won the million dollar jackpot (or both).\"", reason: "∨ is inclusive or — true if either or both hold" },
      { statement: "p → q  →  \"If I bought a lottery ticket this week, then I won the million dollar jackpot.\"", reason: "→ reads as \"if p then q\"" },
      { statement: "p ∧ q  →  \"I bought a lottery ticket this week and I won the million dollar jackpot.\"", reason: "∧ requires both parts true" },
      { statement: "p ↔ q  →  \"I bought a lottery ticket this week if and only if I won the million dollar jackpot.\"", reason: "↔ asserts the two sides always match" },
      { statement: "¬p ∧ ¬q  →  \"I did not buy a lottery ticket this week, and I did not win the million dollar jackpot.\"", reason: "Negate each piece, then join with and" },
    ],
    conclusion: "Each connective has a fixed, literal English reading — the skill is matching the symbol to its exact phrase (∨ = \"or\", → = \"if...then\", ↔ = \"if and only if\").",
  },
  {
    id: "1.1-ex27",
    label: "Section 1.1, Exercise 27 — converse, contrapositive, inverse",
    given: "Conditional statement: \"If it snows tonight, then I will stay home.\" (p → q, where p = \"it snows tonight\", q = \"I will stay home\")",
    goal: "State the converse, contrapositive, and inverse of p → q.",
    steps: [
      { statement: "Converse: q → p", reason: "Swap the hypothesis and conclusion" },
      { statement: "Converse in English: \"If I stay home, then it snows tonight.\"", reason: "Substitute back the plain-English meanings" },
      { statement: "Contrapositive: ¬q → ¬p", reason: "Swap AND negate both sides — this one is logically equivalent to the original" },
      { statement: "Contrapositive in English: \"If I do not stay home, then it does not snow tonight.\"", reason: "Substitute back" },
      { statement: "Inverse: ¬p → ¬q", reason: "Negate both sides without swapping" },
      { statement: "Inverse in English: \"If it does not snow tonight, then I will not stay home.\"", reason: "Substitute back" },
    ],
    conclusion: "Only the contrapositive (¬q → ¬p) is guaranteed logically equivalent to the original p → q. The converse and inverse are each other's contrapositives, but neither is equivalent to the original — a very common source of invalid arguments.",
  },
  {
    id: "1.2-ex9",
    label: "Section 1.2, Exercise 9 — is the system specification consistent?",
    given:
      "\"The router can send packets to the edge system only if it supports the new address space. For the router to support the new address space, it is necessary that the latest software release be installed. The router can send packets to the edge system if the latest software release is installed. The router does not support the new address space.\"",
    goal: "Assign propositional variables and determine whether these four specifications can all be true at once (i.e. are they consistent?).",
    steps: [
      { statement: "Let p = \"the router can send packets to the edge system\", q = \"it supports the new address space\", r = \"the latest software release is installed.\"", reason: "Name every distinct claim once" },
      { statement: "Spec 1: p → q  (send only if supports new address space)", reason: "\"only if\" translates to →" },
      { statement: "Spec 2: q → r  (supporting requires the release installed)", reason: "\"necessary that\" also translates to →, release is the necessary condition" },
      { statement: "Spec 3: r → p  (send if release installed)", reason: "\"if\" translates to →" },
      { statement: "Spec 4: ¬q  (does not support new address space)", reason: "Direct negation" },
      { statement: "From spec 4, q is false. Spec 2 (q → r) is then true no matter what r is — it places no constraint yet.", reason: "A false hypothesis makes any → automatically true" },
      { statement: "Try r = false: spec 3 (r → p) is true automatically; spec 1 (p → q) forces p to be false too (since q is false, p can't be true).", reason: "p → q with q false requires p false" },
      { statement: "Check: p=false, q=false, r=false satisfies all four: p→q ✓, q→r ✓, r→p ✓, ¬q ✓.", reason: "Direct substitution check" },
    ],
    conclusion: "Yes — the specifications are consistent. p = q = r = false (the router doesn't send packets, doesn't support the new address space, and doesn't have the release installed) satisfies every specification simultaneously.",
  },
  {
    id: "1.3-demorgan",
    label: "Section 1.3 — proving a De Morgan's Law: ¬(p ∨ q) ≡ ¬p ∧ ¬q",
    goal: "Prove the two propositions are logically equivalent using a truth table (the membership-table style proof from 1.3).",
    steps: [
      { statement: "List every combination of p, q: (T,T), (T,F), (F,T), (F,F).", reason: "A proof by truth table must cover every case" },
      { statement: "(T,T): p∨q = T, so ¬(p∨q) = F. Also ¬p=F, ¬q=F, so ¬p∧¬q = F. Match.", reason: "Row-by-row evaluation" },
      { statement: "(T,F): p∨q = T, so ¬(p∨q) = F. ¬p=F, ¬q=T, so ¬p∧¬q = F. Match.", reason: "Row-by-row evaluation" },
      { statement: "(F,T): p∨q = T, so ¬(p∨q) = F. ¬p=T, ¬q=F, so ¬p∧¬q = F. Match.", reason: "Row-by-row evaluation" },
      { statement: "(F,F): p∨q = F, so ¬(p∨q) = T. ¬p=T, ¬q=T, so ¬p∧¬q = T. Match.", reason: "Row-by-row evaluation" },
      { statement: "Every row produces identical truth values for ¬(p∨q) and ¬p∧¬q.", reason: "All four cases checked" },
    ],
    conclusion: "Since the two columns match in all 4 rows, ¬(p ∨ q) ≡ ¬p ∧ ¬q — try it yourself in the Truth Table simulator above by typing both expressions.",
  },
];

export const part2WorkedProblems: WorkedProblem[] = [
  {
    id: "1.4-ex1",
    label: "Section 1.4, Exercise 1 — evaluating a predicate",
    given: "P(x): \"x ≥ 4\"",
    goal: "Find the truth values of P(0), P(4), and P(6).",
    steps: [
      { statement: "P(0) asks: is 0 ≥ 4?", reason: "Substitute x = 0 into the predicate" },
      { statement: "P(0) is FALSE.", reason: "0 is not ≥ 4" },
      { statement: "P(4) asks: is 4 ≥ 4?", reason: "Substitute x = 4" },
      { statement: "P(4) is TRUE.", reason: "4 ≥ 4 holds (≥ includes equality)" },
      { statement: "P(6) asks: is 6 ≥ 4?", reason: "Substitute x = 6" },
      { statement: "P(6) is TRUE.", reason: "6 is ≥ 4" },
    ],
    conclusion: "A predicate like P(x) isn't true or false on its own — it only becomes a genuine proposition once you plug in a specific value for x.",
  },
  {
    id: "1.5-ex1",
    label: "Section 1.5, Exercise 1 — translating nested quantifiers",
    given: "Domain: all real numbers. Let Q(x,y): \"x + y = 0\".",
    goal: "Translate ∀x∃y Q(x,y) and ∃x∀y Q(x,y) into English, and determine the truth value of each.",
    steps: [
      { statement: "∀x∃y Q(x,y) reads: \"For every real x, there exists a real y such that x + y = 0.\"", reason: "Read outer-to-inner: ∀x first, then ∃y" },
      { statement: "Given any x, pick y = −x. Then x + y = x + (−x) = 0.", reason: "Every x has its own working y — namely its negative" },
      { statement: "∀x∃y Q(x,y) is TRUE.", reason: "A valid y (=−x) always exists, for every x" },
      { statement: "∃x∀y Q(x,y) reads: \"There exists a real x such that, for every real y, x + y = 0.\"", reason: "Read outer-to-inner: ∃x first, then ∀y" },
      { statement: "This would require ONE fixed x that makes x+y=0 for ALL y simultaneously — impossible unless y never changes.", reason: "y ranges over all reals, so x+y can't stay 0 for every y" },
      { statement: "∃x∀y Q(x,y) is FALSE.", reason: "No single x works for every y" },
    ],
    conclusion: "Same predicate, opposite truth values — purely because of quantifier order. ∀x∃y lets each x pick its own y; ∃x∀y demands one x that beats every y. Try the Quantifier Visualizer above with pattern EA vs AE to see the same flip on a small finite domain.",
  },
  {
    id: "1.6-ex17",
    label: "Section 1.6, Exercise 17 — spotting an invalid inference",
    given:
      "Argument given: \"Everyone in this class has taken a course in computer science. Marla is a student in this class. Therefore, Marla has taken a course in computer science.\"",
    goal: "Determine whether this argument is valid, and if so, name the rule of inference used.",
    steps: [
      { statement: "Formalize: ∀x (Student(x) → TookCS(x)); Student(Marla). Conclusion: TookCS(Marla).", reason: "Assign the universal statement and the specific fact" },
      { statement: "Apply universal instantiation to the first premise with x = Marla: Student(Marla) → TookCS(Marla).", reason: "Universal instantiation: a ∀x statement holds for any specific individual" },
      { statement: "Apply modus ponens: Student(Marla) is true, and Student(Marla) → TookCS(Marla) is true, so TookCS(Marla) is true.", reason: "Modus ponens: from p and p→q, conclude q" },
    ],
    conclusion: "This argument IS valid — it's universal instantiation followed by modus ponens. (Contrast: an argument that instead assumed \"Marla took a CS course, therefore Marla is in this class\" would be the invalid fallacy of affirming the conclusion — order matters.)",
  },
];

export const part3WorkedProblems: WorkedProblem[] = [
  {
    id: "1.7-direct",
    label: "Section 1.7, Example 1 — a direct proof",
    given: "Let n be an integer.",
    goal: "Prove: if n is odd, then n² is odd.",
    steps: [
      { statement: "Assume n is odd (this is the hypothesis we get to use directly).", reason: "Direct proof: assume the hypothesis, derive the conclusion" },
      { statement: "By definition of odd, n = 2k + 1 for some integer k.", reason: "Definition of an odd integer" },
      { statement: "n² = (2k+1)² = 4k² + 4k + 1", reason: "Expand the square" },
      { statement: "n² = 2(2k² + 2k) + 1", reason: "Factor out a 2 from the first two terms" },
      { statement: "2k² + 2k is an integer, call it m. So n² = 2m + 1.", reason: "Sum/product of integers is an integer" },
      { statement: "n² = 2m + 1 matches the exact definition of an odd number.", reason: "Definition of odd" },
    ],
    conclusion: "So n² is odd whenever n is odd — proved directly by unfolding the definition of \"odd\" and algebraically reshaping the result back into that same definition.",
  },
  {
    id: "1.7-contradiction",
    label: "Section 1.7, Example 10 — a proof by contradiction",
    goal: "Prove that √2 is irrational.",
    steps: [
      { statement: "Suppose, for contradiction, that √2 IS rational.", reason: "Proof by contradiction: assume the opposite of what we want, then derive nonsense" },
      { statement: "Then √2 = a/b for some integers a, b with no common factors (the fraction is fully reduced).", reason: "Definition of rational, in lowest terms" },
      { statement: "Squaring both sides: 2 = a²/b², so a² = 2b².", reason: "Algebra" },
      { statement: "a² = 2b² means a² is even, which means a itself must be even (odd² is always odd).", reason: "Contrapositive of the odd² = odd fact just proved above" },
      { statement: "Since a is even, write a = 2c for some integer c.", reason: "Definition of even" },
      { statement: "Substitute: (2c)² = 2b² → 4c² = 2b² → b² = 2c².", reason: "Algebra" },
      { statement: "b² = 2c² means b² is even, so b is even too.", reason: "Same odd/even fact applied again" },
      { statement: "But a and b were assumed to share NO common factors — yet we just showed both are even, i.e. both divisible by 2.", reason: "Direct contradiction of the lowest-terms assumption" },
    ],
    conclusion: "This is a contradiction, so the original assumption (that √2 is rational) must be false. Therefore √2 is irrational. ∎ — one of the oldest and most celebrated proofs in mathematics.",
  },
  {
    id: "1.7-ex22",
    label: "Section 1.7, Exercise 22 — the sock-drawer pigeonhole proof",
    given: "A drawer contains socks of only two colors: black and white.",
    goal: "Prove that if you pull out 3 socks (without looking), at least 2 of them must be the same color.",
    steps: [
      { statement: "There are only 2 possible colors a sock can be: black or white.", reason: "Given constraint" },
      { statement: "Suppose, for contradiction, that all 3 socks pulled are different colors from each other.", reason: "Attempt the opposite of the claim" },
      { statement: "That would require at least 3 distinct colors to exist among the socks.", reason: "3 mutually-different socks need 3 distinct categories" },
      { statement: "But only 2 colors exist in the drawer — contradiction.", reason: "2 categories can't produce 3 mutually distinct items" },
    ],
    conclusion: "So it's impossible for all 3 socks to differ — at least two must share a color. This is the Pigeonhole Principle in miniature: 3 \"pigeons\" (socks), 2 \"holes\" (colors), so some hole gets ≥2 pigeons. It resurfaces formally in Part 8 (Counting).",
  },
  {
    id: "1.8-ex26",
    label: "Section 1.8, Exercise 26 — an if-and-only-if proof",
    goal: "Prove: n is even if and only if 7n + 4 is even.",
    steps: [
      { statement: "An \"iff\" proof needs BOTH directions proved separately.", reason: "p ↔ q means (p→q) AND (q→p)" },
      { statement: "Direction 1 (n even → 7n+4 even): assume n = 2k for some integer k.", reason: "Definition of even" },
      { statement: "7n + 4 = 7(2k) + 4 = 14k + 4 = 2(7k + 2).", reason: "Algebra, factoring out 2" },
      { statement: "7k+2 is an integer, so 7n+4 = 2·(integer) — even. Direction 1 done.", reason: "Definition of even" },
      { statement: "Direction 2 (7n+4 even → n even): use the contrapositive instead — assume n is odd, show 7n+4 is odd.", reason: "Proving the contrapositive ¬q→¬p is equivalent to proving q→p, and is easier here" },
      { statement: "n odd means n = 2k+1. Then 7n+4 = 7(2k+1)+4 = 14k+11 = 2(7k+5)+1.", reason: "Algebra" },
      { statement: "2(7k+5)+1 matches the definition of odd. So n odd ⟹ 7n+4 odd, i.e. ¬(n even) ⟹ ¬(7n+4 even).", reason: "Definition of odd, contrapositive established" },
    ],
    conclusion: "Both directions hold, so n is even ⟺ 7n + 4 is even. ∎ Notice direction 2 was proved via its contrapositive rather than head-on — a standard trick when the direct route is awkward.",
  },
];

export const part4WorkedProblems: WorkedProblem[] = [
  {
    id: "2.1-ex1",
    label: "Section 2.1, Exercise 1 — roster notation",
    given: "The set of all integers whose square is less than or equal to 4.",
    goal: "List the set using roster notation (the {a, b, c, ...} form).",
    steps: [
      { statement: "We need every integer n with n² ≤ 4.", reason: "Direct translation of the description" },
      { statement: "Check candidates: (-3)²=9 too big. (-2)²=4 ✓. (-1)²=1 ✓. 0²=0 ✓. 1²=1 ✓. 2²=4 ✓. 3²=9 too big.", reason: "Test integers moving outward from 0" },
      { statement: "The valid integers are -2, -1, 0, 1, 2.", reason: "Collect every integer that passed the check" },
    ],
    conclusion: "The set is {-2, -1, 0, 1, 2}.",
  },
  {
    id: "2.1-ex19",
    label: "Section 2.1, Exercise 19 — cardinality with nested sets",
    given: "The set {a, {a}}.",
    goal: "Find the cardinality (number of elements) of this set.",
    steps: [
      { statement: "Count the top-level elements only — don't unpack nested sets.", reason: "Cardinality counts elements, and a set can itself be an element" },
      { statement: "Element 1: a (a plain element).", reason: "First listed member" },
      { statement: "Element 2: {a} (the SET containing a, which is a different object from a itself).", reason: "A set and its lone element are not the same thing" },
      { statement: "There are exactly 2 distinct top-level elements.", reason: "a ≠ {a}, so both count separately" },
    ],
    conclusion: "|{a, {a}}| = 2 — a classic trap exercise, since it's tempting to think {a} \"is\" a and collapse it to 1.",
  },
  {
    id: "2.1-ex21",
    label: "Section 2.1, Exercise 21 — power sets",
    given: "The set {0, 1, 2}.",
    goal: "Find the power set P({0,1,2}) — the set of ALL subsets.",
    steps: [
      { statement: "A set with n elements has 2ⁿ subsets, including the empty set and the whole set itself.", reason: "Each of the n elements is independently either 'in' or 'out' of a subset — 2 choices each" },
      { statement: "Here n = 3, so there are 2³ = 8 subsets.", reason: "Direct application of the 2ⁿ formula" },
      { statement: "List them by size: size 0: ∅. size 1: {0},{1},{2}. size 2: {0,1},{0,2},{1,2}. size 3: {0,1,2}.", reason: "Systematically list by how many elements are included" },
    ],
    conclusion: "P({0,1,2}) = { ∅, {0}, {1}, {2}, {0,1}, {0,2}, {1,2}, {0,1,2} } — exactly 8 subsets, matching 2³.",
  },
  {
    id: "2.2-ex3",
    label: "Section 2.2, Exercise 3 — union, intersection, difference",
    given: "A = {1,3,5,7,9}, B = {3,4,5,6,7}.",
    goal: "Find A ∪ B, A ∩ B, A − B, and B − A.",
    steps: [
      { statement: "A ∪ B collects every element that's in A OR in B (no duplicates).", reason: "Definition of union" },
      { statement: "A ∪ B = {1,3,4,5,6,7,9}", reason: "Merge both lists, drop repeats" },
      { statement: "A ∩ B keeps only elements in BOTH A and B.", reason: "Definition of intersection" },
      { statement: "A ∩ B = {3,5,7}", reason: "Elements shared by both lists" },
      { statement: "A − B keeps elements in A that are NOT in B.", reason: "Definition of set difference" },
      { statement: "A − B = {1,9}", reason: "Remove anything from A that also appears in B" },
      { statement: "B − A keeps elements in B that are NOT in A.", reason: "Set difference the other direction" },
      { statement: "B − A = {4,6}", reason: "Remove anything from B that also appears in A" },
    ],
    conclusion: "A∪B={1,3,4,5,6,7,9}, A∩B={3,5,7}, A−B={1,9}, B−A={4,6} — try the same two sets in the Venn diagram simulator above to see it visually.",
  },
  {
    id: "2.2-ex15",
    label: "Section 2.2, Exercise 15 — proving a De Morgan's Law for sets",
    goal: "Prove (A ∩ B)‾ = A‾ ∪ B‾ using a membership table.",
    steps: [
      { statement: "A membership table lists, for every region (in A or not, in B or not), whether each side is 1 (member) or 0 (not).", reason: "This is the set-theory analogue of a truth table" },
      { statement: "Case x∈A, x∈B: A∩B=1 so (A∩B)‾=0. Also A‾=0, B‾=0, so A‾∪B‾=0. Match.", reason: "Row 1" },
      { statement: "Case x∈A, x∉B: A∩B=0 so (A∩B)‾=1. A‾=0, B‾=1, so A‾∪B‾=1. Match.", reason: "Row 2" },
      { statement: "Case x∉A, x∈B: A∩B=0 so (A∩B)‾=1. A‾=1, B‾=0, so A‾∪B‾=1. Match.", reason: "Row 3" },
      { statement: "Case x∉A, x∉B: A∩B=0 so (A∩B)‾=1. A‾=1, B‾=1, so A‾∪B‾=1. Match.", reason: "Row 4" },
      { statement: "All 4 possible membership cases produce identical results on both sides.", reason: "Exhaustive check" },
    ],
    conclusion: "Since every case matches, (A∩B)‾ = A‾∪B‾ — exactly the same proof technique as the propositional-logic De Morgan's law in Part 1, because ∩/∪/complement behave exactly like ∧/∨/¬.",
  },
  {
    id: "2.2-ex32",
    label: "Section 2.2, Exercise 32 — symmetric difference",
    given: "A = {1,2,3,4,5}, B = {4,5,6,7,8}.",
    goal: "Find the symmetric difference A ⊕ B (elements in exactly one of the two sets, not both).",
    steps: [
      { statement: "A ⊕ B = (A − B) ∪ (B − A) — everything in exactly one set.", reason: "Definition of symmetric difference" },
      { statement: "A − B = {1,2,3} (drop the shared 4,5)", reason: "Elements only in A" },
      { statement: "B − A = {6,7,8} (drop the shared 4,5)", reason: "Elements only in B" },
      { statement: "Union those two: {1,2,3,6,7,8}", reason: "Combine both one-sided differences" },
    ],
    conclusion: "A ⊕ B = {1,2,3,6,7,8} — notice the shared elements {4,5} are excluded entirely, which is exactly what \"exclusive or\" for sets means.",
  },
];

export const part5WorkedProblems: WorkedProblem[] = [
  {
    id: "2.3-ex10",
    label: "Section 2.3, Exercise 10 — is this function one-to-one?",
    given: "f: Z → Z defined by f(x) = x² + 1, where Z is the set of integers.",
    goal: "Determine whether f is injective (one-to-one).",
    steps: [
      { statement: "A function is injective if f(a)=f(b) always forces a=b.", reason: "Definition of one-to-one" },
      { statement: "Try x = 2: f(2) = 4+1 = 5. Try x = -2: f(-2) = 4+1 = 5.", reason: "Test a candidate counterexample using the squaring symmetry" },
      { statement: "f(2) = f(-2) = 5, but 2 ≠ -2.", reason: "Two different inputs produced the same output" },
    ],
    conclusion: "f is NOT injective — squaring destroys the sign, so every nonzero output is hit by two different inputs (x and -x).",
  },
  {
    id: "2.3-ex36",
    label: "Section 2.3, Exercise 36 — composing functions",
    given: "f(x) = 2x + 1 and g(x) = 3x + 4, both from Z to Z.",
    goal: "Find (f∘g)(x) and (g∘f)(x), and check whether they're equal.",
    steps: [
      { statement: "(f∘g)(x) means apply g first, then f: f(g(x)).", reason: "Definition of composition, right-to-left" },
      { statement: "g(x) = 3x+4, so f(g(x)) = 2(3x+4)+1 = 6x+8+1 = 6x+9.", reason: "Substitute g(x) into f" },
      { statement: "(g∘f)(x) means apply f first, then g: g(f(x)).", reason: "Definition of composition, the other order" },
      { statement: "f(x) = 2x+1, so g(f(x)) = 3(2x+1)+4 = 6x+3+4 = 6x+7.", reason: "Substitute f(x) into g" },
    ],
    conclusion: "(f∘g)(x) = 6x+9 while (g∘f)(x) = 6x+7 — they're different, confirming function composition is generally NOT commutative.",
  },
  {
    id: "2.4-ex1",
    label: "Section 2.4, Exercise 1 — evaluating sequence terms",
    given: "aₙ = -2n + 25.",
    goal: "Find a₁, a₂, and a₁₀.",
    steps: [
      { statement: "a₁ = -2(1)+25 = -2+25", reason: "Substitute n=1" },
      { statement: "a₁ = 23", reason: "Arithmetic" },
      { statement: "a₂ = -2(2)+25 = -4+25", reason: "Substitute n=2" },
      { statement: "a₂ = 21", reason: "Arithmetic" },
      { statement: "a₁₀ = -2(10)+25 = -20+25", reason: "Substitute n=10" },
      { statement: "a₁₀ = 5", reason: "Arithmetic" },
    ],
    conclusion: "a₁=23, a₂=21, a₁₀=5 — each term just plugs n into the closed formula directly, no need to know earlier terms (unlike a recurrence).",
  },
  {
    id: "2.4-ex16",
    label: "Section 2.4, Exercise 16 — solving a recurrence from an initial condition",
    given: "aₙ = aₙ₋₁ + 2, a₀ = 3.",
    goal: "Find a₁, a₂, a₃, and guess a closed formula for aₙ.",
    steps: [
      { statement: "a₁ = a₀ + 2 = 3+2 = 5", reason: "Apply the recurrence once" },
      { statement: "a₂ = a₁ + 2 = 5+2 = 7", reason: "Apply the recurrence again" },
      { statement: "a₃ = a₂ + 2 = 7+2 = 9", reason: "Apply the recurrence a third time" },
      { statement: "Each step adds 2, starting from 3: the terms are 3, 5, 7, 9 — an arithmetic sequence.", reason: "Pattern recognition" },
      { statement: "Closed form: aₙ = 3 + 2n (starting value plus 2 added n times).", reason: "Generalize the pattern" },
    ],
    conclusion: "aₙ = 2n + 3 — try this recurrence directly in the Sequence Stepper above (a₀=2 preset is the same shape, just different start value).",
  },
  {
    id: "2.4-ex29",
    label: "Section 2.4, Exercise 29 — evaluating a summation",
    goal: "Evaluate Σ (from j=0 to 8) of (2^j).",
    steps: [
      { statement: "Write out each term: 2⁰,2¹,2²,2³,2⁴,2⁵,2⁶,2⁷,2⁸", reason: "Expand the summation notation" },
      { statement: "= 1+2+4+8+16+32+64+128+256", reason: "Evaluate each power of 2" },
      { statement: "Running total: 1,3,7,15,31,63,127,255,511", reason: "Add terms one at a time" },
    ],
    conclusion: "Σ(2^j, j=0..8) = 511. Notice the pattern: the sum of 2⁰ through 2ⁿ is always 2ⁿ⁺¹ − 1 (here 2⁹−1 = 511) — a formula worth memorizing.",
  },
];

export const part6WorkedProblems: WorkedProblem[] = [
  {
    id: "3.1-ex13",
    label: "Section 3.1, Exercise 13 — binary search trace",
    given: "Sorted list: 1, 3, 4, 5, 6, 8, 9, 11. Target: 9.",
    goal: "Trace binary search step by step to find 9 (or show it isn't present).",
    steps: [
      { statement: "Window is the whole list, indices 0-7. Middle index = ⌊(0+7)/2⌋ = 3, a[3] = 5.", reason: "Compute the midpoint of the current window" },
      { statement: "9 > 5, so discard the left half. New window: indices 4-7.", reason: "Target is bigger than the middle, so it must be on the right" },
      { statement: "Middle of [4,7] = ⌊(4+7)/2⌋ = 5, a[5] = 8.", reason: "Recompute midpoint of the new window" },
      { statement: "9 > 8, so discard the left half again. New window: indices 6-7.", reason: "Still bigger, go right" },
      { statement: "Middle of [6,7] = ⌊(6+7)/2⌋ = 6, a[6] = 9.", reason: "Recompute midpoint" },
      { statement: "9 = 9 — match found at index 6.", reason: "Direct comparison" },
    ],
    conclusion: "Found 9 at index 6 in just 3 comparisons, versus up to 8 for linear search — try the same list and target in the Search simulator above.",
  },
  {
    id: "3.1-ex34",
    label: "Section 3.1, Exercises 34/38 — sort 6,2,3,1,5,4 by hand",
    given: "Unsorted list: 6, 2, 3, 1, 5, 4.",
    goal: "Sort this list using bubble sort, tracking each swap.",
    steps: [
      { statement: "Pass 1: compare (6,2)→swap→2,6,3,1,5,4. (6,3)→swap→2,3,6,1,5,4. (6,1)→swap→2,3,1,6,5,4. (6,5)→swap→2,3,1,5,6,4. (6,4)→swap→2,3,1,5,4,6.", reason: "6 is the largest, so it bubbles all the way to the end in pass 1" },
      { statement: "Pass 2: compare (2,3) no swap. (3,1)→swap→2,1,3,5,4,6. (3,5) no swap. (5,4)→swap→2,1,3,4,5,6.", reason: "Second-largest unsorted value (5) settles into place" },
      { statement: "Pass 3: (2,1)→swap→1,2,3,4,5,6. Remaining comparisons find no more swaps.", reason: "Continue until a full pass produces zero swaps" },
    ],
    conclusion: "Fully sorted: 1, 2, 3, 4, 5, 6 — load this exact list into the Sort simulator's bubble-sort mode (same technique, different starting array) to watch it animate.",
  },
  {
    id: "3.2-ex1",
    label: "Section 3.2, Exercise 1 — is f(x) = 8x² + 5x + 3 in O(x²)?",
    goal: "Determine whether f(x) = 8x²+5x+3 is O(x²), and find witnesses C and k.",
    steps: [
      { statement: "We need constants C, k such that |f(x)| ≤ C·x² for all x > k.", reason: "Definition of Big-O" },
      { statement: "For x ≥ 1: 5x ≤ 5x² and 3 ≤ 3x², since x² ≥ x ≥ 1.", reason: "Bound the smaller-order terms by the dominant term" },
      { statement: "So 8x²+5x+3 ≤ 8x²+5x²+3x² = 16x² for all x ≥ 1.", reason: "Sum the bounds" },
    ],
    conclusion: "Yes — f(x) is O(x²), with witnesses C=16 and k=1. The rule of thumb: keep only the fastest-growing term; every lower-order term can always be absorbed by bumping up the constant.",
  },
  {
    id: "3.2-ex21",
    label: "Section 3.2, Exercise 21 — ordering functions by growth rate",
    given: "n log n, n², 2ⁿ, n!, log n, n",
    goal: "Arrange these six functions from slowest-growing to fastest-growing.",
    steps: [
      { statement: "log n grows slower than any positive power of n.", reason: "Logarithms grow slower than polynomials" },
      { statement: "n grows slower than n log n, since log n → ∞.", reason: "Multiplying by a growing factor (log n) only speeds things up" },
      { statement: "n log n grows slower than n², since eventually n log n < n·n.", reason: "log n < n for all n ≥ 1" },
      { statement: "n² grows slower than 2ⁿ — every polynomial is eventually beaten by every exponential.", reason: "Exponential functions overtake all polynomials" },
      { statement: "2ⁿ grows slower than n! — factorial multiplies by a growing number (n) each step, exponential multiplies by a fixed base (2).", reason: "n! outpaces any fixed-base exponential" },
    ],
    conclusion: "Slowest to fastest: log n < n < n log n < n² < 2ⁿ < n! — try toggling these exact six curves in the Big-O chart above to see the gap visually (note the chart's y-axis is logarithmic, or 2ⁿ and n! would be unreadable).",
  },
  {
    id: "3.3-ex1",
    label: "Section 3.3, Example 1 vs Example 3 — counting operations",
    given: "Linear search through n items vs. binary search through n sorted items.",
    goal: "Count the worst-case number of comparisons for each, as a function of n.",
    steps: [
      { statement: "Linear search: worst case (target missing, or last element), you compare against every one of the n elements.", reason: "No information is discarded between comparisons" },
      { statement: "Linear search is Θ(n) — worst case exactly n comparisons.", reason: "Direct count" },
      { statement: "Binary search: each comparison discards HALF the remaining window, so after k comparisons only n/2ᵏ elements remain.", reason: "The core idea of divide-and-conquer" },
      { statement: "The search ends when n/2ᵏ ≈ 1, i.e. k ≈ log₂ n.", reason: "Solve n/2^k = 1 for k" },
    ],
    conclusion: "Linear search is Θ(n); binary search is Θ(log n) — for n = 1,000,000, that's roughly 1,000,000 comparisons versus only about 20. This is exactly why the sorted-list requirement of binary search is so often worth paying for.",
  },
];

export const part7WorkedProblems: WorkedProblem[] = [
  {
    id: "5.1-divisibility",
    label: "Section 5.1, Example 8 — a divisibility induction proof",
    goal: "Prove that n³ − n is divisible by 3 for every non-negative integer n.",
    steps: [
      { statement: "Basis step: n=0. 0³−0 = 0, and 0 is divisible by 3 (0 = 3×0).", reason: "Check the smallest case directly" },
      { statement: "Inductive hypothesis: assume k³−k is divisible by 3 for some k ≥ 0, i.e. k³−k = 3m for some integer m.", reason: "Assume the statement for k" },
      { statement: "Inductive step goal: show (k+1)³−(k+1) is divisible by 3.", reason: "What we must derive" },
      { statement: "Expand: (k+1)³−(k+1) = k³+3k²+3k+1−k−1 = (k³−k) + 3k²+3k", reason: "Algebra, grouping to reveal the hypothesis term" },
      { statement: "Substitute the hypothesis: = 3m + 3k² + 3k = 3(m+k²+k)", reason: "k³−k = 3m by assumption" },
      { statement: "m+k²+k is an integer, so (k+1)³−(k+1) = 3×(integer) — divisible by 3.", reason: "Definition of divisibility" },
    ],
    conclusion: "By induction, n³−n is divisible by 3 for all n ≥ 0. ∎ The key algebraic trick is always the same: expand (k+1)'s version, then isolate the exact k-version so the inductive hypothesis can be substituted in directly.",
  },
  {
    id: "5.1-ex49-fallacy",
    label: "Section 5.1, Exercise 49 — spot the flaw in a fake induction proof",
    given:
      "\"Claim: all horses are the same color. Proof by induction on n = number of horses in a group. Basis: n=1, trivially one horse is 'the same color' as itself. Inductive step: assume any group of k horses is all one color. Given a group of k+1 horses, remove one horse — the remaining k horses are all one color (by the hypothesis). Put that horse back and remove a DIFFERENT one — again the remaining k horses are all one color. Since the two groups of k horses overlap (for k≥2, they share at least one horse), all k+1 horses must be the same color.\"",
    goal: "Find the flaw in this argument (the conclusion is obviously false).",
    steps: [
      { statement: "Check the basis-to-first-step transition very carefully: does the inductive step actually work for k=1 (going from 1 horse to 2 horses)?", reason: "Fallacious induction proofs almost always break at the smallest non-trivial case, not at the 'general' k" },
      { statement: "With k=1, a group of k+1=2 horses: remove one horse, left with 1 horse (trivially 'one color'). Remove a different one, left with the OTHER 1 horse (also trivially 'one color').", reason: "Apply the step literally with k=1" },
      { statement: "But now the two leftover groups of 1 horse each DON'T overlap at all — there's no shared horse to link their colors together.", reason: "The argument depended on the two (k-horse) subgroups sharing a common horse, which requires k ≥ 2" },
      { statement: "The inductive step silently assumes k ≥ 2 (so the two subgroups of size k overlap), but never checks or proves the k=1 → k=2 transition separately.", reason: "This is the exact flaw" },
    ],
    conclusion: "The proof is invalid because the inductive step fails at k=1 — the overlap argument requires groups of size ≥2 to guarantee a shared horse, so the crucial first domino (1 horse's color implies 2 horses share a color) is never actually established. A great reminder: ALWAYS explicitly check that your inductive step holds for the smallest k, not just 'in general'.",
  },
  {
    id: "5.1-ex31",
    label: "Section 5.1, Exercise 31 — another divisibility induction",
    goal: "Prove 2 | (n² + n) for every positive integer n (n²+n is always even).",
    steps: [
      { statement: "Basis step: n=1. 1²+1 = 2, and 2 is divisible by 2.", reason: "Check n=1" },
      { statement: "Inductive hypothesis: assume k²+k is even for some k ≥ 1, i.e. k²+k = 2m.", reason: "Assume for k" },
      { statement: "Goal: show (k+1)²+(k+1) is even.", reason: "What must be shown" },
      { statement: "Expand: (k+1)²+(k+1) = k²+2k+1+k+1 = (k²+k) + 2k+2", reason: "Algebra, isolating the hypothesis term" },
      { statement: "Substitute: = 2m + 2k + 2 = 2(m+k+1)", reason: "k²+k = 2m by hypothesis" },
      { statement: "2(m+k+1) is clearly even (2 × an integer).", reason: "Definition of even" },
    ],
    conclusion: "By induction, n²+n is even for all n ≥ 1. ∎ (An alternative non-inductive proof: n²+n = n(n+1), the product of two consecutive integers, and one of any two consecutive integers is always even.)",
  },
  {
    id: "5.3-ex1",
    label: "Section 5.3, Exercise 1 — tracing a recursive definition",
    given: "f(0) = 3, f(n+1) = 2f(n) + 3 for n ≥ 0.",
    goal: "Find f(1), f(2), and f(3) by unwinding the recursive definition.",
    steps: [
      { statement: "f(1) = 2f(0)+3 = 2(3)+3", reason: "Apply the rule with n=0" },
      { statement: "f(1) = 9", reason: "Arithmetic" },
      { statement: "f(2) = 2f(1)+3 = 2(9)+3", reason: "Apply the rule with n=1" },
      { statement: "f(2) = 21", reason: "Arithmetic" },
      { statement: "f(3) = 2f(2)+3 = 2(21)+3", reason: "Apply the rule with n=2" },
      { statement: "f(3) = 45", reason: "Arithmetic" },
    ],
    conclusion: "f(0)=3, f(1)=9, f(2)=21, f(3)=45 — exactly the values the Recursion Call Stack simulator above computes for this same recurrence.",
  },
  {
    id: "5.3-ex7",
    label: "Section 5.3, Exercise 7 — writing a recursive definition from a closed form",
    given: "Closed-form formula: aₙ = 5n, for n = 0, 1, 2, ...",
    goal: "Write a recursive definition for the same sequence.",
    steps: [
      { statement: "First find the base case: a₀ = 5(0) = 0.", reason: "Evaluate the closed form at the smallest n" },
      { statement: "Now find the relationship between aₙ and aₙ₋₁: aₙ − aₙ₋₁ = 5n − 5(n−1) = 5", reason: "Subtract consecutive closed-form values" },
      { statement: "So aₙ = aₙ₋₁ + 5.", reason: "Rearranging the difference" },
    ],
    conclusion: "Recursive definition: a₀ = 0, aₙ = aₙ₋₁ + 5 for n ≥ 1 — try loading a₀=0 with a +5 step into the Sequence Stepper (Part 5) to confirm it reproduces 0, 5, 10, 15, ...",
  },
];

export const part8WorkedProblems: WorkedProblem[] = [
  {
    id: "6.1-ex1",
    label: "Section 6.1, Exercise 1 — sum rule vs. product rule",
    given: "A student can choose a project from 3 lists: list A has 23 topics, list B has 15 topics, list C has 19 topics. Separately, a lunch consists of one of 4 mains AND one of 3 sides.",
    goal: "Count the number of possible projects, and the number of possible lunches.",
    steps: [
      { statement: "Choosing a project means picking ONE topic from EXACTLY ONE of the three lists — mutually exclusive categories.", reason: "This is a sum-rule situation: OR, not AND" },
      { statement: "Projects = 23 + 15 + 19 = 57", reason: "Sum rule: add the sizes of disjoint choices" },
      { statement: "A lunch requires BOTH a main AND a side — two independent choices made together.", reason: "This is a product-rule situation: AND, not OR" },
      { statement: "Lunches = 4 × 3 = 12", reason: "Product rule: multiply the sizes of independent choices" },
    ],
    conclusion: "57 possible projects (sum rule) vs. 12 possible lunches (product rule) — the giveaway is always whether the choices are exclusive alternatives (sum) or made together (product).",
  },
  {
    id: "6.1-ex27",
    label: "Section 6.1, Exercise 27 — committee with one senator per state",
    given: "A committee needs exactly one representative from each of 3 groups, which have 12, 8, and 10 candidates respectively.",
    goal: "Count how many different committees are possible.",
    steps: [
      { statement: "One choice must be made from each of the 3 independent groups, all simultaneously.", reason: "Three independent choices made together = product rule" },
      { statement: "12 × 8 × 10", reason: "Multiply the three independent choice-counts" },
      { statement: "= 960", reason: "Arithmetic" },
    ],
    conclusion: "960 possible committees — the product rule scales cleanly to any number of independent choice-stages, not just two.",
  },
  {
    id: "6.1-ex55",
    label: "Section 6.1, Exercise 55 — password counting",
    given: "A password must be 6 to 8 characters, each character a letter (26) or digit (10) — 36 possibilities per character.",
    goal: "Count the total number of possible passwords.",
    steps: [
      { statement: "6-character passwords: 36⁶ possibilities (each of the 6 slots independently has 36 choices).", reason: "Product rule applied 6 times" },
      { statement: "7-character passwords: 36⁷ possibilities.", reason: "Product rule applied 7 times" },
      { statement: "8-character passwords: 36⁸ possibilities.", reason: "Product rule applied 8 times" },
      { statement: "The three lengths are mutually exclusive (a password can't be both 6 and 7 characters), so add them.", reason: "Sum rule combines the three product-rule results" },
      { statement: "Total = 36⁶ + 36⁷ + 36⁸ = 2,176,782,336 + 78,364,164,096 + 2,821,109,907,456", reason: "Compute each power of 36" },
    ],
    conclusion: "Total ≈ 2.90 × 10¹² possible passwords — notice how this problem needed BOTH rules: product rule inside each fixed length, sum rule across the three lengths.",
  },
  {
    id: "6.2-ex17",
    label: "Section 6.2, Exercise 17 — a warehouse pigeonhole problem",
    given: "A shipment has apples, bananas, and oranges (3 kinds of fruit) and at least 25 pieces of fruit total.",
    goal: "Show that the shipment must contain at least 9 pieces of the same kind of fruit.",
    steps: [
      { statement: "There are H = 3 \"holes\" (fruit kinds) and P = 25 \"pigeons\" (pieces of fruit).", reason: "Map the problem onto pigeons and holes" },
      { statement: "By the generalized pigeonhole principle, some hole must contain at least ⌈P/H⌉ pigeons.", reason: "Generalized pigeonhole formula" },
      { statement: "⌈25/3⌉ = ⌈8.33⌉ = 9", reason: "Ceiling of the division" },
    ],
    conclusion: "At least 9 pieces of fruit must be the same kind — try P=25, H=3 in the Pigeonhole simulator above to see the same guarantee computed live.",
  },
  {
    id: "6.2-ex33",
    label: "Section 6.2, Exercise 33 — the hairs-on-heads classic (Paris edition)",
    given: "No human head has more than about 1,000,000 hairs. Paris has a population well over 1,000,000 people.",
    goal: "Prove that at least two people in Paris have exactly the same number of hairs on their heads.",
    steps: [
      { statement: "Treat \"number of hairs\" (0 to 1,000,000) as the holes — at most 1,000,001 possible hole values.", reason: "Set up the pigeonhole mapping" },
      { statement: "Treat people as the pigeons — Paris has well over 1,000,001 people.", reason: "More pigeons than holes" },
      { statement: "Since pigeons (people) exceed holes (possible hair-counts), by the pigeonhole principle at least two people must share a hole.", reason: "Direct application of the basic pigeonhole principle" },
    ],
    conclusion: "At least two Parisians have exactly the same number of hairs — a famous illustration that the pigeonhole principle can prove something is guaranteed to exist without ever identifying WHICH two people they are.",
  },
  {
    id: "6.3-ex9",
    label: "Section 6.3, Exercise 9 — a horse race",
    given: "A horse race has 8 horses, no ties.",
    goal: "Count how many ways first, second, and third place can be awarded.",
    steps: [
      { statement: "Order matters (1st ≠ 2nd ≠ 3rd), so this is a permutation: P(8,3).", reason: "Distinguishing positions means order matters" },
      { statement: "P(8,3) = 8!/(8-3)! = 8!/5!", reason: "Permutation formula" },
      { statement: "= 8 × 7 × 6 = 336", reason: "The factorials cancel down to the top 3 factors" },
    ],
    conclusion: "336 possible orderings of first/second/third place — try P(8,3) directly in the Permutation/Combination calculator above.",
  },
  {
    id: "6.3-ex18",
    label: "Section 6.3, Exercise 18 — counting coin-flip outcomes",
    given: "A fair coin is flipped 10 times.",
    goal: "Count how many outcomes have exactly 6 heads.",
    steps: [
      { statement: "Order doesn't matter for WHICH flips are heads — we just need to choose 6 of the 10 positions to be heads.", reason: "This is a combination, not a permutation" },
      { statement: "C(10,6) = 10!/(6!×4!)", reason: "Combination formula" },
      { statement: "= 210", reason: "Arithmetic" },
    ],
    conclusion: "210 outcomes have exactly 6 heads out of 10 flips — this exact style of count (C(n,r) for r successes in n trials) is the foundation of the binomial distribution.",
  },
];

export const part9WorkedProblems: WorkedProblem[] = [
  {
    id: "9.1-ex3",
    label: "Section 9.1, Exercise 3 — property-check drill",
    given: "Relation R on {1,2,3,4}: R = {(1,1),(1,2),(2,1),(2,2),(3,4),(4,1),(4,4)}.",
    goal: "Check R for reflexive, symmetric, antisymmetric, and transitive.",
    steps: [
      { statement: "Reflexive needs (1,1),(2,2),(3,3),(4,4) all present. We have (1,1),(2,2),(4,4) but NOT (3,3).", reason: "Scan for every (a,a)" },
      { statement: "Not reflexive.", reason: "(3,3) is missing" },
      { statement: "Symmetric needs every (a,b) to have a matching (b,a). (1,2) has (2,1) ✓. But (3,4) has no (4,3), and (4,1) has no (1,4).", reason: "Check every pair for its reverse" },
      { statement: "Not symmetric.", reason: "(3,4) and (4,1) both lack their reverse" },
      { statement: "Antisymmetric needs: whenever (a,b) and (b,a) both appear with a≠b, contradiction. Check (1,2)/(2,1): both appear, and 1≠2.", reason: "This single pair already breaks antisymmetry" },
      { statement: "Not antisymmetric.", reason: "(1,2) and (2,1) both present with 1≠2" },
      { statement: "Transitive: check (3,4) and (4,1) ⟹ need (3,1) — NOT present.", reason: "Find one violation to disprove transitivity" },
      { statement: "Not transitive.", reason: "(3,1) is missing" },
    ],
    conclusion: "R has none of the four properties — try pasting this exact relation into the Relation Property Checker above to see the same violations highlighted automatically.",
  },
  {
    id: "9.1-ex8",
    label: "Section 9.1, Exercise 8 — the empty relation is a vacuous edge case",
    given: "The empty relation R = ∅ on a non-empty set A.",
    goal: "Determine which of reflexive/symmetric/antisymmetric/transitive hold for ∅.",
    steps: [
      { statement: "Reflexive requires (a,a) ∈ R for every a ∈ A. Since R is empty and A is non-empty, this fails immediately.", reason: "A non-empty set has at least one element needing a self-pair that isn't there" },
      { statement: "Not reflexive.", reason: "Direct check" },
      { statement: "Symmetric requires: IF (a,b) ∈ R THEN (b,a) ∈ R. Since R has no pairs at all, this conditional is vacuously true — there's nothing to check.", reason: "An implication with a false hypothesis is always true" },
      { statement: "Symmetric (vacuously).", reason: "No pairs to violate the condition" },
      { statement: "Transitive requires: IF (a,b)∈R AND (b,c)∈R THEN (a,c)∈R. Again, no pairs exist, so vacuously true.", reason: "Same vacuous-truth reasoning" },
      { statement: "Transitive (vacuously).", reason: "No pairs to violate the condition" },
      { statement: "Antisymmetric requires: IF (a,b)∈R AND (b,a)∈R AND a≠b THEN contradiction. No pairs exist, so vacuously true too.", reason: "Same reasoning again" },
      { statement: "Antisymmetric (vacuously).", reason: "No pairs to violate the condition" },
    ],
    conclusion: "The empty relation is symmetric, antisymmetric, AND transitive — but NOT reflexive (unless A is also empty). This is a classic \"vacuous truth\" trap: an implication with no cases to check is automatically true, which feels counterintuitive the first time you see it.",
  },
  {
    id: "9.5-ex1",
    label: "Section 9.5, Exercise 1 — is this an equivalence relation?",
    given: "R on the set of all people: (a,b) ∈ R if a and b were born in the same calendar year.",
    goal: "Determine if R is an equivalence relation.",
    steps: [
      { statement: "Reflexive: is every person born in the same year as themself? Yes, trivially.", reason: "a and a always share the exact same birth year" },
      { statement: "Symmetric: if a was born the same year as b, was b born the same year as a? Yes — \"same year as\" is inherently mutual.", reason: "Sameness is always a two-way relationship" },
      { statement: "Transitive: if a and b share a birth year, and b and c share a birth year, do a and c share one? Yes — they all share the same single year.", reason: "Sharing a common year with the same middle person forces all three to match" },
    ],
    conclusion: "R IS an equivalence relation — all three properties hold. Its equivalence classes are exactly \"everyone born in 1990\", \"everyone born in 1991\", etc. — one class per birth year.",
  },
  {
    id: "9.5-ex35",
    label: "Section 9.5, Exercise 35 — congruence classes mod 5",
    goal: "List the equivalence classes [0]₅ through [4]₅ for congruence mod 5, showing a few representative elements each.",
    steps: [
      { statement: "[0]₅ = all integers with remainder 0 when divided by 5: ..., -10, -5, 0, 5, 10, ...", reason: "Definition of a mod-5 congruence class" },
      { statement: "[1]₅ = all integers with remainder 1: ..., -9, -4, 1, 6, 11, ...", reason: "Same definition, remainder 1" },
      { statement: "[2]₅ = ..., -8, -3, 2, 7, 12, ...", reason: "Remainder 2" },
      { statement: "[3]₅ = ..., -7, -2, 3, 8, 13, ...", reason: "Remainder 3" },
      { statement: "[4]₅ = ..., -6, -1, 4, 9, 14, ...", reason: "Remainder 4" },
    ],
    conclusion: "Exactly 5 classes partition all the integers, one per possible remainder (0-4) — try n=5 in the Equivalence Class Partitioner above (congruence mod n mode) to see this generated live.",
  },
  {
    id: "9.5-ex41",
    label: "Section 9.5, Exercise 41 — is this a valid partition?",
    given: "Candidate partition of {1,2,3,4,5,6}: {1,2,3}, {3,4}, {5,6}. A second candidate: {1,2}, {3,4}, {5,6}.",
    goal: "Determine which candidate is a valid partition.",
    steps: [
      { statement: "A valid partition requires the subsets to be pairwise disjoint (no overlap) AND their union to be the whole set.", reason: "Definition of a set partition" },
      { statement: "Candidate 1: {1,2,3} and {3,4} both contain 3 — they overlap.", reason: "Check disjointness" },
      { statement: "Candidate 1 is INVALID — overlapping subsets are never allowed in a partition.", reason: "Violates disjointness" },
      { statement: "Candidate 2: {1,2}, {3,4}, {5,6} — check overlaps: none share any element.", reason: "Check disjointness for candidate 2" },
      { statement: "Check union: {1,2}∪{3,4}∪{5,6} = {1,2,3,4,5,6}, the full set.", reason: "Check the union covers everything" },
    ],
    conclusion: "Candidate 2 is a VALID partition; Candidate 1 is not, because of the shared element 3. Every valid partition corresponds to exactly one equivalence relation, and vice versa — they're two views of the same idea.",
  },
];

export const part10WorkedProblems: WorkedProblem[] = [
  {
    id: "10.2-euler-hamilton",
    label: "Section 10.2 — Euler and Hamilton circuits on named graphs",
    goal: "For which n does Cₙ (a cycle) have an Euler circuit, and for which n does Kₙ (a complete graph) have a Hamilton circuit?",
    steps: [
      { statement: "An Euler circuit exists iff the graph is connected and every vertex has EVEN degree.", reason: "Euler circuit theorem" },
      { statement: "In Cₙ, every vertex has degree exactly 2 (one edge to each neighbor around the cycle).", reason: "Definition of a cycle graph" },
      { statement: "2 is even, for every n ≥ 3 — so Cₙ always has an Euler circuit (in fact, the cycle itself IS the Euler circuit).", reason: "Apply the theorem" },
      { statement: "A Hamilton circuit just needs to visit every vertex exactly once and return to the start — no degree condition required.", reason: "Definition of Hamilton circuit (much weaker requirement than Euler)" },
      { statement: "In Kₙ (n≥3), every vertex connects to every other vertex, so you can visit them in ANY order and always have an edge back to the start.", reason: "Completeness guarantees every needed edge exists" },
    ],
    conclusion: "Cₙ has an Euler circuit for every n ≥ 3 (degree 2 is always even). Kₙ has a Hamilton circuit for every n ≥ 3 — try both in the Named Graph Explorer above and trace a circuit by eye.",
  },
  {
    id: "10.2-hall",
    label: "Section 10.2, Exercises 27/29 — a matching / Hall's theorem scenario",
    given:
      "Three workers (Ama, Kojo, Yaw) and three jobs (Design, Testing, Docs). Ama can do Design or Testing. Kojo can only do Testing. Yaw can do Design, Testing, or Docs.",
    goal: "Determine whether every worker can be matched to a distinct job they're qualified for (a complete matching).",
    steps: [
      { statement: "Model this as a bipartite graph: workers on one side, jobs on the other, edges for 'qualified for'.", reason: "Set up the bipartite matching model" },
      { statement: "Hall's theorem: a complete matching exists iff every subset of workers is collectively qualified for AT LEAST as many jobs as its size.", reason: "Hall's marriage theorem" },
      { statement: "Check the subset {Ama, Kojo}: together qualified for {Design, Testing} — 2 jobs for 2 workers. OK.", reason: "Check a 2-worker subset" },
      { statement: "Check the subset {Kojo} alone: qualified only for {Testing} — 1 job for 1 worker. OK.", reason: "Check singleton subsets — Kojo is the tightest constraint" },
      { statement: "Check all three: {Ama,Kojo,Yaw} qualified for {Design,Testing,Docs} — 3 jobs for 3 workers. OK.", reason: "Check the full set" },
      { statement: "Since Kojo can ONLY do Testing, assign Kojo → Testing first, then Ama → Design (her only remaining option), then Yaw → Docs.", reason: "Always match the most constrained worker first" },
    ],
    conclusion: "A complete matching exists: Kojo→Testing, Ama→Design, Yaw→Docs. Hall's theorem is exactly why checking the most-constrained subsets first (like Kojo's singleton) is the fastest way to spot whether a matching is even possible.",
  },
  {
    id: "10.6-dijkstra-recap",
    label: "Section 10.6, Example 1 — Dijkstra's shortest path, restated",
    given: "Weighted graph: a-b=4, a-d=2, b-c=3, b-e=3, d-e=3, e-z=1.",
    goal: "Find the shortest path from a to z and its total length.",
    steps: [
      { statement: "Initialize distance(a)=0, all others=∞.", reason: "Starting condition" },
      { statement: "Visit a (distance 0). Relax edges: distance(b)=4, distance(d)=2.", reason: "a's only neighbors are b and d" },
      { statement: "Visit d (distance 2, the smallest unvisited). Relax: distance(e) = 2+3 = 5 (better than ∞).", reason: "d connects to e with weight 3" },
      { statement: "Visit e (distance 5, now smallest unvisited — beats b's 4? No, b=4 is smaller, so visit b first).", reason: "Careful: b's distance 4 < e's distance 5, so b is visited before e" },
      { statement: "Visit b (distance 4). Relax: distance(c) = 4+3 = 7. distance(e) stays 5 (4+3=7 is not better than 5).", reason: "b connects to c and e" },
      { statement: "Visit e (distance 5). Relax: distance(z) = 5+1 = 6.", reason: "e connects to z with weight 1" },
      { statement: "Visit z (distance 6) — done, z is reached.", reason: "z has no unvisited neighbors left to relax" },
    ],
    conclusion: "Shortest path a→z has length 6, via a→d→e→z — exactly what the Dijkstra simulator above computes step by step.",
  },
];

export const part11WorkedProblems: WorkedProblem[] = [
  {
    id: "11.2-ex1",
    label: "Section 11.2, Exercise 1 — build a BST from a fruit list",
    given: "Insert in order: banana, peach, apple, pear, coconut, mango, papaya.",
    goal: "Trace the binary search tree that results.",
    steps: [
      { statement: "\"banana\" is inserted first — it becomes the root.", reason: "First insertion into an empty tree" },
      { statement: "\"peach\": peach > banana → goes right of banana.", reason: "Alphabetical comparison, p > b" },
      { statement: "\"apple\": apple < banana → goes left of banana.", reason: "a < b" },
      { statement: "\"pear\": pear > banana → right of banana (peach); pear > peach (comparing letter by letter, 'r' > 'c' at the 4th position) → goes right of peach.", reason: "Alphabetical comparison against each node on the path" },
      { statement: "\"coconut\": coconut > banana → right (peach); coconut < peach → goes left of peach (that spot is still empty).", reason: "c < p alphabetically" },
      { statement: "\"mango\": mango > banana → right (peach); mango < peach → left (coconut); mango > coconut → goes right of coconut.", reason: "m > c alphabetically" },
      { statement: "\"papaya\": papaya > banana → right (peach); papaya < peach → left (coconut); papaya > coconut → right (mango); papaya > mango → goes right of mango.", reason: "Walk the full comparison chain down the left subtree of peach" },
    ],
    conclusion: "Final shape: banana at the root with apple as its only left child; the entire right side hangs off peach, which has coconut as its left child and pear as its right child; coconut in turn has mango as its right child, and mango has papaya as its right child. Try this exact word list in the BST Builder above (it defaults to the book's mathematics/physics/... list, but the identical smaller-goes-left rule applies to any word list).",
  },
  {
    id: "11.3-ex16-expression-tree",
    label: "Section 11.3, Exercise 16 — expression tree conversions",
    given: "Expression tree for: ((x+2)↑3) × (y−(3+x)) − 5   (↑ means exponent)",
    goal: "Write this expression in prefix (Polish) and postfix (reverse Polish) notation.",
    steps: [
      { statement: "The tree's root is the LAST operation applied when reading normally: the outermost subtraction of 5.", reason: "Root of an expression tree = the last operator applied (lowest precedence at the top level)" },
      { statement: "Prefix (preorder: operator, then left, then right): − × ↑ + x 2 3 − y + 3 x 5", reason: "Preorder traversal: visit operator first, then recurse left subtree, then right subtree" },
      { statement: "Postfix (postorder: left, then right, then operator): x 2 + 3 ↑ y 3 x + − × 5 −", reason: "Postorder traversal: recurse left, recurse right, then visit the operator last — this is exactly the form calculators and compilers evaluate directly with a stack" },
    ],
    conclusion: "Same tree, same expression — prefix puts every operator before its operands, postfix puts every operator after. Try switching between preorder/postorder in the Tree Traversal Animator above to see exactly why these two notations fall out of two of the three traversal orders.",
  },
  {
    id: "11.2-huffman-ex23",
    label: "Section 11.2, Exercise 23 — Huffman coding on a different frequency set",
    given: "Frequencies: a:0.20, b:0.10, c:0.15, d:0.25, e:0.30.",
    goal: "Build the Huffman tree and find the average code length.",
    steps: [
      { statement: "Merge the two smallest: b(.10) and c(.15) → bc(.25).", reason: "Always merge the current two smallest weights" },
      { statement: "Remaining: a(.20), bc(.25), d(.25), e(.30). Merge the two smallest: a(.20) and bc(.25) → abc(.45).", reason: "a(.20) is now the smallest, bc(.25) is next-smallest (tied with d, but bc was formed first)" },
      { statement: "Remaining: d(.25), e(.30), abc(.45). Merge the two smallest: d(.25) and e(.30) → de(.55).", reason: "Continue merging smallest pairs" },
      { statement: "Remaining: abc(.45), de(.55). Merge them → root(1.00).", reason: "Final merge combines everything into the root" },
    ],
    conclusion: "This produces code lengths of 2 bits for a, d, e and 3 bits for b, c (b and c ended up nested two levels inside the abc branch) — average length = .20(2)+.10(3)+.15(3)+.25(2)+.30(2) = 0.40+0.30+0.45+0.50+0.60 = 2.25 bits. Switch to the \"a-e frequencies\" preset in the Huffman Builder above to watch this exact merge sequence animate and confirm the same 2.25-bit average.",
  },
];
