import type { CommSkillsQuestion } from "./types";

// Concept questions generated from the lecturer's own slide decks (9 unique lecture
// topics — "Organogram.pptx" and "ENGL 158 - Organizational Communication.pptx" are
// identical decks, so only one is represented here). Multiple questions are generated
// per major concept, testing definitions, identification, distinctions, scenarios, and
// classifications, using the lecturer's own terminology and examples wherever the deck
// supplied one.
export const commSkillsConceptQuestions: CommSkillsQuestion[] = [
  // ==================== Lecture 1: Communication Skills (fundamentals) ====================
  {
    id: "cb-fund-1",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "easy",
    question: "According to Lunenburg (2010), as cited in Lecture 1, communication is best understood as the process of...",
    options: [
      "transmitting and receiving information.",
      "persuading an audience to act.",
      "memorizing key facts for an exam.",
      "avoiding all forms of conflict.",
    ],
    correctIndex: 0,
    explanation: "The lecture defines communication as the process of transmitting and receiving information, involving the organisation and transfer of information.",
  },
  {
    id: "cb-fund-2",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "easy",
    question: "Which of the following is NOT listed among the lecture's key words for communication?",
    options: ["process", "receiver", "organisation of information", "profit"],
    correctIndex: 3,
    explanation: "The lecture's list of key words is: communication, process, receiver, give/transmit/transfer, information, purpose, and organisation of information — \"profit\" is not among them.",
  },
  {
    id: "cb-fund-3",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "The lecture distinguishes \"communication as a system\" from \"communication as a process.\" Which factor is named as conditioning communication AS A SYSTEM?",
    options: ["the number of persons involved", "the emotions of people during interaction", "the changing role of speaker and listener", "the effect on the interlocutors"],
    correctIndex: 0,
    explanation: "Communication as a system is conditioned by factors like the number of persons, required resources, and activities — the other three options describe communication as a PROCESS.",
  },
  {
    id: "cb-fund-4",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Kwaku notices that during a negotiation, both parties keep swapping between speaking and listening as the conversation moves from beginning to end. This best illustrates communication as a...",
    options: ["system", "process", "channel", "barrier"],
    correctIndex: 1,
    explanation: "The changing role of speaker/listener and the movement from the beginning to the end of an interaction are exactly the factors the lecture uses to describe communication as a PROCESS.",
  },
  {
    id: "cb-fund-5",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "According to Lunenburg (2010, as quoted in Lecture 1), the sender \"encodes the idea by...\"",
    options: [
      "selecting words, symbols, or gestures with which to compose a message.",
      "listening carefully to the receiver's response.",
      "choosing the cheapest channel available.",
      "waiting for feedback before sending anything.",
    ],
    correctIndex: 0,
    explanation: "Lunenburg's quoted definition states the sender \"encodes the idea by selecting words, symbols, or gestures with which to compose a message.\"",
  },
  {
    id: "cb-fund-6",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "easy",
    question: "In the classic sender-receiver model, the carrier of the communication — a face-to-face conversation, phone call, e-mail, or written report — is called the...",
    options: ["message", "channel", "noise", "feedback"],
    correctIndex: 1,
    explanation: "The channel/medium is the carrier of communication; examples given in the lecture include face-to-face conversation, telephone call, e-mail, or written report.",
  },
  {
    id: "cb-fund-7",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A customer sends an angry email, and the company replies acknowledging the complaint and explaining the next steps. The company's reply is best described as...",
    options: ["noise", "feedback", "encoding", "distortion"],
    correctIndex: 1,
    explanation: "Feedback occurs when the receiver responds to the sender's message and returns it — it lets the sender know whether the message was received and understood.",
  },
  {
    id: "cb-fund-8",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Under \"Elements of the Communication Process,\" which element does the lecture describe as involving language choice, language rules, mode (spoken/written), formality, and genre conventions?",
    options: ["Source/sender", "Getting information", "Channel", "Reaction"],
    correctIndex: 2,
    explanation: "The Channel is described as involving language choice, language rules and conventions, mode, formality, and genre rules and conventions — the packaging and transmission of information.",
  },
  {
    id: "cb-fund-9",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "According to the lecture, effective communication is best described as a...",
    options: [
      "one-way broadcast requiring only the sender's effort.",
      "two-way process requiring effort and skill from both sender and receiver.",
      "purely mechanical exchange of data.",
      "process that ends once a message is sent.",
    ],
    correctIndex: 1,
    explanation: 'Quoting Lunenburg (2010), the lecture states "Effective communication is a two-way process that requires effort and skill by both sender and receiver."',
  },
  {
    id: "cb-fund-10",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "easy",
    question: "When the intended information does not achieve the desired goal, the lecture calls this a...",
    options: ["communication breakdown", "channel overload", "feedback loop", "noise cancellation"],
    correctIndex: 0,
    explanation: "A communication breakdown is defined as occurring when the intended information did not achieve the desired goals.",
  },
  {
    id: "cb-fund-11",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A teacher tells a joke in class purely for their own amusement, not expecting or intending any student to actually hear it, but a student overhears and laughs. This scenario is an example of the distinction the lecture draws between...",
    options: ["formal vs informal communication", "intended message vs unintended message", "credibility vs congeniality", "channel vs medium"],
    correctIndex: 1,
    explanation: "The lecture explicitly distinguishes intentional vs. unintentional communication and intended message vs. unintended message as part of \"the role of the receiver and kinds of communication.\"",
  },
  {
    id: "cb-fund-12",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Which of these is classified under the Multilineal Forms of interpersonal (verbal) communication in the lecture?",
    options: ["giving a directive", "a letter and its reply", "meetings, interviews, and discussions", "writing a letter"],
    correctIndex: 2,
    explanation: "Multilineal forms involve several participants at once — the lecture gives meetings, interviews, conversations, and discussions as examples.",
  },
  {
    id: "cb-fund-13",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A radio station broadcasts the President's New Year address to the whole nation. This is an example of which category from the lecture?",
    options: ["The intrapersonal, Monolineal form", "The public/Mass communication, Monolineal form", "The public/Mass communication, Bilineal form", "The interpersonal, Multilineal form"],
    correctIndex: 1,
    explanation: "A one-way presidential broadcast to a large audience is public/mass communication, and since it flows one way (no immediate reply channel), it is Monolineal — the lecture gives \"presidential speeches\" as an example under this exact category.",
  },
  {
    id: "cb-fund-14",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "hard",
    question: "A university lecture hall where the lecturer regularly poses questions to individual students who answer is best classified, per the lecture's framework, as which form of public/mass communication?",
    options: ["The Monolineal", "The Bilineal", "The Multilineal", "The intrapersonal"],
    correctIndex: 1,
    explanation: "The lecture gives \"classroom situation — teacher and students\" as the example under the Bilineal form of public/mass communication.",
  },
  {
    id: "cb-fund-15",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Talking to yourself while working through a difficult problem is an example of which type of verbal communication?",
    options: ["Intrapersonal", "Interpersonal", "Public communication", "Mass communication"],
    correctIndex: 0,
    explanation: "Intrapersonal communication is defined as communication within oneself or with oneself.",
  },
  {
    id: "cb-fund-16",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "During a job interview, an interviewer notices the candidate keeps checking the time on their phone. Which form of non-verbal communication does this MOST directly involve?",
    options: ["Proxemics", "Chronemics", "Oculesics", "Haptics"],
    correctIndex: 1,
    explanation: "Chronemics is the perception and use of time in communication — checking the time repeatedly communicates something about the candidate's attitude toward the moment.",
  },
  {
    id: "cb-fund-17",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A manager deliberately sits close to a junior colleague's desk during a friendly chat, but keeps more physical distance when giving a formal warning. This use of physical space to communicate is called...",
    options: ["Proxemics", "Kinesics", "Vocalics", "Objectics"],
    correctIndex: 0,
    explanation: "Proxemics is the use of space (place or location) as a form of non-verbal communication.",
  },
  {
    id: "cb-fund-18",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Which non-verbal communication form covers vocal qualities like pitch, speed, volume, and pauses, distinct from the actual words spoken?",
    options: ["Kinesics", "Vocalics", "Haptics", "Oculesics"],
    correctIndex: 1,
    explanation: "Vocalics covers non-verbal aspects associated with the voice or sound — speed, pitch, intonation, stress, volume, laughter, pause, and so on — also called paralanguage.",
  },
  {
    id: "cb-fund-19",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A firm's grand marble lobby and expensively framed awards communicate prestige to visitors before anyone says a word. This is an example of...",
    options: ["Haptics", "Objectics", "Chronemics", "Proxemics"],
    correctIndex: 1,
    explanation: "Objectics refers to the way artefacts and the environment speak to us or are used to communicate.",
  },
  {
    id: "cb-fund-20",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "According to the lecture, credibility stems from two main sources: perceived authority and...",
    options: ["perceived intention", "perceived wealth", "perceived popularity", "perceived age"],
    correctIndex: 0,
    explanation: "Credibility stems from perceived authority and perceived intention, per the lecture's \"Achieving Communication Goals\" section.",
  },
  {
    id: "cb-fund-21",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Students tend to accept a claim about a legal matter more readily when it comes from a law professor rather than a random classmate. This illustrates credibility built on...",
    options: ["perceived authority", "congeniality", "confidentiality", "noise reduction"],
    correctIndex: 0,
    explanation: "Perceived authority is when information is accepted from someone seen to have the right or standing to give it out, based on their position, reputation, or expertise.",
  },
  {
    id: "cb-fund-22",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "hard",
    question: "To gain greater credibility through perceived intention, the lecture advises a speaker to do all of the following EXCEPT...",
    options: [
      "appear honest and straightforward by giving both sides of an argument.",
      "appear to be an objective, unbiased expert.",
      "appear to be acting for his/her own best interests.",
      "avoid giving out ambiguous information.",
    ],
    correctIndex: 2,
    explanation: "The lecture advises appearing to act NOT necessarily for one's own best interests — appearing self-interested undermines perceived intention rather than building it.",
  },
  {
    id: "cb-fund-23",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A message is described as \"confidential\" when...",
    options: [
      "it inspires trust and belief in the receiver.",
      "it is pleasant to the receiver.",
      "it is kept as a secret without being divulged.",
      "it is delivered through multiple channels at once.",
    ],
    correctIndex: 2,
    explanation: "Confidentiality is when the message received is to be kept as a secret without divulging or disclosing it.",
  },
  {
    id: "cb-fund-24",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "The lecture names two main problems that act as barriers to effective communication: noise and...",
    options: ["distortion", "feedback", "encoding", "channel"],
    correctIndex: 0,
    explanation: "Barriers to effective communication are described as two main problems: distortion (change in meaning) and noise (environmental distractions/interferences).",
  },
  {
    id: "cb-fund-25",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "During a phone call, a bad crackle on the line makes part of the conversation inaudible. This is an example of which source of noise?",
    options: ["Physical noise", "Social noise", "Technical noise", "Psychological noise"],
    correctIndex: 2,
    explanation: "Technical noise is described as a failure or breakdown of the medium or channel of communication — the lecture explicitly gives \"a crackle on a phone line\" as an example.",
  },
  {
    id: "cb-fund-26",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A worker is too anxious and nervous to explain a mistake clearly to their manager, and their explanation comes out garbled. This is best described as an example of...",
    options: ["physical noise", "social noise", "psychological noise", "distortion by jargon"],
    correctIndex: 2,
    explanation: "Psychological noise occurs when someone is emotionally charged (with excitement, fear, nervousness, etc.), clouding the clarity of their message.",
  },
  {
    id: "cb-fund-27",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "Difficulty in communication caused by differences in personality, culture, religion, or the outlook of the sender and recipient is classified by the lecture as...",
    options: ["physical noise", "social noise", "technical noise", "psychological noise"],
    correctIndex: 1,
    explanation: "Social noise is interference created by differences in personality, culture, religion, or outlook between sender and recipient — including differences of social class, age, gender, or role.",
  },
  {
    id: "cb-fund-28",
    source: "lecture-material",
    sourceLabel: "Lecture 1: Communication Skills",
    topic: "communication-fundamentals",
    difficulty: "medium",
    question: "A speaker uses heavy regional dialect words that listeners from a different area of the country cannot understand. According to the lecture, this is a source of...",
    options: ["distortion", "channel overload", "feedback failure", "objectics"],
    correctIndex: 0,
    explanation: "The lecture names dialectical differences (e.g. Asante Twi vs. Fanti vs. Akuapem Twi) as one of the sources of distortion, alongside incorrect word use, jargon, and ambiguous language.",
  },

  // ==================== Lecture 3: Writing as a Process ====================
  {
    id: "cb-wp-1",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "easy",
    question: "The lecture names three approaches to writing: the Product approach, the Genre approach, and the...",
    options: ["Grammar approach", "Process approach", "Analysis approach", "Reader approach"],
    correctIndex: 1,
    explanation: "The three named approaches are the Product approach, the Genre approach, and the Process approach.",
  },
  {
    id: "cb-wp-2",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The motto of the Process Approach, as stated in the lecture, is...",
    options: ["\"Writing is rewriting.\"", "\"Practice makes perfect.\"", "\"Grammar comes first.\"", "\"One draft is enough.\""],
    correctIndex: 0,
    explanation: 'The lecture explicitly states: "The motto of the Process Approach is: Writing is rewriting."',
  },
  {
    id: "cb-wp-3",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The lecture describes writing as \"messy, recursive, convoluted, and uneven,\" appealing to common-sense life activities such as...",
    options: ["cooking, sweeping, dressing", "banking, investing, saving", "swimming, running, cycling", "singing, dancing, acting"],
    correctIndex: 0,
    explanation: "The lecture compares the process approach to everyday activities like cooking, sweeping, and dressing, plus vocations such as sewing, carpentry, and painting.",
  },
  {
    id: "cb-wp-4",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The three broad stages of the Process Approach, in order, are:",
    options: [
      "Prewriting, Writing, Post-writing",
      "Drafting, Editing, Publishing",
      "Planning, Grammar-checking, Submission",
      "Brainstorming, Outlining, Proofreading",
    ],
    correctIndex: 0,
    explanation: "The lecture names three stages/steps: the Prewriting Stage, the Writing Stage, and the Post-writing Stage.",
  },
  {
    id: "cb-wp-5",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Which of the following is NOT listed among the factors to consider when selecting a topic in the prewriting stage?",
    options: ["Relevance", "Availability of resources", "Personal interest", "Popularity on social media"],
    correctIndex: 3,
    explanation: "The lecture lists relevance, availability of resources/information, accessibility, personal interest, competence, duration, and length of work — social media popularity is not among them.",
  },
  {
    id: "cb-wp-6",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "According to the lecture's advice on topic selection, a good topic should be...",
    options: ["as broad as possible, to allow flexibility.", "extremely narrow, to save time.", "neither too narrow nor too broad.", "chosen only by the lecturer."],
    correctIndex: 2,
    explanation: 'The lecture explicitly notes: "The topic should not be too narrow nor broad."',
  },
  {
    id: "cb-wp-7",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "\"Go for quantity,\" \"withhold criticism,\" and \"welcome wild ideas\" are all rules underpinning which prewriting technique?",
    options: ["Outlining", "Clustering", "Brainstorming", "Proofreading"],
    correctIndex: 2,
    explanation: "These are three of the four rules underpinning brainstorming named in the lecture (the fourth is \"combine and improve ideas\").",
  },
  {
    id: "cb-wp-8",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The brainstorming rule \"withhold criticism\" means that...",
    options: [
      "no ideas should ever be written down.",
      "criticism of ideas should be held off until a later, critical stage of the process.",
      "only the group leader may generate ideas.",
      "ideas must be criticized immediately as they are suggested.",
    ],
    correctIndex: 1,
    explanation: "The lecture explains this rule as: focus on extending or adding to ideas during brainstorming, and reserve criticism for a later 'critical stage' of the process.",
  },
  {
    id: "cb-wp-9",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "\"It is a way of narrowing your thoughts by classifying related ideas\" — this is the lecture's definition of...",
    options: ["Outlining", "Clustering", "Drafting", "Editing"],
    correctIndex: 1,
    explanation: "Clustering is defined in the lecture as narrowing your thoughts by classifying related ideas, grouping items that are more similar to each other than to items in other groups.",
  },
  {
    id: "cb-wp-10",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "According to the lecture, an outline can serve all of the following purposes EXCEPT...",
    options: [
      "helping to set up an essay or research paper.",
      "helping to revise an essay or research paper.",
      "serving as a study tool to summarize key ideas in reading.",
      "replacing the need for a first draft entirely.",
    ],
    correctIndex: 3,
    explanation: "The lecture lists outlining as helping to set up, revise, and summarize/study — it never suggests an outline can replace the need to actually draft.",
  },
  {
    id: "cb-wp-11",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The lecture identifies two types of outlines:",
    options: ["formal and informal", "long and short", "numbered and bulleted", "written and spoken"],
    correctIndex: 0,
    explanation: "The lecture states outlining has two types: formal and informal.",
  },
  {
    id: "cb-wp-12",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Which of the following is NOT one of the three named principles of outlining?",
    options: ["Heading", "Labeling (numbering)", "Structuring (topic or sentence forms)", "Colour-coding"],
    correctIndex: 3,
    explanation: "The lecture's three principles of outlining are Heading, Labeling (with the note that ideas of the same rank get the same label), and Structuring.",
  },
  {
    id: "cb-wp-13",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The Writing Stage, as described in the lecture, involves freewriting on the developed outline with...",
    options: [
      "no focus on grammar and language.",
      "strict attention to every grammar rule.",
      "a focus on formatting first.",
      "peer editing before any draft exists.",
    ],
    correctIndex: 0,
    explanation: "The Writing Stage calls for freewriting on the developed outline, with no focus on grammar and language at this point — that comes later.",
  },
  {
    id: "cb-wp-14",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The lecture names three types of editing. Which of these is NOT one of them?",
    options: ["Self-editing", "Peer-editing", "Group-editing", "AI-editing"],
    correctIndex: 3,
    explanation: "The three types of editing named are Self-editing, Peer-editing, and Group-editing.",
  },
  {
    id: "cb-wp-15",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The focus of editing labelled \"Content\" checks for relevance, adequacy, consistency, and...",
    options: ["accuracy", "font size", "margins", "pagination"],
    correctIndex: 0,
    explanation: "The lecture's \"Focus of Editing: Content\" section lists relevance, adequacy, consistency, and accuracy.",
  },
  {
    id: "cb-wp-16",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Checking whether a piece follows generic requirements (letter, memo, abstract), is well-organized, and uses logical sequencing and transitional markers falls under the editing focus of...",
    options: ["Content", "Structure", "Clarity", "Conciseness"],
    correctIndex: 1,
    explanation: "\"Focus of Editing: Structure\" covers generic requirements, organization (introduction/body/conclusion), logical sequencing, and transitional markers.",
  },
  {
    id: "cb-wp-17",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Checking for ambiguity, dangling constructions, sentence fragments, run-on sentences, and awkward sentences falls under the editing focus of...",
    options: ["Clarity", "Style", "Formatting", "Conciseness"],
    correctIndex: 0,
    explanation: "\"Focus of Editing: Clarity\" checks word/phrase/clausal/sentence-level issues including ambiguity, dangling constructions, fragments, run-ons, and awkward sentences.",
  },
  {
    id: "cb-wp-18",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Checking the level of formality, appropriate tone, sentence variety, and gender-sensitive language falls under the editing focus of...",
    options: ["Style", "Formatting", "Content", "Conciseness"],
    correctIndex: 0,
    explanation: "\"Focus of Editing: Style\" covers formality, tone, sentence beginning/length/variety/complexity, paragraph length, and gender-sensitive language.",
  },
  {
    id: "cb-wp-19",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Which of the following words does the lecture flag as having \"very little utility value\" and worth dispensing with, under Conciseness?",
    options: ["\"actually\", \"basically\", \"practically\"", "\"however\", \"therefore\", \"thus\"", "\"and\", \"but\", \"or\"", "\"the\", \"a\", \"an\""],
    correctIndex: 0,
    explanation: "Under Conciseness, the lecture names filler words like \"actually,\" \"basically,\" and \"practically\" as having very little utility value.",
  },
  {
    id: "cb-wp-20",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "\"Basic fundamentals\", \"free gift\", and \"large in size\" are examples the lecture gives of...",
    options: ["redundancies to avoid", "acceptable technical jargon", "correct sentence combining", "appropriate transitional markers"],
    correctIndex: 0,
    explanation: "The lecture lists \"basic fundamentals\", \"free gift\", \"large in size\", and \"round in shape\" as examples of redundancies to avoid for conciseness.",
  },
  {
    id: "cb-wp-21",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "easy",
    question: "Proofreading is described in the lecture as...",
    options: [
      "a surface revision largely focused on the mechanics of language use.",
      "the very first step in the writing process.",
      "identical in scope to structural editing.",
      "an optional step that can be skipped for short documents.",
    ],
    correctIndex: 0,
    explanation: "Proofreading is described as \"surface revision,\" focused largely on the mechanics of language use.",
  },
  {
    id: "cb-wp-22",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "The focus of proofreading, per the lecture, includes concord, spelling, punctuation, tense, and...",
    options: ["repetition of words", "font choice", "line spacing", "citation style"],
    correctIndex: 0,
    explanation: "The lecture names concord, spelling, punctuation, tense, and repetition of words as the focus areas of proofreading, giving \"Africans must be be patriotic\" as an example of a repeated-word error.",
  },
  {
    id: "cb-wp-23",
    source: "lecture-material",
    sourceLabel: "Lecture 3: Writing as a Process",
    topic: "writing-process",
    difficulty: "medium",
    question: "Which guideline for editing/proofreading does the lecture explicitly recommend?",
    options: [
      "Edit and proofread in several short blocks of time, rather than all at once.",
      "Edit immediately after writing, without any pause.",
      "Always proofread aloud in a crowded room.",
      "Skip proofreading if the first draft feels strong.",
    ],
    correctIndex: 0,
    explanation: "The lecture's guidelines include maintaining distance from the text over time, finding a quiet place, and editing in several short blocks of time rather than all at once.",
  },

  // ==================== Lectures 9-10: Report Writing ====================
  {
    id: "cb-rw-1",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "easy",
    question: "Per Sekyi-Baidoo (2003), as cited in the lecture, a report is best described as an intervention between...",
    options: ["the present and the future.", "two departments.", "the writer and the editor.", "a sender and a receiver."],
    correctIndex: 0,
    explanation: "A report looks at the past/present so a decision can be made for the future — it is described as an intervention between the present and the future.",
  },
  {
    id: "cb-rw-2",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "Report writing focuses on adequately answering the reader's questions such as what happened, where, why, when and...",
    options: ["how it happened.", "who is to blame.", "how much it cost.", "who approved it."],
    correctIndex: 0,
    explanation: "The lecture states report writing focuses on answering what happened, where, why, when, and how it happened.",
  },
  {
    id: "cb-rw-3",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "The lecture describes the report-writing process as consisting of three activities: researching, presentation of analysed facts, and...",
    options: ["analysis and interpretation of information.", "printing and binding.", "peer review.", "translation."],
    correctIndex: 0,
    explanation: "The three activities are researching (looking for facts), analysis and interpretation of information, and presentation of analysed facts.",
  },
  {
    id: "cb-rw-4",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "A report noted for its conciseness and brevity, representing a lower level of formality than a long report, is called a...",
    options: ["Short Report", "Letter Report", "Memorandum Report", "Steward Report"],
    correctIndex: 0,
    explanation: "The Short Report is described as noted for conciseness and brevity, a compressed form of the long report with a lower level of formality.",
  },
  {
    id: "cb-rw-5",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "A formal report that is usually personal, uses the pronouns \"I\" and \"we,\" and directly communicates the speech of the investigator (who signs it) is called a...",
    options: ["Long Report", "Letter Report", "Memorandum Report", "Attachment Report"],
    correctIndex: 1,
    explanation: "The Letter Report is described as a formal letter, usually personal, using \"I\"/\"we\", directly communicating the investigator's own voice, who signs and names themself in the subscription.",
  },
  {
    id: "cb-rw-6",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "easy",
    question: "Which of the following is NOT one of the \"some specific types of reports\" named in the lecture?",
    options: ["Attachment reports", "Lab reports", "Project reports", "Grocery reports"],
    correctIndex: 3,
    explanation: "The lecture names attachment reports, lab reports, project/end-of-project reports, and steward reports (SONAs, VC's reports, Headmaster's reports) as specific examples.",
  },
  {
    id: "cb-rw-7",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "According to the lecture, almost every report has this basic structure: Title, The Introduction, The Main Body, and...",
    options: ["The Ending of the Report", "The Appendix only", "A Table of Figures", "The Bibliography only"],
    correctIndex: 0,
    explanation: "The lecture states the basic structure is Title, Introduction, Main Body, and the Ending of the Report.",
  },
  {
    id: "cb-rw-8",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "A formal report's more detailed structure, per the lecture, includes Title, Terms of Reference or Introduction, Procedure or Method, Findings/Content, Conclusions, and...",
    options: ["Recommendations", "Foreword only", "Acknowledgements only", "Preface only"],
    correctIndex: 0,
    explanation: "The formal report structure listed is: Title, Terms of Reference/Introduction, Procedure/Method, Findings/Content, Conclusions, Recommendations, References/Bibliography/Appendix.",
  },
  {
    id: "cb-rw-9",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "The lecture names three functions of an executive summary. Which of the following is NOT one of them?",
    options: [
      "It helps those too busy to read the whole report.",
      "It prepares the reader's mind for what the report contains.",
      "It can serve as a source of revision for those who already read it.",
      "It legally replaces the need for a signature page.",
    ],
    correctIndex: 3,
    explanation: "The three named functions are helping busy readers, preparing the reader's mind, and serving as a revision source — nothing about replacing a signature page.",
  },
  {
    id: "cb-rw-10",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "A copy of the letter that authorised an investigator to carry out a study, reminding the recipient that the report responds to this request, is called a letter of...",
    options: ["authorization", "transmittal", "introduction", "recommendation"],
    correctIndex: 0,
    explanation: "A letter of authorization is a copy of the letter that authorised the investigation, containing the problem, purpose, methodology, and a statement of authorisation.",
  },
  {
    id: "cb-rw-11",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "A document that formally hands over a completed report to its recipient, sometimes carrying a summary of findings, is called a letter of...",
    options: ["transmittal", "authorization", "salutation", "subscription"],
    correctIndex: 0,
    explanation: "A letter of transmittal (or letter of submission) formally transmits the report, often referring to the problem and authorisation, and may summarize findings.",
  },
  {
    id: "cb-rw-12",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "In the sample report on the fire outbreak at Maya Canteen, the fire was ultimately attributed, in the report's Conclusions, to...",
    options: [
      "the negligence and disrespect for authority shown by the bursar.",
      "an electrical fault in the kitchen.",
      "a deliberate act of sabotage by a rival canteen.",
      "insufficient firefighting equipment on campus.",
    ],
    correctIndex: 0,
    explanation: "The sample report's Conclusions state the fire was caused by the negligence and gross disrespect for authority demonstrated by the bursar, who fled the canteen leaving the cookers burning.",
  },
  {
    id: "cb-rw-13",
    source: "lecture-material",
    sourceLabel: "Lectures 9-10: Report Writing",
    topic: "report-writing",
    difficulty: "medium",
    question: "Regarding the language of reports, the lecture advises writers to...",
    options: [
      "avoid colloquial language and eliminate needless filler words.",
      "use as many abbreviations as possible for brevity.",
      "vary tense freely within the same paragraph for interest.",
      "use contractions like \"doesn't\" and \"can't\" for a friendly tone.",
    ],
    correctIndex: 0,
    explanation: "The lecture advises avoiding colloquial/informal language and eliminating fillers and needless words, limiting abbreviations, being consistent in tense, and avoiding contractions.",
  },

  // ==================== Organizational Communication ====================
  {
    id: "cb-oc-1",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "easy",
    question: "Per Adolinama (2005), as cited in the lecture, an organization is defined as a group of individuals with coordinated activities for the achievement of a common goal through a hierarchy of...",
    options: ["authority and responsibility.", "salary and benefits.", "friendship and trust.", "age and experience."],
    correctIndex: 0,
    explanation: "An organization is defined as a group of individuals with coordinated work/activities for a common goal, achieved through a hierarchy of authority and responsibility.",
  },
  {
    id: "cb-oc-2",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "easy",
    question: "An organogram is defined in the lecture as a diagram that shows...",
    options: [
      "the structure of an organization and the relationships of its parts and positions.",
      "the financial performance of a firm over time.",
      "the geographic locations of an organization's branches.",
      "a company's marketing strategy.",
    ],
    correctIndex: 0,
    explanation: "An organogram is a diagram showing an organization's structure and the relationships of its parts and positions, defining roles, the flow of power, and communication routes.",
  },
  {
    id: "cb-oc-3",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "According to the lecture, KNUST's University Statutes enshrine which three officers as the Principal Officers?",
    options: [
      "Chancellor, Chairman of the University Council, and the Vice Chancellor",
      "Registrar, Pro Vice Chancellor, and the Provost",
      "Dean, Head of Department, and the Vice Chancellor",
      "Chancellor, Registrar, and the Pro Vice Chancellor",
    ],
    correctIndex: 0,
    explanation: "The lecture names the Chancellor, Chairman of the University Council, and the Vice Chancellor as the Principal Officers enshrined in KNUST's statutes.",
  },
  {
    id: "cb-oc-4",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "The lecture describes KNUST's academic/administrative structure for the College system as a 3-Tier structure of Provosts, Deans, and...",
    options: ["Heads of Department", "Registrars", "Bursars", "Chancellors"],
    correctIndex: 0,
    explanation: "The 3-Tier Academic/Administrative Structure named is: Provosts of the six Colleges, Deans of the various Faculties, and Heads of the various Departments.",
  },
  {
    id: "cb-oc-5",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "The flow of information from a superior to a subordinate — such as a job description, appointment to a committee, dismissal, or query — is called...",
    options: ["Downward Communication", "Upward Communication", "Horizontal Communication", "Diagonal Communication"],
    correctIndex: 0,
    explanation: "Downward Communication is defined as the flow of information from a superior to a subordinate, with examples including job descriptions, appointments, dismissals, and queries.",
  },
  {
    id: "cb-oc-6",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "A junior officer submits a formal petition and a set of suggestions to management. This is an example of...",
    options: ["Upward Communication", "Downward Communication", "Diagonal Communication", "Grapevine Communication"],
    correctIndex: 0,
    explanation: "Upward Communication is the process of sending information from a subordinate to a superior; the lecture names petitions, task reports, complaints, and suggestions as examples.",
  },
  {
    id: "cb-oc-7",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "Sharing information between individuals of different levels of the hierarchy AND in different sections or departments is called...",
    options: ["Horizontal Communication", "Diagonal Communication", "Downward Communication", "Vertical Communication"],
    correctIndex: 1,
    explanation: "Diagonal Communication is the sharing of information between individuals of different levels of the hierarchy, in different sections or departments — a type the lecture says is discouraged in most organizations.",
  },
  {
    id: "cb-oc-8",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "Which of the following is a strategy the lecture recommends for improving Downward Communication specifically?",
    options: [
      "Establishing a culture of communication (pleasantries, briefings, meetings).",
      "Introducing a suggestion box.",
      "Rotating jobs between officers.",
      "Appointing a liaison officer.",
    ],
    correctIndex: 0,
    explanation: "Under \"Ways to Improve Downward Communication,\" the lecture lists establishing a culture of communication, training managers, creating social interaction opportunities, and treating communication skills as a recruitment/promotion criterion.",
  },
  {
    id: "cb-oc-9",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "Introducing a suggestion box for workers' comments and complaints is a strategy the lecture recommends specifically for improving...",
    options: ["Upward Communication", "Downward Communication", "Diagonal Communication", "Mass Communication"],
    correctIndex: 0,
    explanation: "Under \"Ways to Improve Upward Communication,\" the lecture lists regular meetings with employee representatives, suggestion boxes, and an open-door policy.",
  },
  {
    id: "cb-oc-10",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "medium",
    question: "Instituting inter-departmental work teams and rotating jobs are strategies the lecture recommends for improving...",
    options: ["Horizontal Communication", "Downward Communication", "Diagonal Communication", "Mass Communication"],
    correctIndex: 0,
    explanation: "Under \"Ways to Improve Horizontal Communication,\" the lecture lists inter-departmental teams, job rotation, peer counselling, and a liaison-officer communicator role.",
  },
  {
    id: "cb-oc-11",
    source: "lecture-material",
    sourceLabel: "Communication in Organizations",
    topic: "organizational-communication",
    difficulty: "easy",
    question: "Which of the following is NOT listed among the \"Some Communication Formats in Organizations\" in the lecture?",
    options: ["Letter Writing", "Memorandum", "Minutes", "Personal diary entries"],
    correctIndex: 3,
    explanation: "The lecture lists Letter Writing, Memorandum, E-mails, Reports, Minutes, and other technological means (IP Messenger, WhatsApp, Telegram) as organizational communication formats.",
  },

  // ==================== CV Writing ====================
  {
    id: "cb-cv-1",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "easy",
    question: "The term \"Curriculum Vitae\" is a Latin phrase which means...",
    options: ["\"Course of Life\"", "\"Summary of Skills\"", "\"Path to Success\"", "\"Record of Work\""],
    correctIndex: 0,
    explanation: "Curriculum Vitae is a Latin phrase meaning \"Course of Life\" — a document of personal advertisement for opportunities like employment or scholarship.",
  },
  {
    id: "cb-cv-2",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "A CV that outlines an individual's work and educational history in reverse chronological order, and is most commonly requested by potential employers, is called...",
    options: ["Traditional/Chronological CV", "Functional/Skills based CV", "Technical CV", "General Purpose CV"],
    correctIndex: 0,
    explanation: "The Traditional/Chronological CV outlines work and educational history in reverse order (starting with the most current) and is what potential employers mostly ask for.",
  },
  {
    id: "cb-cv-3",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "A recent graduate with no work history wants to highlight the skills and achievements gained during training rather than a work timeline. Which CV type suits them best?",
    options: ["Traditional/Chronological CV", "Functional/Skills based CV", "Technical CV", "Specific Purpose CV"],
    correctIndex: 1,
    explanation: "The Functional/Skills-based CV is described as useful for a graduate or apprentice who just completed their education, to show relevant skills rather than a work history.",
  },
  {
    id: "cb-cv-4",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "A CV that showcases the skills and experience required for a specific technical position — commonly used in IT and Engineering — is called a...",
    options: ["Technical CV", "General Purpose CV", "Functional CV", "Chronological CV"],
    correctIndex: 0,
    explanation: "The Technical CV showcases skills/experience for a technical position, focusing on a particular skill set, and is usually used by IT and Engineering professionals.",
  },
  {
    id: "cb-cv-5",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "A CV encapsulating every significant detail of a person's accomplishments, not written for one specific purpose, is called a...",
    options: ["General Purpose CV", "Specific Purpose CV", "Technical CV", "Traditional CV"],
    correctIndex: 0,
    explanation: "The General Purpose CV is described as encapsulating every significant detail to give a holistic impression, not written for specific purposes (though it can be edited when needed).",
  },
  {
    id: "cb-cv-6",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "hard",
    question: "According to the lecture, one difference between a CV and a Resume is that...",
    options: [
      "a CV is comprehensive (2-20 pages or more) while a resume is concise (1-2 pages).",
      "a resume always includes references while a CV never does.",
      "a CV is always shorter than a resume.",
      "a resume is used only in Ghana, while a CV is used everywhere else.",
    ],
    correctIndex: 0,
    explanation: "The lecture notes a CV is comprehensive (2-20 pages or more) while a resume is concise (1-2 pages); it also notes References ARE included in a CV but not in a resume.",
  },
  {
    id: "cb-cv-7",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "Which of these is listed by the lecture as a SIMILARITY between CVs and Resumes, rather than a difference?",
    options: [
      "Both are tailored for the specific job/company being applied to.",
      "Both are the same length.",
      "Both always include personal interests.",
      "Both are more oriented to academic credentials.",
    ],
    correctIndex: 0,
    explanation: "The lecture lists similarities including: both are tailored to the job/company, represent the candidate as best qualified, are used to secure an interview, and do NOT usually include personal interests.",
  },
  {
    id: "cb-cv-8",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "easy",
    question: "According to the lecture, the four general areas a CV typically covers are Personal Details/Data, Education, Experience, and...",
    options: ["Reference/Referees", "Hobbies only", "Salary expectations", "Marital status only"],
    correctIndex: 0,
    explanation: "The general CV areas listed are Personal Details/Data, Education, Experience, and Reference/Referees.",
  },
  {
    id: "cb-cv-9",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "In the Education section of a CV, dissertation or thesis topics are recommended for inclusion mainly for individuals...",
    options: [
      "applying in academia or jobs requiring research skills.",
      "with no other information to add to the CV.",
      "applying strictly for entry-level clerical roles.",
      "who have not yet chosen a research topic.",
    ],
    correctIndex: 0,
    explanation: "Dissertation/thesis topics can be added for individuals using the CV for specific purposes in academia or jobs requiring research skills.",
  },
  {
    id: "cb-cv-10",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "In the Work Experience section, stating the job title is important mainly because...",
    options: [
      "it eases the verification process for prospective employers.",
      "it is a legal requirement in all countries.",
      "it determines the CV's overall length.",
      "it replaces the need to name the workplace.",
    ],
    correctIndex: 0,
    explanation: "Stating the job title (alongside the workplace name) eases verification for prospective employers, who could otherwise not confirm the claimed job experience.",
  },
  {
    id: "cb-cv-11",
    source: "lecture-material",
    sourceLabel: "Writing a CV",
    topic: "cv-writing",
    difficulty: "medium",
    question: "Which of the following is listed among the \"Other areas\" a CV might include, beyond the four general areas?",
    options: ["Professional Development (workshops, symposia, seminars attended)", "The applicant's blood type", "The applicant's star sign", "The applicant's favourite colour"],
    correctIndex: 0,
    explanation: "\"Other areas\" listed include Personal Statement, Professional Skills, Professional Development, Publications, Presentations, Memberships, Community Service, Awards, and Interests/Hobbies.",
  },

  // ==================== Letter Writing (Formal Letters) ====================
  {
    id: "cb-lw-1",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "easy",
    question: "A formal letter is defined in the lecture as a written form of communication for...",
    options: ["official or business purposes.", "casual daily updates.", "purely personal, family news.", "anonymous complaints only."],
    correctIndex: 0,
    explanation: "A formal letter is a written form of communication for official or business purposes, concerning work, employment, or offices/positions.",
  },
  {
    id: "cb-lw-2",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The Writer's Address has two components: the Institution and Mail Element, and the...",
    options: ["Location Element", "Time Element", "Salutation Element", "Signature Element"],
    correctIndex: 0,
    explanation: "The Writer's Address has two components: the Institution and Mail Element (institution name plus mail address), and the Location Element.",
  },
  {
    id: "cb-lw-3",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "When a writer has no institutional address of their own, the lecture says they can use a \"Care of\" address, abbreviated as...",
    options: ["C/o", "Att:", "Ref:", "Cc:"],
    correctIndex: 0,
    explanation: "In the case where the writer has no address, a \"Care of\" (C/o) address can be used, with replies sent to the stated address and received by the named intermediary.",
  },
  {
    id: "cb-lw-4",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "If a writer places their address at the \"Top-right corner\" of the letter, the lecture says the subscription must be placed at the...",
    options: ["down-right corner", "down-left corner", "top-left corner", "very bottom-center"],
    correctIndex: 0,
    explanation: "When the Writer's Address is at the top-right, the subscription must also be at the down-right corner, after the conclusion of the main body.",
  },
  {
    id: "cb-lw-5",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The Recipient's Address has three parts: the recipient's name or designation, the institution's name, and the...",
    options: ["Location", "Salutation", "Date", "Heading"],
    correctIndex: 0,
    explanation: "The Recipient's Address has three parts: the recipient's name/designation, the institution's name, and the location of the institution.",
  },
  {
    id: "cb-lw-6",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "A letter addressed to \"The Chief Administrative Officer\" rather than to a personal name is, per the lecture, considered the property of...",
    options: ["the institution, and can be opened by the Secretary.", "no one until the CEO personally opens it.", "the writer only.", "the postal service."],
    correctIndex: 0,
    explanation: "Letters carrying a designation (rather than a personal name) are deemed the property of the institution and can be opened by the Secretary.",
  },
  {
    id: "cb-lw-7",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "hard",
    question: "The lecture distinguishes four broadened categories of recipient. Which one refers to a person the writer thinks should be informed about the content of the letter, marked with a \"CC\" caption?",
    options: ["Copy Recipient", "Direct Recipient", "Attention Recipient", "Through Recipient"],
    correctIndex: 0,
    explanation: "The Copy Recipient is a person the writer wants informed about the letter's content, marked with \"CC\" (Courtesy Copy/Carbon Copy) at the close of the letter.",
  },
  {
    id: "cb-lw-8",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "hard",
    question: "The recipient category expected to carry out some duty related to the letter's content, written with \"Attention\" or \"Attn\" at the close of the letter, is called the...",
    options: ["\"Attention\" Recipient", "\"Through\" Recipient", "Copy Recipient", "Direct Recipient"],
    correctIndex: 0,
    explanation: "The \"Attention\" recipient is expected to carry out duties related to the letter's content, and is written as \"Attention\" or \"Attn\" at the letter's close.",
  },
  {
    id: "cb-lw-9",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "hard",
    question: "A letter addressed to the Vice Chancellor, but routed \"Through\" the Provost, then \"Through\" the Dean, then \"Through\" the Head of Department, illustrates that a Through recipient serves as...",
    options: [
      "an official transit point that plays an important role in the letter's onward action.",
      "the ultimate and final destination of the letter.",
      "someone with no real involvement in the letter's outcome.",
      "a person who cancels the letter's purpose.",
    ],
    correctIndex: 0,
    explanation: "The \"Through\" recipient serves as an official transit for a letter on its way to the direct recipient, playing important roles in the action to be taken.",
  },
  {
    id: "cb-lw-10",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The lecture lists three accepted salutations for a formal letter, all requiring a mandatory comma. Which of these is NOT one of them?",
    options: ["\"Dear Sir,\"", "\"Dear Madam,\"", "\"Dear Sir/Madam,\"", "\"Hey there,\""],
    correctIndex: 3,
    explanation: "The accepted salutations are \"Dear Sir,\" (male recipient), \"Dear Madam,\" (female recipient), and \"Dear Sir/Madam,\" (unknown recipient, best avoided if possible).",
  },
  {
    id: "cb-lw-11",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The lecture notes that a letter's Heading must NOT be...",
    options: ["written in a sentence form and punctuated with a full stop.", "capitalized.", "placed above the salutation.", "longer than three words."],
    correctIndex: 0,
    explanation: "The Heading captures the purpose of the letter and must not be written as a sentence, so it should not end with a full stop.",
  },
  {
    id: "cb-lw-12",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: 'When replying to an earlier letter, the lecture says the previous heading should be copied with the prefix...',
    options: ['"Re:"', '"Fwd:"', '"Ref. No.:"', '"Att:"'],
    correctIndex: 0,
    explanation: 'When writing in response to an earlier letter, the previous heading should be copied with the prefix "Re:" — for example, "Re: Offer of Appointment."',
  },
  {
    id: "cb-lw-13",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The Content/Body of a formal letter is partitioned into introduction, main body, and...",
    options: ["conclusion.", "footer.", "signature block.", "table of contents."],
    correctIndex: 0,
    explanation: "The Content/Body is partitioned into Introduction, Main Body, and Conclusion.",
  },
  {
    id: "cb-lw-14",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "In an application letter's conclusion, ending with \"I humbly hope that my application is considered\" is an example of a...",
    options: ["Statement of Hope", "Statement of Attachment", "Statement of Fact", "Statement of Complaint"],
    correctIndex: 0,
    explanation: "A Statement of Hope is where the writer ends by expressing hope of being offered the appointment — exactly this example sentence.",
  },
  {
    id: "cb-lw-15",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The Subscription has four parts: complimentary close, signature, name, and...",
    options: ["designation and identification.", "the date again.", "the recipient's address again.", "a postscript."],
    correctIndex: 0,
    explanation: "The Subscription's four parts are complimentary close/closing, signature, name, and designation and identification.",
  },
  {
    id: "cb-lw-16",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "According to the lecture, \"Yours sincerely\" is used specifically when...",
    options: [
      "there is some rapport between the writer and recipient, or the recipient's name is known.",
      "the letter is a job application to an unknown recipient.",
      "the letter is extremely urgent.",
      "the writer is uncertain of the recipient's gender.",
    ],
    correctIndex: 0,
    explanation: '"Yours sincerely" is used when there is rapport between writer and recipient, or when the recipient\'s name is written at the recipient address section — "Yours faithfully" is preferred for job applications.',
  },
  {
    id: "cb-lw-17",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "hard",
    question: 'The lecture\'s rule for "Yours" vs. "Your" in a closing is that...',
    options: [
      '"Yours" is used when an adverb (often ending in -ly) follows, and "Your" is used otherwise.',
      '"Your" is always correct, "Yours" is always wrong.',
      'Both are interchangeable in every case.',
      '"Yours" is only used in American English.',
    ],
    correctIndex: 0,
    explanation: '"Yours" should be used when an adverb (e.g. "faithfully") follows in the closing; "Your" can be used when no adverb follows, as in "Your Trustee."',
  },
  {
    id: "cb-lw-18",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "Which of the following phrases does the lecture explicitly warn AGAINST using in a formal or application letter?",
    options: ['"Thanking you in advance"', '"I respectfully write to..."', '"I humbly hope that..."', '"Yours faithfully,"'],
    correctIndex: 0,
    explanation: 'The lecture warns never to use sentences like "bye for now" or participial phrases such as "Thanking you in advance" or "Hoping to hear soon from you."',
  },
  {
    id: "cb-lw-19",
    source: "lecture-material",
    sourceLabel: "Formal Letters",
    topic: "letter-writing",
    difficulty: "medium",
    question: "The lecture advises against \"begging\" or sounding overly religious in a business letter, recommending words like \"plead\" or \"implore\" instead of...",
    options: ['"beg."', '"request."', '"ask."', '"inquire."'],
    correctIndex: 0,
    explanation: 'The lecture advises against sounding like you are "begging," recommending "plead" or "implore" as more appropriate alternatives.',
  },

  // ==================== Memorandum ====================
  {
    id: "cb-memo-1",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "easy",
    question: "The lecture describes a memorandum as differing from a formal letter mainly in its formal features, range of circulation, and its...",
    options: ["range of formality.", "use of colour.", "length in pages only.", "postage cost."],
    correctIndex: 0,
    explanation: "A memorandum differs from a formal letter in its formal features, its range of circulation, and its range of formality.",
  },
  {
    id: "cb-memo-2",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "medium",
    question: "The lecture classifies memoranda into three types: informal, semi-formal, and...",
    options: ["formal (policy)", "confidential", "urgent", "annual"],
    correctIndex: 0,
    explanation: "Memoranda are classified into the Informal Memoranda, the Semi-formal Memorandum, and the Formal or Policy Memorandum.",
  },
  {
    id: "cb-memo-3",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "medium",
    question: "Hand-written, conversational messages of one to six lines, typically not following the three-part structure and rarely kept on file, describe which type of memo?",
    options: ["Informal Memoranda", "Semi-formal Memorandum", "Formal/Policy Memorandum", "Circular Memorandum"],
    correctIndex: 0,
    explanation: "Informal Memoranda are hand-written, conversational, one-to-six-line messages that don't usually follow the three-part structure and aren't typically kept on record.",
  },
  {
    id: "cb-memo-4",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "medium",
    question: "A memo concerned with general policies and directives (rather than day-to-day activities), often addressed to communal recipients like \"All Employees\" or \"All Heads of Departments,\" is called the...",
    options: ["Formal or Policy Memorandum", "Informal Memoranda", "Circular Letter", "Attachment Report"],
    correctIndex: 0,
    explanation: "The Formal or Policy Memorandum deals with general policies/directives, not day-to-day information, and is often addressed to communal recipients.",
  },
  {
    id: "cb-memo-5",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "medium",
    question: "Which memo type follows the three-part structure (introduction, body, conclusion) and is a communication between roughly equal-status colleagues about day-to-day activities?",
    options: ["The Semi-formal Memorandum", "The Informal Memoranda", "The Policy Memorandum only", "None of the memo types use this structure"],
    correctIndex: 0,
    explanation: "The Semi-formal Memorandum is a day-to-day communication between roughly equal-status individuals, and — unlike the informal memo — it follows the three-part structure and is filed.",
  },
  {
    id: "cb-memo-6",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "medium",
    question: "The specific headings on a memo pad, coming below the corresponding heading, typically comprise From, To, Date, and...",
    options: ["Subject", "Cc", "Enclosure", "Priority"],
    correctIndex: 0,
    explanation: "The specific headings named are From, To, Date, and Subject.",
  },
  {
    id: "cb-memo-7",
    source: "lecture-material",
    sourceLabel: "Memorandum",
    topic: "memorandum",
    difficulty: "medium",
    question: "Which of the following is NOT among the uses of a memorandum listed in the lecture?",
    options: ["Report information", "Make requests", "Recommend an action", "Formally terminate an employee's contract"],
    correctIndex: 3,
    explanation: "The lecture lists reporting information, making requests, recommending an action, and communicating issues of immediate importance — not formal dismissal, which is handled by a formal letter instead.",
  },

  // ==================== Meetings & Minutes ====================
  {
    id: "cb-mm-1",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "The lecture names five types of meetings. Which of these is a meeting held every year to assess an organization's management?",
    options: ["Annual General Meeting (AGM)", "Statutory meeting", "Board meeting", "Informal meeting"],
    correctIndex: 0,
    explanation: "The Annual General Meeting (AGM) is held every year to assess the management of an organization over the year.",
  },
  {
    id: "cb-mm-2",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "A meeting held so that directors and shareholders can communicate and consider special reports, which companies are required by law to hold, is called a...",
    options: ["Statutory meeting", "Informal meeting", "AGM", "Board meeting"],
    correctIndex: 0,
    explanation: "Statutory meetings are held for directors and shareholders to communicate and consider special reports, and companies are legally required to hold them.",
  },
  {
    id: "cb-mm-3",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "A meeting attended by all directors, chaired by the Chairman of the board, held as often as required, is called a...",
    options: ["Board meeting", "AGM", "Informal meeting", "Statutory meeting"],
    correctIndex: 0,
    explanation: "Board meetings are attended by all directors and chaired by the Chairman of the board, held as often as individual organizations require.",
  },
  {
    id: "cb-mm-4",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "In Informal Meetings, the lecture notes that unlike formal meetings...",
    options: [
      "strict agendas may not be necessary, and minutes may not be kept.",
      "a quorum is always mandatory.",
      "only the Chairman may speak.",
      "attendance is always compulsory by law.",
    ],
    correctIndex: 0,
    explanation: "Informal meetings are not restricted by the same rules as formal meetings — strict agendas may not be necessary, and minutes may not be kept.",
  },
  {
    id: "cb-mm-5",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "A document informing members or directors about an upcoming meeting, specifying date, time, place, and the general nature of the business, is called a...",
    options: ["Notice of Meeting", "Minutes", "Agenda", "Motion"],
    correctIndex: 0,
    explanation: "A Notice of Meeting is a document informing members/directors about an upcoming meeting, specifying date, time, place, and the nature of the business to be transacted.",
  },
  {
    id: "cb-mm-6",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "The list of items to be considered at a meeting, also called \"business\" or \"order of business,\" is called the...",
    options: ["Agenda", "Notice", "Motion", "Minutes"],
    correctIndex: 0,
    explanation: "The agenda is the list of items to be considered at a meeting, also called business or order of business.",
  },
  {
    id: "cb-mm-7",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "A formal statement, usually involving a proposed action, put to a meeting for discussion and a subsequent vote, is called a...",
    options: ["Motion", "Point of Order", "Quorum", "Amendment"],
    correctIndex: 0,
    explanation: "A motion is a formal statement, usually involving a proposed action, put to a meeting for discussion and subsequent decision by vote.",
  },
  {
    id: "cb-mm-8",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "A member interrupts to say the chairperson is not following correct meeting procedure and wants the meeting brought back on track. This member is raising a...",
    options: ["Point of Order", "Point of Information", "Motion", "Amendment"],
    correctIndex: 0,
    explanation: "A Point of Order is used when a member feels the meeting procedure is not being followed and wants the meeting returned to the correct procedure.",
  },
  {
    id: "cb-mm-9",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "A proposed modification to a motion, which does not conflict with the motion's general thrust, is called an...",
    options: ["Amendment", "Point of Order", "Quorum", "Notice"],
    correctIndex: 0,
    explanation: "An Amendment is a proposed modification to a motion that does not conflict with its general thrust — if adopted, it becomes part of the \"motion as amended.\"",
  },
  {
    id: "cb-mm-10",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "Minutes that describe in detail the various contributions preceding decisions and vetoes, showing how thorough discussions were, are called...",
    options: ["Narrative minutes", "Resolution minutes", "Action minutes", "Summary minutes"],
    correctIndex: 0,
    explanation: "Narrative minutes describe the various contributions preceding decisions and vetoes in detail, showing how thorough the discussion was and whether decisions were by consensus.",
  },
  {
    id: "cb-mm-11",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "Minutes that focus specifically on answering \"What decisions were taken at the meeting?\" are called...",
    options: ["Resolution minutes", "Narrative minutes", "Action minutes", "Draft minutes"],
    correctIndex: 0,
    explanation: "Resolution minutes concentrate on responding to \"What decisions were taken at the meeting?\" — recording only the decisions reached and related essential details.",
  },
  {
    id: "cb-mm-12",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "Minutes that place further emphasis on the person and strategies by which decisions are implemented — including executing officers and timeframes — are called...",
    options: ["Action minutes", "Narrative minutes", "Resolution minutes", "Verbatim minutes"],
    correctIndex: 0,
    explanation: "Action minutes are close to resolution minutes but emphasize the person and strategies for implementation — including executing officers, timeframes, and equipment.",
  },
  {
    id: "cb-mm-13",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "According to the lecture, which item is generally NOT recorded in minutes unless there was discussion or agitation about it?",
    options: ["Corrections to previous minutes", "The meeting's title", "The closing time", "Motions and counter-motions"],
    correctIndex: 0,
    explanation: "Under \"Previous Minutes,\" the lecture states corrections are generally not recorded unless there were some discussions or agitation about them.",
  },
  {
    id: "cb-mm-14",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "Under the structure of minutes, the section that records discussions not part of the drawn-up agenda (announcements, remarks, complaints, suggestions) is called...",
    options: ["Any Other Business (AOB)", "Main Business", "Opening", "Endorsement"],
    correctIndex: 0,
    explanation: "Any Other Business (AOB), also called Other Matters, records discussions not part of the agenda — generally announcements, remarks, complaints, suggestions, and enquiries.",
  },
  {
    id: "cb-mm-15",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "The Endorsement section of minutes comprises...",
    options: [
      "the name and signature of the person who recorded the minutes.",
      "the agenda for the next meeting.",
      "a summary of the treasurer's report.",
      "the notice of the meeting.",
    ],
    correctIndex: 0,
    explanation: "The Endorsement comprises the name and signature of the minutes-recorder, and sometimes the Chairman's name and signature too.",
  },
  {
    id: "cb-mm-16",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: "Regarding the language of minutes, the lecture states that the tense generally used is...",
    options: ["the simple past tense.", "the simple present tense.", "the future tense.", "the present continuous tense."],
    correctIndex: 0,
    explanation: "Because minutes are a record of past speeches and decisions, the simple past tense is generally used.",
  },
  {
    id: "cb-mm-17",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "hard",
    question: "The lecture explains that the passive voice is frequently used in minutes because...",
    options: [
      "what is said and decided is considered more important than who said it.",
      "the passive voice is grammatically required in all formal writing.",
      "minutes must always be anonymous.",
      "active voice is too difficult for most secretaries to use.",
    ],
    correctIndex: 0,
    explanation: "The passive is frequent in minutes because what is said and the decisions made are considered more important than the individuals who said them, highlighting group interest over the individual.",
  },
  {
    id: "cb-mm-18",
    source: "lecture-material",
    sourceLabel: "Meeting and Minutes Writing",
    topic: "meetings-minutes",
    difficulty: "medium",
    question: 'The lecture notes that reported speech (rather than direct speech) is used in minutes because it...',
    options: [
      "facilitates summary and removes untidy or irrelevant parts of contributions.",
      "is legally mandatory in all countries.",
      "is easier for non-native speakers to write.",
      "allows the secretary to quote people verbatim.",
    ],
    correctIndex: 0,
    explanation: "Reported speech facilitates summary and helps remove untidy and irrelevant parts of what was actually said, unlike direct quotation.",
  },

  // ==================== Oral Communication ====================
  {
    id: "cb-oral-1",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "easy",
    question: "The lecture names seven characteristics of effective oral communication, often called the \"7 Cs.\" Which of the following is NOT one of them?",
    options: ["Completeness", "Conciseness", "Confidence", "Correctness"],
    correctIndex: 2,
    explanation: "The named characteristics are Completeness, Conciseness, Concreteness, Courtesy, Clearness, Correctness, and Consideration — \"Confidence\" on its own is not one of them.",
  },
  {
    id: "cb-oral-2",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "A speaker supports their claims with facts and figures to make the message specific, tangible, and vivid. This best exemplifies which characteristic of effective oral communication?",
    options: ["Concreteness", "Courtesy", "Consideration", "Completeness"],
    correctIndex: 0,
    explanation: "Concreteness means the message is specific, tangible, and vivid, supported by facts and figures for enhanced trustworthiness.",
  },
  {
    id: "cb-oral-3",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "A face-to-face conversation where either party can immediately ask for clarification is an example of which type of oral communication, per the lecture?",
    options: ["Interactive", "Partially interactive", "Non-interactive", "Mass"],
    correctIndex: 0,
    explanation: "Interactive oral communication includes face-to-face conversation, interviews, and phone calls — situations that allow an immediate chance to ask for clarification or make a request.",
  },
  {
    id: "cb-oral-4",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "A recorded podcast episode, where the speaker cannot see or respond to listener reactions in real time, is an example of which type of oral communication?",
    options: ["Non-interactive", "Interactive", "Partially interactive", "Bilineal"],
    correctIndex: 0,
    explanation: "Non-interactive oral communication includes recordings, performing in a play, singing, or reciting a poem — there is no real-time exchange with the audience.",
  },
  {
    id: "cb-oral-5",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "Which term does the lecture use for stage fright, defined as a state of fear or shyness when facing the requirement of performing before an audience?",
    options: ["Glossophobia", "Aphasia", "Amnesia", "Dyslexia"],
    correctIndex: 0,
    explanation: "Glossophobia is the lecture's term for stage fright/performance anxiety.",
  },
  {
    id: "cb-oral-6",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "According to the lecture's list of symptoms of stage fright, sweating and an altered heart rate fall under which category of symptom?",
    options: ["Psychological", "Cognitive", "Behavioural", "Chronic"],
    correctIndex: 0,
    explanation: "Psychological symptoms listed include sweating, altered heart rate, headache, upset stomach, chills, and nausea.",
  },
  {
    id: "cb-oral-7",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "Congestion and mental confusion, along with fear of failure and ridicule, are symptoms of stage fright the lecture classifies as...",
    options: ["Cognitive", "Psychological", "Behavioural", "Physical"],
    correctIndex: 0,
    explanation: "Cognitive symptoms include congestion and mental confusion, and fear of failure and ridicule.",
  },
  {
    id: "cb-oral-8",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "The urge to escape a situation, stuttering, and long silences are, per the lecture, examples of which category of stage-fright symptom?",
    options: ["Behavioural", "Cognitive", "Psychological", "Environmental"],
    correctIndex: 0,
    explanation: "Behavioural symptoms include the urge to escape from the situation, stuttering, and frequent, long silences.",
  },
  {
    id: "cb-oral-9",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "Which of the following is NOT one of the lecture's tips for controlling stage fright?",
    options: [
      "Practise privately in front of a mirror and analyse your performance.",
      "Prepare your environment in advance so you can concentrate on delivery.",
      "Speak as quickly as possible to finish before nerves take over.",
      "Bring something to hold onto if you tend to fidget when nervous.",
    ],
    correctIndex: 2,
    explanation: 'The lecture specifically advises "do not hurry through it," since speaking quickly is associated with hurried breaths, fear, and panic — the opposite of the recommended approach.',
  },
  {
    id: "cb-oral-10",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "In a chairperson's remarks BEFORE the main programme, the lecture recommends the chairperson do all of the following EXCEPT...",
    options: [
      "greet guests informally with light-hearted language.",
      "express gratitude for attendance.",
      "read out a long list of every sponsor's name in detail.",
      "introduce the event's name and purpose briefly.",
    ],
    correctIndex: 2,
    explanation: "The lecture advises acknowledging only a handful of highlights and avoiding reading off a long list of people or sponsors, since the audience will get bored.",
  },
  {
    id: "cb-oral-11",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "Which linguistic routine does the lecture describe as marking the closing of events like meetings, lectures, or workshops, and is a symbol of love between benefactor and beneficiary?",
    options: ["Thanking/Thanksgiving", "Apology", "Request", "Recounting one's mission"],
    correctIndex: 0,
    explanation: "Thanking/Thanksgiving is described as ritualized and institutionalized, marking the closing of events, and serving as a symbol of love between benefactor and beneficiary.",
  },
  {
    id: "cb-oral-12",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "For a Vote of Thanks, the lecture advises that in a very formal occasion, thanking God...",
    options: ["may not be necessary, since a closing prayer will cover this.", "must always be the first sentence.", "should never be mentioned at all.", "should take up most of the speech."],
    correctIndex: 0,
    explanation: "In a very formal occasion, thanking God may not be necessary in the vote of thanks — that is left to the closing prayer instead.",
  },
  {
    id: "cb-oral-13",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "A Proposal of Toast is defined as wishing a person future health, happiness, and success, and asking others to...",
    options: ["raise their glasses and join in a drink.", "sign a formal document.", "stand for a moment of silence.", "applaud for one full minute."],
    correctIndex: 0,
    explanation: "A toast wishes a person future health, happiness, and success, and asks others to raise their glasses and join in a drink.",
  },
  {
    id: "cb-oral-14",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "In the guidance on how to propose a toast, the lecture advises to \"keep short and sweet,\" catch the audience's attention, and to be witty but never...",
    options: ["vulgar.", "brief.", "prepared.", "sincere."],
    correctIndex: 0,
    explanation: "The lecture advises being witty but never vulgar, alongside being prepared, brief, and audience-aware.",
  },
  {
    id: "cb-oral-15",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "For efficient telephone use, the lecture advises all of the following EXCEPT...",
    options: [
      "speak clearly and audibly.",
      "actively listen and take notes.",
      "leave the caller on hold for as long as needed to multitask.",
      "avoid shouting or whispering."],
    correctIndex: 2,
    explanation: "The lecture explicitly advises: \"Do not leave caller on hold for too long.\"",
  },
  {
    id: "cb-oral-16",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "easy",
    question: "An interview is defined by the lecture as a selection process designed to obtain information from a person through...",
    options: ["oral responses to oral inquiries.", "a written multiple-choice test.", "silent observation only.", "a background check alone."],
    correctIndex: 0,
    explanation: "An interview is a selection process designed to obtain information from a person through oral responses to oral inquiries.",
  },
  {
    id: "cb-oral-17",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "An interview with probing, open-ended questions and no set format, allowing the interviewer to pursue points of interest as they develop, is called an...",
    options: ["Unstructured/Nondirective Interview", "Structured/Directive Interview", "Panel Interview", "Mass Interview"],
    correctIndex: 0,
    explanation: "The Unstructured/Nondirective Interview involves open-ended, probing questions with no set format, letting the interviewer follow up on points of interest.",
  },
  {
    id: "cb-oral-18",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "hard",
    question: "\"Job-sample simulation questions,\" which involve situations where an applicant must actually perform a sample task, belong to which named category from the lecture?",
    options: [
      "One of the four types of questions under a structured/directive interview.",
      "A category unique to unstructured interviews.",
      "A category found only in panel interviews.",
      "A category unrelated to any interview type."],
    correctIndex: 0,
    explanation: "The four types of questions under a structured/directive interview are situational, job knowledge, job-sample simulation, and worker requirements questions.",
  },
  {
    id: "cb-oral-19",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "In a Behavioral Interview, applicants are asked to...",
    options: [
      "describe how they reacted to actual situations in the past.",
      "solve a hypothetical math problem on a whiteboard.",
      "role-play a customer complaint scenario live.",
      "sit silently while the panel observes body language."],
    correctIndex: 0,
    explanation: "In a behavioral interview, applicants describe how they reacted to actual past situations, using standardized questions about handling situations similar to those they may face on the job.",
  },
  {
    id: "cb-oral-20",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "A Panel/Board Interview involves...",
    options: [
      "a team of interviewers who together interview each candidate and combine their ratings.",
      "one interviewer meeting one candidate at a time.",
      "several candidates being interviewed together in a leaderless discussion.",
      "no interviewers at all, only a written test."],
    correctIndex: 0,
    explanation: "A Panel Interview (Board Interview) is conducted by a team of interviewers who together interview each candidate and combine their ratings into a final score.",
  },
  {
    id: "cb-oral-21",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "hard",
    question: "A Mass/Group Interview is described in the lecture as a procedure for the discovery of...",
    options: ["leadership.", "salary expectations.", "typing speed.", "physical fitness."],
    correctIndex: 0,
    explanation: "The mass/group interview places several applicants in a leaderless discussion while interviewers observe — it is a procedure for the discovery of leadership.",
  },
  {
    id: "cb-oral-22",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "Before an interview day, the lecture advises applicants to prepare by researching the organization's background, putting together their CV/certificates, and...",
    options: [
      "thinking about possible questions and preparing answers.",
      "memorizing the entire company handbook.",
      "avoiding all contact with current employees.",
      "arriving exactly on time, never earlier."],
    correctIndex: 0,
    explanation: "Before-the-interview preparation includes researching the organization, gathering documents, and thinking about possible questions to prepare answers for.",
  },
  {
    id: "cb-oral-23",
    source: "lecture-material",
    sourceLabel: "Oral Communication",
    topic: "oral-communication",
    difficulty: "medium",
    question: "On the day of the interview, the lecture notes that your interview effectively begins...",
    options: [
      "the moment you step inside the organization.",
      "only once you sit in the interview chair.",
      "only when the panel asks the first question.",
      "only after the interview officially ends."],
    correctIndex: 0,
    explanation: "The lecture states your interview begins the moment you step inside the organization, so courtesy toward everyone (including the receptionist) matters from that point on.",
  },
];
