export type EconsTopic =
  | "macro-fundamentals"
  | "circular-flow"
  | "national-income"
  | "business-cycle-growth"
  | "unemployment"
  | "inflation"
  | "phillips-curve"
  | "balance-of-payments"
  | "exchange-rates";

export type QuestionType = "concept" | "code-analysis" | "debugging" | "best-practice";

export interface EconsExamQuestion {
  id: string;
  topic: EconsTopic;
  subtopic: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  type: QuestionType;
  code?: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  misconception?: string;
  relatedPartId: string;
}

export const ECONS_EXAM_TOPICS: { id: EconsTopic; label: string }[] = [
  { id: "macro-fundamentals", label: "Macro Fundamentals & Objectives" },
  { id: "circular-flow", label: "Circular Flow of Income" },
  { id: "national-income", label: "Measuring National Income" },
  { id: "business-cycle-growth", label: "Business Cycle & Growth" },
  { id: "unemployment", label: "Unemployment" },
  { id: "inflation", label: "Inflation" },
  { id: "phillips-curve", label: "The Phillips Curve" },
  { id: "balance-of-payments", label: "Balance of Payments" },
  { id: "exchange-rates", label: "Exchange Rates" },
];

export const econsExamBank: EconsExamQuestion[] = [
  // ---------- Macro Fundamentals & Objectives (8) ----------
  {
    id: "econs-1",
    topic: "macro-fundamentals",
    subtopic: "Macro vs micro",
    difficulty: 1,
    type: "concept",
    question: "Which best distinguishes macroeconomics from microeconomics?",
    options: [
      "Macroeconomics studies the economy as a whole; microeconomics studies a single market or household",
      "Macroeconomics only studies government policy; microeconomics studies private firms",
      "Macroeconomics is only concerned with inflation; microeconomics with everything else",
      "There is no real difference, just different names",
    ],
    correctIndex: 0,
    explanation: "Macroeconomics deliberately simplifies by ignoring differences among individual households/firms to study the economy overall; microeconomics focuses on individual markets.",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-2",
    topic: "macro-fundamentals",
    subtopic: "The four macro objectives",
    difficulty: 1,
    type: "concept",
    question: "Which of these is NOT typically listed as one of the major macroeconomic objectives?",
    options: ["Economic growth", "Low unemployment", "Stable prices (low inflation)", "Maximising a single firm's profit"],
    correctIndex: 3,
    explanation: "The major macro objectives are economic growth, high employment, stable prices, and a healthy balance of payments/stable exchange rate — a single firm's profit is a microeconomic concern.",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-3",
    topic: "macro-fundamentals",
    subtopic: "Economic growth",
    difficulty: 1,
    type: "concept",
    question: "The rate of economic growth is best defined as...",
    options: [
      "The percentage increase in national output over a 12-month period",
      "The total value of a country's exports",
      "The change in the unemployment rate",
      "The change in the exchange rate",
    ],
    correctIndex: 0,
    explanation: "Economic growth is measured as the percentage increase in national output (real GDP) over a year.",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-4",
    topic: "macro-fundamentals",
    subtopic: "Inflation definition",
    difficulty: 2,
    type: "concept",
    question: "The rate of inflation measures...",
    options: [
      "The percentage increase in prices over a 12-month period",
      "The total number of goods produced in a year",
      "The percentage of people unemployed",
      "The value of a country's currency in gold",
    ],
    correctIndex: 0,
    explanation: "Inflation is a persistent increase in the general price level; the rate of inflation is its percentage increase over 12 months.",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-5",
    topic: "macro-fundamentals",
    subtopic: "Who counts as unemployed",
    difficulty: 2,
    type: "concept",
    question: "Which of these people would NOT normally be counted as officially unemployed?",
    options: [
      "A person actively seeking work but currently without a job",
      "A discouraged worker who has given up looking for a job in frustration",
      "A person laid off and available to start work immediately",
      "A person waiting to take up a job offer they've already accepted",
    ],
    correctIndex: 1,
    explanation: "Unemployment is defined as being of working age, without work, but available for and actively seeking work. Discouraged workers who've stopped searching fall outside this definition.",
    misconception: "Assuming everyone without a job is automatically counted as 'unemployed' in official statistics.",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-6",
    topic: "macro-fundamentals",
    subtopic: "Exchange rate definition",
    difficulty: 1,
    type: "concept",
    question: "An exchange rate is best described as...",
    options: [
      "The rate at which one national currency exchanges for another",
      "The interest rate set by a central bank",
      "The rate of company tax",
      "The rate of inflation in a foreign country",
    ],
    correctIndex: 0,
    explanation: "e.g. Gh¢14 = $1 — the exchange rate is simply the price of one currency in terms of another.",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-7",
    topic: "macro-fundamentals",
    subtopic: "Balance of payments definition",
    difficulty: 2,
    type: "concept",
    question: "The balance of payments account is a record of...",
    options: [
      "A government's domestic tax revenue and spending",
      "A country's transactions with the rest of the world (payments/receipts)",
      "A single firm's import bill only",
      "The exchange rate over the last 10 years",
    ],
    correctIndex: 1,
    explanation: "It records payments to/deposits in other countries (debits) and receipts/deposits from other countries (credits).",
    relatedPartId: "e-part-0",
  },
  {
    id: "econs-8",
    topic: "macro-fundamentals",
    subtopic: "Trade-offs between objectives",
    difficulty: 3,
    type: "best-practice",
    question: "Why can't a government simply maximise growth, employment, low inflation, and a strong balance of payments all at the same time?",
    options: [
      "It's actually always possible; policymakers just choose not to",
      "Because pushing hard on one objective (e.g. faster growth) often worsens another (e.g. the balance of payments) — this is an opportunity cost / trade-off",
      "Because only one objective is ever measured at a time",
      "Because the objectives are unrelated to each other",
    ],
    correctIndex: 1,
    explanation: "Faster growth can worsen the balance of payments; lower unemployment can conflict with lower inflation. These genuine trade-offs mean policymakers must prioritise.",
    relatedPartId: "e-part-0",
  },

  // ---------- Circular Flow of Income (8) ----------
  {
    id: "econs-9",
    topic: "circular-flow",
    subtopic: "Aggregate demand identity",
    difficulty: 1,
    type: "concept",
    question: "In the identity AD = C + I + G + X − M, what does the G represent?",
    options: ["Gross profit", "Government expenditure", "GDP growth rate", "Gold reserves"],
    correctIndex: 1,
    explanation: "G is government expenditure on goods and services — one of the four components of aggregate demand.",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-10",
    topic: "circular-flow",
    subtopic: "Withdrawals",
    difficulty: 2,
    type: "concept",
    question: "Which three items make up the 'withdrawals' (leakages) from the circular flow of income?",
    options: [
      "Investment, government spending, exports",
      "Savings, net taxes, import expenditure",
      "Consumption, wages, profit",
      "Exports, imports, exchange rate",
    ],
    correctIndex: 1,
    explanation: "Withdrawals are the three ways money leaks out of the inner household-firm spending flow: savings (S), net taxes (T), and import expenditure (M).",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-11",
    topic: "circular-flow",
    subtopic: "Injections",
    difficulty: 2,
    type: "concept",
    question: "Which three items make up the 'injections' into the circular flow of income?",
    options: [
      "Savings, taxes, imports",
      "Investment, government expenditure, export expenditure",
      "Consumption, wages, dividends",
      "GDP, GNP, NNP",
    ],
    correctIndex: 1,
    explanation: "Injections are additional demand entering from outside the inner flow: investment (I), government expenditure (G), and export expenditure (X).",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-12",
    topic: "circular-flow",
    subtopic: "Equilibrium condition",
    difficulty: 2,
    type: "concept",
    question: "The circular flow of income is in equilibrium when...",
    options: ["Consumption equals savings", "Planned injections equal planned withdrawals", "Exports equal imports exactly every year", "GDP equals GNP"],
    correctIndex: 1,
    explanation: "Equilibrium occurs when J = W. If they're unequal, national income will keep adjusting until they match.",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-13",
    topic: "circular-flow",
    subtopic: "Effect of J exceeding W",
    difficulty: 3,
    type: "concept",
    question: "If injections exceed withdrawals in the circular flow, what tends to happen to the four macro objectives?",
    options: [
      "Unemployment falls, inflation tends to rise, the balance of payments tends to worsen, and there is economic growth",
      "Unemployment rises, inflation falls, and the economy shrinks",
      "Nothing changes because injections and withdrawals always offset automatically",
      "Only the exchange rate is affected",
    ],
    correctIndex: 0,
    explanation: "Rising aggregate demand (J > W) generally reduces unemployment, pushes inflation up, worsens the trade balance (more imports as incomes rise), and drives short-term growth.",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-14",
    topic: "circular-flow",
    subtopic: "Classifying flows",
    difficulty: 2,
    type: "concept",
    question: "Which of the following is classified as an injection, not a withdrawal?",
    options: ["Household savings", "Income tax payments", "Government expenditure on public services", "Spending on imported goods"],
    correctIndex: 2,
    explanation: "Government expenditure is an injection. Savings, taxes, and import spending are all withdrawals.",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-15",
    topic: "circular-flow",
    subtopic: "Links between injections and withdrawals",
    difficulty: 3,
    type: "concept",
    question: "How are savings and investment indirectly linked in the circular flow?",
    options: [
      "They are completely unrelated",
      "Higher savings put more funds into financial institutions, which can then be lent out as investment",
      "Investment always equals savings exactly by law",
      "Savings directly become government expenditure",
    ],
    correctIndex: 1,
    explanation: "If more money is saved, more becomes available for banks and other financial institutions to lend out for investment — an indirect link via the financial system.",
    relatedPartId: "e-part-1",
  },
  {
    id: "econs-16",
    topic: "circular-flow",
    subtopic: "Import-export feedback",
    difficulty: 3,
    type: "concept",
    question: "If a country's imports (M) increase, what indirect effect can this have on its exports (X)?",
    options: [
      "None — imports and exports are always unrelated",
      "It can raise the incomes of people abroad, enabling them to buy more of the country's exports",
      "It always automatically reduces exports",
      "It only affects the exchange rate, never exports",
    ],
    correctIndex: 1,
    explanation: "When imports rise, incomes abroad rise correspondingly (foreign firms/workers are paid), which can enable them to purchase more of the domestic country's exports in turn.",
    relatedPartId: "e-part-1",
  },

  // ---------- Measuring National Income (14) ----------
  {
    id: "econs-17",
    topic: "national-income",
    subtopic: "The three GDP methods",
    difficulty: 1,
    type: "concept",
    question: "Which three approaches are used to measure GDP?",
    options: [
      "The product (output) method, the income method, the expenditure method",
      "The tax method, the tariff method, the subsidy method",
      "The import method, the export method, the balance method",
      "The fixed method, the floating method, the managed method",
    ],
    correctIndex: 0,
    explanation: "GDP can be measured by adding up output produced, incomes earned, or total expenditure — all three should, in principle, give the same total.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-18",
    topic: "national-income",
    subtopic: "Output method",
    difficulty: 2,
    type: "concept",
    question: "The product (output) method of measuring GDP works by...",
    options: [
      "Adding up the market value of final goods and services produced by all firms in a given period",
      "Adding up all household savings",
      "Adding up government tax revenue only",
      "Subtracting imports from exports",
    ],
    correctIndex: 0,
    explanation: "The output method sums the market value of total output across all sectors (agriculture, mining, manufacturing, services, etc.) in a year.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-19",
    topic: "national-income",
    subtopic: "Income method factors of production",
    difficulty: 2,
    type: "concept",
    question: "The income method arrives at national income by summing rewards paid to which four factors of production?",
    options: [
      "Labour, land, capital, entrepreneurship",
      "Consumption, investment, government, net exports",
      "Wages, taxes, subsidies, tariffs",
      "Imports, exports, savings, spending",
    ],
    correctIndex: 0,
    explanation: "Wages go to labour, rent to land, interest to capital, and profit to entrepreneurship — summing these gives national income by the income method.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-20",
    topic: "national-income",
    subtopic: "Expenditure method formula",
    difficulty: 2,
    type: "concept",
    question: "The expenditure method formula for aggregate expenditure (AE) is...",
    options: ["AE = C + I + G + (X − M)", "AE = C − I − G", "AE = GDP ÷ population", "AE = S + T + M"],
    correctIndex: 0,
    explanation: "Aggregate expenditure sums consumption, investment, government spending, and net exports (exports minus imports).",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-21",
    topic: "national-income",
    subtopic: "GDP to GNP",
    difficulty: 3,
    type: "concept",
    question: "To convert GDP at market prices into GNP at market prices, you must...",
    options: [
      "Add net factor income from abroad",
      "Subtract depreciation",
      "Subtract indirect taxes",
      "Add government subsidies only",
    ],
    correctIndex: 0,
    explanation: "GNP at market prices = GDP at market prices + net factor income from abroad (income earned by citizens abroad minus income earned by foreigners domestically).",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-22",
    topic: "national-income",
    subtopic: "GNP market price to factor cost",
    difficulty: 3,
    type: "concept",
    question: "To convert GNP at market prices into GNP at factor cost, you...",
    options: [
      "Subtract indirect taxes and add subsidies",
      "Add indirect taxes and subtract subsidies",
      "Subtract depreciation only",
      "Add net factor income from abroad",
    ],
    correctIndex: 0,
    explanation: "GNP at factor cost = GNP at market prices − indirect taxes + subsidies, since market prices include tax effects that don't reflect the true cost of factors of production.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-23",
    topic: "national-income",
    subtopic: "GNP factor cost to NNP",
    difficulty: 2,
    type: "concept",
    question: "Net National Product (NNP) at factor cost is calculated as...",
    options: [
      "GNP at factor cost minus depreciation",
      "GNP at factor cost plus depreciation",
      "GDP at market prices minus subsidies",
      "GDP divided by total population",
    ],
    correctIndex: 0,
    explanation: "NNP at factor cost = GNP at factor cost − depreciation, accounting for wear and tear on capital used in production.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-24",
    topic: "national-income",
    subtopic: "Problems with the output method",
    difficulty: 3,
    type: "concept",
    question: "Which of these is a well-known problem with the product (output) method of measuring GDP?",
    options: [
      "Double or multiple counting of the same output at different production stages",
      "It's impossible to add up outputs across different sectors",
      "It only works for agricultural economies",
      "It always undercounts government services",
    ],
    correctIndex: 0,
    explanation: "Without care, the value of intermediate goods can get counted more than once as they pass through multiple stages of production — hence the need to count only final output (or value added at each stage).",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-25",
    topic: "national-income",
    subtopic: "Problems with the expenditure method",
    difficulty: 3,
    type: "best-practice",
    question: "Why is the expenditure approach to measuring national income especially difficult in a developing country like Ghana?",
    options: [
      "There are no firms to survey",
      "High illiteracy rates make record-keeping on expenditure difficult, and small-scale earners may under-report spending to avoid taxes",
      "Expenditure is always exactly equal to output, so there's nothing to measure",
      "Government spending cannot be measured at all",
    ],
    correctIndex: 1,
    explanation: "Poor record-keeping, fear of taxation among small earners, and significant subsistence production all make the expenditure method harder to apply accurately in developing economies.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-26",
    topic: "national-income",
    subtopic: "Nominal vs real GDP",
    difficulty: 2,
    type: "concept",
    question: "The key difference between nominal GDP and real GDP is that real GDP...",
    options: [
      "Is always larger than nominal GDP",
      "Is measured using constant base-year prices, removing the effect of pure price changes",
      "Only counts exports",
      "Is measured in a foreign currency",
    ],
    correctIndex: 1,
    explanation: "Real GDP uses fixed base-year prices, so changes in real GDP reflect changes in actual quantity produced, not just inflation.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-27",
    topic: "national-income",
    subtopic: "Nominal GDP worked example",
    difficulty: 3,
    type: "code-analysis",
    code: "Year 2002: Price of good A = $1, Quantity = 10; Price of good B = $10, Quantity = 3\nYear 2003: Price of good A = $2, Quantity = 15; Price of good B = $15, Quantity = 4",
    question: "What is nominal GDP in 2003, using each year's own prices and quantities?",
    options: ["$40", "$55", "$90", "$100"],
    correctIndex: 2,
    explanation: "Nominal GDP 2003 = ($2 × 15) + ($15 × 4) = $30 + $60 = $90.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-28",
    topic: "national-income",
    subtopic: "Real GDP worked example",
    difficulty: 4,
    type: "code-analysis",
    code: "Year 2002 (base year): Price of good A = $1, Price of good B = $10\nYear 2003 quantities: Good A = 15, Good B = 4",
    question: "Using 2002 as the base year, what is real GDP in 2003?",
    options: ["$40", "$55", "$90", "$120"],
    correctIndex: 1,
    explanation: "Real GDP 2003 = 2003 quantities × 2002 (base year) prices = ($1 × 15) + ($10 × 4) = $15 + $40 = $55 — much less than the $90 nominal figure, showing most of the nominal rise was just price increases.",
    misconception: "Using the current year's prices instead of the base year's prices when computing real GDP.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-29",
    topic: "national-income",
    subtopic: "Purchasing power parity",
    difficulty: 3,
    type: "concept",
    question: "Why might GDP figures need to be converted using a purchasing power parity (PPP) exchange rate?",
    options: [
      "PPP makes GDP figures larger for marketing purposes",
      "A simple market exchange rate may not reflect how much of the same goods $1 can actually buy in each country",
      "PPP is required by international law",
      "It has nothing to do with comparing living standards across countries",
    ],
    correctIndex: 1,
    explanation: "$1 might exchange for Gh¢8, but $1 in the US may not buy the same amount of goods as Gh¢8 does in Ghana — PPP adjusts for this so cross-country comparisons are meaningful.",
    relatedPartId: "e-part-2",
  },
  {
    id: "econs-30",
    topic: "national-income",
    subtopic: "GDP as a welfare measure",
    difficulty: 3,
    type: "best-practice",
    question: "Which of these is a genuine limitation of using GDP per capita as a measure of living standards?",
    options: [
      "It perfectly captures every aspect of well-being",
      "It excludes non-marketed activities and the underground economy, and ignores the distribution of income and externalities",
      "It is always calculated incorrectly by statistical agencies",
      "It cannot be calculated for any country",
    ],
    correctIndex: 1,
    explanation: "GDP misses non-marketed work (e.g. subsistence farming, unpaid housework), underground economic activity, pollution/externalities, and says nothing about how income is distributed across the population.",
    relatedPartId: "e-part-2",
  },

  // ---------- Business Cycle & Growth (10) ----------
  {
    id: "econs-31",
    topic: "business-cycle-growth",
    subtopic: "Actual vs potential growth",
    difficulty: 2,
    type: "concept",
    question: "Potential economic growth refers to...",
    options: [
      "The actual percentage increase in national output this year",
      "The percentage annual increase in the economy's capacity to produce",
      "The growth rate of the stock market",
      "The growth in government spending only",
    ],
    correctIndex: 1,
    explanation: "Potential growth is about the economy's underlying productive capacity growing, driven by things like new resources and technology — distinct from actual output, which can be above or below this trend.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-32",
    topic: "business-cycle-growth",
    subtopic: "Business cycle definition",
    difficulty: 1,
    type: "concept",
    question: "The business cycle is best defined as...",
    options: [
      "A one-time, permanent shift in an economy's output",
      "The periodic fluctuation of national output around its long-term trend",
      "The cycle of exchange rate movements only",
      "A fixed 10-year pattern that never varies",
    ],
    correctIndex: 1,
    explanation: "The business cycle describes alternating periods of economic growth and contraction — a repeating wobble of actual output around the long-term potential output trend.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-33",
    topic: "business-cycle-growth",
    subtopic: "Phases of the business cycle",
    difficulty: 2,
    type: "concept",
    question: "What is the correct order of the four phases of the business cycle?",
    options: [
      "Peak → Expansion → Upturn → Recession",
      "Upturn → Expansion → Peak → Slowdown/Recession",
      "Recession → Peak → Upturn → Expansion",
      "Expansion → Recession → Upturn → Peak",
    ],
    correctIndex: 1,
    explanation: "The classic order is: upturn (recovery begins), expansion (rapid growth), peak (growth slows/ceases), then slowdown or recession (little/no growth or decline).",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-34",
    topic: "business-cycle-growth",
    subtopic: "Boom vs recession",
    difficulty: 2,
    type: "concept",
    question: "An economy is said to be in a 'boom' or 'expansion' when...",
    options: [
      "Actual GDP is below trend for a number of years",
      "Actual GDP is above trend for a number of years in a row",
      "Unemployment is at its highest level ever recorded",
      "The exchange rate is fixed",
    ],
    correctIndex: 1,
    explanation: "A boom/expansion is when actual GDP runs above the long-term trend for a sustained period; a recession is the opposite — actual GDP below trend.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-35",
    topic: "business-cycle-growth",
    subtopic: "Causes of long-term growth",
    difficulty: 2,
    type: "concept",
    question: "For growth to be sustained over the long term, which of the following must increase?",
    options: [
      "Only government spending",
      "The quantity of factors of production (labour, land, capital) and/or their productivity",
      "Only the exchange rate",
      "Only the price level",
    ],
    correctIndex: 1,
    explanation: "Long-term growth requires either more factors of production or those factors becoming more productive — the country's actual capacity to produce must increase.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-36",
    topic: "business-cycle-growth",
    subtopic: "Demand-side vs supply-side growth policies",
    difficulty: 3,
    type: "best-practice",
    question: "Supply-side policies aimed at achieving growth work primarily by...",
    options: [
      "Increasing aggregate demand through tax cuts",
      "Increasing the economy's potential output — e.g. via subsidies, R&D incentives, and training",
      "Fixing the exchange rate permanently",
      "Reducing the money supply",
    ],
    correctIndex: 1,
    explanation: "Supply-side policies target potential output directly — increasing the supply of factor inputs and productivity — unlike demand-side (fiscal/monetary) policies which boost aggregate demand.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-37",
    topic: "business-cycle-growth",
    subtopic: "Benefits of growth",
    difficulty: 2,
    type: "concept",
    question: "Which of these is a genuine benefit of economic growth?",
    options: [
      "It automatically eliminates all pollution",
      "Increased consumption and an easier ability to redistribute income to the poor",
      "It guarantees zero inflation",
      "It always reduces the population",
    ],
    correctIndex: 1,
    explanation: "Growth generally increases what people can consume, and can make redistributing income to the poor politically and practically easier since the total 'pie' is bigger.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-38",
    topic: "business-cycle-growth",
    subtopic: "Costs of growth",
    difficulty: 3,
    type: "concept",
    question: "Which of these is a recognised cost of pursuing rapid economic growth?",
    options: [
      "It always instantly raises everyone's happiness with no downsides",
      "The current opportunity cost of higher savings for investment (a cut in current consumption), plus environmental costs like pollution and resource depletion",
      "It has no relationship to consumption at all",
      "It automatically fixes the balance of payments",
    ],
    correctIndex: 1,
    explanation: "Growth has real costs: sacrificing current consumption to save/invest more, plus environmental costs from pollution, waste, and depleting resources, and potentially adverse social effects.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-39",
    topic: "business-cycle-growth",
    subtopic: "Production possibility curve",
    difficulty: 3,
    type: "concept",
    question: "On a production possibility curve (PPC), long-term economic growth is represented by...",
    options: [
      "Moving to a point inside the existing curve",
      "The whole curve shifting outward",
      "The curve becoming a straight vertical line",
      "The curve shifting inward",
    ],
    correctIndex: 1,
    explanation: "Growth increases the economy's overall production capacity, shifting the entire production possibility curve outward — more of both goods can now potentially be produced.",
    relatedPartId: "e-part-3",
  },
  {
    id: "econs-40",
    topic: "business-cycle-growth",
    subtopic: "Actual growth stimulating potential growth",
    difficulty: 3,
    type: "concept",
    question: "How can a period of strong actual growth help increase potential growth too?",
    options: [
      "It has no effect on potential growth at all",
      "It stimulates investment and the development of new technology, expanding future capacity",
      "It automatically reduces the labour force",
      "It always causes potential output to shrink",
    ],
    correctIndex: 1,
    explanation: "A boom encourages firms to invest and innovate (since demand is strong), and that investment/technology expands the economy's future productive capacity — actual growth feeding into potential growth.",
    relatedPartId: "e-part-3",
  },

  // ---------- Unemployment (16) ----------
  {
    id: "econs-41",
    topic: "unemployment",
    subtopic: "ILO definition",
    difficulty: 2,
    type: "concept",
    question: "Under the ILO/OECD measure, who counts as unemployed?",
    options: [
      "Anyone not currently working, including retirees and students",
      "People of working age, without work, available to start within two weeks, and actively seeking employment",
      "Only people receiving unemployment benefits",
      "Anyone who has never had a job",
    ],
    correctIndex: 1,
    explanation: "The ILO/OECD measure requires availability to start within two weeks AND active job search (or waiting to take up an appointment).",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-42",
    topic: "unemployment",
    subtopic: "Underemployment",
    difficulty: 2,
    type: "concept",
    question: "Underemployment describes people who...",
    options: [
      "Are seeking full-time work but can only get part-time work or work below their capacity",
      "Have no interest in working at all",
      "Are working overtime willingly",
      "Have already retired",
    ],
    correctIndex: 0,
    explanation: "Underemployed workers want full-time paid work but the job market structure only permits part-time work, or they work below their skill/capacity level.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-43",
    topic: "unemployment",
    subtopic: "Claimant unemployment",
    difficulty: 2,
    type: "concept",
    question: "'Claimant unemployment' is a measure of...",
    options: [
      "Everyone actively looking for work, employed or not",
      "Those in receipt of unemployment-related benefits",
      "Only university graduates without jobs",
      "People employed part-time",
    ],
    correctIndex: 1,
    explanation: "Claimant unemployment simply counts people currently claiming unemployment-related benefits — a narrower, administrative measure than the ILO definition.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-44",
    topic: "unemployment",
    subtopic: "Duration of unemployment formula",
    difficulty: 3,
    type: "code-analysis",
    code: "Stock of unemployed (U) = 400\nOutflow from unemployment per period (F) = 50",
    question: "Using DU = U / F, what is the average duration of unemployment here?",
    options: ["4 periods", "8 periods", "50 periods", "450 periods"],
    correctIndex: 1,
    explanation: "DU = U / F = 400 / 50 = 8 periods.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-45",
    topic: "unemployment",
    subtopic: "Determinants of duration",
    difficulty: 3,
    type: "concept",
    question: "Which factor affects the average duration of unemployment, according to the standard model?",
    options: [
      "The colour of the national currency",
      "The rate of inflow to and outflow from the stock of unemployment, and the phase of the business cycle",
      "Only the exchange rate",
      "Only the level of government debt",
    ],
    correctIndex: 1,
    explanation: "Duration depends on the balance of inflows/outflows from unemployment, and tends to lengthen the longer a recession lasts.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-46",
    topic: "unemployment",
    subtopic: "Costs of unemployment",
    difficulty: 2,
    type: "concept",
    question: "Which of these is a recognised cost/effect of unemployment?",
    options: [
      "Guaranteed higher tax revenue",
      "Loss of self-esteem, loss of national output, and loss of tax revenue",
      "Automatic reduction in inflation to zero",
      "It has no effect on society at all",
    ],
    correctIndex: 1,
    explanation: "Unemployment carries real costs: psychological (loss of self-esteem), economic (lost output, lost tax revenue), and social (e.g. social problems, brain drain).",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-47",
    topic: "unemployment",
    subtopic: "Aggregate supply of labour",
    difficulty: 2,
    type: "concept",
    question: "The aggregate supply of labour curve shows...",
    options: [
      "The total demand for labour at each wage rate",
      "The number of workers willing to accept jobs at each wage rate",
      "The total output of the economy",
      "The exchange rate at each wage rate",
    ],
    correctIndex: 1,
    explanation: "The ASL curve plots how many workers are willing to work at each real wage rate — typically upward sloping (higher wages attract more willing workers).",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-48",
    topic: "unemployment",
    subtopic: "Aggregate demand for labour",
    difficulty: 2,
    type: "concept",
    question: "The aggregate demand for labour curve shows...",
    options: [
      "The number of workers seeking jobs",
      "The total demand for labour by firms at different average real wage rates",
      "The total government budget",
      "The unemployment rate directly",
    ],
    correctIndex: 1,
    explanation: "ADL shows how many workers firms want to hire at each real wage — typically downward sloping (higher wages mean firms hire fewer workers).",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-49",
    topic: "unemployment",
    subtopic: "Labour market equilibrium",
    difficulty: 2,
    type: "concept",
    question: "In the labour market model, equilibrium occurs where...",
    options: ["ASL = 0", "ADL = ASL", "ADL = 0", "The wage rate is zero"],
    correctIndex: 1,
    explanation: "Equilibrium in the labour market model, like any market, is where aggregate demand for labour equals aggregate supply of labour.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-50",
    topic: "unemployment",
    subtopic: "Disequilibrium unemployment conditions",
    difficulty: 3,
    type: "concept",
    question: "Disequilibrium unemployment requires two conditions to hold. What are they?",
    options: [
      "Aggregate supply of labour must exceed aggregate demand, AND wages must be 'sticky' (not falling to the market-clearing level)",
      "The exchange rate must be fixed and inflation must be zero",
      "GDP must be falling and exports must be rising",
      "Only that unemployment benefits exist",
    ],
    correctIndex: 0,
    explanation: "Disequilibrium unemployment needs an excess of labour supply over demand AND wage stickiness that prevents the wage falling to clear that excess.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-51",
    topic: "unemployment",
    subtopic: "Real-wage (classical) unemployment",
    difficulty: 2,
    type: "concept",
    question: "Real-wage (classical) unemployment is caused by...",
    options: [
      "A fall in aggregate demand for goods and services",
      "Trade unions or a minimum wage pushing wages above the market-clearing level",
      "Workers moving between jobs",
      "Seasonal changes in demand for labour",
    ],
    correctIndex: 1,
    explanation: "Real-wage unemployment occurs when wages are pushed (by unions or minimum wage law) above the level that would clear the labour market.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-52",
    topic: "unemployment",
    subtopic: "Demand-deficient (cyclical) unemployment",
    difficulty: 2,
    type: "concept",
    question: "Demand-deficient (cyclical) unemployment is caused by...",
    options: [
      "A fall in aggregate demand with no corresponding fall in the real wage rate",
      "Workers voluntarily leaving their jobs",
      "A rise in the minimum wage only",
      "Seasonal weather patterns",
    ],
    correctIndex: 0,
    explanation: "When aggregate demand falls (e.g. in a recession) but wages don't adjust down, firms demand fewer workers at the unchanged wage — hence 'cyclical' unemployment tied to the business cycle.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-53",
    topic: "unemployment",
    subtopic: "Frictional unemployment",
    difficulty: 2,
    type: "concept",
    question: "Frictional (search) unemployment exists because...",
    options: [
      "There are genuinely no vacancies anywhere in the economy",
      "Imperfect information means it takes time for workers to find jobs, even when vacancies exist",
      "Wages are too high across the whole economy",
      "The exchange rate has depreciated",
    ],
    correctIndex: 1,
    explanation: "Frictional unemployment is about the TIME it takes to match available workers with available vacancies, due to imperfect information — it exists even in an otherwise 'cleared' labour market.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-54",
    topic: "unemployment",
    subtopic: "Structural unemployment",
    difficulty: 2,
    type: "concept",
    question: "Structural unemployment arises from...",
    options: [
      "Changes in the pattern of demand or supply in the economy, combined with occupational/geographical immobility of labour",
      "A temporary lull between jobs of only a few days",
      "Workers demanding lower wages than employers offer",
      "The government fixing the exchange rate",
    ],
    correctIndex: 0,
    explanation: "Structural unemployment happens when whole sectors decline (e.g. due to changing demand or new technology) and displaced workers can't easily move to growing sectors due to skills or location mismatches.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-55",
    topic: "unemployment",
    subtopic: "Seasonal unemployment",
    difficulty: 1,
    type: "concept",
    question: "Seasonal unemployment is best illustrated by which example?",
    options: ["A software engineer laid off during a recession", "A farm labourer only needed during harvest season", "A worker on strike", "A worker who quit for a better job"],
    correctIndex: 1,
    explanation: "Seasonal unemployment occurs when demand for certain labour (like agricultural work) fluctuates predictably with the seasons of the year.",
    relatedPartId: "e-part-4",
  },
  {
    id: "econs-56",
    topic: "unemployment",
    subtopic: "Cures for unemployment",
    difficulty: 3,
    type: "best-practice",
    question: "Demand-side policies to reduce unemployment work primarily by...",
    options: [
      "Increasing the economy's potential output directly",
      "Using fiscal and monetary policy to increase aggregate demand, and hence the equilibrium level of national income",
      "Reducing the minimum wage to zero",
      "Fixing the exchange rate permanently",
    ],
    correctIndex: 1,
    explanation: "Demand-side (fiscal/monetary) policies aim to boost aggregate demand and thereby raise the equilibrium level of national income and employment — as opposed to supply-side policies, which target potential output.",
    relatedPartId: "e-part-4",
  },

  // ---------- Inflation (18) ----------
  {
    id: "econs-57",
    topic: "inflation",
    subtopic: "Inflation definition",
    difficulty: 1,
    type: "concept",
    question: "Inflation is best defined as...",
    options: [
      "A one-time increase in a single product's price",
      "A persistent and appreciable increase in the general price level of goods and services",
      "A decrease in the exchange rate only",
      "An increase in the unemployment rate",
    ],
    correctIndex: 1,
    explanation: "Inflation refers to a continuing, persistent tendency for the overall price level to rise, not a one-off price change in a single good.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-58",
    topic: "inflation",
    subtopic: "Deflation",
    difficulty: 1,
    type: "concept",
    question: "Deflation is the opposite of inflation, meaning...",
    options: [
      "A persistent tendency for the general price level to fall",
      "A rise in unemployment only",
      "A rise in the exchange rate",
      "An increase in government debt",
    ],
    correctIndex: 0,
    explanation: "Deflation is a persistent fall in the general price level, the mirror image of inflation.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-59",
    topic: "inflation",
    subtopic: "CPI definition",
    difficulty: 2,
    type: "concept",
    question: "The Consumer Price Index (CPI) measures...",
    options: [
      "The cost of a fixed basket of goods/services relative to the cost of the same basket in a base year",
      "Total government spending",
      "The total number of consumers in a country",
      "The exchange rate against the US dollar",
    ],
    correctIndex: 0,
    explanation: "CPI tracks the cost of buying the SAME fixed basket of goods over time, relative to its cost in a chosen base year.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-60",
    topic: "inflation",
    subtopic: "CPI formula",
    difficulty: 2,
    type: "concept",
    question: "The CPI for a given period is calculated as...",
    options: [
      "(Current cost of the basket ÷ cost of the same basket in the base year) × 100",
      "Current cost of the basket minus base year cost",
      "Base year cost divided by current cost",
      "Current cost of the basket times population",
    ],
    correctIndex: 0,
    explanation: "CPI = (current basket cost ÷ base year basket cost) × 100 — this yields exactly 100 in the base year itself.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-61",
    topic: "inflation",
    subtopic: "GDP deflator",
    difficulty: 2,
    type: "concept",
    question: "The GDP deflator is used to...",
    options: [
      "Convert nominal GDP into real GDP by adjusting for price changes",
      "Measure only import prices",
      "Set the country's exchange rate",
      "Count the total number of firms in an economy",
    ],
    correctIndex: 0,
    explanation: "The GDP deflator is a broader price index (covering all domestically produced goods, not just a consumer basket) used to separate real output changes from pure price changes.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-62",
    topic: "inflation",
    subtopic: "Creeping inflation",
    difficulty: 2,
    type: "concept",
    question: "'Creeping inflation' describes a situation where...",
    options: [
      "Prices are perfectly stable every year",
      "The inflation rate is fairly stable year to year, averaging less than about 5%",
      "Inflation exceeds several thousand percent per day",
      "Prices are falling persistently",
    ],
    correctIndex: 1,
    explanation: "Creeping inflation is mild and gradual — prices creep upward slowly and predictably, typically under 5% per year.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-63",
    topic: "inflation",
    subtopic: "Strato-inflation",
    difficulty: 2,
    type: "concept",
    question: "Strato-inflation refers to an inflation rate that ranges roughly from...",
    options: ["0% to 2%", "About 10% to several hundred percent, without becoming full hyperinflation", "Exactly 5% every year", "Negative territory (deflation)"],
    correctIndex: 1,
    explanation: "Strato-inflation sits between creeping inflation and full hyperinflation — high and damaging, but not yet spiralling into thousands of percent.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-64",
    topic: "inflation",
    subtopic: "Hyperinflation",
    difficulty: 2,
    type: "concept",
    question: "Hyperinflation (galloping inflation) is characterised by...",
    options: [
      "A stable rate under 5% per year",
      "Inflation accelerating from several hundred to many thousands of percent, as historically seen in Zimbabwe",
      "Prices falling every day",
      "An inflation rate of exactly 10%",
    ],
    correctIndex: 1,
    explanation: "Hyperinflation is extreme and rapidly accelerating — the classic example given is Zimbabwe, where inflation reached many thousands of percent.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-65",
    topic: "inflation",
    subtopic: "Bottleneck inflation",
    difficulty: 3,
    type: "concept",
    question: "Bottleneck inflation occurs when...",
    options: [
      "Aggregate demand falls drastically while supply stays constant",
      "Aggregate supply falls drastically while aggregate demand stays at the same level",
      "Both AD and AS rise by the same amount",
      "The exchange rate is fixed",
    ],
    correctIndex: 1,
    explanation: "Bottleneck inflation is driven by supply constraints (immobility or mismanagement of resources) rather than a rise in aggregate demand.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-66",
    topic: "inflation",
    subtopic: "Suppressed inflation",
    difficulty: 3,
    type: "concept",
    question: "Suppressed inflation refers to a situation where...",
    options: [
      "Price and wage controls are used to restrain the price level from rising, without eliminating the underlying inflationary pressure",
      "Inflation is completely eliminated by government policy",
      "Prices are allowed to rise freely with no controls",
      "Inflation only happens in the informal sector",
    ],
    correctIndex: 0,
    explanation: "Suppressed inflation masks (rather than removes) inflationary pressure through direct controls — the underlying pressure can resurface once controls are lifted.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-67",
    topic: "inflation",
    subtopic: "Costs of inflation",
    difficulty: 3,
    type: "concept",
    question: "'Shoe leather cost' and 'menu cost' both refer to...",
    options: [
      "Costs of unemployment benefits",
      "Real costs businesses and individuals incur adapting to inflation (e.g. constantly updating prices, more frequent trips to the bank)",
      "The cost of producing shoes specifically",
      "Costs related only to the balance of payments",
    ],
    correctIndex: 1,
    explanation: "'Menu costs' are the costs of frequently re-pricing goods; 'shoe leather costs' are the costs (like extra trips to the bank) of holding less cash to avoid losing value to inflation.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-68",
    topic: "inflation",
    subtopic: "Demand-pull causes",
    difficulty: 2,
    type: "concept",
    question: "Which of these is a recognised cause of demand-pull inflation?",
    options: [
      "A rise in wages/salaries without a corresponding rise in output",
      "A fall in aggregate demand",
      "A fall in exports",
      "Exhaustion of natural resources",
    ],
    correctIndex: 0,
    explanation: "Wage rises outpacing output (along with things like war, rising exports, or rapid industrialisation) push aggregate demand up, causing demand-pull inflation.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-69",
    topic: "inflation",
    subtopic: "Cost-push causes",
    difficulty: 2,
    type: "concept",
    question: "Which of these is a recognised cause of cost-push inflation?",
    options: ["A rise in aggregate demand from tax cuts", "Import-price-push, wage-push, and tax-push increases in production costs", "A fall in wages", "Falling import prices"],
    correctIndex: 1,
    explanation: "Cost-push inflation is driven by rising costs of production — from wages, import prices, taxes, or resource exhaustion — that shift the aggregate supply curve left/upward.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-70",
    topic: "inflation",
    subtopic: "Demand-pull and cost-push interaction",
    difficulty: 4,
    type: "concept",
    question: "If powerful groups keep pushing production costs up while the government keeps boosting aggregate demand to protect employment, the likely net effect is...",
    options: [
      "Large increases in output and employment with stable prices",
      "Prices rising substantially while the net effect on output/employment stays small",
      "Deflation",
      "No effect on prices at all",
    ],
    correctIndex: 1,
    explanation: "When cost-push pressure and demand-pull policy offset each other's effects on output, the main visible outcome tends to be substantial price rises rather than output/employment gains.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-71",
    topic: "inflation",
    subtopic: "Real GDP controls for inflation",
    difficulty: 2,
    type: "concept",
    question: "Why can changes in real GDP only be due to changes in quantity, not price?",
    options: [
      "Because real GDP is constructed using constant base-year prices",
      "Because real GDP always equals nominal GDP",
      "Because real GDP ignores quantities entirely",
      "Because prices never change in an economy",
    ],
    correctIndex: 0,
    explanation: "By fixing prices at base-year levels, any change in real GDP must come from a change in the quantities actually produced — inflation's effect is deliberately stripped out.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-72",
    topic: "inflation",
    subtopic: "CPI worked example",
    difficulty: 3,
    type: "code-analysis",
    code: "Basket: 20 bags of cocoa + 10 bags of rice\n2009 (base year): Cocoa Gh¢10/bag, Rice Gh¢15/bag\n2010: Cocoa Gh¢11/bag, Rice Gh¢15/bag",
    question: "Using 2009 as the base year, what is the CPI for 2010?",
    options: ["100.0", "105.7", "110.0", "150.0"],
    correctIndex: 1,
    explanation: "2009 basket cost = (20×10)+(10×15) = 200+150 = 350. 2010 basket cost = (20×11)+(10×15) = 220+150 = 370. CPI = (370/350)×100 ≈ 105.7.",
    misconception: "Comparing individual prices instead of the TOTAL cost of the whole basket.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-73",
    topic: "inflation",
    subtopic: "GDP deflator worked example",
    difficulty: 4,
    type: "code-analysis",
    code: "Nominal GDP this year = Gh¢500m\nReal GDP this year (in base-year prices) = Gh¢400m",
    question: "What is the GDP deflator for this year (base year = 100)?",
    options: ["80", "100", "125", "400"],
    correctIndex: 2,
    explanation: "GDP deflator = (Nominal GDP ÷ Real GDP) × 100 = (500/400) × 100 = 125 — prices have risen 25% relative to the base year.",
    relatedPartId: "e-part-5",
  },
  {
    id: "econs-74",
    topic: "inflation",
    subtopic: "Policies to tackle inflation",
    difficulty: 3,
    type: "best-practice",
    question: "Which of these is a supply-side policy for tackling inflation?",
    options: [
      "Cutting government spending",
      "Introducing more efficient production methods to lower costs",
      "Raising interest rates",
      "Increasing the money supply",
    ],
    correctIndex: 1,
    explanation: "Supply-side inflation policy targets production costs and efficiency directly (e.g. more efficient methods, restrictions on factor price increases) rather than manipulating aggregate demand.",
    relatedPartId: "e-part-5",
  },

  // ---------- The Phillips Curve (8) ----------
  {
    id: "econs-75",
    topic: "phillips-curve",
    subtopic: "What the curve shows",
    difficulty: 2,
    type: "concept",
    question: "The Phillips curve illustrates a relationship between...",
    options: ["GDP and population", "Inflation and unemployment", "Exports and imports", "Interest rates and savings"],
    correctIndex: 1,
    explanation: "The Phillips curve shows that (historically) lower unemployment tended to come with higher inflation, and vice versa.",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-76",
    topic: "phillips-curve",
    subtopic: "Origin",
    difficulty: 1,
    type: "concept",
    question: "The Phillips curve is named after which economist, who first observed this relationship?",
    options: ["John Maynard Keynes", "Milton Friedman", "Bill Phillips", "Adam Smith"],
    correctIndex: 2,
    explanation: "New Zealand economist Bill Phillips first illustrated the inflation-unemployment trade-off, giving the curve its name.",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-77",
    topic: "phillips-curve",
    subtopic: "Movement along vs shift",
    difficulty: 3,
    type: "concept",
    question: "A rise in aggregate demand (relative to potential output) is illustrated on the Phillips curve as...",
    options: [
      "The whole curve shifting outward",
      "An upward movement ALONG the existing curve — inflation rises and unemployment falls",
      "The curve becoming a horizontal line",
      "No change at all",
    ],
    correctIndex: 1,
    explanation: "A demand-driven change moves you along the SAME curve; only non-demand factors (cost-push, structural shifts, expectations) shift the curve itself.",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-78",
    topic: "phillips-curve",
    subtopic: "Why the curve is bowed",
    difficulty: 3,
    type: "concept",
    question: "Why was the original Phillips curve bowed in toward the origin (steeper at low unemployment)?",
    options: [
      "At low unemployment, labour becomes scarce and firms must offer increasingly higher wages to attract workers, strengthening unions' bargaining position",
      "Because government always fixes wages at low unemployment",
      "Because the exchange rate is always fixed at low unemployment",
      "There is no real explanation for this shape",
    ],
    correctIndex: 0,
    explanation: "As demand expands and surplus labour is used up, firms increasingly compete for scarce workers, pushing wage inflation up faster and faster — hence the steepening curve at low unemployment.",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-79",
    topic: "phillips-curve",
    subtopic: "What shifts the curve",
    difficulty: 3,
    type: "concept",
    question: "Which of the following would shift the whole Phillips curve outward (worse trade-off)?",
    options: [
      "A rise in cost-push inflation and structural unemployment happening together",
      "A simple rise in aggregate demand alone",
      "A fall in aggregate demand alone",
      "Nothing can shift the curve",
    ],
    correctIndex: 0,
    explanation: "Non-demand factors — cost-push inflation, rising frictional/structural unemployment, or changed inflation expectations — shift the curve itself, unlike pure demand changes which move you along it.",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-80",
    topic: "phillips-curve",
    subtopic: "Stagflation",
    difficulty: 2,
    type: "concept",
    question: "'Stagflation' refers to...",
    options: [
      "Low inflation and low unemployment together",
      "High inflation combined with high (and growing) unemployment at the same time",
      "A fixed exchange rate regime",
      "Zero economic growth with zero inflation",
    ],
    correctIndex: 1,
    explanation: "Stagflation is the simultaneous occurrence of high inflation AND high unemployment — the opposite of what the simple Phillips trade-off predicted.",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-81",
    topic: "phillips-curve",
    subtopic: "The 1970s breakdown",
    difficulty: 3,
    type: "concept",
    question: "What happened to the simple Phillips curve relationship during the 1970s?",
    options: [
      "It held perfectly, exactly as originally observed",
      "It broke down — economies experienced high inflation and high unemployment together (stagflation), contradicting the simple trade-off",
      "Unemployment disappeared completely",
      "Inflation became permanently negative",
    ],
    correctIndex: 1,
    explanation: "The 1970s saw stagflation, which the simple Phillips curve couldn't explain — this led economists to recognise the curve could shift due to non-demand factors like oil-price shocks (cost-push).",
    relatedPartId: "e-part-6",
  },
  {
    id: "econs-82",
    topic: "phillips-curve",
    subtopic: "Money illusion",
    difficulty: 4,
    type: "concept",
    question: "'Money illusion' in the Phillips curve context refers to...",
    options: [
      "Workers correctly perceiving that a nominal wage rise is offset by inflation",
      "Unemployed workers mistakenly believing a nominal wage rise represents a real wage increase, and so accepting jobs, reducing unemployment",
      "The government printing more physical currency",
      "A country using two different currencies",
    ],
    correctIndex: 1,
    explanation: "Money illusion is when workers respond to a rise in NOMINAL wages as if it were a real wage increase (ignoring inflation eating into it) — leading them to accept jobs they otherwise might not, temporarily lowering unemployment.",
    relatedPartId: "e-part-6",
  },

  // ---------- Balance of Payments (9) ----------
  {
    id: "econs-83",
    topic: "balance-of-payments",
    subtopic: "BOP definition",
    difficulty: 1,
    type: "concept",
    question: "The balance of payments records...",
    options: [
      "Only a country's government budget",
      "A country's transactions with the rest of the world",
      "Only stock market transactions",
      "Only domestic bank transactions",
    ],
    correctIndex: 1,
    explanation: "The BOP is the full record of a country's economic transactions with every other country — trade, income, and financial flows.",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-84",
    topic: "balance-of-payments",
    subtopic: "Current account components",
    difficulty: 2,
    type: "concept",
    question: "Which of these is NOT part of the current account?",
    options: ["Trade in goods", "Trade in services", "Income flows and current transfers", "Purchases of foreign company shares"],
    correctIndex: 3,
    explanation: "Buying foreign shares is an ASSET purchase, recorded in the financial account, not the current account (which covers goods, services, income, and transfers).",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-85",
    topic: "balance-of-payments",
    subtopic: "Capital account",
    difficulty: 2,
    type: "concept",
    question: "The capital account primarily records...",
    options: [
      "Trade in goods and services",
      "Flows of funds like migrant transfers and government grants for overseas projects",
      "The country's total tax revenue",
      "The exchange rate history",
    ],
    correctIndex: 1,
    explanation: "The capital account covers things like the transfer of funds by migrants and payment/receipt of grants for overseas projects — smaller in scale than the current or financial accounts for most countries.",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-86",
    topic: "balance-of-payments",
    subtopic: "Financial account",
    difficulty: 2,
    type: "concept",
    question: "The financial account is primarily concerned with...",
    options: [
      "Money incomes earned from trade",
      "The purchase and sale of assets — shares, property, bank deposits, loans, government securities",
      "The unemployment rate",
      "Consumer price inflation",
    ],
    correctIndex: 1,
    explanation: "Unlike the current account (concerned with incomes), the financial account tracks cross-border changes in the ownership of assets.",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-87",
    topic: "balance-of-payments",
    subtopic: "Current vs financial account focus",
    difficulty: 3,
    type: "concept",
    question: "What is the key conceptual difference between the current account and the financial account?",
    options: [
      "There is no real difference",
      "The current account concerns money INCOMES; the financial account concerns the purchase/sale of ASSETS",
      "The current account only covers government transactions",
      "The financial account only covers imports",
    ],
    correctIndex: 1,
    explanation: "This is the central distinction: current account = income flows (trade, wages, transfers); financial account = asset ownership changes (shares, property, deposits, securities).",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-88",
    topic: "balance-of-payments",
    subtopic: "Types of investment flows",
    difficulty: 2,
    type: "concept",
    question: "Within the financial account, 'portfolio investment' refers to...",
    options: [
      "Building a factory abroad and directly running it",
      "Buying shares, bonds, and securities without seeking direct control of the firm",
      "Government grants for foreign projects",
      "Trade in physical goods",
    ],
    correctIndex: 1,
    explanation: "Portfolio investment is buying financial assets (shares, bonds) for their return, without seeking management control — unlike direct investment.",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-89",
    topic: "balance-of-payments",
    subtopic: "Trade in goods vs services",
    difficulty: 2,
    type: "concept",
    question: "Which of these would be recorded under 'trade in services', not 'trade in goods'?",
    options: ["Export of cocoa beans", "Export of crude oil", "Earnings from foreign tourists visiting Ghana", "Import of machinery"],
    correctIndex: 2,
    explanation: "Tourism is a service (not a physical good), so foreign tourist spending is recorded under trade in services.",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-90",
    topic: "balance-of-payments",
    subtopic: "Balance of trade",
    difficulty: 2,
    type: "concept",
    question: "The 'balance of trade in goods and services' refers to...",
    options: [
      "Total government spending",
      "The net position combining trade in goods and trade in services (exports minus imports of both)",
      "Only the exchange rate",
      "Only income flows",
    ],
    correctIndex: 1,
    explanation: "This combines the goods balance and services balance into one figure showing the net trade position with the rest of the world.",
    relatedPartId: "e-part-7",
  },
  {
    id: "econs-91",
    topic: "balance-of-payments",
    subtopic: "Why BOP balances under floating rates",
    difficulty: 4,
    type: "concept",
    question: "Under a purely floating exchange rate, why does the overall balance of payments automatically balance?",
    options: [
      "Because the government forces it to balance by law",
      "Because the exchange rate adjusts until the demand for the domestic currency (driven by credits) equals the supply of it (driven by debits)",
      "It never actually balances under any system",
      "Because all trade is banned",
    ],
    correctIndex: 1,
    explanation: "Credits (e.g. foreigners buying exports) create demand for the domestic currency; debits (e.g. residents buying imports) create supply of it. A freely floating rate adjusts until these are equal, automatically balancing the accounts.",
    relatedPartId: "e-part-7",
  },

  // ---------- Exchange Rates (9) ----------
  {
    id: "econs-92",
    topic: "exchange-rates",
    subtopic: "Nominal exchange rate",
    difficulty: 1,
    type: "concept",
    question: "The nominal exchange rate is...",
    options: [
      "The quantity of local currency needed to exchange for one unit of a foreign currency",
      "The interest rate set by the central bank",
      "The inflation rate difference between two countries",
      "A country's total exports minus imports",
    ],
    correctIndex: 0,
    explanation: "e.g. Gh¢7.8 = $1 — the nominal exchange rate is simply the direct currency-for-currency conversion rate.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-93",
    topic: "exchange-rates",
    subtopic: "Fixed exchange rate",
    difficulty: 2,
    type: "concept",
    question: "A fixed (pegged) exchange rate is one where...",
    options: [
      "The currency's value is pegged by a monetary authority against another currency",
      "The rate changes freely every second with no intervention",
      "There is no exchange rate at all",
      "Only used by countries with no international trade",
    ],
    correctIndex: 0,
    explanation: "Under a fixed/pegged regime, a monetary authority commits to maintaining the currency's value at (or near) a specific rate against another currency.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-94",
    topic: "exchange-rates",
    subtopic: "Managed floating exchange rate",
    difficulty: 2,
    type: "concept",
    question: "A managed floating exchange rate means...",
    options: [
      "The rate is fixed permanently by law",
      "Market forces mostly determine the rate, but the government occasionally intervenes by buying/selling currency or adjusting money supply",
      "The government never intervenes under any circumstances",
      "The rate is determined only by interest rates abroad",
    ],
    correctIndex: 1,
    explanation: "Managed floating blends market determination with occasional government intervention to influence the rate's movement.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-95",
    topic: "exchange-rates",
    subtopic: "Purely floating exchange rate",
    difficulty: 2,
    type: "concept",
    question: "Under a purely (freely) floating exchange rate...",
    options: [
      "The government sets the rate by decree",
      "The government does not intervene at all — demand and supply alone determine the rate",
      "The rate never changes",
      "Only exports determine the rate",
    ],
    correctIndex: 1,
    explanation: "A purely floating rate is left entirely to market forces of demand and supply, with zero government intervention.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-96",
    topic: "exchange-rates",
    subtopic: "Appreciation",
    difficulty: 2,
    type: "concept",
    question: "A currency 'appreciates' when...",
    options: [
      "More local currency is needed to buy the same foreign currency",
      "Less local currency is needed to buy the same unit of foreign currency — the currency's free-market value rises",
      "The government fixes the rate",
      "Inflation rises sharply at home",
    ],
    correctIndex: 1,
    explanation: "Appreciation is a rise in the free-market exchange rate — the domestic currency becomes stronger and buys more foreign currency than before.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-97",
    topic: "exchange-rates",
    subtopic: "Depreciation",
    difficulty: 2,
    type: "concept",
    question: "A currency 'depreciates' when...",
    options: [
      "Less local currency is needed to buy the same foreign currency",
      "More local currency is now required to exchange for the same unit of foreign currency",
      "The exchange rate is fixed by law",
      "Exports suddenly stop entirely",
    ],
    correctIndex: 1,
    explanation: "Depreciation is a fall in the free-market value of the domestic currency — it now takes MORE of it to buy the same amount of foreign currency.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-98",
    topic: "exchange-rates",
    subtopic: "Causes of depreciation",
    difficulty: 3,
    type: "concept",
    question: "Which of these factors could lead to a depreciation of a country's currency?",
    options: [
      "Lower domestic inflation than abroad",
      "Higher domestic inflation than abroad, and falling domestic interest rates",
      "A rise in domestic interest rates only",
      "Falling domestic incomes only",
    ],
    correctIndex: 1,
    explanation: "Higher relative inflation erodes competitiveness (more imports demanded, fewer exports), and falling domestic interest rates make holding the currency less attractive — both push the currency toward depreciation.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-99",
    topic: "exchange-rates",
    subtopic: "Shifts in currency demand/supply",
    difficulty: 3,
    type: "concept",
    question: "If Ghana's demand for US dollars rises (e.g. to buy more imports), what happens in a floating exchange rate market?",
    options: [
      "The dollar depreciates and the cedi appreciates",
      "The demand curve for $ shifts right; the dollar appreciates and the cedi depreciates",
      "Nothing changes at all",
      "The government must immediately fix the rate",
    ],
    correctIndex: 1,
    explanation: "More Ghanaians wanting dollars shifts the demand curve for $ to the right — dollars become relatively scarcer, so the dollar appreciates while the cedi depreciates against it.",
    relatedPartId: "e-part-8",
  },
  {
    id: "econs-100",
    topic: "exchange-rates",
    subtopic: "Managing the exchange rate",
    difficulty: 3,
    type: "best-practice",
    question: "Which of these is a tool governments use to manage/intervene in the exchange rate?",
    options: [
      "Using foreign currency reserves to buy/sell currency, adjusting interest rates, and import controls (tariffs/quotas)",
      "Ignoring the exchange rate entirely under all circumstances",
      "Only changing the national anthem",
      "Abolishing the currency completely",
    ],
    correctIndex: 0,
    explanation: "Governments manage exchange rates via reserve intervention, interest rate changes, borrowing from abroad, and trade/import controls — used to reduce fluctuations or maintain a target rate.",
    relatedPartId: "e-part-8",
  },
];
