import type { MCQ } from "@/lib/mcqBank";

export const econsMcqBank: MCQ[] = [
  {
    id: "e-mcq-1",
    question: "Which of these is a macroeconomic (not microeconomic) question?",
    options: [
      "Why does this bakery charge more for bread than its rival?",
      "Why is the national unemployment rate rising?",
      "Why did this one household switch from rice to bread?",
      "Why does this firm's supply curve slope upward?",
    ],
    correctIndex: 1,
    explanation: "Macroeconomics looks at the economy as a whole (national unemployment, inflation, growth) rather than a single market or household.",
  },
  {
    id: "e-mcq-2",
    question: "In the aggregate demand identity AD = C + I + G + X − M, what does the M stand for?",
    options: ["Money supply", "Manufacturing output", "Imports", "Marginal propensity to consume"],
    correctIndex: 2,
    explanation: "M is imports — spending that leaves the domestic circular flow, which is why it's subtracted.",
  },
  {
    id: "e-mcq-3",
    question: "Which of these is a withdrawal (leakage) from the circular flow of income?",
    options: ["Government expenditure", "Exports", "Savings", "Investment"],
    correctIndex: 2,
    explanation: "Savings, net taxes, and import expenditure are the three withdrawals — money that leaves the inner spending flow. Investment, government spending, and exports are injections, not withdrawals.",
  },
  {
    id: "e-mcq-4",
    question: "Which method of measuring national income adds up wages, rent, interest, and profit?",
    options: ["The output (product) method", "The income method", "The expenditure method", "The deflator method"],
    correctIndex: 1,
    explanation: "The income method sums all factor incomes (wages to labour, rent to land, interest to capital, profit to entrepreneurship).",
  },
  {
    id: "e-mcq-5",
    question: "Real GDP, unlike nominal GDP, is calculated using...",
    options: ["Current-year prices", "Constant base-year prices", "Foreign currency prices", "Only export prices"],
    correctIndex: 1,
    explanation: "Real GDP uses fixed base-year prices so that changes in real GDP reflect changes in actual quantities produced, not just price inflation.",
  },
  {
    id: "e-mcq-6",
    question: "Frictional unemployment is best described as unemployment caused by...",
    options: [
      "A fall in aggregate demand",
      "Imperfect information — it takes time to match searching workers to vacancies",
      "Trade unions pushing wages above the market-clearing level",
      "The seasons of the year",
    ],
    correctIndex: 1,
    explanation: "Frictional (search) unemployment exists even when vacancies are available, simply because matching workers to jobs takes time.",
  },
  {
    id: "e-mcq-7",
    question: "Cost-push inflation is most directly caused by a shift in which curve?",
    options: ["Aggregate demand shifts right", "Aggregate supply shifts left (costs rise)", "Aggregate supply shifts right", "The Phillips curve shifts left"],
    correctIndex: 1,
    explanation: "Cost-push inflation comes from rising production costs, which shift the aggregate supply curve left/upward, raising prices while output tends to fall.",
  },
  {
    id: "e-mcq-8",
    question: "The Phillips curve originally illustrated a trade-off between...",
    options: ["Growth and inflation", "Inflation and unemployment", "Imports and exports", "Interest rates and savings"],
    correctIndex: 1,
    explanation: "The original Phillips curve showed that lower unemployment tended to come with higher inflation, and vice versa.",
  },
  {
    id: "e-mcq-9",
    question: "A country's balance of payments current account records all of the following EXCEPT...",
    options: ["Trade in goods", "Trade in services", "Purchases of foreign shares and property", "Income flows and current transfers"],
    correctIndex: 2,
    explanation: "Purchases of foreign shares/property/assets belong to the financial account, not the current account, which is about incomes from trade and investment.",
  },
  {
    id: "e-mcq-10",
    question: "If the Ghana cedi depreciates against the US dollar, this means...",
    options: [
      "Fewer cedis are now needed to buy one dollar",
      "More cedis are now needed to buy one dollar",
      "The cedi and the dollar now have equal value",
      "Ghana has adopted a fixed exchange rate",
    ],
    correctIndex: 1,
    explanation: "Depreciation is a fall in the free-market value of the domestic currency — it now takes MORE cedis to buy the same one dollar.",
  },
  {
    id: "e-mcq-11",
    question: "In C = a + bY, the coefficient 'b' is called the...",
    options: ["Marginal propensity to save", "Marginal propensity to consume", "Average propensity to consume", "Multiplier"],
    correctIndex: 1,
    explanation: "'b' is the MPC — how much extra consumption results from each extra unit of income.",
  },
  {
    id: "e-mcq-12",
    question: "MPC + MPS always equals...",
    options: ["0", "1", "The multiplier", "The tax rate"],
    correctIndex: 1,
    explanation: "Every extra cedi of income is either consumed or saved, so MPC + MPS = 1 by definition.",
  },
  {
    id: "e-mcq-13",
    question: "Which of these is NOT one of the three withdrawals?",
    options: ["Savings", "Net taxes", "Imports", "Government spending"],
    correctIndex: 3,
    explanation: "Government spending is an injection, not a withdrawal. The three withdrawals are savings, net taxes, and imports.",
  },
  {
    id: "e-mcq-14",
    question: "The marginal propensity to withdraw, mpw, is the sum of...",
    options: ["mpc + mps", "mps + mpt + mpm", "mpc × mps × mpm", "1 − mpc only"],
    correctIndex: 1,
    explanation: "mpw stacks the three individual leak rates together: the propensity to save, to tax, and to import.",
  },
  {
    id: "e-mcq-15",
    question: "If MPC = 0.6 (no taxes or imports), the multiplier k equals...",
    options: ["0.4", "1.5", "2.5", "0.6"],
    correctIndex: 2,
    explanation: "k = 1/(1 − MPC) = 1/(1 − 0.6) = 1/0.4 = 2.5.",
  },
  {
    id: "e-mcq-16",
    question: "National income is in equilibrium when...",
    options: ["Consumption equals investment", "Withdrawals equal injections", "Exports equal imports", "Savings equal zero"],
    correctIndex: 1,
    explanation: "Equilibrium national income is where W = J (equivalently, where Y = AE — the AE line crosses the 45° line).",
  },
  {
    id: "e-mcq-17",
    question: "A rise in the tax rate (t), holding everything else constant, will...",
    options: [
      "Increase the multiplier",
      "Decrease the multiplier",
      "Have no effect on the multiplier at all",
      "Only affect exports",
    ],
    correctIndex: 1,
    explanation: "A higher tax rate raises mpw (more leaks out as tax on each extra cedi), which shrinks the multiplier k = 1/mpw.",
  },

  // ---------- Computer Science Foundations (economics as applied to tech/CS) ----------
  {
    id: "e-mcq-cs-1",
    question: "The Keynesian multiplier effect (an initial injection of spending leads to a larger final rise in national income) is economically similar to which phenomenon in tech platforms?",
    options: [
      "Viral/network growth, where one new user triggers a cascade of additional users joining through their connections",
      "Binary search",
      "Garbage collection",
      "A compiler's syntax check",
    ],
    correctIndex: 0,
    explanation: "Both describe a small initial change cascading into a much larger final effect through repeated rounds of knock-on activity — extra spending triggering more spending, or one user's invites triggering more invites.",
  },
  {
    id: "e-mcq-cs-2",
    question: "The economic concept of \"opportunity cost\" (the value of the next-best alternative given up) has a direct analogue in computer science, in the idea of:",
    options: [
      "A space-time tradeoff, where choosing to save memory (e.g., recomputing a value instead of storing it) costs you time, and vice versa",
      "Object-oriented inheritance",
      "A hash collision",
      "Binary representation of negative numbers",
    ],
    correctIndex: 0,
    explanation: "Both ideas are about the same underlying tradeoff logic: choosing one option (memory saved) means giving up another (time saved) — you can't have both at once, so you weigh which one you value more for the situation.",
  },
  {
    id: "e-mcq-cs-3",
    question: "Game theory, a branch of economics studying strategic decision-making, is directly used in computer science to analyze:",
    options: [
      "How independent, self-interested network nodes or algorithms behave when routing traffic or bidding in auctions — reaching a Nash equilibrium",
      "How fast a CPU can execute an instruction",
      "The physical layout of a circuit board",
      "How much RAM a program uses",
    ],
    correctIndex: 0,
    explanation: "Algorithmic game theory studies exactly this: what happens when self-interested agents (routers, bidders, distributed nodes) each optimize for themselves — the equilibrium that emerges (or fails to) is central to auction design and network routing analysis.",
  },
  {
    id: "e-mcq-cs-4",
    question: "Google and Facebook's online advertising systems, which decide which ad wins a slot and what the advertiser pays, are built directly on economic theory from:",
    options: ["Auction theory and mechanism design", "Graph colouring", "Regular expressions", "Binary search trees"],
    correctIndex: 0,
    explanation: "Real-time ad placement is literally a live auction run billions of times a day; the rules for how bids translate into winners and prices come straight out of auction theory and mechanism design.",
  },
  {
    id: "e-mcq-cs-5",
    question: "The economic law of diminishing marginal returns (each extra unit of input adds a smaller extra output than the one before) shows up directly in computing as:",
    options: [
      "Diminishing parallel speedup — adding more CPU cores to a program eventually yields smaller and smaller performance gains (related to Amdahl's Law)",
      "A hash table always getting faster the more buckets it has, with no limit",
      "Compilers always producing identical machine code regardless of optimization level",
      "Networks never experiencing any latency",
    ],
    correctIndex: 0,
    explanation: "Amdahl's Law formalizes exactly this: the speedup from adding more parallel processors is capped by the portion of the program that can't be parallelized, so each additional core adds a shrinking benefit — the same curve shape as diminishing marginal returns.",
  },
  {
    id: "e-mcq-cs-6",
    question: "A \"network effect\" — a platform becoming more valuable as more people use it — is exactly the economic principle behind:",
    options: [
      "Why social networks and messaging apps become dramatically harder to compete with once they reach a large user base",
      "Why CPUs run faster with more transistors",
      "Why hash tables need collision resolution",
      "Why compilers optimize code",
    ],
    correctIndex: 0,
    explanation: "Each new user makes the platform more valuable to every existing user (more people to talk to, more content, more liquidity) — a self-reinforcing loop that is the economic engine behind why dominant social platforms are so hard to displace.",
  },
  {
    id: "e-mcq-cs-7",
    question: "Operating system schedulers deciding which process gets CPU time next are solving a problem economists would immediately recognize as:",
    options: [
      "Resource allocation under scarcity — a finite resource (CPU time) must be divided among competing demands",
      "An entirely unrelated problem with no economic parallel",
      "A pure hardware manufacturing issue",
      "A cryptography problem",
    ],
    correctIndex: 0,
    explanation: "Economics is fundamentally the study of allocating scarce resources among competing wants; a CPU scheduler is doing exactly that with a scarce resource (processor time) and competing demands (waiting processes).",
  },
  {
    id: "e-mcq-cs-8",
    question: "The economic principle of comparative advantage (each party specializes in what they're relatively most efficient at, then trades) parallels which modern software architecture idea?",
    options: [
      "Microservices — breaking a system into specialized services, each handling one concern well, that communicate over the network",
      "A single monolithic file containing all the code",
      "Never modularizing code at all",
      "Deleting unused functions",
    ],
    correctIndex: 0,
    explanation: "Just as trading nations specialize in what they do relatively best and exchange the rest, a microservices architecture lets each service specialize in one responsibility and rely on other services (via network calls) for everything else.",
  },
  {
    id: "e-mcq-cs-9",
    question: "Open-source software is a commonly cited real-world example of an economic \"public good\" because it is:",
    options: [
      "Non-excludable and non-rivalrous — one person using or copying the code doesn't prevent anyone else from doing the same",
      "Extremely expensive and scarce",
      "Only usable by one person at a time",
      "Always proprietary and closed",
    ],
    correctIndex: 0,
    explanation: "A public good is defined by being non-excludable (you can't easily stop people from using it) and non-rivalrous (one person's use doesn't reduce availability for others) — both true of freely copyable source code, unlike a physical, scarce resource.",
  },
  {
    id: "e-mcq-cs-10",
    question: "In security economics, if a software vendor bears little of the cost when their product is breached (the cost mostly falls on users), this creates what economists call:",
    options: [
      "A moral hazard — the party best able to prevent a risk isn't the one bearing its cost, so they under-invest in prevention",
      "A network effect",
      "A public good",
      "Comparative advantage",
    ],
    correctIndex: 0,
    explanation: "Moral hazard arises whenever the party making the risk-related decision doesn't bear the full consequences of that risk — a well-studied reason cited for why security investment in software is often below the socially optimal level.",
  },
  {
    id: "e-mcq-cs-11",
    question: "Cloud providers charging higher \"spot prices\" for compute capacity during high-demand periods is a direct application of which economic idea?",
    options: [
      "Price acting as a signal that rations a scarce resource (compute capacity) toward its highest-value uses when demand is high",
      "The multiplier effect",
      "Comparative advantage",
      "A public good",
    ],
    correctIndex: 0,
    explanation: "Dynamic/surge pricing is a textbook price mechanism: when demand for a limited resource spikes, letting price rise rations that resource toward whoever values it most, and signals the market to bring more supply online.",
  },
  {
    id: "e-mcq-cs-12",
    question: "Studies showing that even a small increase in a website's page-load time causes a disproportionately large drop in traffic and conversions is web engineering's version of which economic concept?",
    options: [
      "Elasticity — how sensitive quantity demanded is to a change in price (here, \"price\" is the user's time/latency)",
      "User demand being perfectly inelastic, with zero relationship between speed and demand",
      "A network effect",
      "Comparative advantage",
    ],
    correctIndex: 0,
    explanation: "Elasticity measures how responsive demand is to a change in cost. Users treat waiting time as a real cost, and the well-documented outsized drop-off from small latency increases shows that demand for a fast web experience is highly elastic.",
  },
  {
    id: "e-mcq-cs-13",
    question: "GDP measures the total value of output an economy produces in a period. In computer-systems terminology, this is most analogous to a system's:",
    options: ["Throughput — the total amount of useful work completed per unit time", "Latency — the delay for a single request", "Uptime — the fraction of time a system is available", "The bandwidth of a single network cable"],
    correctIndex: 0,
    explanation: "GDP is a flow measure of total output over a period, exactly matching the definition of system throughput: total useful work processed per unit of time, not the speed of any one individual request.",
  },
  {
    id: "e-mcq-cs-14",
    question: "Cloud infrastructure that auto-scales server capacity up during high-traffic periods and down during quiet periods is responding to the same underlying pattern economists study as:",
    options: [
      "The business cycle — demand naturally expands and contracts over time, and capacity must adapt to match",
      "A fixed, constant, never-changing level of demand",
      "The multiplier effect, and only the multiplier effect",
      "Comparative advantage",
    ],
    correctIndex: 0,
    explanation: "Just as the economy cycles through expansion and contraction, real-world traffic to a system rises and falls in cycles (daily, seasonal, event-driven) — auto-scaling is essentially real-time capacity management against a business-cycle-like demand pattern.",
  },
  {
    id: "e-mcq-cs-15",
    question: "Game designers who create in-game currencies must actively manage \"inflation\" in their virtual economies for the same underlying reason central banks do, because:",
    options: [
      "If the money supply (in-game currency) grows faster than the goods/services it can buy, each unit of currency buys less over time, eroding its value",
      "Virtual currencies are immune to inflation by design",
      "Inflation only ever occurs in real, physical currencies",
      "More currency in circulation always makes an economy healthier, with no downside",
    ],
    correctIndex: 0,
    explanation: "In-game currency inflation is a well-documented, real phenomenon in game economies (e.g., unchecked gold-farming or reward loops) — the exact same supply-vs-goods imbalance that causes inflation in real economies.",
  },
  {
    id: "e-mcq-cs-16",
    question: "Just as economists measure the \"output gap\" between an economy's actual and potential output, systems engineers track an analogous idea called:",
    options: [
      "Resource utilization — the gap between a server's actual workload and its full processing capacity represents wasted, idle potential",
      "Network latency",
      "Binary search depth",
      "Hash table load factor, exclusively",
    ],
    correctIndex: 0,
    explanation: "Both metrics measure the same kind of gap: how much of the available capacity (labour and capital in an economy; CPU/memory in a server) is actually being put to productive use versus sitting idle.",
  },
  {
    id: "e-mcq-cs-17",
    question: "Cryptocurrency exchanges and payment APIs that convert between currencies in real time are built to handle the exact economic phenomenon covered in this room's Exchange Rates section:",
    options: [
      "Continuously fluctuating exchange rates driven by supply and demand for each currency",
      "A single, permanently fixed conversion rate that never changes for any currency pair",
      "No relationship between currencies at all",
      "Rates that are set once at launch and never updated",
    ],
    correctIndex: 0,
    explanation: "Whether it's cedis-to-dollars or Bitcoin-to-dollars, the software has to constantly track a rate that moves with supply and demand — the same exchange-rate mechanics covered in this room, just applied to a newer asset class.",
  },
  {
    id: "e-mcq-cs-18",
    question: "The balance of payments is recorded using double-entry bookkeeping (every transaction has a matching credit and debit). This exact accounting principle also underlies:",
    options: [
      "How blockchain and financial-ledger software track transactions, ensuring the books always balance",
      "How hash functions are computed",
      "How a compiler translates source code",
      "How a CPU's clock speed is measured",
    ],
    correctIndex: 0,
    explanation: "Double-entry bookkeeping — every transaction recorded as an equal and opposite credit/debit — is the same accounting logic that keeps ledger software (and blockchains, which are essentially distributed ledgers) internally consistent.",
  },
  {
    id: "e-mcq-cs-19",
    question: "The Phillips curve, showing a trade-off between inflation and unemployment, is an economic example of a more general concept computer scientists call:",
    options: [
      "A Pareto frontier — the set of best possible trade-off points when optimizing two competing objectives at once (e.g., accuracy vs. speed in a machine-learning model)",
      "A hash table",
      "A sorting algorithm",
      "A binary tree",
    ],
    correctIndex: 0,
    explanation: "Both describe the same shape of problem: you cannot improve one objective without giving up some of the other, and the curve/frontier traces out all the efficient trade-off points available — whether the two objectives are inflation/unemployment or speed/accuracy.",
  },
  {
    id: "e-mcq-cs-20",
    question: "A government trying to simultaneously maximize growth, minimize unemployment, minimize inflation, and maintain a healthy balance of payments faces the same fundamental challenge as an engineer tuning a system for speed, memory use, and accuracy at once:",
    options: [
      "Multi-objective optimization — improving one metric often requires accepting a worse outcome on another",
      "No real tradeoff exists between any of these goals",
      "Only one metric ever matters in engineering",
      "These are entirely unrelated fields with no shared concepts",
    ],
    correctIndex: 0,
    explanation: "Both are multi-objective optimization problems: several goals matter simultaneously, they often conflict, and there's rarely one setting that maximizes all of them at once — you have to choose a balance point.",
  },
  {
    id: "e-mcq-cs-21",
    question: "The marginal propensity to consume (MPC) — how much of each extra cedi of income gets spent again — determines the size of the multiplier, in the same way a control system's \"gain\" determines:",
    options: [
      "How much a system's output amplifies (or dampens) in response to a change in its input",
      "The exact colour used in a UI",
      "The number of lines in a program",
      "The size of a hash table",
    ],
    correctIndex: 0,
    explanation: "Both MPC and control-system gain describe the same feedback idea: a higher gain (or MPC) means a given input change produces a larger amplified response as it feeds back through the system, exactly like the multiplier amplifying an initial injection.",
  },
  {
    id: "e-mcq-cs-22",
    question: "An economist's \"cost-benefit analysis\" before undertaking a project is essentially the same reasoning a software engineer uses when deciding:",
    options: [
      "Whether the performance benefit of adding a cache or optimization is worth its added memory and complexity cost",
      "Which programming language has the prettiest syntax",
      "How to name a variable",
      "What colour scheme to use for a website",
    ],
    correctIndex: 0,
    explanation: "Both are weighing a concrete benefit against a concrete cost before committing resources — whether that's public money on infrastructure, or engineering time and memory budget on a code optimization.",
  },
  {
    id: "e-mcq-cs-23",
    question: "In the circular flow model, \"investment\" (I) means spending on capital goods that expand future productive capacity. A tech company's spending on new data centres or R&D is a direct real-world example of:",
    options: ["Investment (I) as an injection into the circular flow of income", "Consumption (C) only", "A withdrawal, not an injection", "Government spending, exclusively"],
    correctIndex: 0,
    explanation: "Building data centres and funding R&D is spending on capital that expands future output capacity — precisely what \"investment\" means in the circular flow model, and it counts as an injection (J), not a withdrawal.",
  },
  {
    id: "e-mcq-cs-24",
    question: "Economists studying how an economy \"responds\" to a stimulus injection use the same kind of thinking as engineers modelling how a software system responds to injected load in a simulation — both are examples of:",
    options: [
      "Systems/dynamic modelling — tracing how an initial change propagates and settles through a system with feedback effects",
      "Static, one-time calculations with no feedback at all",
      "Encryption",
      "Sorting algorithms",
    ],
    correctIndex: 0,
    explanation: "Both are dynamic systems questions: an initial disturbance (spending injection, or injected load) ripples through a system with internal feedback loops (the multiplier's rounds of spending, or a system's queues and dependencies) before settling at a new equilibrium.",
  },
  {
    id: "e-mcq-cs-25",
    question: "Modern algorithmic trading firms and central banks both rely heavily on which shared computational approach to make economic decisions?",
    options: [
      "Building computational/statistical models that process large amounts of data to forecast future economic or market conditions",
      "Manually writing every decision on paper with no computer involvement",
      "Random guessing",
      "Ignoring all historical data",
    ],
    correctIndex: 0,
    explanation: "Both fields depend on data-driven forecasting models — quantitative trading firms and central bank economists alike build computational models trained on historical and real-time data to inform decisions.",
  },
  {
    id: "e-mcq-cs-26",
    question: "Software products that set a helpful \"default\" option (e.g., defaulting new users into a recommended privacy setting) are directly applying an idea from:",
    options: ["Behavioural economics — defaults strongly influence choices because most people don't actively change them (the \"nudge\" concept)", "Binary search", "TCP/IP networking", "Boolean algebra"],
    correctIndex: 0,
    explanation: "Behavioural economics' \"nudge\" theory shows that because of inertia, most people stick with whatever default they're given — a principle UX designers deliberately use when choosing default settings.",
  },
  {
    id: "e-mcq-cs-27",
    question: "A cloud company calculating the cost of serving one additional user (extra server capacity, bandwidth, etc.) is applying which core economic concept directly to infrastructure decisions?",
    options: ["Marginal cost — the additional cost of producing or serving one more unit", "Total revenue", "GDP", "The multiplier"],
    correctIndex: 0,
    explanation: "Marginal cost is specifically the cost of one more unit of output — exactly the question a cloud company asks when pricing plans or deciding whether onboarding another customer is still profitable at the margin.",
  },
  {
    id: "e-mcq-cs-28",
    question: "As IPv4 addresses became scarce, an actual secondary market emerged where companies buy, sell, and lease IPv4 address blocks. This is a real-world example of:",
    options: [
      "Price mechanisms allocating a genuinely scarce resource to its highest-value use, once free allocation ran out",
      "A resource that can never run out",
      "A public good with unlimited supply",
      "Something with no economic content at all",
    ],
    correctIndex: 0,
    explanation: "Once the free, first-come allocation of IPv4 space ran out, a real market with real prices emerged to ration the now-scarce addresses toward whoever valued them most — textbook price-mechanism behaviour applied to Internet infrastructure.",
  },
  {
    id: "e-mcq-cs-29",
    question: "A team that keeps pouring resources into patching an outdated, failing system \"because we've already invested so much in it\" is falling for what classic economic reasoning error?",
    options: [
      "The sunk cost fallacy — letting an unrecoverable past cost influence a decision that should be based only on future costs and benefits",
      "Comparative advantage",
      "A network effect",
      "The multiplier effect",
    ],
    correctIndex: 0,
    explanation: "Past spending is already gone regardless of what you choose next — rational decisions should weigh only future costs and benefits (e.g., rewrite vs. keep patching), not how much has already been sunk into the old approach.",
  },
  {
    id: "e-mcq-cs-30",
    question: "At their core, both economics and computer science are, in a sense, studying the same underlying problem. Which best captures it?",
    options: [
      "How to allocate scarce resources (money, time, labour — or CPU cycles, memory, bandwidth) as efficiently as possible given competing demands",
      "Economics studies money and computer science studies computers, with no conceptual overlap",
      "Neither field involves any kind of optimization",
      "Only computer science deals with any form of scarcity",
    ],
    correctIndex: 0,
    explanation: "Strip away the surface-level differences and both disciplines are fundamentally about optimization under constraints: allocating something finite (money, labour, CPU time, memory, bandwidth) as effectively as possible among competing uses.",
  },
];
