export type EconsPassSection =
  | "macro-scope-cycle-growth"
  | "national-income-gdp"
  | "consumption-multiplier-fiscal"
  | "money-banking"
  | "monetary-fiscal-policy-tools"
  | "ad-as-inflation";

export interface EconsPassQuestion {
  id: string;
  section: EconsPassSection;
  question: string;
  code?: string;
  options?: string[];
  answer: string;
  explanation: string;
}

export const ECONS_PASS_SECTIONS: { id: EconsPassSection; label: string }[] = [
  { id: "macro-scope-cycle-growth", label: "Macro Scope, Business Cycle & Growth" },
  { id: "national-income-gdp", label: "National Income & GDP" },
  { id: "consumption-multiplier-fiscal", label: "Consumption, Multiplier & Fiscal Policy" },
  { id: "money-banking", label: "Money & Banking" },
  { id: "monetary-fiscal-policy-tools", label: "Monetary & Fiscal Policy Tools" },
  { id: "ad-as-inflation", label: "AD-AS, Inflation & Phillips Curve" },
];

export const econsPasscoBank: EconsPassQuestion[] = [
  {
    id: "econs-passco-1",
    section: "macro-scope-cycle-growth",
    question: "Macroeconomics deals with",
    options: ["the activities of individual units", "the behaviour of the electronics industry", "economic aggregates", "the behaviour of firms"],
    answer: "economic aggregates",
    explanation: "Macroeconomics studies the economy as a whole using aggregate measures (total output, total employment, the overall price level) rather than individual units or firms.",
  },
  {
    id: "econs-passco-2",
    section: "macro-scope-cycle-growth",
    question: "The study of inflation is part of",
    options: ["microeconomics", "descriptive economics", "macroeconomics", "normative economics"],
    answer: "macroeconomics",
    explanation: "Inflation — a change in the overall/general price level — is a classic macroeconomic topic, since it concerns the whole economy rather than a single market.",
  },
  {
    id: "econs-passco-3",
    section: "ad-as-inflation",
    question: "Aggregate supply is the total amount",
    options: ["of goods and services produced in an economy", "produced by the government", "of products produced by a given industry", "of labour supplied by all households"],
    answer: "of goods and services produced in an economy",
    explanation: "Aggregate supply is an economy-wide concept — the total output of goods and services the whole economy is willing to produce at each price level.",
  },
  {
    id: "econs-passco-4",
    section: "ad-as-inflation",
    question: "The total demand for goods and services in an economy is known as",
    options: ["gross national product", "national demand", "economy-wide demand", "aggregate demand"],
    answer: "aggregate demand",
    explanation: "Aggregate demand is the standard term for total planned spending on goods and services across the whole economy.",
  },
  {
    id: "econs-passco-5",
    section: "ad-as-inflation",
    question: "Inflation is",
    options: ["an increase in the overall level of economic activity", "a decrease in the overall price level", "a decrease in the overall level of economic activity", "an increase in the overall price level"],
    answer: "an increase in the overall price level",
    explanation: "Inflation specifically refers to prices rising, not output/activity changing — that distinction is exactly what this question tests.",
  },
  {
    id: "econs-passco-6",
    section: "macro-scope-cycle-growth",
    question: "A recession is",
    options: ["a period during which aggregate output declines", "a period of very rapidly declining prices", "a period of declining prices", "a period of declining unemployment"],
    answer: "a period during which aggregate output declines",
    explanation: "A recession is defined by falling real output/GDP, not by prices or unemployment directly (though unemployment typically rises alongside it).",
  },
  {
    id: "econs-passco-7",
    section: "national-income-gdp",
    question: "Gross Domestic Product is defined as",
    options: [
      "disposable income + taxes + investment spending + exports + imports",
      "consumer spending + government purchases + financial spending + exports − imports",
      "consumer spending + government purchases + investment spending + exports − imports",
      "consumer spending + government transfers + investment spending + exports − imports",
    ],
    answer: "consumer spending + government purchases + investment spending + exports − imports",
    explanation: "This is the standard expenditure identity: GDP = C + I + G + (X − M). The other options substitute in the wrong terms (financial spending, transfers, disposable income).",
  },
  {
    id: "econs-passco-8",
    section: "national-income-gdp",
    code: "Base year = 2004\nGino's pizza: 2004 units 4,000 @ $10; 2005 units 4,000 @ $8\nBruno's dough: 2004 units 3,000 @ $9; 2005 units 1,000 @ $6\nCarlo's tomatoes: 2004 units 2,000 @ $6; 2005 units 1,000 @ $1\nAldo's pepperoni: 2004 units 5,000 @ $7; 2005 units 2,000 @ $4",
    question: "(Table: Pizza Economy) Considering 2004 as the base year, real GDP in 2005 was",
    options: ["$69,000", "$72,000", "$114,000", "$47,000"],
    answer: "$69,000",
    explanation: "Real GDP prices 2005's quantities at 2004 (base-year) prices: (4,000×$10)+(1,000×$9)+(1,000×$6)+(2,000×$7) = $40,000+$9,000+$6,000+$14,000 = $69,000.",
  },
  {
    id: "econs-passco-9",
    section: "national-income-gdp",
    code: "Same table as the previous question.",
    question: "(Table: Pizza Economy) Considering 2004 as the base year, nominal GDP in 2005 was",
    options: ["$69,000", "$72,000", "$114,000", "$47,000"],
    answer: "$47,000",
    explanation: "Nominal GDP uses each year's own prices: (4,000×$8)+(1,000×$6)+(1,000×$1)+(2,000×$4) = $32,000+$6,000+$1,000+$8,000 = $47,000 — far lower than real GDP here because most 2005 prices fell.",
  },
  {
    id: "econs-passco-10",
    section: "macro-scope-cycle-growth",
    question: "Which of the following is a chief measure of economic growth over time?",
    options: ["Increase in real per capita GDP", "Increases in the available labour supply", "Inflation", "Decline in real interest rates"],
    answer: "Increase in real per capita GDP",
    explanation: "Real GDP per capita (adjusted for both inflation and population) is the standard headline measure of whether living standards/output are genuinely growing.",
  },
  {
    id: "econs-passco-11",
    section: "macro-scope-cycle-growth",
    question: "All of the following are examples of government policies aimed at promoting economic growth except",
    options: [
      "implementing a monetary policy that increases inflation",
      "subsidizing education",
      "providing political stability and protecting property rights",
      "building infrastructure and providing public goods",
    ],
    answer: "implementing a monetary policy that increases inflation",
    explanation: "Deliberately increasing inflation is not a growth policy — inflation imposes costs and doesn't build productive capacity, unlike education, stable institutions, and infrastructure.",
  },
  {
    id: "econs-passco-12",
    section: "consumption-multiplier-fiscal",
    question: "Crowding out means",
    options: [
      "some bond holders will be squeezed out of the market",
      "there are too many players in the financial markets",
      "private savings decreases when the government borrows",
      "private investment decreases when the government borrows",
    ],
    answer: "private investment decreases when the government borrows",
    explanation: "Crowding out: government borrowing competes for loanable funds, pushing up interest rates and reducing private investment.",
  },
  {
    id: "econs-passco-13",
    section: "consumption-multiplier-fiscal",
    question: "The multiplier is",
    options: ["MPS/MPC", "1/[MPC]", "1[1+MPC]", "1/[1-MPC]"],
    answer: "1/[1-MPC]",
    explanation: "The simple spending multiplier is 1/(1−MPC), equivalently 1/MPS, since MPS = 1 − MPC.",
  },
  {
    id: "econs-passco-14",
    section: "consumption-multiplier-fiscal",
    code: "MPC = 0.8\nInvestment spending increases by $100 billion",
    question: "The increase in aggregate demand is",
    options: [
      "$125 billion, composed of $100 billion in investment spending and $25 billion in consumption",
      "$500 billion, composed of $100 billion in investment spending and $400 billion in consumption",
      "$100 billion, the amount of investment spending",
      "$80 billion, composed of $100 billion in investment spending and a decrease in consumption of $20 billion",
    ],
    answer: "$500 billion, composed of $100 billion in investment spending and $400 billion in consumption",
    explanation: "Multiplier = 1/(1−0.8) = 5. Total ΔAD = $100bn × 5 = $500bn — the initial $100bn investment plus $400bn of induced consumption spending.",
  },
  {
    id: "econs-passco-15",
    section: "macro-scope-cycle-growth",
    question: "The phase of the business cycle in which real domestic output decreases is called",
    options: ["the peak", "a recovery", "a recession", "the trough", "the expansion"],
    answer: "a recession",
    explanation: "\"Recession\" names the phase where output is actively falling. The peak and trough are single turning points, not phases; recovery/expansion are the phases where output rises.",
  },
  {
    id: "econs-passco-16",
    section: "consumption-multiplier-fiscal",
    question: "The marginal propensity to consume equals 1 minus the",
    options: ["marginal propensity to invest", "marginal propensity to save", "marginal propensity to import", "marginal propensity to pay taxes"],
    answer: "marginal propensity to save",
    explanation: "By definition, each extra unit of income is either consumed or saved: MPC + MPS = 1, so MPC = 1 − MPS.",
  },
  {
    id: "econs-passco-17",
    section: "consumption-multiplier-fiscal",
    question: "Which of the following are included in autonomous expenditure?",
    options: ["Investment", "Government purchase", "Autonomous consumption expenditure", "All of the above"],
    answer: "All of the above",
    explanation: "Autonomous expenditure means spending that doesn't depend on current income — investment, government purchases, and the autonomous (intercept) part of consumption are all treated as autonomous in the simple Keynesian model.",
  },
  {
    id: "econs-passco-18",
    section: "macro-scope-cycle-growth",
    question: "In a recession,",
    options: [
      "investment is low and the capital stock grows quickly",
      "investment is low and the capital stock grows slowly",
      "investment is high and consumption is low",
      "consumption is high and government spending is low",
    ],
    answer: "investment is low and the capital stock grows slowly",
    explanation: "Recessions are typically marked by weak investment, which in turn slows the growth of the economy's capital stock.",
  },
  {
    id: "econs-passco-19",
    section: "national-income-gdp",
    question: "All of the following are government expenditure items except",
    options: ["interest on government debt", "transfer payment", "purchases of corporate bonds", "purchase of goods and services"],
    answer: "transfer payment",
    explanation: "In national-income accounting, transfer payments (e.g. welfare, subsidies to individuals) don't correspond to any current production and are explicitly excluded from GDP's government spending component — unlike genuine purchases of goods/services or debt interest. A common mistake is assuming any government outlay automatically counts as a GDP-relevant expenditure item.",
  },
  {
    id: "econs-passco-20",
    section: "macro-scope-cycle-growth",
    question: "During a recession,",
    options: ["labour is not fully utilised", "capital is not fully utilised", "land is not fully utilised", "all of the above"],
    answer: "all of the above",
    explanation: "A recession means the economy is producing below potential — all factors of production (labour, capital, land) tend to sit at least partly idle.",
  },
  {
    id: "econs-passco-21",
    section: "ad-as-inflation",
    question: "The aggregate demand curve is",
    options: ["upward sloping", "downward sloping", "a vertical line", "a horizontal line"],
    answer: "downward sloping",
    explanation: "AD slopes downward: as the price level falls, real spending rises (via the real-balance, interest-rate, and foreign-purchases effects).",
  },
  {
    id: "econs-passco-22",
    section: "money-banking",
    question: "M1 refers to",
    options: ["currency", "currency plus total reserves", "currency plus checkable deposits", "currency, checkable deposits, savings deposits, money market mutual funds, and small-time deposits"],
    answer: "currency plus checkable deposits",
    explanation: "M1 is the narrowest common money-supply measure: currency in circulation plus checkable (demand) deposits. The last option actually describes the broader M2.",
  },
  {
    id: "econs-passco-23",
    section: "macro-scope-cycle-growth",
    question: "Cyclical unemployment",
    options: ["is due mainly to job leavers", "may increase or decrease during an expansion", "occurs when technology improvements change job requirements", "fluctuates over the business cycle"],
    answer: "fluctuates over the business cycle",
    explanation: "Cyclical unemployment is, by definition, the portion of unemployment tied to the ups and downs of the business cycle — rising in recessions, falling in expansions.",
  },
  {
    id: "econs-passco-24",
    section: "monetary-fiscal-policy-tools",
    question: "Fiscal policy refers to the",
    options: [
      "household's attempts to change savings to encourage growth",
      "government's use of spending and taxing policies to influence aggregate demand and aggregate supply",
      "government's use of policy tools to influence the net export function, thereby influencing GDP",
      "business sector's influence on investment and GDP",
    ],
    answer: "government's use of spending and taxing policies to influence aggregate demand and aggregate supply",
    explanation: "Fiscal policy is precisely the government's deliberate use of spending and tax changes to influence the macroeconomy.",
  },
  {
    id: "econs-passco-25",
    section: "ad-as-inflation",
    question: "According to Keynes, the level of employment is determined by",
    options: ["the level of aggregate demand for goods and services", "price and wages", "flexible wages and prices", "interest rates"],
    answer: "the level of aggregate demand for goods and services",
    explanation: "Keynes's central departure from classical theory was arguing wages/prices are sticky, NOT freely flexible — so it's the level of aggregate demand, not wage/price flexibility, that determines employment. Don't confuse this with the classical view Keynes was arguing against (that flexible wages/prices clear the labour market).",
  },
  {
    id: "econs-passco-26",
    section: "national-income-gdp",
    question: "Gross domestic product measures",
    options: ["the total spending of everyone in the economy", "the total income of everyone in the economy", "the value of all output in the economy", "all of the above"],
    answer: "all of the above",
    explanation: "By the circular flow identity, total spending, total income, and the total value of output are all equal — GDP measures all three simultaneously, which is exactly the point this classic question tests.",
  },
  {
    id: "econs-passco-27",
    section: "national-income-gdp",
    code: "$Billions\nDurable goods 800\nNonresidential investment 400\nFederal purchases of goods 300\nExports 400\nState and local purchases of goods 200\nResidential investment 50\nServices 500\nImports 250\nChange in business inventories -25\nNondurable goods 700",
    question: "The value for gross private domestic investment in billions is",
    options: ["$300", "$375", "$425", "$450"],
    answer: "$425",
    explanation: "Gross private domestic investment = nonresidential investment + residential investment + change in business inventories = 400 + 50 + (−25) = $425bn.",
  },
  {
    id: "econs-passco-28",
    section: "national-income-gdp",
    code: "$Billions\nDepreciation 40\nReceipts of factor incomes from the rest of the world 30\nGovernment purchases 100\nImports 50\nPayments of factor income to the rest of the world 50\nNet private domestic investment 200\nPersonal income taxes 120\nPersonal consumption expenditures 600\nDividends 20\nExports 60\nAmount of national income not going to households 20",
    question: "The value of GDP in billions is",
    options: ["$910", "$920", "$950", "$1,050"],
    answer: "$950",
    explanation: "Gross private domestic investment = net investment + depreciation = 200+40 = 240. GDP = C + I(gross) + G + (X−M) = 600 + 240 + 100 + (60−50) = $950bn.",
  },
  {
    id: "econs-passco-29",
    section: "national-income-gdp",
    code: "Same table as the previous question.",
    question: "The value for GNP in billions is",
    options: ["$900", "$930", "$980", "$1,010"],
    answer: "$930",
    explanation: "GNP = GDP + net factor income from abroad = 950 + (30 − 50) = $930bn.",
  },
  {
    id: "econs-passco-30",
    section: "national-income-gdp",
    code: "Same table as the previous question.",
    question: "The value for NNP in billions is",
    options: ["$890", "$910", "$940", "$970"],
    answer: "$890",
    explanation: "NNP = GNP − depreciation = 930 − 40 = $890bn.",
  },
  {
    id: "econs-passco-31",
    section: "national-income-gdp",
    question: "Gross domestic product measured in terms of the prices of a fixed, or base, year is",
    options: ["real GDP", "base GDP", "current GDP", "nominal GDP"],
    answer: "real GDP",
    explanation: "Real GDP is exactly this: output valued at constant, base-year prices, so it isolates changes in quantity from changes in price.",
  },
  {
    id: "econs-passco-32",
    section: "macro-scope-cycle-growth",
    question: "Productivity is the ratio of",
    options: ["total output to the total population", "total capital to the total number of workers", "total output to the total number of unemployed", "total output to the total number of worker hours"],
    answer: "total output to the total number of worker hours",
    explanation: "Labour productivity is standardly defined as output per hour worked — output divided by total worker-hours.",
  },
  {
    id: "econs-passco-33",
    section: "national-income-gdp",
    question: "Nominal GDP is gross domestic product measured",
    options: [
      "as the difference between the current year's GDP and last year's GDP",
      "in the prices of a base year",
      "at a constant output level but at the base-year prices",
      "in current cedis",
    ],
    answer: "in current cedis",
    explanation: "Nominal GDP uses each year's own (current) prices — unlike real GDP, which fixes prices at a base year. Options b and c both actually describe real GDP.",
  },
  {
    id: "econs-passco-34",
    section: "consumption-multiplier-fiscal",
    question: "The MPS is",
    options: ["income divided by saving", "the change in saving divided by the change in income", "1 + MPC", "Total saving divided by total income"],
    answer: "the change in saving divided by the change in income",
    explanation: "MPS (marginal propensity to save) = ΔSaving / ΔIncome — how much of each EXTRA unit of income gets saved, not a total-saving ratio (that would be the average propensity to save).",
  },
  {
    id: "econs-passco-35",
    section: "consumption-multiplier-fiscal",
    question: "If the MPS is 0.60, MPC",
    options: ["is 0.40", "is 1.60", "is 0.30", "cannot be determined by the given information"],
    answer: "is 0.40",
    explanation: "MPC + MPS = 1, so MPC = 1 − 0.60 = 0.40.",
  },
  {
    id: "econs-passco-36",
    section: "national-income-gdp",
    question: "Which of the following is not considered investment?",
    options: ["The purchase of government bonds", "The increase in planned inventories", "The acquisition of capital goods", "The construction of a new factory"],
    answer: "The purchase of government bonds",
    explanation: "Buying a government bond is a financial asset transaction, not real investment. Real (economic) investment means adding to physical capital: new factories, capital goods, and inventory build-up all count; buying existing financial securities does not.",
  },
  {
    id: "econs-passco-37",
    section: "consumption-multiplier-fiscal",
    question: "In macroeconomics, equilibrium is defined as that point at which",
    options: [
      "planned aggregate expenditure equals aggregate output",
      "aggregate output equals consumption minus investment",
      "planned aggregate expenditure equals consumption",
      "saving equals consumption",
    ],
    answer: "planned aggregate expenditure equals aggregate output",
    explanation: "The basic Keynesian equilibrium condition is that what firms plan to sell (planned aggregate expenditure) matches what they actually produce (aggregate output) — no unplanned build-up or run-down of inventories.",
  },
  {
    id: "econs-passco-38",
    section: "consumption-multiplier-fiscal",
    code: "No government or foreign sector. Multiplier = 4.",
    question: "A $20 billion increase in investment will cause aggregate output to increase by",
    options: ["$40 billion", "$20 billion", "$80 billion", "$5 billion"],
    answer: "$80 billion",
    explanation: "Δoutput = multiplier × ΔI = 4 × $20bn = $80bn.",
  },
  {
    id: "econs-passco-39",
    section: "consumption-multiplier-fiscal",
    code: "C = 800 + 0.8Yd\nIncome (Y) = $2,000, net taxes = $500",
    question: "Consumption equals",
    options: ["2,000", "1,500", "2,050", "2,150"],
    answer: "2,000",
    explanation: "Disposable income Yd = Y − T = 2,000 − 500 = 1,500. C = 800 + 0.8×1,500 = 800 + 1,200 = 2,000.",
  },
  {
    id: "econs-passco-40",
    section: "macro-scope-cycle-growth",
    question: "Inflation tends to ______ during the expansion phase of the business cycle and _____ during the recession phase of the business cycle.",
    options: ["decrease; increase", "increase; decrease", "increase; increase further", "decrease; decrease further"],
    answer: "increase; decrease",
    explanation: "Rising demand during an expansion typically pushes prices up; weaker demand during a recession eases inflationary pressure.",
  },
  {
    id: "econs-passco-41",
    section: "macro-scope-cycle-growth",
    question: "During the expansion phase of the business cycle, which of the following eventually increases?",
    options: ["Employment", "Production", "Income", "All of the above"],
    answer: "All of the above",
    explanation: "An expansion lifts production, which raises employment and, in turn, incomes — all three move together during a genuine expansion.",
  },
  {
    id: "econs-passco-42",
    section: "money-banking",
    question: "Money functions as",
    options: ["store of value", "unit of account", "medium of exchange", "all of the above"],
    answer: "all of the above",
    explanation: "These are the three classic textbook functions of money, and money is defined by fulfilling all three simultaneously.",
  },
  {
    id: "econs-passco-43",
    section: "money-banking",
    question: "The largest component of the M1 money supply is",
    options: ["gold certificates", "checkable deposits", "currency", "time deposits"],
    answer: "checkable deposits",
    explanation: "Checkable (demand) deposits typically make up the largest share of M1, exceeding physical currency in circulation. Time deposits aren't part of M1 at all.",
  },
  {
    id: "econs-passco-44",
    section: "money-banking",
    question: "Coins held in commercial banks are",
    options: ["included in M1, but not M2", "included in both M1 and M2", "included in M2, but not M1", "not part of the nation's money supply"],
    answer: "not part of the nation's money supply",
    explanation: "Coins/currency sitting in bank vaults (vault cash/reserves) are excluded from both M1 and M2 to avoid double-counting — only currency actually in public circulation counts toward the money supply, not physical currency wherever it happens to sit.",
  },
  {
    id: "econs-passco-45",
    section: "money-banking",
    question: "The total demand for money will shift to the left as a result of",
    options: ["a decline in nominal GDP", "an increase in the price level", "a change in the interest rate", "an increase in nominal GDP"],
    answer: "a decline in nominal GDP",
    explanation: "Money demand is driven by the value of transactions people need to make. A decline in nominal GDP means fewer/smaller transactions, reducing money demand at every interest rate — shifting the whole curve left. (A change in the interest rate instead causes a movement ALONG the curve, not a shift.)",
  },
  {
    id: "econs-passco-46",
    section: "money-banking",
    question: "If the quantity of money demanded exceeds the quantity supplied,",
    options: ["the supply of money curve will shift to the left", "the demand for money curve will shift to the right", "the interest rate will rise", "the interest rate will fall"],
    answer: "the interest rate will rise",
    explanation: "Just like any market, excess demand for money (holding the supply fixed) pushes its \"price\" — the interest rate — upward until the market clears.",
  },
  {
    id: "econs-passco-47",
    section: "money-banking",
    question: "Which of the following statement is correct?",
    options: [
      "Interest rates and bond prices vary directly",
      "Interest rates and bond prices vary indirectly",
      "Interest rates and bond prices are unrelated",
      "Interest rates and bond prices vary directly during inflation and inversely during recession",
    ],
    answer: "Interest rates and bond prices vary indirectly",
    explanation: "Bond prices and interest rates move inversely: when interest rates rise, the fixed payments of existing bonds become less attractive, so their market price falls, and vice versa.",
  },
  {
    id: "econs-passco-48",
    section: "money-banking",
    question: "Other things equal, if there is an increase in nominal GDP,",
    options: ["the demand for money will decrease", "the interest rate will rise", "bond prices will rise", "consumption spending will fall"],
    answer: "the interest rate will rise",
    explanation: "Higher nominal GDP raises money demand (more transactions to finance), pushing the interest rate up — and, following the inverse relationship from the previous question, that means bond prices FALL, not rise.",
  },
  {
    id: "econs-passco-49",
    section: "monetary-fiscal-policy-tools",
    question: "The main tools of monetary policy are",
    options: [
      "tax rate changes, the discount rate, and open-market operations",
      "tax rate changes, changes in government expenditures, and open-market operations",
      "the discount rate, the reserve ratio, and open-market operations",
      "changes in government expenditures, the reserve ratio, and the discount rate",
    ],
    answer: "the discount rate, the reserve ratio, and open-market operations",
    explanation: "These three are the classic monetary-policy tools; tax rates and government expenditure belong to fiscal policy, not monetary policy.",
  },
  {
    id: "econs-passco-50",
    section: "monetary-fiscal-policy-tools",
    question: "The purchase of government securities from the public by the Central Bank will cause",
    options: ["commercial bank reserves to decrease", "the money supply to increase", "demand deposits to decrease", "the interest rate to increase"],
    answer: "the money supply to increase",
    explanation: "An open-market purchase injects new reserves into the banking system, which commercial banks can lend out, expanding the money supply.",
  },
  {
    id: "econs-passco-51",
    section: "ad-as-inflation",
    question: "Which of the following explains why the aggregate demand schedule is downward sloping?",
    options: ["The real-balance effect", "The interest rate effect", "The foreign purchases effect", "All of the above"],
    answer: "All of the above",
    explanation: "All three effects independently make lower price levels correspond to higher real spending, together explaining AD's downward slope.",
  },
  {
    id: "econs-passco-52",
    section: "ad-as-inflation",
    question: "The economy's long-run aggregate supply curve",
    options: ["slopes downward and to the right", "is vertical", "is horizontal", "slopes upward and to the right"],
    answer: "is vertical",
    explanation: "In the long run, output is determined by the economy's real productive capacity (potential output), not the price level — hence a vertical LRAS at potential output.",
  },
  {
    id: "econs-passco-53",
    section: "monetary-fiscal-policy-tools",
    question: "An appropriate fiscal policy for a severe recession would be",
    options: ["a decrease in government spending", "a decrease in tax rates", "appreciation of the cedi", "an increase in interest rates"],
    answer: "a decrease in tax rates",
    explanation: "Expansionary fiscal policy — cutting taxes (or raising spending) — is the standard textbook response to boost aggregate demand during a severe recession.",
  },
  {
    id: "econs-passco-54",
    section: "monetary-fiscal-policy-tools",
    code: "MPS = 0.1 (1/10)",
    question: "Government could shift the aggregate demand curve rightward by $40 billion by",
    options: [
      "increasing government spending by $4 billion",
      "increasing government spending by $40 billion",
      "decreasing taxes by $4 billion",
      "increasing taxes by $4 billion",
    ],
    answer: "increasing government spending by $4 billion",
    explanation: "Multiplier = 1/MPS = 1/0.1 = 10. To shift AD by $40bn via government spending directly (which enters AD with the full multiplier), only $40bn/10 = $4bn of new spending is needed.",
  },
  {
    id: "econs-passco-55",
    section: "macro-scope-cycle-growth",
    question: "Periods in which output and employment are falling are known as",
    options: ["recessions", "booms", "expansions", "deflations"],
    answer: "recessions",
    explanation: "Falling output and employment together define a recession.",
  },
  {
    id: "econs-passco-56",
    section: "macro-scope-cycle-growth",
    question: "A business cycle is",
    options: [
      "a very deep and prolonged economic downturn",
      "a period in which output and employment are rising",
      "a period in which output and employment are falling",
      "a short-run alternation between economic upturns and downturns",
    ],
    answer: "a short-run alternation between economic upturns and downturns",
    explanation: "The business cycle is the repeating pattern of expansions and contractions, not any single phase or a specific deep downturn (that would describe a depression).",
  },
  {
    id: "econs-passco-57",
    section: "macro-scope-cycle-growth",
    question: "A recession leads to all of the following except",
    options: ["higher unemployment", "reduced output", "reduced income and living standards", "higher employment"],
    answer: "higher employment",
    explanation: "A recession causes higher unemployment (lower employment), not higher employment — that's the one outcome that doesn't fit.",
  },
  {
    id: "econs-passco-58",
    section: "monetary-fiscal-policy-tools",
    question: "Fiscal policy attempts to stabilise the economy by changes in",
    options: ["the interest rate", "the money supply", "banking regulations", "taxes and spending"],
    answer: "taxes and spending",
    explanation: "Fiscal policy works through the government's own budget levers — taxation and spending — not interest rates or the money supply (which are monetary policy tools).",
  },
  {
    id: "econs-passco-59",
    section: "ad-as-inflation",
    question: "Which of the following would likely cause the short-run aggregate supply curve to shift to the left?",
    options: ["a decrease in consumer spending", "a decrease in the price of imported oil", "an increase in the price of imported oil", "an increase in consumer spending"],
    answer: "an increase in the price of imported oil",
    explanation: "A rise in a key input cost (like imported oil) raises production costs economy-wide, shifting SRAS left. Consumer spending changes affect AD, not AS.",
  },
  {
    id: "econs-passco-60",
    section: "ad-as-inflation",
    question: "The total demand for goods and services in an economy is known as",
    options: ["economy-wide demand", "gross national product", "national demand", "aggregate demand"],
    answer: "aggregate demand",
    explanation: "Same concept as before — aggregate demand is the standard term.",
  },
  {
    id: "econs-passco-61",
    section: "consumption-multiplier-fiscal",
    code: "MPC = 0.8",
    question: "The simple multiplier is",
    options: ["0.25", "2.00", "4.00", "none of the above"],
    answer: "none of the above",
    explanation: "Multiplier = 1/(1−0.8) = 1/0.2 = 5.00, which doesn't match any of the first three options — a good reminder to actually compute it rather than pattern-match to a listed value.",
  },
  {
    id: "econs-passco-62",
    section: "monetary-fiscal-policy-tools",
    question: "Expansionary policies are policies",
    options: [
      "that aim to reduce the level of GDP",
      "taken to move the economy away from potential output",
      "that aim to increase the level of GDP",
      "aimed at dampening booms",
    ],
    answer: "that aim to increase the level of GDP",
    explanation: "\"Expansionary\" describes any policy (fiscal or monetary) intended to boost aggregate demand and raise GDP — the opposite of a contractionary policy.",
  },
  {
    id: "econs-passco-63",
    section: "monetary-fiscal-policy-tools",
    question: "Policies taken to move the economy closer to potential output are called",
    options: ["stabilisation policies", "policies with inside lags", "expansionary policies only", "contractionary policies only"],
    answer: "stabilisation policies",
    explanation: "\"Stabilisation policy\" is the general umbrella term, since closing the gap to potential output might require EITHER expansionary policy (below potential) OR contractionary policy (above potential, overheating).",
  },
  {
    id: "econs-passco-64",
    section: "monetary-fiscal-policy-tools",
    question: "In order to increase the aggregate demand curve, a government must _____ spending and _____ taxation.",
    options: ["decrease, decrease", "decrease, increase", "increase, decrease", "increase, increase"],
    answer: "increase, decrease",
    explanation: "Expansionary fiscal policy means MORE government spending and LESS taxation — both push aggregate demand up.",
  },
  {
    id: "econs-passco-65",
    section: "monetary-fiscal-policy-tools",
    question: "A government budget deficit is when the government spends _____ than it collects in taxes.",
    options: ["all of its money", "more", "the same amount", "less"],
    answer: "more",
    explanation: "A deficit is definitionally spending exceeding tax revenue for the period.",
  },
  {
    id: "econs-passco-66",
    section: "consumption-multiplier-fiscal",
    code: "C = 25 + 0.9Y",
    question: "The level of autonomous consumption is",
    options: ["25.9", "25", "0.1", "0.9"],
    answer: "25",
    explanation: "Autonomous consumption is the constant/intercept term — the amount consumed even at zero income — which is 25 here.",
  },
  {
    id: "econs-passco-67",
    section: "consumption-multiplier-fiscal",
    question: "The sum of marginal propensity to consume (MPC) and the marginal propensity to save (MPS) is",
    options: ["less than one", "negative", "greater than one", "equal to one"],
    answer: "equal to one",
    explanation: "Every extra unit of income is either consumed or saved, so MPC + MPS always equals exactly 1.",
  },
  {
    id: "econs-passco-68",
    section: "money-banking",
    question: "The supply of money in the economy is determined primarily by",
    options: ["the banking system", "the actions of the central bank", "consumers", "both A and B"],
    answer: "both A and B",
    explanation: "The money supply emerges from the interaction between central-bank actions (reserves, policy rate) and the commercial banking system's lending behaviour (the money multiplier) — neither alone tells the whole story.",
  },
  {
    id: "econs-passco-69",
    section: "money-banking",
    question: "When money is accepted as payment for a good or service, it is being used as a",
    options: ["medium of exchange", "a mechanism for transforming current purchases into future purchases", "store of value", "unit of account"],
    answer: "medium of exchange",
    explanation: "Being accepted directly in exchange for goods/services is the medium-of-exchange function specifically.",
  },
  {
    id: "econs-passco-70",
    section: "money-banking",
    question: "If money is used as a mechanism to hold purchasing power for a period of time, it is functioning as a",
    options: ["unit of account", "store of value", "standard of value", "medium of exchange"],
    answer: "store of value",
    explanation: "Holding purchasing power over time is precisely the store-of-value function.",
  },
  {
    id: "econs-passco-71",
    section: "monetary-fiscal-policy-tools",
    question: "The most commonly used tool in monetary policy is",
    options: ["changes in the discount rate", "open market operations", "changes in required reserve ratios", "express lending transactions"],
    answer: "open market operations",
    explanation: "Open market operations (buying/selling government securities) are used far more routinely than discount-rate or reserve-ratio changes, which are blunter and less frequently adjusted tools.",
  },
  {
    id: "econs-passco-72",
    section: "money-banking",
    question: "An increase in the level of real GDP in the economy leads to",
    options: [
      "a rightward shift in the demand for money curve",
      "a leftward movement along the demand for money curve",
      "a leftward shift in the demand for money curve",
      "a rightward movement along the demand for money curve",
    ],
    answer: "a rightward shift in the demand for money curve",
    explanation: "Since the money-demand curve is drawn against the interest rate, a change in income (not the interest rate) shifts the whole curve — higher real GDP means more transactions demand for money at every interest rate, i.e. a rightward shift.",
  },
  {
    id: "econs-passco-73",
    section: "money-banking",
    question: "Based on the model of the money market, when real income decreases, the equilibrium interest rate should",
    options: ["decrease", "stay the same", "increase", "increase to the same extent that the supply of money increases"],
    answer: "decrease",
    explanation: "Lower real income reduces money demand; with the money supply unchanged, the equilibrium interest rate falls to the new lower demand.",
  },
  {
    id: "econs-passco-74",
    section: "national-income-gdp",
    question: "All of the following are government expenditure items except",
    options: ["interest on government debt", "transfer payment", "purchase of corporate bonds", "purchase of goods and services"],
    answer: "transfer payment",
    explanation: "Same reasoning as the earlier version of this question: transfer payments don't correspond to current production and are excluded from GDP-relevant government spending.",
  },
  {
    id: "econs-passco-75",
    section: "monetary-fiscal-policy-tools",
    question: "If the Central Bank sells a significant amount of government securities in the open market, which of the following will occur?",
    options: [
      "The total amount of loans made by commercial banks will decrease",
      "The total amount of loans made by commercial banks will increase",
      "The money supply will increase",
      "Rates of interest will decrease",
    ],
    answer: "The total amount of loans made by commercial banks will decrease",
    explanation: "Selling securities withdraws reserves from the banking system, which contracts banks' capacity to lend — the opposite of an open-market purchase.",
  },
  {
    id: "econs-passco-76",
    section: "macro-scope-cycle-growth",
    question: "Which of the following will most likely occur as a result of an increase in labour productivity in an economy?",
    options: [
      "An increase in output and a decrease in inflation",
      "An increase in interest rates and a decrease in investment",
      "A decrease in both money demand and money supply",
      "A decrease in exports and an increase in unemployment",
    ],
    answer: "An increase in output and a decrease in inflation",
    explanation: "Higher productivity shifts aggregate supply to the right, allowing more output to be produced at a given (or lower) price level — raising output and easing inflationary pressure.",
  },
  {
    id: "econs-passco-77",
    section: "ad-as-inflation",
    question: "On a short-run Phillips curve, high rates of inflation coincide with",
    options: ["high interest rates", "low interest rates", "high unemployment rates", "low unemployment"],
    answer: "low unemployment",
    explanation: "The classic short-run Phillips curve trade-off: high inflation tends to coincide with low unemployment, and vice versa.",
  },
  {
    id: "econs-passco-78",
    section: "ad-as-inflation",
    question: "An increase in which of the following would cause an increase in aggregate supply?",
    options: ["Labour productivity", "The wage rate", "Prices of imports", "Consumer spending"],
    answer: "Labour productivity",
    explanation: "Higher productivity lowers the cost of producing each unit of output, increasing aggregate supply. A higher wage rate or import prices would instead decrease AS (raise costs), and consumer spending affects AD, not AS.",
  },
];
