export type ExamTopic =
  | "fundamentals-control-flow"
  | "functions"
  | "pointers-references"
  | "memory"
  | "arrays-strings"
  | "structs-enums"
  | "oop-core"
  | "inheritance-polymorphism"
  | "stl"
  | "exceptions";

export type QuestionType = "concept" | "code-analysis" | "debugging" | "best-practice";

export interface ExamQuestion {
  id: string;
  topic: ExamTopic;
  subtopic: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  type: QuestionType;
  code?: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  misconception?: string;
  relatedPartId: string;
}

export const EXAM_TOPICS: { id: ExamTopic; label: string }[] = [
  { id: "fundamentals-control-flow", label: "Fundamentals & Control Flow" },
  { id: "functions", label: "Functions" },
  { id: "pointers-references", label: "Pointers & References" },
  { id: "memory", label: "Memory (Stack, Heap, Leaks)" },
  { id: "arrays-strings", label: "Arrays & Strings" },
  { id: "structs-enums", label: "Structs & Enums" },
  { id: "oop-core", label: "OOP Core (Classes, Encapsulation)" },
  { id: "inheritance-polymorphism", label: "Inheritance & Polymorphism" },
  { id: "stl", label: "STL Containers & Algorithms" },
  { id: "exceptions", label: "Exception Handling" },
];

export const examBank: ExamQuestion[] = [
  // ---------- Fundamentals & Control Flow (10) ----------
  {
    id: "exam-1",
    topic: "fundamentals-control-flow",
    subtopic: "Comments",
    difficulty: 1,
    type: "concept",
    question: "Which of these is a valid single-line comment in C++?",
    options: ["# comment", "// comment", "<!-- comment -->", "' comment"],
    correctIndex: 1,
    explanation:
      "// starts a single-line comment in C++. # marks a preprocessor directive (like #include), <!-- --> is HTML syntax, and ' is not a comment marker in C++.",
    misconception: "Confusing the preprocessor directive marker # with a comment marker.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-2",
    topic: "fundamentals-control-flow",
    subtopic: "Program entry point",
    difficulty: 1,
    type: "concept",
    question: "Which is the correct entry-point signature for a standard C++ program?",
    options: ["void main()", "int main()", "main() void", "int Main()"],
    correctIndex: 1,
    explanation:
      "int main() is the standard entry point. void main() is non-standard, and C++ is case-sensitive so Main() would just be an unrelated function.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-3",
    topic: "fundamentals-control-flow",
    subtopic: "Primitive types",
    difficulty: 2,
    type: "concept",
    question: "Which type would you use to store a single character in standard C++?",
    options: ["string", "char", "int", "bool"],
    correctIndex: 1,
    explanation: "char stores one character. std::string stores a sequence of characters.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-4",
    topic: "fundamentals-control-flow",
    subtopic: "Integer division",
    difficulty: 2,
    type: "code-analysis",
    code: "int x = 7 / 2;\nstd::cout << x;",
    question: "What does this print?",
    options: ["3.5", "3", "4", "Compile error"],
    correctIndex: 1,
    explanation:
      "7 and 2 are both int, so / performs integer division and truncates toward zero, giving 3 — not 3.5.",
    misconception: "Expecting integer division to produce a fractional result automatically.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-5",
    topic: "fundamentals-control-flow",
    subtopic: "Operators",
    difficulty: 2,
    type: "concept",
    question: "What does the % (modulus) operator compute?",
    options: ["The quotient of a division", "The remainder after integer division", "A floating-point division", "A bitwise complement"],
    correctIndex: 1,
    explanation: "% returns the remainder left over after dividing the left operand by the right one.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-6",
    topic: "fundamentals-control-flow",
    subtopic: "while loops",
    difficulty: 3,
    type: "code-analysis",
    code: "int i = 0;\nwhile (i < 3) {\n    std::cout << i;\n    i++;\n}",
    question: "What does this print?",
    options: ["012", "0123", "123", "Infinite loop"],
    correctIndex: 0,
    explanation: "i is printed while it is 0, 1, then 2; once i becomes 3 the condition i < 3 fails and the loop stops.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-7",
    topic: "fundamentals-control-flow",
    subtopic: "for loops",
    difficulty: 3,
    type: "code-analysis",
    code: 'for (int i = 0; i < 5; i += 2) std::cout << i << " ";',
    question: "What does this print?",
    options: ["0 1 2 3 4", "0 2 4", "0 2 4 6 8", "1 3 5"],
    correctIndex: 1,
    explanation: "i starts at 0 and increases by 2 each iteration (0, 2, 4); at i=6 the condition i<5 fails, so the loop stops after printing 4.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-8",
    topic: "fundamentals-control-flow",
    subtopic: "do-while vs while",
    difficulty: 3,
    type: "concept",
    question: "A do-while loop's body runs, at minimum, how many times compared to a while loop with the same false-from-the-start condition?",
    options: ["Zero times, same as while", "At least once, since the condition is checked after the body runs", "Exactly twice always", "Only if the condition is true first"],
    correctIndex: 1,
    explanation: "do-while checks its condition after executing the body, so the body always runs at least once — even if the condition is false from the start, unlike a plain while loop.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-9",
    topic: "fundamentals-control-flow",
    subtopic: "Assignment vs equality",
    difficulty: 4,
    type: "debugging",
    code: "int x = 3;\nif (x = 5) {\n    std::cout << \"yes\";\n}",
    question: "What is actually wrong with this code (it compiles)?",
    options: [
      "Nothing — this checks whether x equals 5",
      "x = 5 is an assignment, not a comparison; it sets x to 5 and the condition is always true because 5 is nonzero (the intent was x == 5)",
      "This is a compile error: you cannot assign inside an if",
      "if conditions can only contain boolean variables",
    ],
    correctIndex: 1,
    explanation:
      "= is assignment, == is comparison. if (x = 5) assigns 5 to x and then evaluates that assignment's result (5, which is truthy), so the branch always runs — a classic and very common bug.",
    misconception: "Confusing = (assignment) with == (equality comparison) inside a condition.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-10",
    topic: "fundamentals-control-flow",
    subtopic: "switch fallthrough",
    difficulty: 5,
    type: "code-analysis",
    code:
      'int x = 2;\nswitch (x) {\n    case 1: std::cout << "one ";\n    case 2: std::cout << "two ";\n    case 3: std::cout << "three "; break;\n    default: std::cout << "other";\n}',
    question: "What does this print?",
    options: ['"two "', '"two three "', '"one two three "', '"other"'],
    correctIndex: 1,
    explanation:
      "Execution jumps to case 2 (matching x), then falls through into case 3 because there is no break after case 2 — printing \"two three \" before the break stops it.",
    misconception: "Forgetting that C++ switch statements fall through to the next case unless a break is present.",
    relatedPartId: "part-0",
  },

  // ---------- Functions (10) ----------
  {
    id: "exam-11",
    topic: "functions",
    subtopic: "Return types",
    difficulty: 1,
    type: "concept",
    question: "What must every C++ function specify, even one that returns nothing?",
    options: ["A return type (void if it returns nothing)", "A name for every parameter", "A default argument", "That it returns a pointer"],
    correctIndex: 0,
    explanation: "Every function needs a return type; void explicitly means \"returns nothing.\" Parameter names and default arguments are optional.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-12",
    topic: "functions",
    subtopic: "Declarations",
    difficulty: 1,
    type: "concept",
    question: "What is a function prototype (forward declaration) mainly used for?",
    options: ["To define the function's body", "To tell the compiler the function's signature before its full definition appears later", "To allocate memory for the function", "To import the function from another program automatically"],
    correctIndex: 1,
    explanation: "A prototype lets code earlier in the file call a function whose full body is defined later (or in another file), by declaring its signature up front.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-13",
    topic: "functions",
    subtopic: "Basic calls",
    difficulty: 2,
    type: "code-analysis",
    code: "int square(int n) { return n * n; }\nint main() { std::cout << square(4); }",
    question: "What does this print?",
    options: ["8", "16", "4", "Compile error"],
    correctIndex: 1,
    explanation: "square(4) returns 4 * 4 = 16.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-14",
    topic: "functions",
    subtopic: "Pass by value",
    difficulty: 2,
    type: "concept",
    question: "Which best describes \"pass by value\"?",
    options: ["The function receives the original variable and can modify it", "The function receives a copy of the argument; changes inside it don't affect the caller's variable", "The function automatically receives a pointer", "The argument is always passed by reference unless marked const"],
    correctIndex: 1,
    explanation: "By value means a copy is made for the parameter; modifying the parameter inside the function has no effect on the caller's original variable.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-15",
    topic: "functions",
    subtopic: "Default arguments",
    difficulty: 3,
    type: "concept",
    question: 'Given void greet(std::string name = "friend");, which calls are valid?',
    options: ['Both greet(); and greet("Ama");', 'Only greet("Ama");', "Only greet();", "Neither compiles"],
    correctIndex: 0,
    explanation: "A default argument makes the parameter optional — the function can be called with or without supplying it.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-16",
    topic: "functions",
    subtopic: "Overload ambiguity",
    difficulty: 3,
    type: "debugging",
    code: "void f(int a, int b = 2);\nvoid f(int a);\n\nint main() { f(5); }",
    question: "What happens when f(5) is called here?",
    options: ["Compile error: the call is ambiguous between the two overloads", "Calls void f(int a)", "Calls void f(int a, int b = 2) using b = 2", "Undefined behavior"],
    correctIndex: 0,
    explanation: "Both overloads can satisfy f(5) equally well (one directly, one via its default argument), so the compiler cannot pick one — this is a genuine ambiguous-call error.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-17",
    topic: "functions",
    subtopic: "Recursion",
    difficulty: 3,
    type: "code-analysis",
    code: "int fact(int n) {\n    if (n <= 1) return 1;\n    return n * fact(n - 1);\n}",
    question: "What is fact(4)?",
    options: ["24", "12", "4", "10"],
    correctIndex: 0,
    explanation: "fact(4) = 4 * 3 * 2 * 1 = 24, unwinding from the base case fact(1) = 1.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-18",
    topic: "functions",
    subtopic: "Reference parameters",
    difficulty: 4,
    type: "code-analysis",
    code: "void increment(int &x) { x++; }\nint main() { int a = 5; increment(a); std::cout << a; }",
    question: "What does this print?",
    options: ["5", "6", "Compile error", "Undefined behavior"],
    correctIndex: 1,
    explanation: "x is a reference parameter, so it refers to a directly — incrementing x inside the function changes a itself, printing 6.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-19",
    topic: "functions",
    subtopic: "Recursion",
    difficulty: 4,
    type: "code-analysis",
    code: "int mystery(int n) {\n    if (n == 0) return 0;\n    return n + mystery(n - 1);\n}",
    question: "What is mystery(4)?",
    options: ["10", "4", "24", "0"],
    correctIndex: 0,
    explanation: "mystery(4) = 4 + 3 + 2 + 1 + 0 = 10, summing down to the base case.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-20",
    topic: "functions",
    subtopic: "Dangling references",
    difficulty: 5,
    type: "debugging",
    code: "int& bad() {\n    int x = 42;\n    return x;\n}",
    question: "What is wrong with this function?",
    options: ["Nothing — it safely returns 42", "It returns a reference to a local variable that is destroyed when the function returns — using the result is undefined behavior (most compilers warn about this)", "It fails to compile", "It always returns 0"],
    correctIndex: 1,
    explanation: "x lives on the stack and is destroyed the instant bad() returns; the returned reference dangles. Compilers typically emit a warning, but it still compiles — the danger is at runtime.",
    misconception: "Assuming returning by reference is just as safe as returning by value, regardless of what's being referenced.",
    relatedPartId: "part-1",
  },

  // ---------- Pointers & References (12) ----------
  {
    id: "exam-21",
    topic: "pointers-references",
    subtopic: "Address-of operator",
    difficulty: 1,
    type: "concept",
    question: "When applied to a variable (not in a declaration), what does the & operator do?",
    options: ["Dereferences a pointer", "Returns the memory address of the variable", "Declares a reference", "Always performs a bitwise AND"],
    correctIndex: 1,
    explanation: "As a unary operator applied to a variable, & (address-of) yields the variable's memory address.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-22",
    topic: "pointers-references",
    subtopic: "Dereference operator",
    difficulty: 1,
    type: "concept",
    question: "When applied to a pointer variable, what does the * operator (dereference) do?",
    options: ["Multiplies the pointer by a number", "Declares a new pointer", "Accesses the value stored at the address the pointer holds", "Deletes the pointer"],
    correctIndex: 2,
    explanation: "Dereferencing (*p) gives you the value stored at the address p holds, letting you read or modify it.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-23",
    topic: "pointers-references",
    subtopic: "Modifying through a pointer",
    difficulty: 2,
    type: "code-analysis",
    code: "int x = 10;\nint *p = &x;\n*p = 20;\nstd::cout << x;",
    question: "What does this print?",
    options: ["10", "20", "The address of x", "Compile error"],
    correctIndex: 1,
    explanation: "*p = 20 writes through the pointer into x itself, so x becomes 20.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-24",
    topic: "pointers-references",
    subtopic: "Reference rebinding",
    difficulty: 2,
    type: "concept",
    question: "Once a reference is bound to a variable at declaration, can it later be made to refer to a different variable?",
    options: ["Yes, at any time", "No — a reference must be initialized when declared and always refers to that same variable", "Only if declared const", "Only inside a loop body"],
    correctIndex: 1,
    explanation: "Unlike a pointer, a reference cannot be rebound after initialization — it is permanently an alias for the variable it was bound to.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-25",
    topic: "pointers-references",
    subtopic: "Uninitialized pointers",
    difficulty: 3,
    type: "concept",
    question: "What is the value of a local pointer that is declared but not initialized?",
    options: ["Always nullptr", "Always 0", "An indeterminate, garbage address", "It's a compile error to leave a pointer uninitialized"],
    correctIndex: 2,
    explanation: "An uninitialized local pointer holds whatever garbage was already in that memory — it is not automatically set to nullptr.",
    misconception: "Assuming pointers are automatically null-initialized the way some other languages initialize references.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-26",
    topic: "pointers-references",
    subtopic: "Pointer arithmetic",
    difficulty: 3,
    type: "code-analysis",
    code: "int arr[5] = {10, 20, 30, 40, 50};\nint *p = arr;\nstd::cout << *(p + 2);",
    question: "What does this print?",
    options: ["10", "20", "30", "2"],
    correctIndex: 2,
    explanation: "p points to arr[0]; p + 2 advances two int-sized steps to arr[2], which holds 30.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-27",
    topic: "pointers-references",
    subtopic: "Null dereference",
    difficulty: 3,
    type: "debugging",
    code: "int *p = nullptr;\nstd::cout << *p;",
    question: "What happens when this runs?",
    options: ["Prints 0", "Compiles and runs fine, printing garbage", "Undefined behavior — typically a crash (segmentation fault)", "Compile error"],
    correctIndex: 2,
    explanation: "Dereferencing a null pointer is undefined behavior; in practice it usually crashes the program (segmentation fault) rather than printing anything meaningful.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-28",
    topic: "pointers-references",
    subtopic: "References vs pointers",
    difficulty: 4,
    type: "concept",
    question: "Which statement about references, compared to pointers, is true?",
    options: ["A reference can be null", "A reference must be initialized when declared and cannot later be made to refer to nothing", "A reference occupies a completely different kind of memory than pointers", "A reference supports pointer arithmetic like p++"],
    correctIndex: 1,
    explanation: "References must always refer to something valid from the moment they're created and can't be null or rebound — unlike pointers.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-29",
    topic: "pointers-references",
    subtopic: "Pointer to pointer",
    difficulty: 4,
    type: "code-analysis",
    code: "int x = 5;\nint *p = &x;\nint **pp = &p;\nstd::cout << **pp;",
    question: "What does this print?",
    options: ["5", "The address of x", "The address of p", "Compile error"],
    correctIndex: 0,
    explanation: "pp points to p; *pp gives p (the address of x); **pp dereferences that again, giving x's value, 5.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-30",
    topic: "pointers-references",
    subtopic: "Dangling pointers",
    difficulty: 4,
    type: "debugging",
    code: "int* makeDangling() {\n    int local = 99;\n    int* p = &local;\n    return p;\n}",
    question: "What is the problem with the pointer this function returns?",
    options: ["Nothing — p safely points to 99 forever", "p becomes a dangling pointer once local goes out of scope; dereferencing the returned pointer is undefined behavior", "This is a compile error", "local is automatically moved to the heap"],
    correctIndex: 1,
    explanation: "local lives on the stack and is destroyed when makeDangling() returns. The returned pointer still holds that now-invalid address — a classic dangling pointer.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-31",
    topic: "pointers-references",
    subtopic: "const with pointers",
    difficulty: 5,
    type: "concept",
    question: "Which declaration means \"p is a constant pointer to a non-const int\" — p itself can never be reassigned, but *p can be modified?",
    options: ["const int *p;", "int *const p;", "const int *const p;", "int const p;"],
    correctIndex: 1,
    explanation: "int *const p reads right-to-left from p: p is a const pointer to int. const int *p is the opposite — a pointer to a const int (the pointed-to value can't change, but p can be reassigned).",
    misconception: "Mixing up 'pointer to const' and 'const pointer' because the const keyword's position is subtle.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-32",
    topic: "pointers-references",
    subtopic: "Why containers return references",
    difficulty: 5,
    type: "best-practice",
    question: "Why do container types (like std::vector) return a reference (T&) from operator[] instead of a copy?",
    options: ["So the caller can modify the element in place, e.g. v[0] = 5;, rather than modifying a throwaway copy", "Because copying is illegal in C++", "To make the container immutable", "It's just a naming convention with no real effect"],
    correctIndex: 0,
    explanation: "Returning a reference lets v[0] = 5; actually write into the container's real storage. If it returned a copy, that assignment would silently modify a temporary and have no visible effect.",
    relatedPartId: "part-1",
  },

  // ---------- Memory (12) ----------
  {
    id: "exam-33",
    topic: "memory",
    subtopic: "Stack basics",
    difficulty: 1,
    type: "concept",
    question: "Where are local (automatic) variables typically stored?",
    options: ["The heap", "The stack", "The static/global data segment", "CPU registers only"],
    correctIndex: 1,
    explanation: "Local variables live on the call stack, allocated when their scope is entered and freed automatically when it's left.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-34",
    topic: "memory",
    subtopic: "Dynamic allocation",
    difficulty: 1,
    type: "concept",
    question: "Which operator allocates memory dynamically on the heap in idiomatic C++?",
    options: ["malloc only", "new", "alloc", "heap()"],
    correctIndex: 1,
    explanation: "new is the idiomatic C++ operator for heap allocation (malloc is inherited from C and doesn't run constructors).",
    relatedPartId: "part-1",
  },
  {
    id: "exam-35",
    topic: "memory",
    subtopic: "Stack lifetime",
    difficulty: 2,
    type: "concept",
    question: "What happens to a function's stack memory when it returns?",
    options: ["It stays allocated until the program ends", "It is automatically reclaimed", "The programmer must free it manually", "It is moved to the heap"],
    correctIndex: 1,
    explanation: "Stack memory is reclaimed automatically the moment its scope ends — no manual cleanup is needed, unlike heap memory.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-36",
    topic: "memory",
    subtopic: "Use-after-free",
    difficulty: 2,
    type: "debugging",
    code: "int *p = new int(5);\ndelete p;\nstd::cout << *p;",
    question: "What is wrong with this code?",
    options: ["Nothing, it prints 5", "It's undefined behavior — p is a dangling pointer after delete, so dereferencing it is invalid", "It prints 0 safely", "Compile error"],
    correctIndex: 1,
    explanation: "delete frees the memory but does not change p itself — p still holds the old address, now dangling. Using *p afterward is undefined behavior.",
    misconception: "Assuming delete automatically sets the pointer to nullptr.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-37",
    topic: "memory",
    subtopic: "Memory leaks",
    difficulty: 3,
    type: "concept",
    question: "What is a memory leak?",
    options: ["Memory that was never allocated", "Heap memory allocated with new but never freed with delete, and no longer reachable to be freed later", "A crash caused by deep recursion", "The stack running out of space"],
    correctIndex: 1,
    explanation: "A leak is heap memory that stays reserved because nothing ever calls delete on it, and the program has lost any way to reach it and free it.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-38",
    topic: "memory",
    subtopic: "Memory leaks",
    difficulty: 3,
    type: "debugging",
    code: "void leak() {\n    int *p = new int(10);\n} // p goes out of scope here",
    question: "What happens when leak() returns?",
    options: ["The heap memory is freed automatically since p is local", "The pointer variable p is destroyed, but the heap memory it pointed to is NOT freed — it's leaked", "Compile error", "10 is printed"],
    correctIndex: 1,
    explanation: "Only p (the local pointer variable) is destroyed automatically. The int it pointed to on the heap is never delete'd, so that memory is leaked.",
    misconception: "Confusing 'the pointer variable is destroyed' with 'the memory it points to is freed.'",
    relatedPartId: "part-1",
  },
  {
    id: "exam-39",
    topic: "memory",
    subtopic: "Double free",
    difficulty: 3,
    type: "debugging",
    code: "int *p = new int(5);\ndelete p;\ndelete p;",
    question: "What is wrong with deleting p twice like this?",
    options: ["Nothing, the second delete safely does nothing", "It's undefined behavior — a double free — which can corrupt the heap or crash the program", "Compile error", "It automatically reallocates memory"],
    correctIndex: 1,
    explanation: "Deleting the same pointer twice is undefined behavior; it does not safely no-op like some might assume.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-40",
    topic: "memory",
    subtopic: "new[] / delete[] mismatch",
    difficulty: 4,
    type: "debugging",
    code: "int *arr = new int[10];\ndelete arr; // should be delete[] arr;",
    question: "What is wrong here?",
    options: ["Nothing, delete and delete[] are interchangeable", "Undefined behavior — an array allocated with new[] must be freed with delete[], not delete", "Compile error", "This correctly frees all 10 ints"],
    correctIndex: 1,
    explanation: "new[] and delete[] must be paired; mismatching them (using plain delete on an array) is undefined behavior.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-41",
    topic: "memory",
    subtopic: "Stack overflow",
    difficulty: 4,
    type: "concept",
    question: "What commonly causes a \"stack overflow\" at runtime?",
    options: ["Allocating too much heap memory with new", "Deep or infinite recursion consuming all available stack space", "Forgetting to call delete", "Declaring too many global variables"],
    correctIndex: 1,
    explanation: "Each recursive call adds a new stack frame; without a base case (or with too much depth), the stack's limited space is exhausted.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-42",
    topic: "memory",
    subtopic: "Stack vs heap lifetime",
    difficulty: 4,
    type: "code-analysis",
    question: "Assuming its pointer is returned out of the creating function, which of these objects can still be validly used afterward?",
    options: ["A local stack variable (int x;)", "A heap allocation (int *p = new int(5);)", "Both, equally", "Neither"],
    correctIndex: 1,
    explanation: "Heap memory outlives the function that created it — it stays valid until explicitly deleted. A local stack variable is destroyed the moment its function returns.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-43",
    topic: "memory",
    subtopic: "Smart pointers",
    difficulty: 5,
    type: "best-practice",
    question: "What is the main benefit of std::unique_ptr over a raw pointer obtained from new?",
    options: ["It performs arithmetic faster", "It automatically calls delete when it goes out of scope, preventing leaks", "It allows unlimited owners to share the same pointer freely", "It converts heap memory into stack memory"],
    correctIndex: 1,
    explanation: "std::unique_ptr wraps a raw pointer and deletes it automatically in its destructor, so a leak can't happen even if an exception or early return skips past a manual delete.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-44",
    topic: "memory",
    subtopic: "Avoiding dangling pointers",
    difficulty: 5,
    type: "best-practice",
    question: "Which practice best avoids a dangling-pointer bug immediately after delete?",
    options: ["Never check pointers before using them", "Set the pointer to nullptr right after delete, and check for nullptr before dereferencing it again", "Call delete twice to be safe", "Avoid using pointers to primitive types entirely"],
    correctIndex: 1,
    explanation: "Nulling a pointer right after deleting it turns an accidental later dereference into a detectable null-pointer check rather than silent undefined behavior.",
    relatedPartId: "part-1",
  },

  // ---------- Arrays & Strings (10) ----------
  {
    id: "exam-45",
    topic: "arrays-strings",
    subtopic: "Array indexing",
    difficulty: 1,
    type: "concept",
    question: "What index does the first element of a C++ array have?",
    options: ["1", "0", "-1", "It's configurable"],
    correctIndex: 1,
    explanation: "C++ arrays are zero-indexed: the first element is at index 0.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-46",
    topic: "arrays-strings",
    subtopic: "Array access",
    difficulty: 1,
    type: "code-analysis",
    code: "int arr[3] = {10, 20, 30};\nstd::cout << arr[1];",
    question: "What does this print?",
    options: ["10", "20", "30", "Compile error"],
    correctIndex: 1,
    explanation: "arr[1] is the second element (index 1), which is 20.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-47",
    topic: "arrays-strings",
    subtopic: "Out-of-bounds access",
    difficulty: 2,
    type: "concept",
    question: "What happens when you access arr[10] on a 3-element array using [] (not .at())?",
    options: ["Compile error", "Automatically throws an exception", "Undefined behavior — [] performs no bounds checking", "Automatically returns 0"],
    correctIndex: 2,
    explanation: "Raw arrays (and std::vector's operator[]) don't check bounds. Reading past the end is undefined behavior, not a guaranteed error or zero.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-48",
    topic: "arrays-strings",
    subtopic: "C-strings",
    difficulty: 2,
    type: "concept",
    question: "Why must a C-string (char array) reserve room for a null terminator '\\0'?",
    options: ["It doesn't — C-strings track their own length like std::string does", "Because functions like strlen and strcpy scan characters until they find '\\0' to know where the string ends", "Only for alignment purposes", "'\\0' is only needed for an empty string"],
    correctIndex: 1,
    explanation: "C-strings carry no separate length field; C string functions rely entirely on finding '\\0' to know where the data stops.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-49",
    topic: "arrays-strings",
    subtopic: "Buffer overflow",
    difficulty: 3,
    type: "debugging",
    code: 'char name[4];\nstrcpy(name, "Amanda");',
    question: "What happens here?",
    options: ["Safe — strcpy resizes the destination automatically", "Undefined behavior — a buffer overflow. strcpy doesn't check the destination's size, and \"Amanda\" plus its null terminator can't fit in 4 bytes", "Compile error", "It's silently truncated to \"Ama\""],
    correctIndex: 1,
    explanation: "name only has room for 4 bytes total. \"Amanda\" needs 7 bytes (6 letters + '\\0'), so strcpy writes past the end of name — a classic buffer overflow.",
    misconception: "Assuming strcpy checks that the destination buffer is large enough.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-50",
    topic: "arrays-strings",
    subtopic: "Comparing C-strings",
    difficulty: 3,
    type: "debugging",
    code: 'char a[] = "hi";\nchar b[] = "hi";\nif (a == b) { std::cout << "equal"; } else { std::cout << "not equal"; }',
    question: "What does this print, and why?",
    options: ['"equal" — both arrays hold the same characters', '"not equal" — a == b compares the two arrays\' memory addresses (which differ here), not their contents; strcmp is needed to compare contents', 'This is a compile error', '"equal" only if the strings are under 4 characters'],
    correctIndex: 1,
    explanation: "Arrays decay to pointers in this comparison, so == checks whether a and b point to the same address — they don't, even though their contents match. Use strcmp(a, b) == 0 to compare contents.",
    misconception: "Forgetting that == compares pointers for C-strings/arrays rather than their contents.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-51",
    topic: "arrays-strings",
    subtopic: "std::string concatenation",
    difficulty: 3,
    type: "code-analysis",
    code: 'std::string s = "Hello, " + std::string("world");\nstd::cout << s;',
    question: "What does this print?",
    options: ['"Hello, world"', "Compile error: cannot add string literals directly", '"HelloWorld"', '"Hello, world!"'],
    correctIndex: 0,
    explanation: 'operator+ is overloaded for std::string, so concatenating a string literal with a std::string produces "Hello, world".',
    relatedPartId: "part-0",
  },
  {
    id: "exam-52",
    topic: "arrays-strings",
    subtopic: "Linear search",
    difficulty: 4,
    type: "code-analysis",
    code: "int arr[5] = {4, 8, 15, 16, 23};\n// linear search for target = 15, checking index 0, 1, 2, ...",
    question: "How many comparisons does a linear search make before finding 15?",
    options: ["1", "2", "3", "5"],
    correctIndex: 2,
    explanation: "The search checks index 0 (4, no match), index 1 (8, no match), index 2 (15, match) — 3 comparisons total.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-53",
    topic: "arrays-strings",
    subtopic: "Bubble sort",
    difficulty: 4,
    type: "code-analysis",
    question: "Given the array [5, 3, 4, 1], what does it look like after ONE full pass of bubble sort (comparing and swapping adjacent elements, left to right)?",
    options: ["[3, 4, 1, 5]", "[1, 3, 4, 5]", "[3, 5, 4, 1]", "[5, 3, 4, 1]"],
    correctIndex: 0,
    explanation: "Compare(5,3)->swap: [3,5,4,1]. Compare(5,4)->swap: [3,4,5,1]. Compare(5,1)->swap: [3,4,1,5]. One pass bubbles the largest unsorted element (5) to the end.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-54",
    topic: "arrays-strings",
    subtopic: "std::string vs C-strings",
    difficulty: 5,
    type: "best-practice",
    question: "What is the best reason modern C++ code prefers std::string over raw char arrays for most text handling?",
    options: ["std::string is always faster in every situation", "std::string manages its own memory (resizing, the null terminator) automatically and safely, avoiding manual buffer-size bugs like buffer overflows", "char arrays no longer compile in modern C++", "std::string cannot be compared with =="],
    correctIndex: 1,
    explanation: "std::string handles its own storage and growth internally, eliminating the class of manual-buffer-size bugs (overflow, missing null terminator) that plague raw char arrays.",
    relatedPartId: "part-0",
  },

  // ---------- Structs & Enums (8) ----------
  {
    id: "exam-55",
    topic: "structs-enums",
    subtopic: "Struct purpose",
    difficulty: 1,
    type: "concept",
    question: "What is the main purpose of a struct in C++?",
    options: ["To define a function", "To group related variables (members) together under one named type", "To create a loop", "To import a library"],
    correctIndex: 1,
    explanation: "A struct bundles related data fields into a single custom type, e.g. a Point with x and y members.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-56",
    topic: "structs-enums",
    subtopic: "Struct member access",
    difficulty: 1,
    type: "code-analysis",
    code: "struct Point { int x; int y; };\nPoint p;\np.x = 3;\np.y = 4;\nstd::cout << p.x + p.y;",
    question: "What does this print?",
    options: ["7", "34", "Compile error", "0"],
    correctIndex: 0,
    explanation: "p.x is 3 and p.y is 4, so p.x + p.y is 7.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-57",
    topic: "structs-enums",
    subtopic: "Default access",
    difficulty: 2,
    type: "concept",
    question: "By default, are struct members public or private in C++?",
    options: ["private", "public", "protected", "It depends on the compiler"],
    correctIndex: 1,
    explanation: "Unlike class, a struct's members (and base classes) default to public access.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-58",
    topic: "structs-enums",
    subtopic: "struct vs class",
    difficulty: 2,
    type: "concept",
    question: "What is the main default-access difference between struct and class in C++?",
    options: ["There is no difference at all", "struct members default to public; class members default to private", "struct cannot have member functions", "class cannot be used for plain data"],
    correctIndex: 1,
    explanation: "That default-access rule (public vs private) is essentially the only functional difference between struct and class in C++.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-59",
    topic: "structs-enums",
    subtopic: "Enum purpose",
    difficulty: 3,
    type: "concept",
    question: "What is the purpose of an enum (enumeration) in C++?",
    options: ["To store a range of floating-point values", "To give meaningful names to a set of related integer constants", "To define a new struct type", "To create dynamically resizable arrays"],
    correctIndex: 1,
    explanation: "An enum lets you name a fixed set of related constant values (e.g. RED, GREEN, BLUE) instead of using unlabeled integers.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-60",
    topic: "structs-enums",
    subtopic: "Unscoped enum values",
    difficulty: 3,
    type: "code-analysis",
    code: "enum Color { RED, GREEN, BLUE };\nColor c = GREEN;\nstd::cout << c;",
    question: "What does this print?",
    options: ['"GREEN"', "1", "0", "Compile error"],
    correctIndex: 1,
    explanation: "A plain (unscoped) enum's values implicitly convert to int for output; RED=0, GREEN=1, BLUE=2 by default, so c prints as 1, not its name.",
    misconception: "Expecting cout to print the enumerator's name rather than its underlying integer value.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-61",
    topic: "structs-enums",
    subtopic: "enum class",
    difficulty: 4,
    type: "concept",
    question: "What is the key advantage of enum class (a scoped enum) over a plain enum?",
    options: ["Its members convert implicitly to int automatically, unlike plain enum", "Its enumerators are scoped (accessed as Color::Red) and do NOT implicitly convert to int, preventing accidental mixing between unrelated enums", "It cannot be compared with ==", "There is no real difference"],
    correctIndex: 1,
    explanation: "enum class requires qualifying enumerators with the enum's name and blocks implicit int conversion, catching bugs where two different enums get mixed up by accident.",
    relatedPartId: "part-0",
  },
  {
    id: "exam-62",
    topic: "structs-enums",
    subtopic: "Array of structs",
    difficulty: 5,
    type: "code-analysis",
    code: "struct Pair { int a; int b; };\nPair arr[3];\nstd::cout << (sizeof(arr) == 3 * sizeof(Pair));",
    question: "What does this print?",
    options: ["1 (true) — an array's total size is its element count times one element's size", "0 (false)", "Compile error", "Undefined behavior"],
    correctIndex: 0,
    explanation: "sizeof an array of N elements equals N times sizeof one element, so the comparison holds and prints 1 (true).",
    relatedPartId: "part-0",
  },

  // ---------- OOP Core (14) ----------
  {
    id: "exam-63",
    topic: "oop-core",
    subtopic: "Classes",
    difficulty: 1,
    type: "concept",
    question: "What is a class in C++?",
    options: ["A built-in primitive type", "A user-defined type combining data (members) and the functions (methods) that operate on that data", "A loop construct", "Just another name for a namespace"],
    correctIndex: 1,
    explanation: "A class is a blueprint that bundles state (member variables) with behavior (member functions) into one type.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-64",
    topic: "oop-core",
    subtopic: "Objects",
    difficulty: 1,
    type: "concept",
    question: "What is an object, in OOP terms?",
    options: ["A function definition", "A specific instance of a class, with its own copy of the class's member data", "A type of loop", "Another word for 'class'"],
    correctIndex: 1,
    explanation: "An object is a concrete instance created from a class — each object has its own member data, though they share the class's method definitions.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-65",
    topic: "oop-core",
    subtopic: "Constructors",
    difficulty: 2,
    type: "concept",
    question: "When is a constructor automatically called?",
    options: ["When the object is destroyed", "When the object is created", "Only when explicitly invoked by name", "Never automatically"],
    correctIndex: 1,
    explanation: "A constructor runs automatically at the moment an object is created, to set up its initial state.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-66",
    topic: "oop-core",
    subtopic: "Destructors",
    difficulty: 2,
    type: "concept",
    question: "When is a destructor automatically called?",
    options: ["When the object is created", "When the object goes out of scope (or is explicitly deleted for heap objects)", "Only if the programmer calls it by name", "Never for stack objects"],
    correctIndex: 1,
    explanation: "A destructor runs automatically when an object's lifetime ends — leaving scope for stack objects, or on delete for heap objects.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-67",
    topic: "oop-core",
    subtopic: "Constructor/destructor order",
    difficulty: 3,
    type: "code-analysis",
    code: 'class Counter {\npublic:\n    Counter() { std::cout << "created "; }\n    ~Counter() { std::cout << "destroyed "; }\n};\nint main() {\n    { Counter c; }\n    std::cout << "end";\n}',
    question: "What does this print?",
    options: ['"created destroyed end"', '"created end destroyed"', '"destroyed created end"', '"end created destroyed"'],
    correctIndex: 0,
    explanation: "c is constructed on entering the inner block, then destructed when that block ends — both happen before \"end\" is printed afterward.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-68",
    topic: "oop-core",
    subtopic: "Encapsulation",
    difficulty: 3,
    type: "concept",
    question: "What is encapsulation?",
    options: ["Making all members public for easy access", "Bundling data with the methods that operate on it, and restricting direct outside access to internal state (e.g. via private members and public methods)", "Inheriting from multiple base classes", "Overloading an operator"],
    correctIndex: 1,
    explanation: "Encapsulation hides an object's internal representation, exposing only a controlled public interface to interact with it.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-69",
    topic: "oop-core",
    subtopic: "Private access",
    difficulty: 3,
    type: "debugging",
    code: "class Account {\nprivate:\n    double balance;\n};\nint main() {\n    Account a;\n    a.balance = 100;\n}",
    question: "What happens here?",
    options: ["Compiles fine and sets balance to 100", "Compile error — balance is private and cannot be accessed from outside the class", "Runtime error", "Silently ignored, balance stays 0"],
    correctIndex: 1,
    explanation: "private members can only be accessed from within the class's own member functions (or friends) — outside code like main() cannot reach a.balance directly.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-70",
    topic: "oop-core",
    subtopic: "Static members",
    difficulty: 4,
    type: "concept",
    question: "What distinguishes a static data member from a regular (instance) data member?",
    options: ["A separate copy exists per object, exactly like a regular member", "A single shared copy exists for the entire class, not one per object", "It can only ever be an integer", "It must always be private"],
    correctIndex: 1,
    explanation: "static data members are shared across every instance of the class — there's exactly one copy, not one per object.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-71",
    topic: "oop-core",
    subtopic: "Static members",
    difficulty: 4,
    type: "code-analysis",
    code: "class Widget {\npublic:\n    static int count;\n    Widget() { count++; }\n};\nint Widget::count = 0;\nint main() {\n    Widget a, b, c;\n    std::cout << Widget::count;\n}",
    question: "What does this print?",
    options: ["0", "1", "3", "Compile error"],
    correctIndex: 2,
    explanation: "Each of the three Widget constructions increments the single shared count, so after a, b, and c are created, count is 3.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-72",
    topic: "oop-core",
    subtopic: "Friend functions",
    difficulty: 4,
    type: "concept",
    question: "What is a friend function?",
    options: ["A member function that can only be called by other friend functions", "A non-member function that is granted access to a class's private and protected members", "A function that must be declared virtual", "A synonym for a static member function"],
    correctIndex: 1,
    explanation: "Declaring a function friend inside a class gives that external function special access to the class's private/protected members, bypassing normal encapsulation for that one function.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-73",
    topic: "oop-core",
    subtopic: "this pointer",
    difficulty: 4,
    type: "concept",
    question: "What does the this pointer refer to inside a non-static member function?",
    options: ["The class definition itself", "A pointer to the specific object the method was called on", "The base class instance", "It only exists inside static methods"],
    correctIndex: 1,
    explanation: "this is an implicit parameter holding the address of the object a member function is currently operating on.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-74",
    topic: "oop-core",
    subtopic: "this pointer disambiguation",
    difficulty: 5,
    type: "code-analysis",
    code: "class Point {\n    int x;\npublic:\n    Point(int x) { this->x = x; }\n};",
    question: "Why is this->x = x; needed here instead of just x = x;?",
    options: ["It isn't needed — x = x; would behave identically", "The constructor parameter x shadows the member x in this scope; this->x explicitly refers to the member, while plain x refers to the parameter", "this-> is required syntax before every assignment in C++", "x = x; would delete the member"],
    correctIndex: 1,
    explanation: "Inside the constructor body, the parameter name x hides the member name x. this->x is the only way to refer to the member when a same-named parameter is in scope.",
    misconception: "Not realizing a parameter name can shadow a member variable with the same name.",
    relatedPartId: "part-3",
  },
  {
    id: "exam-75",
    topic: "oop-core",
    subtopic: "When destructors are needed",
    difficulty: 5,
    type: "best-practice",
    question: "When does a class typically need a user-defined destructor?",
    options: ["Always — every class needs one written explicitly", "When the class manually manages a resource (like heap memory obtained via new) that must be released; otherwise the compiler-generated destructor is often sufficient", "Only if it has more than three members", "Never — destructors are deprecated in modern C++"],
    correctIndex: 1,
    explanation: "The compiler-generated destructor already destroys members correctly for most classes. A custom destructor is needed mainly when the class owns a raw resource it must explicitly release.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-76",
    topic: "oop-core",
    subtopic: "Friend classes",
    difficulty: 5,
    type: "code-analysis",
    code: 'class Engine {\n    friend class Car;\nprivate:\n    int horsepower = 300;\n};\nclass Car {\npublic:\n    void show(Engine &e) { std::cout << e.horsepower; }\n};',
    question: "What does calling show() with an Engine object print?",
    options: ["Compile error — horsepower is private", "300 — Car is declared a friend of Engine, so its member functions can access Engine's private members", "0", "Undefined behavior"],
    correctIndex: 1,
    explanation: "friend class Car; grants every member function of Car access to Engine's private members, so Car::show can read e.horsepower directly.",
    relatedPartId: "part-3",
  },

  // ---------- Inheritance & Polymorphism (18) ----------
  {
    id: "exam-77",
    topic: "inheritance-polymorphism",
    subtopic: "Inheritance basics",
    difficulty: 1,
    type: "concept",
    question: "What does inheritance allow a derived class to do?",
    options: ["Delete the base class", "Reuse and extend the members and behavior of a base class", "Only override private members", "Convert itself into a struct"],
    correctIndex: 1,
    explanation: "Inheritance lets a derived class automatically gain (and optionally extend or override) the base class's members.",
    relatedPartId: "part-5",
  },
  {
    id: "exam-78",
    topic: "inheritance-polymorphism",
    subtopic: "Base vs derived",
    difficulty: 1,
    type: "concept",
    question: "In class Dog : public Animal { };, which is the base class?",
    options: ["Dog", "Animal", "Both, equally", "Neither — this isn't inheritance"],
    correctIndex: 1,
    explanation: "Animal is the base (parent) class; Dog is the derived (child) class inheriting from it.",
    relatedPartId: "part-5",
  },
  {
    id: "exam-79",
    topic: "inheritance-polymorphism",
    subtopic: "Polymorphism concept",
    difficulty: 2,
    type: "concept",
    question: "What is polymorphism, in one sentence?",
    options: ["Having multiple constructors", "The ability for a base class pointer or reference to invoke different derived-class behavior depending on the object's actual runtime type", "Making all members static", "Another name for encapsulation"],
    correctIndex: 1,
    explanation: "Polymorphism lets code written in terms of a base type automatically behave differently depending on which derived type the object actually is at runtime.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-80",
    topic: "inheritance-polymorphism",
    subtopic: "virtual keyword",
    difficulty: 2,
    type: "concept",
    question: "Which keyword enables runtime (dynamic) polymorphism for a member function?",
    options: ["static", "const", "virtual", "inline"],
    correctIndex: 2,
    explanation: "Marking a base class method virtual makes calls through a base pointer/reference resolve at runtime to the actual object's override.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-81",
    topic: "inheritance-polymorphism",
    subtopic: "Virtual dispatch",
    difficulty: 3,
    type: "code-analysis",
    code: 'class Animal {\npublic:\n    virtual void speak() { std::cout << "..."; }\n};\nclass Dog : public Animal {\npublic:\n    void speak() override { std::cout << "Woof"; }\n};\nint main() {\n    Animal *a = new Dog();\n    a->speak();\n}',
    question: "What does this print?",
    options: ['"..."', '"Woof"', "Compile error", "Undefined behavior"],
    correctIndex: 1,
    explanation: "Because speak() is virtual, the call dispatches based on the object's actual type (Dog), not the pointer's static type (Animal), printing \"Woof\".",
    relatedPartId: "part-6",
  },
  {
    id: "exam-82",
    topic: "inheritance-polymorphism",
    subtopic: "Missing virtual",
    difficulty: 3,
    type: "debugging",
    code: 'class Animal {\npublic:\n    void speak() { std::cout << "..."; } // NOT virtual\n};\nclass Dog : public Animal {\npublic:\n    void speak() { std::cout << "Woof"; }\n};\nint main() {\n    Animal *a = new Dog();\n    a->speak();\n}',
    question: "What does this print?",
    options: ['"Woof" — it always calls the derived version', '"..." — without virtual, the call is resolved at compile time based on the pointer\'s static type (Animal), not the object\'s actual type', "Compile error: speak is redefined", "Both versions run"],
    correctIndex: 1,
    explanation: "Without virtual, member function calls use static (compile-time) binding based on the pointer's declared type, so a->speak() calls Animal::speak regardless of what a actually points to.",
    misconception: "Assuming that redefining a non-virtual base method in a derived class still gives dynamic dispatch.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-83",
    topic: "inheritance-polymorphism",
    subtopic: "Pure virtual functions",
    difficulty: 3,
    type: "concept",
    question: "Which declaration makes area() a pure virtual function, forcing derived classes to implement it?",
    options: ["virtual void area();", "virtual void area() = 0;", "void area() = 0;", "abstract void area();"],
    correctIndex: 1,
    explanation: "The = 0 syntax after a virtual function's declaration marks it pure virtual — it has no implementation in the base class, and any derived class must override it to be instantiable.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-84",
    topic: "inheritance-polymorphism",
    subtopic: "Abstract classes",
    difficulty: 3,
    type: "debugging",
    question: "Given a class Shape with a pure virtual area(), what happens if you write Shape s;?",
    options: ["Compiles fine; s.area() simply does nothing", "Compile error — a class with at least one pure virtual function is abstract and cannot be instantiated directly", "Runtime error", "s silently becomes a null object"],
    correctIndex: 1,
    explanation: "A class containing a pure virtual function is abstract; the compiler refuses to create a Shape object directly since area() has no implementation to call.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-85",
    topic: "inheritance-polymorphism",
    subtopic: "Abstract class pointers",
    difficulty: 4,
    type: "concept",
    question: "Given the same Shape (abstract) / Circle (overrides area()) setup, is Shape *s = new Circle(); valid?",
    options: ["No — still a compile error, since Shape is abstract", "Yes — you can't create a bare Shape, but a pointer to Shape can validly point to a fully-implemented derived object like Circle", "Only if Circle is also abstract", "Only with a static_cast"],
    correctIndex: 1,
    explanation: "The restriction is on instantiating Shape directly. A Shape* can freely point to any concrete derived object, like Circle, which does implement area().",
    relatedPartId: "part-6",
  },
  {
    id: "exam-86",
    topic: "inheritance-polymorphism",
    subtopic: "Multiple inheritance",
    difficulty: 4,
    type: "concept",
    question: "Given class C : public A, public B { };, what does C inherit?",
    options: ["Only A's members", "Only B's members", "Members from both A and B", "Neither — this is a syntax error"],
    correctIndex: 2,
    explanation: "Listing multiple base classes separated by commas gives C multiple inheritance — it receives members from both A and B.",
    relatedPartId: "part-5",
  },
  {
    id: "exam-87",
    topic: "inheritance-polymorphism",
    subtopic: "Default inheritance access",
    difficulty: 4,
    type: "concept",
    question: "For a class (not a struct), what is the default inheritance access if you write class Dog : Animal { }; without specifying public/protected/private?",
    options: ["It defaults to public inheritance", "It defaults to private inheritance — you must write : public Animal explicitly for public inheritance", "It defaults to protected inheritance", "This is always a compile error"],
    correctIndex: 1,
    explanation: "class defaults to private inheritance when no access specifier is given (struct defaults to public) — a common source of confusion since most tutorials always show explicit public inheritance.",
    relatedPartId: "part-5",
  },
  {
    id: "exam-88",
    topic: "inheritance-polymorphism",
    subtopic: "Overriding vs overloading",
    difficulty: 4,
    type: "concept",
    question: "Which best distinguishes overriding from overloading?",
    options: ["Overriding redefines a base class's virtual function in a derived class with the same signature; overloading defines multiple functions with the same name but different parameter lists in the same scope", "They are the same concept with different names", "Overloading only applies to constructors", "Overriding requires the const keyword"],
    correctIndex: 0,
    explanation: "Overriding is about a derived class replacing a virtual base method's behavior; overloading is about having several same-named functions distinguished by their parameters.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-89",
    topic: "inheritance-polymorphism",
    subtopic: "Non-virtual destructor",
    difficulty: 4,
    type: "debugging",
    code: 'class Base {\npublic:\n    ~Base() { std::cout << "~Base "; }\n};\nclass Derived : public Base {\npublic:\n    ~Derived() { std::cout << "~Derived "; }\n};\nint main() {\n    Base *b = new Derived();\n    delete b;\n}',
    question: "What does this print, and what's the danger?",
    options: ['"~Derived ~Base " — both run correctly', '"~Base " only — since ~Base() isn\'t virtual, deleting through a Base* only calls Base\'s destructor, so any resources Derived owns are leaked', '"~Derived " only', "Compile error"],
    correctIndex: 1,
    explanation: "Deleting a derived object through a non-virtual base destructor only runs the base's destructor — Derived::~Derived never executes, silently skipping any cleanup it was responsible for.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-90",
    topic: "inheritance-polymorphism",
    subtopic: "Object slicing",
    difficulty: 5,
    type: "debugging",
    code: "Animal a = Dog(); // assigning a Dog object into an Animal by value",
    question: "What happens to the Dog-specific parts of the object here?",
    options: ["a behaves polymorphically and still calls Dog's overrides", "This 'slices' the object — only the Animal portion is copied into a; Dog-specific data and any overridden behavior are lost", "This is a compile error", "Dog is automatically converted into a pointer"],
    correctIndex: 1,
    explanation: "Assigning or passing a derived object into a base object BY VALUE copies only the base part — this is object slicing. Polymorphism only works through pointers or references, never through by-value base objects.",
    misconception: "Assuming polymorphic behavior is preserved when a derived object is copied into a base object by value.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-91",
    topic: "inheritance-polymorphism",
    subtopic: "Default arguments are not virtual",
    difficulty: 5,
    type: "code-analysis",
    code: 'class Base {\npublic:\n    virtual void greet(std::string msg = "Base") { std::cout << msg; }\n};\nclass Derived : public Base {\npublic:\n    void greet(std::string msg = "Derived") override { std::cout << msg; }\n};\nint main() {\n    Base *b = new Derived();\n    b->greet();\n}',
    question: 'What does this print?',
    options: ['"Derived"', '"Base" — Derived::greet() still runs (virtual dispatch picks the override), but its default argument is NOT used; the default from the pointer\'s static type (Base) is used instead', "Compile error: conflicting default arguments", "An empty string"],
    correctIndex: 1,
    explanation: "Virtual dispatch chooses which function body runs (Derived::greet), but default argument values are resolved statically from the pointer's declared type (Base), not virtually — a subtle, well-known gotcha.",
    misconception: "Assuming default arguments follow virtual dispatch the same way the function body does.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-92",
    topic: "inheritance-polymorphism",
    subtopic: "Diamond problem",
    difficulty: 5,
    type: "concept",
    question: "When two base classes both inherit from the same common ancestor, and a class inherits from both of them, what problem can arise regarding that ancestor's members?",
    options: ["No problem — C++ automatically removes the duplicates", "The 'diamond problem' — the most-derived class ends up with two separate copies of the common ancestor's members, causing ambiguity, unless virtual inheritance is used", "A compile error is always raised immediately regardless of usage", "This can only happen with private inheritance"],
    correctIndex: 1,
    explanation: "Without virtual inheritance, the common ancestor's members are duplicated once per inheritance path, and referring to them becomes ambiguous — the classic diamond problem.",
    relatedPartId: "part-5",
  },
  {
    id: "exam-93",
    topic: "inheritance-polymorphism",
    subtopic: "vtable mental model",
    difficulty: 5,
    type: "concept",
    question: "What mechanism does a C++ compiler typically use to implement dynamic dispatch for virtual functions at runtime?",
    options: ["A hidden vtable (virtual table) pointer per object, pointing to a table of function pointers resolved at runtime", "String comparison of function names at runtime", "The preprocessor rewrites every call before compiling", "There is no mechanism — it works purely by convention"],
    correctIndex: 0,
    explanation: "Each polymorphic object carries a hidden pointer to its class's vtable — an array of function pointers — which is consulted at runtime to find the correct override to call.",
    relatedPartId: "part-6",
  },
  {
    id: "exam-94",
    topic: "inheritance-polymorphism",
    subtopic: "override keyword safety",
    difficulty: 5,
    type: "debugging",
    code: "class Base {\npublic:\n    virtual void speak(int x) { }\n};\nclass Derived : public Base {\npublic:\n    void speak(double x) override { } // signature mismatch!\n};",
    question: "What happens when this is compiled?",
    options: ["Compiles fine, and speak(double) properly overrides Base's speak(int)", "Compile error — override catches that speak(double) doesn't actually match any virtual function in Base, since Base only has speak(int), a different signature", "This silently creates a new unrelated overload with no error", "Only a runtime warning is produced"],
    correctIndex: 1,
    explanation: "override tells the compiler to verify this function really overrides a base virtual function with a matching signature. Since Base only has speak(int), not speak(double), the mismatch is caught at compile time instead of silently creating an unrelated overload.",
    misconception: "Not realizing that without override, a signature typo would silently compile as an unrelated overload instead of an override, hiding the bug.",
    relatedPartId: "part-6",
  },

  // ---------- STL (12) ----------
  {
    id: "exam-95",
    topic: "stl",
    subtopic: "STL overview",
    difficulty: 1,
    type: "concept",
    question: "What does STL refer to in C++?",
    options: ["The Standard Template Library — a collection of generic containers, iterators, and algorithms", "A single fixed-size array type", "A networking library", "A memory allocator only"],
    correctIndex: 0,
    explanation: "The STL provides reusable, generic building blocks: containers (vector, map, ...), iterators to traverse them, and algorithms (sort, find, ...) that work across container types.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-96",
    topic: "stl",
    subtopic: "std::vector",
    difficulty: 1,
    type: "concept",
    question: "Which STL container provides a dynamically resizable array?",
    options: ["std::array", "std::vector", "std::map", "std::pair"],
    correctIndex: 1,
    explanation: "std::vector grows and shrinks at runtime, unlike std::array which has a fixed compile-time size.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-97",
    topic: "stl",
    subtopic: "push_back / size",
    difficulty: 2,
    type: "code-analysis",
    code: "std::vector<int> v;\nv.push_back(10);\nv.push_back(20);\nstd::cout << v.size();",
    question: "What does this print?",
    options: ["0", "1", "2", "10"],
    correctIndex: 2,
    explanation: "Two elements were pushed onto v, so v.size() is 2.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-98",
    topic: "stl",
    subtopic: "[] vs .at()",
    difficulty: 2,
    type: "concept",
    question: "What is the key difference between v[i] and v.at(i) for a std::vector v?",
    options: ["They are identical in every way", "v.at(i) performs bounds checking and throws std::out_of_range on an invalid index; v[i] does not check and is undefined behavior if out of range", "v[i] is always slower than v.at(i)", "v.at(i) cannot be used to modify elements"],
    correctIndex: 1,
    explanation: "at() is the safe, bounds-checked accessor; operator[] trades that safety for speed by skipping the check entirely.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-99",
    topic: "stl",
    subtopic: "out_of_range",
    difficulty: 3,
    type: "code-analysis",
    code: 'std::vector<int> v = {1, 2, 3};\ntry {\n    v.at(10);\n} catch (const std::out_of_range &e) {\n    std::cout << "caught";\n}',
    question: "What does this print?",
    options: ['"caught"', "Undefined behavior, nothing printed", "Compile error", "10"],
    correctIndex: 0,
    explanation: "v.at(10) is out of range for a 3-element vector, so it throws std::out_of_range, which the catch block handles, printing \"caught\".",
    relatedPartId: "part-2",
  },
  {
    id: "exam-100",
    topic: "stl",
    subtopic: "std::map",
    difficulty: 3,
    type: "concept",
    question: "What kind of data does std::map<K, V> store?",
    options: ["An unordered list of values only", "Key-value pairs, automatically kept sorted by key", "A fixed-size array of pairs", "Only string keys are allowed"],
    correctIndex: 1,
    explanation: "std::map stores unique keys mapped to values, keeping entries ordered by key (by default, using operator<).",
    relatedPartId: "part-2",
  },
  {
    id: "exam-101",
    topic: "stl",
    subtopic: "std::pair",
    difficulty: 3,
    type: "concept",
    question: "What does std::pair<int, std::string> p; let you store?",
    options: ["Two independent std::pair objects", "A single object bundling two values of possibly different types, accessed as p.first and p.second", "A dynamic array of ints and strings", "This is invalid syntax"],
    correctIndex: 1,
    explanation: "std::pair groups exactly two values (of any two types) into one object, accessed via .first and .second.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-102",
    topic: "stl",
    subtopic: "std::set",
    difficulty: 3,
    type: "concept",
    question: "What makes std::set different from std::vector?",
    options: ["std::set allows duplicate elements, vector doesn't", "std::set stores only unique elements, automatically kept in sorted order; vector allows duplicates in insertion order", "std::set cannot be iterated over", "There is no functional difference"],
    correctIndex: 1,
    explanation: "std::set enforces uniqueness and sorted order automatically; std::vector is an ordered, duplicate-allowing sequence with no automatic sorting.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-103",
    topic: "stl",
    subtopic: "Iterators",
    difficulty: 4,
    type: "concept",
    question: "What is an iterator in the STL, conceptually?",
    options: ["A function that sorts a container", "An object that behaves like a generalized pointer, letting you traverse a container's elements without knowing its internal structure", "A synonym for an integer index only", "A type of exception"],
    correctIndex: 1,
    explanation: "Iterators provide a uniform pointer-like interface (increment, dereference) for moving through any container, whether it's a contiguous array or a linked structure.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-104",
    topic: "stl",
    subtopic: "Range-based for by value",
    difficulty: 4,
    type: "debugging",
    code: 'std::vector<int> v = {1, 2, 3};\nfor (int x : v) x *= 2;\nfor (int x : v) std::cout << x << " ";',
    question: "What does this print?",
    options: ['"2 4 6 "', '"1 2 3 "', "Compile error", '"6 6 6 "'],
    correctIndex: 1,
    explanation: "for (int x : v) copies each element into x by value; modifying x has no effect on v's actual elements. Writing for (int &x : v) instead would modify v in place.",
    misconception: "Forgetting that range-based for copies each element by value unless you explicitly use a reference (int &x).",
    relatedPartId: "part-2",
  },
  {
    id: "exam-105",
    topic: "stl",
    subtopic: "std::sort",
    difficulty: 4,
    type: "concept",
    question: "What does std::sort(v.begin(), v.end()); do to a std::vector<int> v?",
    options: ["Reverses v", "Sorts v's elements in ascending order by default", "Removes duplicates from v", "Searches for a specific value in v"],
    correctIndex: 1,
    explanation: "std::sort rearranges the range [begin, end) into ascending order by default, using operator< to compare elements.",
    relatedPartId: "part-2",
  },
  {
    id: "exam-106",
    topic: "stl",
    subtopic: "std::find",
    difficulty: 5,
    type: "code-analysis",
    code: 'std::vector<int> v = {10, 20, 30};\nauto it = std::find(v.begin(), v.end(), 99);\nif (it == v.end()) std::cout << "not found";',
    question: "What does this print?",
    options: ['"not found" — 99 isn\'t in v, so std::find returns the end() iterator as a not-found sentinel', "30", "Compile error", "Infinite loop"],
    correctIndex: 0,
    explanation: "std::find returns an iterator to the first match, or the range's end() iterator if nothing matches — comparing against end() is the standard way to detect \"not found.\"",
    relatedPartId: "part-2",
  },

  // ---------- Exceptions (8) ----------
  {
    id: "exam-107",
    topic: "exceptions",
    subtopic: "try/catch purpose",
    difficulty: 1,
    type: "concept",
    question: "What is the purpose of a try/catch block?",
    options: ["To declare a new function", "To detect and handle runtime errors (exceptions) gracefully instead of crashing", "To optimize loop performance", "To define a class"],
    correctIndex: 1,
    explanation: "try/catch lets a program detect an exceptional runtime condition and respond to it, rather than letting the program terminate abruptly.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-108",
    topic: "exceptions",
    subtopic: "throw keyword",
    difficulty: 1,
    type: "concept",
    question: "Which keyword actually raises (signals) an exception in C++?",
    options: ["catch", "try", "throw", "except"],
    correctIndex: 2,
    explanation: "throw is the statement that raises an exception, transferring control to the nearest matching catch handler.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-109",
    topic: "exceptions",
    subtopic: "Basic catch",
    difficulty: 2,
    type: "code-analysis",
    code: 'try {\n    throw std::runtime_error("bad input");\n} catch (const std::exception &e) {\n    std::cout << "caught: " << e.what();\n}',
    question: "What does this print?",
    options: ['"caught: bad input"', "The program crashes, nothing is caught", "Compile error", "Nothing is printed"],
    correctIndex: 0,
    explanation: "std::runtime_error derives from std::exception, so the catch (const std::exception &e) block catches it, and e.what() returns the message passed to the constructor.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-110",
    topic: "exceptions",
    subtopic: "Uncaught exceptions",
    difficulty: 2,
    type: "concept",
    question: "What happens if an exception is thrown but there is no matching catch anywhere in the call stack?",
    options: ["It is silently ignored", "std::terminate is called and the program aborts", "It's automatically converted into a return value", "The nearest loop catches it by default"],
    correctIndex: 1,
    explanation: "An exception that propagates all the way out of main() (or past every frame) with no handler causes std::terminate to be invoked, ending the program.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-111",
    topic: "exceptions",
    subtopic: "Propagation",
    difficulty: 3,
    type: "code-analysis",
    code: 'void c() { throw std::runtime_error("fail"); }\nvoid b() { c(); }\nvoid a() {\n    try { b(); }\n    catch (...) { std::cout << "caught in a"; }\n}',
    question: "What does calling a() print?",
    options: ['"caught in a" — the exception propagates up through b() and c() (neither has a try/catch) until a matching handler is found in a()', "Compile error — c() must have its own catch block", '"caught in b"', "Nothing is printed"],
    correctIndex: 0,
    explanation: "An exception unwinds the call stack frame by frame until it finds a matching catch. Since only a() has one, it propagates through c() and b() first, then is caught in a().",
    relatedPartId: "part-1",
  },
  {
    id: "exam-112",
    topic: "exceptions",
    subtopic: "catch(...)",
    difficulty: 3,
    type: "concept",
    question: "What does catch (...) mean in C++?",
    options: ["It only catches std::exception and its subclasses", "It's a catch-all handler that catches any thrown value, regardless of its type", "It's a syntax error", "It only catches integers"],
    correctIndex: 1,
    explanation: "catch (...) matches any exception type at all, making it a last-resort catch-all — though it can't inspect what was actually thrown.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-113",
    topic: "exceptions",
    subtopic: "Stack unwinding",
    difficulty: 4,
    type: "concept",
    question: "When an exception propagates out of a function, what happens to that function's local objects that have destructors?",
    options: ["They are leaked — destructors never run during unwinding", "Their destructors are automatically called as the stack unwinds, before the exception reaches its handler", "Only static objects get destroyed", "The catch block must destroy them manually"],
    correctIndex: 1,
    explanation: "Stack unwinding automatically destroys local objects in each frame the exception passes through, exactly as if those scopes had exited normally.",
    relatedPartId: "part-1",
  },
  {
    id: "exam-114",
    topic: "exceptions",
    subtopic: "Catching by reference",
    difficulty: 5,
    type: "best-practice",
    question: "Why is catch (const std::exception &e) generally preferred over catch (std::exception e)?",
    options: ["Catching by value isn't legal C++", "Catching by reference avoids slicing a derived exception type (e.g. a thrown std::out_of_range) down to just its std::exception base, and avoids an unnecessary copy", "Catching by value is always faster", "There is no real difference between the two"],
    correctIndex: 1,
    explanation: "Catching by value copies (and potentially slices) the exception object; catching by reference preserves the thrown object's real derived type and skips the copy.",
    relatedPartId: "part-1",
  },
];
