export type PassSection = "mcq" | "true-false" | "fill-blank" | "code-trace";

export interface PassQuestion {
  id: string;
  section: PassSection;
  question: string;
  code?: string;
  options?: string[];
  answer: string;
  explanation: string;
}

export const PASS_SECTIONS: { id: PassSection; label: string }[] = [
  { id: "mcq", label: "Multiple Choice" },
  { id: "true-false", label: "True / False" },
  { id: "fill-blank", label: "Fill in the Blank" },
  { id: "code-trace", label: "Code Trace" },
];

export const passcoBank: PassQuestion[] = [
  // ---------- Multiple choice (from the sample MCQ section) ----------
  {
    id: "passco-1",
    section: "mcq",
    question: "Which of the following can best be used to alter the execution of statement order in a program with a conditional statement?",
    options: ["A Boolean expression", "A question type", "A selection statement", "A sequence"],
    answer: "A selection statement",
    explanation: "A selection statement (if/else, switch) is what actually branches execution based on a condition — a Boolean expression is just the test it uses.",
  },
  {
    id: "passco-2",
    section: "mcq",
    question: "Boolean expressions can only be used in an IF statement. Is this true or false?",
    options: ["True", "False"],
    answer: "False",
    explanation: "Boolean expressions can also drive while/for loops, ternary expressions, and more — they aren't exclusive to if statements.",
  },
  {
    id: "passco-3",
    section: "mcq",
    question: "An input data can be read into a Boolean variable using a cin statement. Is this true or false?",
    options: ["True", "False", "Difficult to tell"],
    answer: "True",
    explanation: "cin >> boolVar; works and reads 0 or 1 into the bool by default (use std::boolalpha first if you want to accept the words \"true\"/\"false\").",
  },
  {
    id: "passco-4",
    section: "mcq",
    question: "Given that A = true, B = false and C = false, what is the result of: A || B && C",
    options: ["True", "False"],
    answer: "True",
    explanation: "&& binds tighter than ||, so this is A || (B && C) = true || (false && false) = true || false = true.",
  },
  {
    id: "passco-5",
    section: "mcq",
    question: "Which of the following statements correctly declares the variable MyBalance to be used in storing account balances in a program?",
    options: ["MyBalance float;", "real MyBalance;", "integer MyBalance;", "double : MyBalance;", "None of the above"],
    answer: "None of the above",
    explanation: "The valid form is `double MyBalance;` (type first, no colon) — none of the listed options are legal C++.",
  },
  {
    id: "passco-6",
    section: "mcq",
    question: 'Which of the following statements correctly displays the data held in variable total?',
    options: ['cout << "total";', "cout >> total;", "cout >> 'total';", "write total;", "None of the above"],
    answer: "None of the above",
    explanation: 'The correct form is `cout << total;` (no quotes, and << not >>) — every listed option either prints the literal word "total" or uses the wrong operator.',
  },
  {
    id: "passco-7",
    section: "mcq",
    question: "Which of the following statements correctly assigns the sum of the variables midsem and exams and stores the result in a variable total?",
    options: ["total = midsem + exams", "total ==midsem + exams;", "total = midsem + exams;", "total += midsem + exams"],
    answer: "total = midsem + exams;",
    explanation: "This is a plain assignment with the required trailing semicolon. The others are missing the semicolon or use == (comparison) instead of =.",
  },
  {
    id: "passco-8",
    section: "mcq",
    question: 'Which of the following statements best describes the expression "What is your name ?" in:\ncout << "What is your name ? ";\ncin >> name;',
    options: ["A question", "Output statement", "A prompt", "cout statement", "All of the above"],
    answer: "A prompt",
    explanation: 'It IS technically an output/cout statement, but the term being tested here is "prompt" — text displayed to tell the user what input is expected next.',
  },
  {
    id: "passco-9",
    section: "mcq",
    question: "Which of the following statements best instructs the computer to display to the screen the data held in the variable Small such that it will have at most three print positions?",
    options: ['cout >> "small_value",3;', "cout << small_value:3 ;", "write 'small_value:3';", "cout << small_value:3;", "None of the above"],
    answer: "None of the above",
    explanation: "Field width in C++ needs the setw() manipulator: `cout << setw(3) << small_value;`. None of the listed options use it or valid syntax.",
  },
  {
    id: "passco-10",
    section: "mcq",
    code: 'PANEL (i):\ncin >> n;\nif (n == 2) { cin >> a1 >> a2; sum = a1 + a2; }\nelse if (n == 3) { cin >> a1 >> a2 >> a3; sum = a1 + a2 + a3; }\nelse cout << "Please, wrong input!!!!!";\n\nPANEL (ii):\ncin >> n;\nif (n > 1 && n < 4) {\n  cin >> a1 >> a2; sum = a1 + a2;\n  if (n == 3) { cin >> a3; sum = sum + a3; }\n}\nelse cout << "Please, wrong input!!! ";',
    question: "Which of the following correctly adds 10 and 20 given the input '2 10 20', and correctly adds 30, 20 and 10 given the input '3 30 20 10'?",
    options: ["I only", "II only", "I and II", "None of them"],
    answer: "I and II",
    explanation: "Trace both: panel (i) gives sum=30 then sum=60 for the two inputs; panel (ii) gives the same results via its combined range check and nested if(n==3). Both panels work correctly.",
  },
  {
    id: "passco-11",
    section: "mcq",
    question: "In a complete program, under no circumstance should one have statements after the return 0; of the main program. Is this true or false?",
    options: ["True", "False"],
    answer: "False",
    explanation: "Code placed after a return statement is legal (if unusual) — it's simply unreachable and never executes. It's poor style, not illegal.",
  },
  {
    id: "passco-12",
    section: "mcq",
    code: '#include<iostream>\nusing namespace std;\nint main()\n{\n  const int large(666);\n  int a,b;\n  cout <<"Please enter values of A and B ";\n  cin>>a >>b;\n  if (a > b)\n    if (a <= large)\n      cout <<(a+b);\n    else\n      cout <<a <<" is larger than " <<b <<" and maximum";\n  else\n    cout <<(a+b);\n  system("pause");\n  return 0;\n}',
    question: "The program above is meant to compare input data against 666 and print the sum when the first value entered is strictly smaller than the second — but it's logically incorrect. Which change(s) alone correctly fix it?\ni. interchange line 15 with lines 10-13\nii. interchange a and b on the `if (a > b)` line\niii. replace `cin >> a >> b;` with `cin >> b >> a;`",
    options: ["I only", "II only", "III only", "II and III only", "I, II and III"],
    answer: "II and III only",
    explanation: "Swapping a and b in the condition (making it `if (b > a)`, i.e. a < b) and swapping which variable the two inputs land in both independently flip the comparison to the intended \"first value smaller than second\" — either one alone fixes it. Rearranging the code blocks (i) doesn't touch the actual comparison, so it doesn't help alone.",
  },
  {
    id: "passco-13",
    section: "mcq",
    question: "Using the unmodified program above, what will be displayed when the inputs are entered as 800 and 250, in that order?",
    options: ["1050", "800 is larger than 250 and maximum", "None of the above"],
    answer: "800 is larger than 250 and maximum",
    explanation: "a=800, b=250: a>b is true, and a<=666 is false (800 isn't ≤ 666), so it takes the else branch and prints \"800 is larger than 250 and maximum\".",
  },
  {
    id: "passco-14",
    section: "mcq",
    question: "Which of the following statements correctly declares the integer variables Sum and Counter, and initialises both variables to zero?",
    options: ["int sum=counter=0;", "integer sum=0 and counter=0;", "int sum=0 && counter = 0;", "int = 0 sum, counter;"],
    answer: "None of these actually work",
    explanation: 'This is a trick item: `int sum=counter=0;` looks tempting but only declares sum — counter is never declared, so it fails to compile unless counter already exists elsewhere. The correct form is `int sum = 0, counter = 0;`, which isn\'t offered.',
  },
  {
    id: "passco-15",
    section: "mcq",
    question: "Which of the following is an invalid C++ relational operator?",
    options: ["=", "<>", "<", ">"],
    answer: "=",
    explanation: "= is the assignment operator, not a relational (comparison) operator — that's == in C++. This is one of the most common beginner mix-ups.",
  },
  {
    id: "passco-16",
    section: "mcq",
    question: "Write a C++ statement which compares the integer variable sum to the constant value 99, and if it is the same, prints the string 'XCIX'.",
    options: ['if sum = 99 then cout <<"XCIX";', "if (sum == 99) cout << 'XCIX';", "if (sum=99) cout<<'XCIX';", "if sum=99 cout << ('XCIX');"],
    answer: "if (sum == 99) cout << 'XCIX';",
    explanation: "This is the only option using the correct == comparison operator inside required parentheses. (Strictly, a multi-character literal like \"XCIX\" should use double quotes — single quotes are for one character — but this option is the one testing the intended == comparison correctly.)",
  },
  {
    id: "passco-17",
    section: "mcq",
    question: "Which of the following statements correctly defines MyAge as integer?",
    options: ["MyAge :integer;", "MyAge : year;", "MyAge year;", "int MyAge;", "None of the above"],
    answer: "int MyAge;",
    explanation: "C++ declarations are `type name;` — `int MyAge;` is the only valid form here.",
  },
  {
    id: "passco-18",
    section: "mcq",
    question: "Which of the following statements can best be used to accept data into the variable alphabet?",
    options: ["cin >> 'letter';", 'cin >> "letter";', "read letter;", "cin << letter;", "None of the above"],
    answer: "None of the above",
    explanation: "The correct form is `cin >> alphabet;` — no quotes around the variable name, and cin reads with >>, not <<. Every option here is invalid.",
  },
  {
    id: "passco-19",
    section: "mcq",
    question: "Write a C++ statement which compares the string variable letter to the character variable YourLetter, and if they are not the same, prints the value of YourLetter.",
    options: [
      "if (letter <> YourLetter) cout << 'YourLetter';",
      "if strcmp(letter, YourLetter) cout << YourLetter;",
      "if (letter != YourLetter) cout << YourLetter;",
      "if (strcmp(letter,YourLetter) !=0) cout << YourLetter;",
      "At least two of the above are correct",
    ],
    answer: "if (letter != YourLetter) cout << YourLetter;",
    explanation: "std::string overloads != so comparing it directly to a char works and reads cleanly. strcmp() is for C-style char* strings and needs its own !=0 check with proper parentheses around the whole if condition.",
  },
  {
    id: "passco-20",
    section: "mcq",
    question: "Which of the following can be used to specify the number of characters that should be displayed for a string variable?",
    options: ["setw", "setwidth", "length", "charlength"],
    answer: "setw",
    explanation: "setw() (from <iomanip>) sets the field width for the very next value inserted into the stream.",
  },
  {
    id: "passco-21",
    section: "mcq",
    question: `If the characters "A" and "C" are compared, the computer will indicate that "A" is smaller than "C". Which best describes why?`,
    options: ["Alphabetically, A is before C", "If A is the first alphabet and C is the third then A is smaller than C", "The ASCII value of A is smaller than that of C, so A is smaller than C", "All the above"],
    answer: "The ASCII value of A is smaller than that of C, so A is smaller than C",
    explanation: "Characters compare by their underlying numeric character codes — 'A' is 65 and 'C' is 67 in ASCII — that's the actual mechanism a computer uses, not alphabetical intuition.",
  },
  {
    id: "passco-22",
    section: "mcq",
    question: "Which of the following C++ user-defined function headers indicates that the elements of the array Wages cannot be modified by the function MyFunction?",
    options: ["const int MyFunction(int Wages);", "int const MyFunction(int Wages);", "const MyFunction(int Wages);", "int MyFunction(const int Wages[]);", "All the above"],
    answer: "int MyFunction(const int Wages[]);",
    explanation: "const has to qualify the parameter itself to protect it — putting const on the return type (as in the first two options) protects nothing about the array argument.",
  },
  {
    id: "passco-23",
    section: "mcq",
    question: "Write a C++ statement which declares a constant called MAXSIZE with a value of 80.",
    options: ["constant MAXSIZE = 80;", "const MAXSIZE == 80;", "const MAXSIZE 80;", "constant MAXSIZE = 80", "None of the above"],
    answer: "None of the above",
    explanation: 'The correct form needs an explicit type: `const int MAXSIZE = 80;`. "constant" is not a C++ keyword, and none of the listed options are valid as written.',
  },
  {
    id: "passco-24",
    section: "mcq",
    question: "Which of the following for loops can correctly display the following output?\n1\n22\n333\n4444\n55555",
    code: "A:\nfor (i=1;i<6;i++)\n{\n  for (j=1;j<=i;j++)\n    cout << i;\n  cout << endl;\n}\n\nB:\nfor (i=1;i<=5;i++)\n{\n  for (j=1;j<=i;j++)\n    cout << j;\n  cout << endl;\n}\n\nC:\nfor (i=1;i<=5;i++)\n{\n  for (j=1;j<i;j++)\n    cout << j;\n  cout << endl;\n}",
    options: ["A", "B", "C"],
    answer: "A",
    explanation: "A prints i itself, i times per row (1, then 22, then 333...) — exactly the target pattern. B prints the running counter j instead (giving 1, 12, 123...), and C's j<i bound skips a value each row.",
  },
  {
    id: "passco-25",
    section: "mcq",
    question: "A variable which is not defined before or at the start of the main function can NEVER be used in the body of the main function. Is this true or false?",
    options: ["True", "False", "Not easy to tell", "It depends on the compiler"],
    answer: "False",
    explanation: "C++ allows local variables to be declared partway through a function body — they just have to be declared before their first use, not necessarily at the very top.",
  },
  {
    id: "passco-26",
    section: "mcq",
    question: "Which of the following will you say correctly declares the variable MyInitials as a character variable?",
    options: ["character : MyInitials;", "char : MyInitials;", "char := MyInitials", "MyInitials character;", "char MyInitials;"],
    answer: "char MyInitials;",
    explanation: "Standard C++ declaration syntax: type first, then name, no colon and no Pascal-style :=.",
  },
  {
    id: "passco-27",
    section: "mcq",
    question: "Which of the following statements can correctly display the alphabets A to Z inclusive?",
    code: "A:\nloop = 'A';\nwhile (loop <= 'Z') do\n{\n  cout << loop << ' ';\n  loop = loop + 1;\n}\n\nB:\nloop = 'Z';\nwhile (loop > 'A') do\n{\n  cout << loop << ' ');\n  loop = loop - 1;\n}\n\nC:\nloop:= A;\nwhile (loop <=Z) do\n{\n  cout << loop << ' ';\n  loop = loop ++;\n}",
    options: ["A", "B", "C"],
    answer: "A",
    explanation: "A uses valid character increment (loop = loop + 1) across the whole A-Z range. B misses 'Z' itself (loop > 'A' stops one early) and has a stray closing parenthesis; C uses invalid Pascal-style := and an invalid loop++ expression.",
  },
  {
    id: "passco-28",
    section: "mcq",
    question: "Which of the following can be used to add comments in a C++ program?",
    options: ["{}", "/**/", ";;", "comment", "At least two of the above"],
    answer: "/**/",
    explanation: "/* ... */ is the standard multi-line comment delimiter in C++ (// is used for single-line comments).",
  },
  {
    id: "passco-29",
    section: "mcq",
    question: "Which of the following correctly moves the cursor to the start of the next line?",
    options: ["cout <<;", "cout <<nextLine;", "cout <<endOfLine;", "cout << 'endl';", "None of the above"],
    answer: "None of the above",
    explanation: "The correct form is `cout << endl;` with no quotes — endl is a manipulator, not a string literal, so quoting it is invalid.",
  },
  {
    id: "passco-30",
    section: "mcq",
    question: "The statement that declares a variable called WholeNumber, capable of storing any integer value, is:",
    options: ["WholeNumber : integer;", "integer WholeNumber;", "WholeNumber as integer;", "int WholeNumber;", "WholeNumber of integers;"],
    answer: "int WholeNumber;",
    explanation: "int is the C++ keyword for an integer type — \"integer\" is not a valid C++ type name.",
  },
  {
    id: "passco-31",
    section: "mcq",
    question: "To print a single quote as part of an output string, which of the following will you use with the cout statement?",
    options: ["use a double quote in place of the single quote", "use two double quotes in place of the single quote", "precede the single quote with a backslash", "precede the single quote with a single quote"],
    answer: "precede the single quote with a backslash",
    explanation: `\\' is the escape sequence for a literal single quote inside a string.`,
  },
  {
    id: "passco-32",
    section: "mcq",
    question: "In C++ all valid program statements should be terminated by a semi-colon. Is this true or false?",
    options: ["True", "False"],
    answer: "True",
    explanation: "As the general rule taught at this level: yes. (The one nuance worth knowing: control-flow headers like if(...)/for(...)/while(...) and block braces { } don't themselves take a trailing semicolon — it's the simple statements inside that do.)",
  },
  {
    id: "passco-33",
    section: "mcq",
    question: "Which of the following statements declares an array called numbers to store 20 integer values?",
    options: ["int numbers = ARRAY[1..20];", "int numbers = ARRAY[0..19];", "int numbers[20];", "int numbers = ARRAY[20];"],
    answer: "int numbers[20];",
    explanation: "C++ array declaration syntax is `type name[size];` — the ARRAY[...] forms shown are not valid C++.",
  },
  {
    id: "passco-34",
    section: "mcq",
    question: "Which of the following is syntactically correct?",
    options: ["WelcomeMessage = 'Hello there! ';", "WelcomeMessage == 'Hello there! ';", 'WelcomeMessage = "Hello there! ";', "WelcomeMessage = Hello there!;"],
    answer: 'WelcomeMessage = "Hello there! ";',
    explanation: "Multi-character text needs double quotes, and this is a plain assignment (=), not a comparison (==).",
  },
  {
    id: "passco-35",
    section: "mcq",
    question: 'Which of the following statements will correctly display the ASCII value of the letter "A" to the screen?',
    options: ["cout << chr('A');", "cout << str('A');", "cout <<ASCII('A') ;", "cout << char('A');", "None of the above"],
    answer: "None of the above",
    explanation: "The correct way is `cout << int('A');` — casting the char to an int prints its numeric code (65). char('A') just prints the letter 'A' itself, and chr()/str()/ASCII() aren't real C++ functions.",
  },
  {
    id: "passco-36",
    section: "mcq",
    question: "Which of the following statements correctly declares the variable counter and initialises it to 100?",
    options: ["counter = 100;", "int counter[100];", "integer counter =100;", "int counter(100);"],
    answer: "int counter(100);",
    explanation: "This is direct-initialization syntax. The classic trap here is `int counter[100];` — that declares an array of 100 elements, not a single variable holding the value 100.",
  },
  {
    id: "passco-37",
    section: "mcq",
    question: "Which of the following operators has the least priority when used in the same expression?",
    options: ["=", "+", "/", "NOT"],
    answer: "=",
    explanation: "Assignment (=) sits near the very bottom of C++'s precedence table — lower than arithmetic operators and lower than logical NOT.",
  },
  {
    id: "passco-38",
    section: "mcq",
    question: "Which of the following statements correctly stores the number 20 at the 10th location of the array MyNumbers?",
    options: ["MyNumbers[20] = 10;", "MyNumbers [10] = 20;", "MyNumbers [9] = 20;", "MyNumbers [20] = 9;", "B and C are both correct"],
    answer: "MyNumbers [9] = 20;",
    explanation: "C++ arrays are 0-indexed, so the 10th element (counting from 1) sits at index 9. MyNumbers[10] is actually the 11th element — a classic off-by-one trap.",
  },
  {
    id: "passco-39",
    section: "mcq",
    question: "What is the only programming language that a computer understands directly?",
    options: ["English, as spoken in countries like Ghana.", "BASIC, the Beginners' All-purpose Symbolic Instruction Code", "Machine language, different for every type of CPU", "All the above"],
    answer: "Machine language, different for every type of CPU",
    explanation: "Only machine code (raw binary instructions specific to a CPU's architecture) is executed directly by hardware — everything else needs translating first.",
  },
  {
    id: "passco-40",
    section: "mcq",
    question: "What are the three main types of computer programming languages?",
    options: ["machine language, assembly language, high level language", "imperative language, functional language, declarative language", "Pascal, Java, C++", "Interpreter, Compiler, Assembler"],
    answer: "machine language, assembly language, high level language",
    explanation: "This is the classic three-tier classification by how close a language is to raw hardware instructions. The other options are either an alternative CS classification, example languages, or translation tools — not the intro-course \"three main types\".",
  },
  {
    id: "passco-41",
    section: "mcq",
    question: "Which of the following is the main reason why computer programmers prefer to use a high-level language to the internal machine code or assembler language?",
    options: ["Program portability from one machine to another", "Ease and speed of writing program", "Efficiency", "All"],
    answer: "Ease and speed of writing program",
    explanation: "High-level languages are chosen mainly because they're far faster and easier to write and read. Portability is a genuine secondary benefit too, but efficiency is actually usually a downside compared to hand-tuned assembly, not a reason to prefer high-level languages.",
  },
  {
    id: "passco-42",
    section: "mcq",
    question: "A compiler produces an error in compiling a program because a closing curly bracket has been missed out in the source code. What type of error is this?",
    options: ["Syntax Error", "Logical Error", "Linker Error", "Compiler Error", "Missing Error"],
    answer: "Syntax Error",
    explanation: "A missing brace breaks the grammatical structure of the program, which the compiler catches as a syntax error — before it ever gets to checking meaning/logic.",
  },
  {
    id: "passco-43",
    section: "mcq",
    question: "Which of the following is an essential statement type for describing algorithms?",
    options: ["sequence", "selection", "repetition", "All the above"],
    answer: "All the above",
    explanation: "Sequence, selection, and repetition are the three fundamental building blocks of structured programming — every algorithm can be expressed with just these three.",
  },
  {
    id: "passco-44",
    section: "mcq",
    question: "Which of the following best describes a condition?",
    options: ["A value which is true or false", "A numerical value", "A value which is yes or no", "A and B are correct", "is a question type"],
    answer: "A value which is true or false",
    explanation: "A condition is fundamentally a Boolean value — true or false. A plain numerical value on its own isn't a condition.",
  },
  {
    id: "passco-45",
    section: "mcq",
    question: "Which of the following statements best describes a compiler?",
    options: [
      '"A compiler translates your program into machine code and then, if possible, runs the program"',
      '"A compiler produces a list of syntax and logical errors"',
      '"A compiler translates a correct program into machine code. Anything that cannot be translated causes a syntax error."',
      '"A compiler simply joins the different classes in your program together."',
      "None of these",
    ],
    answer: '"A compiler translates a correct program into machine code. Anything that cannot be translated causes a syntax error."',
    explanation: "A compiler translates and stops with a syntax error on anything it can't parse — it doesn't run the program (that's a separate step), reliably catch logical errors, or link classes together (that's the linker's job).",
  },

  // ---------- True / False block ----------
  {
    id: "passco-46",
    section: "true-false",
    question: "A user defined function cannot be defined before the main function.",
    answer: "False",
    explanation: "You can perfectly well write a function's full definition before main() in the same file — no prototype is even needed in that case.",
  },
  {
    id: "passco-47",
    section: "true-false",
    question: "A user defined function can be defined within the body of the main function.",
    answer: "False",
    explanation: "Standard C++ does not support nested function definitions — a function cannot be defined inside another function's body.",
  },
  {
    id: "passco-48",
    section: "true-false",
    question: "After the return 0; of the main function, a user defined function can follow.",
    answer: "True",
    explanation: "Function definitions can physically appear later in the file, after main() — that's a very common file layout.",
  },
  {
    id: "passco-49",
    section: "true-false",
    question: "If a user defined function is not called by the main function or other user defined function, the compiler will display an error message during program compilation.",
    answer: "False",
    explanation: "An unused function is not a compile error — at worst some compilers may emit a warning, but it will still compile and link fine.",
  },
  {
    id: "passco-50",
    section: "true-false",
    question: "The use of curly brackets to enclose the body of a user defined function is optional.",
    answer: "False",
    explanation: "A function body must be enclosed in { }; this is required, not optional.",
  },
  {
    id: "passco-51",
    section: "true-false",
    question: "The C++ compiler is not likely to indicate there is an error if the following are used as user defined function names: double, for, and repeat.",
    answer: "False",
    explanation: '"double" and "for" are reserved C++ keywords and cannot be used as function names — that would be a compile error. ("repeat" alone would be fine, since it isn\'t a keyword.)',
  },
  {
    id: "passco-52",
    section: "true-false",
    question: "All elements of an array are placed randomly in a computer memory for use.",
    answer: "False",
    explanation: "Array elements are stored contiguously (back-to-back) in memory, not randomly scattered — that's exactly what makes index arithmetic work.",
  },
  {
    id: "passco-53",
    section: "true-false",
    question: "It is not possible to write an arithmetic expression such that * is to the left of the = sign.",
    answer: "False",
    explanation: "It's very possible — a pointer declaration like `int *p = &x;` has * sitting to the left of =. (You just can't put a multiplication expression like `a*b` on the left of a plain assignment — that's a different point.)",
  },

  // ---------- Continuing MCQ/True-False numbering (54-78) ----------
  {
    id: "passco-54",
    section: "mcq",
    question: "The smallest amount of information possible is known as what?",
    options: ["Word", "byte", "Bit", "Data"],
    answer: "Bit",
    explanation: "A bit (binary digit, 0 or 1) is the smallest unit of information — a byte is a group of (usually) 8 bits.",
  },
  {
    id: "passco-55",
    section: "mcq",
    question: "Which of the following defines the correct order of steps to get a program to work on a personal computer?",
    options: ["type, edit, link, run, compile", "compile, link, edit, run", "edit, compile, link, run", "edit, link, compile, run"],
    answer: "edit, compile, link, run",
    explanation: "You write/edit the source first, compile it to object code, link it into an executable, then run it.",
  },
  {
    id: "passco-56",
    section: "mcq",
    question: "If at the end of a compilation process, a compiler displays the number of errors to be 1, then which of the following may best give the total number of errors in the program?",
    options: ["1", "8", "99", "any of the above", "Cannot tell exact number"],
    answer: "any of the above",
    explanation: "A single reported error can be the root cause of several cascading errors further down — once you fix it and recompile, more errors may surface. The reported count isn't necessarily the true total.",
  },
  {
    id: "passco-57",
    section: "mcq",
    question: "Which of the following best describes the program that allows you to type your source program so that it can later be compiled without having to exit the program?",
    options: ["Compiler", "Editor", "Linker", "Word processor such as Microsoft Word", "Algorithm"],
    answer: "Editor",
    explanation: "An (integrated) editor is where you type and manage source code before handing it off to the compiler, all without leaving the environment.",
  },
  {
    id: "passco-58",
    section: "mcq",
    question: "Which of the following is the best reason why one will have to document a program?",
    options: ["to assist the program user", "to assist the programmer", "to give to the software owner", "All the above", "both A and B above"],
    answer: "both A and B above",
    explanation: "Documentation exists to help both the people using the program and the programmers maintaining/extending it later — \"give it to the software owner\" isn't itself a purpose of documentation.",
  },
  {
    id: "passco-59",
    section: "true-false",
    question: "The main function of a program should have at least one return statement.",
    answer: "True",
    explanation: "This is good, recommended practice and what's taught at this level. (Technically, C++11 onward lets you omit it in main() specifically — the compiler implicitly returns 0 — but writing it explicitly is still the expected style.)",
  },
  {
    id: "passco-60",
    section: "true-false",
    question: "If two or more independent and very good programmers are asked to write an algorithm or program for finding the area under a curve using Simpson's rule, then one would expect that (assuming all solutions are correct) the programmers will come out with algorithms and programs of the same length or same number of lines in the source code. This is most of the time",
    answer: "False",
    explanation: "Different correct implementations can vary a lot in length and style — there's no single \"correct\" line count for a working solution.",
  },
  {
    id: "passco-61",
    section: "mcq",
    question: "Which statement can be used to obtain the remainder after dividing 5.32 by 4.91?",
    options: ["5.32 % 4.91", "5.32 mod 4.91", "mod (5.32, 4.91)", "fmod(5.32, 4.91)", "remainder cannot be obtained in floating point division"],
    answer: "fmod(5.32, 4.91)",
    explanation: "The % operator only works on integer types in C++. For floating-point remainders you need fmod() from <cmath>.",
  },
  {
    id: "passco-62",
    section: "mcq",
    question: "Which symbol is allowed in a variable name?",
    options: ["!", "¬", "^", "_", "#"],
    answer: "_",
    explanation: "The underscore is the only special character C++ identifiers are allowed to contain (along with letters and digits, though a digit can't start the name).",
  },
  {
    id: "passco-63",
    section: "mcq",
    question: "Which of the following will round off a number from 6.666 to 7.0?",
    options: ["roundup(6.666)", "floor(6.666)", "ceil(6.666)", "integer(6.666)", "None of the above"],
    answer: "ceil(6.666)",
    explanation: "ceil() rounds up to the next whole number. floor() would round down to 6, and roundup()/integer() aren't real C++ functions.",
  },
  {
    id: "passco-64",
    section: "mcq",
    question: "In most C++ compilers, by default a real number is considered as what?",
    options: ["double", "long double", "float", "short", "real"],
    answer: "double",
    explanation: "A floating-point literal like 3.14 defaults to type double unless it's explicitly suffixed with f/F (float) or l/L (long double).",
  },
  {
    id: "passco-65",
    section: "mcq",
    question: "Which of the following statements can be used to obtain the remainder when 2.81 is divided by 2.1, into the variable rem?",
    options: ["rem = 2.81/2.1;", "rem = 2.81%2.1;", "rem = mod(2.81,2.1);", "rem = fmod(2.81,2.1);", "None of the above"],
    answer: "rem = fmod(2.81,2.1);",
    explanation: "Same rule as before: % doesn't work on doubles, so fmod() from <cmath> is required.",
  },
  {
    id: "passco-66",
    section: "mcq",
    question: "Which of the following symbols is allowed in a variable name?",
    options: ["*", "~", "_", "-", "None of the above"],
    answer: "_",
    explanation: "Underscore is the only one of these that's legal inside a C++ identifier.",
  },
  {
    id: "passco-67",
    section: "mcq",
    question: "Which of the following statements can be used to round off 1.83 to 2.0?",
    options: ["ceiling(1.83)", "roundup(1.83)", "rounddown(1.83)", "floor(1.83)", "ceil(1.830)"],
    answer: "ceil(1.830)",
    explanation: "ceil() is the real C++ function for rounding up. floor() rounds down to 1 (wrong direction), and ceiling()/roundup()/rounddown() aren't standard functions.",
  },
  {
    id: "passco-68",
    section: "mcq",
    question: "A real number has which of the following as a default data type?",
    options: ["double", "float", "long double", "long float", "real"],
    answer: "double",
    explanation: "Same rule as before — floating-point literals default to double.",
  },
  {
    id: "passco-69",
    section: "mcq",
    question: "At what stage of coding do we make mention of a function prototype?",
    options: ["declaration", "definition", "calling", "prototyping", "None of the above"],
    answer: "declaration",
    explanation: "A function prototype is a declaration — it tells the compiler the function's signature before it's defined or called.",
  },
  {
    id: "passco-70",
    section: "mcq",
    question: "To transfer control from a user defined function back to the calling function one can use which of the following?",
    options: ["break", "continue", "goto", "return", "goback"],
    answer: "return",
    explanation: "return hands control (and optionally a value) back to whoever called the function. break/continue only affect loops/switches, and goback isn't a real keyword.",
  },
  {
    id: "passco-71",
    section: "mcq",
    question: "Passing an array as an argument to a function will normally pass what?",
    options: ["first element of the array", "last element of the array", "all elements of the array", "address of the array", "name of the array"],
    answer: "address of the array",
    explanation: "A plain array argument decays to a pointer to its first element — effectively its address — rather than copying every element.",
  },
  {
    id: "passco-72",
    section: "mcq",
    question: "Usually, a recursive function can result in infinite recursion if the following is left out.",
    options: ["recursive call", "an if statement", "a local variable declaration", "non-recursive call", "No subtraction"],
    answer: "an if statement",
    explanation: "Recursion needs a conditional base case (typically an if statement) that stops the recursive calls — without it, the function keeps calling itself forever.",
  },
  {
    id: "passco-73",
    section: "mcq",
    question: "It is possible to have two member functions of the same class sharing the same name. Is this statement true or false?",
    options: ["True", "False"],
    answer: "True",
    explanation: "That's function overloading — two member functions can share a name as long as their parameter lists differ.",
  },
  {
    id: "passco-74",
    section: "mcq",
    question: "Which of the following illustrates a relationship?",
    options: ["polymorphism", "overloading", "inheritance", "Data hiding", "None of the above"],
    answer: "inheritance",
    explanation: 'Inheritance describes an "is-a" relationship between a base class and a derived class. Overloading, polymorphism, and data hiding are behaviors/mechanisms, not relationships between classes.',
  },
  {
    id: "passco-75",
    section: "mcq",
    question: "Which of the following usually refers to accessing both the data and the methods defined together only in the same class or unit?",
    options: ["Encapsulation", "polymorphism", "Data hiding", "Data binding", "inheritance"],
    answer: "Encapsulation",
    explanation: "Encapsulation is exactly this: bundling data and the methods that operate on it together inside one class/unit.",
  },
  {
    id: "passco-76",
    section: "mcq",
    question: "Which of the following is a reason why it is good to use an object oriented programming language?",
    options: [
      "The language can taught to correct its own errors",
      "The language is intelligent to correct its own errors",
      "The language allows you to define your own data types",
      "The language makes it possible to conceptualise an object oriented program",
      "both (C) and (D) above",
    ],
    answer: "both (C) and (D) above",
    explanation: "Defining your own data types (classes) and being able to model/conceptualise a program in object-oriented terms are the real benefits. Languages don't correct their own errors — that's not a real capability.",
  },
  {
    id: "passco-77",
    section: "mcq",
    question: "A constructor can be taken to be ......",
    options: [
      "A function that is called when an instance of a class is to removed from memory",
      "A function that is called when an instance of a class is initialised",
      "A function that is called to change the initial value of a member variable",
      "A function that is called when it has not been called by the operating system",
      "None of the above",
    ],
    answer: "A function that is called when an instance of a class is initialised",
    explanation: "A constructor runs automatically when an object is created, to set up (initialise) its initial state. (The first option describes a destructor instead.)",
  },
  {
    id: "passco-78",
    section: "mcq",
    question: "Which of the following is true of a derived class?",
    options: [
      "Inherits constructor and destruction from base class",
      "inherits all members of a base class",
      "inherits all protected members of a base class",
      "inherits all public members of a base class",
      "both (C) and (D) are true",
    ],
    answer: "both (C) and (D) are true",
    explanation: "A derived class inherits its base class's protected and public members (though it doesn't get direct access to private members, and constructors/destructors themselves aren't inherited — they're re-run via the base class automatically instead).",
  },

  // ---------- Fill in the gap ----------
  { id: "passco-fib-1", section: "fill-blank", question: "The logical set of instructions that the computer follows in solving a given problem is known as ...............", answer: "an algorithm", explanation: "A step-by-step procedure for solving a problem, independent of any particular programming language." },
  { id: "passco-fib-2", section: "fill-blank", question: "The only language that the computer has been designed to understand is the .......................", answer: "machine language", explanation: "Raw binary instructions specific to the CPU — everything else must be translated down to this." },
  { id: "passco-fib-3", section: "fill-blank", question: "Words that have special meaning in a programming language are known as ................", answer: "keywords (reserved words)", explanation: 'Words like int, if, return, and class have fixed meaning to the compiler and can\'t be reused as identifiers.' },
  { id: "passco-fib-4", section: "fill-blank", question: "Names or words that are used by programmers in their programs are known as ....................", answer: "identifiers", explanation: "Programmer-chosen names for variables, functions, classes, etc." },
  { id: "passco-fib-5", section: "fill-blank", question: "................ accepts as input an object code and library functions, if any, as input during program compilation.", answer: "The linker", explanation: "The linker combines your compiled object code with any needed library code to produce the final executable." },
  { id: "passco-fib-6", section: "fill-blank", question: "A single line of comment usually starts with ............ while a multiple line comment usually starts with ..............", answer: "// … /*", explanation: "// comments out to the end of the line; /* ... */ can span multiple lines." },
  { id: "passco-fib-7", section: "fill-blank", question: "A programmer must follow ................ rule when writing his/her program.", answer: "syntax", explanation: "The grammar rules of the language — get them wrong and the compiler reports a syntax error." },
  { id: "passco-fib-8", section: "fill-blank", question: "................ is a diagram that graphically represents the structure of a program.", answer: "A flowchart", explanation: "Flowcharts show a program's logic visually using standard shapes for steps, decisions, and flow." },
  { id: "passco-fib-9", section: "fill-blank", question: "................ is information that a program sends to the outside world.", answer: "Output", explanation: "As opposed to input, which is information the program receives." },
  { id: "passco-fib-10", section: "fill-blank", question: "A predefined header file is usually enclosed in ............ while a programmer defined header file is enclosed in ................", answer: "angle brackets < > … double quotes \" \"", explanation: 'e.g. #include<iostream> for standard headers vs #include"myheader.h" for your own.' },
  { id: "passco-fib-11", section: "fill-blank", question: "The built-in or predefined function for finding the factorial of a number is ..........................", answer: "There isn't one built in", explanation: "C++ has no standard factorial() function — you write your own loop or recursive function. (The closest standard-library relative is tgamma(n+1) from <cmath>, since the Gamma function relates to factorials.)" },
  { id: "passco-fib-12", section: "fill-blank", question: "The escape sequence, ............, causes the computer to beep.", answer: "\\a", explanation: "The alert/bell escape sequence." },
  { id: "passco-fib-13", section: "fill-blank", question: "The equivalent of 'endl' is ..........................", answer: "\\n", explanation: "Both move output to a new line; endl also flushes the output buffer, which \\n alone does not." },
  { id: "passco-fib-14", section: "fill-blank", question: "Assume the int data type has the range -32768 to +32767. What will be the value of an int variable whose current value is -32768 if one (1) is deducted from this value?", answer: "32767", explanation: "Going one below the minimum representable value wraps around to the maximum (32767) under typical two's-complement overflow — though strictly, signed integer overflow is undefined behaviour in C++." },
  { id: "passco-fib-15", section: "fill-blank", question: "A variable name must begin with either ............... or ...................", answer: "a letter … an underscore (_)", explanation: "It can't start with a digit." },
  { id: "passco-fib-16", section: "fill-blank", question: "The ............ must be included in any program that uses the mathematical functions.", answer: "<cmath> header", explanation: 'Needed for functions like sqrt(), pow(), ceil(), floor(), and fmod().' },
  { id: "passco-fib-17", section: "fill-blank", question: "The operator, &, is known as ...................", answer: "the address-of operator", explanation: "Placed before a variable, & yields that variable's memory address (it's also used to declare references)." },
  { id: "passco-fib-18", section: "fill-blank", question: "The name of the symbol, >>, is ..........................", answer: "the extraction operator", explanation: "Used with cin to pull data out of the input stream into a variable." },
  { id: "passco-fib-19", section: "fill-blank", question: "The symbol, <<, is known as ..........................", answer: "the insertion operator", explanation: "Used with cout to insert data into the output stream." },
  { id: "passco-fib-20", section: "fill-blank", question: "The fastest sorting technique is known as ..................", answer: "Quicksort (commonly cited)", explanation: "Quicksort averages O(n log n) and is the classic answer at this level — though in reality the \"fastest\" sort depends on the data, and no single algorithm wins in every case." },
  { id: "passco-fib-21", section: "fill-blank", question: "The two main ways of finding an item in an array are .............. and ..............", answer: "linear search … binary search", explanation: "Linear search checks every element in order; binary search repeatedly halves a sorted range." },
  { id: "passco-fib-22", section: "fill-blank", question: "One can compare the first 3 characters of two strings by using the .............. function.", answer: "strncmp", explanation: "strncmp(str1, str2, 3) compares only the first 3 characters of two C-strings." },
  { id: "passco-fib-23", section: "fill-blank", question: "The value usually returned by a relational expression when it evaluates to true is ..................", answer: "1", explanation: "C++ represents boolean true as the integer 1 (and false as 0) when treated as an int." },
  { id: "passco-fib-24", section: "fill-blank", question: "A variable that has a ................ scope can only be used in a user defined function in which it is declared.", answer: "local", explanation: "A local variable only exists and is visible inside the function (or block) where it's declared." },
  { id: "passco-fib-25", section: "fill-blank", question: "A program usually falls through a case section the ................ statement is missing.", answer: "break", explanation: "Without break, a switch statement keeps executing into the next case (\"fall-through\")." },
  { id: "passco-fib-26", section: "fill-blank", question: "A/An .................... can give you all you need to know about the use of a function.", answer: "function prototype (declaration)", explanation: "The prototype spells out the function's name, parameters, and return type — everything a caller needs to know." },
  { id: "passco-fib-27", section: "fill-blank", question: "The part of a user defined function definition that shows the name of the function, parameter list and the return type is ..................................", answer: "the function header", explanation: "e.g. `int add(int a, int b)` — everything before the opening brace." },
  { id: "passco-fib-28", section: "fill-blank", question: "If a function does not return a value then its return data type should be specified as ..................", answer: "void", explanation: "void explicitly signals \"this function returns nothing.\"" },
  { id: "passco-fib-29", section: "fill-blank", question: "A function A that needs the services of function B will have to .................... function B.", answer: "call", explanation: "Function A invokes (calls) function B to use its behavior." },
  { id: "passco-fib-30", section: "fill-blank", question: "Two or more functions can share the same name but must have different ..............................", answer: "parameter lists (signatures)", explanation: "This is function overloading — the compiler tells overloads apart by their parameter types/count." },
  { id: "passco-fib-31", section: "fill-blank", question: "Function headers are usually terminated with ..........................", answer: "nothing — no semicolon", explanation: "Unlike a function prototype (which ends in a semicolon), a function's header is followed directly by its body's opening brace { , with no semicolon." },
  { id: "passco-fib-32", section: "fill-blank", question: "The .......... error is the most difficult to detect when they occur.", answer: "logical", explanation: "Logic errors compile and run fine, but produce the wrong result — there's no compiler message pointing you to the bug." },
  { id: "passco-fib-33", section: "fill-blank", question: "A union that has no name is known as ..................................................", answer: "an anonymous union", explanation: "Its members are accessed directly in the enclosing scope, without a union-name qualifier." },
  { id: "passco-fib-34", section: "fill-blank", question: "By default the members of a class are .......................................................", answer: "private", explanation: "class defaults to private members; struct defaults to public — that's the one difference between the two keywords in C++." },

  // ---------- Code trace bonus ----------
  {
    id: "passco-trace-1",
    section: "code-trace",
    question: "Trace this program's output for the three given inputs. Pay close attention to the third one.",
    code: '#include<iostream>\n#include<iomanip>\nusing namespace std;\nvoid getInput();\nvoid display();\nint dd,mm,yy;\nint main()\n{\n  getInput();\n  display();\n  system("pause");\n  return 0;\n}\nvoid getInput()\n{\n  cout<<"Please enter the date in the form dd mm yy ";\n  cin >>dd >>mm >>yy;\n}\nvoid display()\n{\n  char mth[13][10]={"","January","February","March","April",\n  "May","June","July","August","September","October","November",\n  "December"};\n  cout<<setw(4) <<dd <<setw(4)<<mm <<setw(7)<<yy <<" is "<<dd;\n  switch (dd)\n  {\n    case 1: case 21:case 31:cout<<"st ";break;\n    case 2: case 22 :cout<<"nd ";break;\n    case 3: case 23 :cout<<"rd ";break;\n    default: cout<<"th ";\n  }\n  cout<<mth[mm]<<" "<<yy<<endl;\n}',
    answer: "i. \"10 10 2012\" → prints \"10th October 2012\"\nii. \"2 12 2011\" → prints \"2nd December 2011\"\niii. \"33 15 2\" → undefined behaviour — mth[15] reads past the end of the mth array",
    explanation: "For (i) and (ii), dd picks the right ordinal suffix from the switch and mm indexes a valid month name. For (iii), mm=15 is out of range for `char mth[13][10]` (valid indices are 0-12) — reading mth[15] is undefined behaviour: it might print garbage text, unrelated memory, or crash, since C++ does not bounds-check plain array access.",
  },
];
