import type { MCQ } from "@/lib/mcqBank";

export const networkingMcqBank: MCQ[] = [
  {
    id: "n-mcq-1",
    question: "A host has IP 192.168.10.70 with mask 255.255.255.192 (/26). What is its network address?",
    options: ["192.168.10.0", "192.168.10.64", "192.168.10.128", "192.168.10.192"],
    correctIndex: 1,
    explanation:
      "70 in binary is 01000110; ANDed with the mask's last octet 11000000 (192) gives 01000000 = 64. So the network address is 192.168.10.64.",
  },
  {
    id: "n-mcq-2",
    question: "How many usable host addresses does a /28 subnet provide?",
    options: ["16", "14", "30", "32"],
    correctIndex: 1,
    explanation:
      "/28 leaves 4 host bits, so 2^4 = 16 total addresses. Subtracting the network and broadcast addresses (never assignable to a host) leaves 14 usable.",
  },
  {
    id: "n-mcq-3",
    question: "Which IPv4 address class does 200.15.6.4 belong to?",
    options: ["Class A", "Class B", "Class C", "Class D"],
    correctIndex: 2,
    explanation: "First-octet ranges: A = 0-127, B = 128-191, C = 192-223, D = 224-239. 200 falls in the class C range.",
  },
  {
    id: "n-mcq-4",
    question: "What does the /24 in CIDR notation like 10.0.5.0/24 actually specify?",
    options: [
      "The encryption strength used on the connection",
      "How many leftmost bits of the address count as the network portion",
      "The physical length of the network cable",
      "The maximum number of packets per second",
    ],
    correctIndex: 1,
    explanation:
      "CIDR's /n is simply the prefix length — the number of leftmost bits treated as the network part, replacing the old fixed class A/B/C boundaries.",
  },
  {
    id: "n-mcq-5",
    question: "Borrowing 3 bits from a Class C network's host portion creates how many subnets?",
    options: ["4", "6", "8", "16"],
    correctIndex: 2,
    explanation: "Each borrowed bit doubles the number of subnets: 2^3 = 8 subnets.",
  },
  {
    id: "n-mcq-6",
    question: "Which protocol sits on top of IP and adds reliability — resending lost packets and keeping them in order?",
    options: ["UDP", "TCP", "ARP", "ICMP"],
    correctIndex: 1,
    explanation:
      "TCP is connection-oriented and reliable: it splits messages into packets, reassembles them in order, and resends anything lost. IP itself makes no such guarantees.",
  },
  {
    id: "n-mcq-7",
    question: "Why can't Wi-Fi detect collisions the same way wired Ethernet does?",
    options: [
      "Wi-Fi doesn't use radio waves",
      "A wireless device can't reliably transmit and listen for other signals at the same time",
      "Wireless packets are too small to collide",
      "Collisions cannot physically happen over the air",
    ],
    correctIndex: 1,
    explanation:
      "An Ethernet device can listen while it transmits, so it can notice a collision as it happens. A Wi-Fi radio's own transmission drowns out anything else, so it can't listen at the same time — hence collision avoidance (CSMA/CA) instead of detection.",
  },
  {
    id: "n-mcq-8",
    question: "Compared to a switch, a router's defining job is to:",
    options: [
      "Connect networks with different/incompatible addressing into a network of networks (an internet)",
      "Simply extend one network's signal range",
      "Only ever operate within a single LAN",
      "Encrypt all traffic that passes through it",
    ],
    correctIndex: 0,
    explanation:
      "A switch connects several compatible devices/networks. A router specifically connects networks that aren't directly compatible — wiring enough routers together is literally what \"an internet\" means.",
  },
  {
    id: "n-mcq-9",
    question: "In binary, how does a subnet's broadcast address relate to its network address?",
    options: [
      "All host bits set to 0",
      "All host bits set to 1",
      "Only the first host bit set to 1",
      "It's identical to the network address",
    ],
    correctIndex: 1,
    explanation:
      "The network address has all host bits at 0; the broadcast address is the same network prefix with every host bit flipped to 1 — the highest address in the block.",
  },
  {
    id: "n-mcq-10",
    question:
      "A network needs 3 subnets sized for 110, 45, and 50 hosts from a single Class C network. Why can't one fixed subnet mask satisfy all three?",
    options: [
      "A single fixed mask forces every subnet to be the same size, but these departments need different sizes",
      "Class C networks cannot be subnetted at all",
      "CIDR blocks are not allowed to be split further",
      "VLSM only works on Class A and B networks",
    ],
    correctIndex: 0,
    explanation:
      "One subnet mask always produces equal-sized subnets. Since the three requirements are all different sizes, no single mask can fit all of them without wasting a lot of addresses — that's exactly the problem VLSM (Variable Length Subnet Masking) solves.",
  },

  // ---------- Computer Science Foundations (networking as applied CS) ----------
  {
    id: "n-mcq-cs-1",
    question: "The OSI model's seven layers illustrate a general computer science design principle. Which one?",
    options: [
      "Abstraction/separation of concerns — each layer only needs its neighbour's interface, not how that neighbour works internally",
      "Recursion",
      "Object-oriented inheritance",
      "Dynamic programming",
    ],
    correctIndex: 0,
    explanation: "Layering is abstraction in action: the transport layer doesn't need to know how the physical layer moves bits, it just needs the interface the network layer below it exposes — the same principle behind APIs and modular software design.",
  },
  {
    id: "n-mcq-cs-2",
    question: "Link-state routing protocols like OSPF compute shortest paths using an algorithm most similar to:",
    options: ["Dijkstra's shortest-path algorithm", "Bubble sort", "Binary search", "Depth-first search for cycle detection only"],
    correctIndex: 0,
    explanation: "Each link-state router builds a full map of the network as a graph, then runs a Dijkstra-style shortest-path computation rooted at itself to build its routing table.",
  },
  {
    id: "n-mcq-cs-3",
    question: "Distance-vector routing protocols (like the original RIP) are based on which graph algorithm?",
    options: ["Bellman-Ford", "Dijkstra", "Kruskal's minimum spanning tree", "Depth-first search"],
    correctIndex: 0,
    explanation: "Distance-vector routing iteratively relaxes distance estimates using only neighbour-reported distances — the Bellman-Ford approach — unlike Dijkstra, which needs a full, globally known graph.",
  },
  {
    id: "n-mcq-cs-4",
    question: "DNS resolves domain names to IP addresses using what kind of system?",
    options: [
      "A distributed, hierarchical database queried top-down from root servers to authoritative servers",
      "A single centralized server that every request in the world goes to",
      "A blockchain ledger",
      "A local file only, never queried over the network",
    ],
    correctIndex: 0,
    explanation: "DNS is deliberately distributed and hierarchical (root → TLD → authoritative servers) — exactly the kind of design a single global system needs to scale without one server being a bottleneck or a single point of failure.",
  },
  {
    id: "n-mcq-cs-5",
    question: "A DNS record's TTL (time to live) exists for the same fundamental reason a cache entry expires in any computer system:",
    options: [
      "To balance staleness (serving outdated cached data) against the cost/latency of repeatedly fetching fresh data",
      "To encrypt the record",
      "To count how many network hops a packet has taken",
      "To limit how many bits the record can use",
    ],
    correctIndex: 0,
    explanation: "This is the classic caching tradeoff in computer science: cache too long and you risk staleness; refetch too often and you lose the whole performance benefit of caching. DNS TTLs are that same tradeoff applied to name resolution.",
  },
  {
    id: "n-mcq-cs-6",
    question: "Packet switching (used by the Internet) differs from circuit switching (used by the traditional telephone network) mainly in that:",
    options: [
      "Packet switching dynamically shares link capacity among many flows (statistical multiplexing) instead of reserving one dedicated path for a whole session",
      "Packet switching requires establishing a dedicated end-to-end circuit before any data can move",
      "Circuit switching is what splits messages into small packets",
      "Packet switching cannot be used for real-time traffic under any circumstances",
    ],
    correctIndex: 0,
    explanation: "Circuit switching reserves fixed capacity for the whole call's duration, even during silence. Packet switching instead statistically multiplexes many flows' packets over the same shared links — far more efficient use of capacity, at the cost of variable delay.",
  },
  {
    id: "n-mcq-cs-7",
    question: "TCP congestion control (slow start, additive increase/multiplicative decrease) is best described in computer-science terms as:",
    options: [
      "A feedback control loop that adapts the sending rate based on observed network conditions like packet loss",
      "A fixed, unchanging transmission rate agreed once at connection start",
      "A purely random retransmission strategy",
      "A method for compressing data before sending it",
    ],
    correctIndex: 0,
    explanation: "TCP congestion control continuously measures signals like packet loss and adjusts its sending rate in response — a textbook feedback control loop, the same kind of adaptive-system idea that shows up throughout CS (thermostat-style control, adaptive algorithms, etc.).",
  },
  {
    id: "n-mcq-cs-8",
    question: "A checksum or CRC (cyclic redundancy check) attached to a packet exists to:",
    options: [
      "Let the receiver detect (though not usually correct) whether the data was corrupted in transit",
      "Encrypt the payload so no one else can read it",
      "Compress the packet down to a smaller size",
      "Guarantee the packet arrives faster",
    ],
    correctIndex: 0,
    explanation: "A CRC is an error-detecting code: the sender computes a value from the data and attaches it; the receiver recomputes it and compares. A mismatch reveals corruption — but detection is not correction, and it says nothing about confidentiality.",
  },
  {
    id: "n-mcq-cs-9",
    question: "HTTPS uses TLS, which typically works by:",
    options: [
      "Using asymmetric (public-key) cryptography to securely agree on a shared secret, then switching to fast symmetric encryption for the rest of the session",
      "Using one shared static password for every website in the world",
      "Sending all data in plain text but over a different port number",
      "Compressing data instead of encrypting it",
    ],
    correctIndex: 0,
    explanation: "TLS combines both cryptographic families: slow-but-key-exchange-friendly asymmetric crypto during the handshake, then fast symmetric crypto (which needs a shared key) for the bulk of the actual data — the standard hybrid approach used across applied cryptography.",
  },
  {
    id: "n-mcq-cs-10",
    question: "In a peer-to-peer (P2P) architecture, compared to a classic client-server architecture:",
    options: [
      "Every node can act as both a client and a server, sharing resources directly with other peers instead of relying on one central server",
      "Only one designated server may ever exist",
      "All communication must first pass through a central authority",
      "There is no such thing as a peer-to-peer network on the modern Internet",
    ],
    correctIndex: 0,
    explanation: "P2P systems decentralize the client/server roles — every participant can serve data to, and request data from, any other peer, removing the single central bottleneck a pure client-server model relies on.",
  },
  {
    id: "n-mcq-cs-11",
    question: "A load balancer distributing incoming requests across backend servers using \"round robin\" means:",
    options: [
      "It sends each new request to the next server in a fixed rotating order, cycling back to the start",
      "It always sends every request to the single fastest server",
      "It randomly drops half of all incoming requests",
      "It merges all the backend servers into a single machine",
    ],
    correctIndex: 0,
    explanation: "Round robin is one of the simplest load-balancing algorithms: cycle through the list of servers in order, one request each, wrapping back to the first server once the list is exhausted.",
  },
  {
    id: "n-mcq-cs-12",
    question: "Bandwidth and latency are different network performance metrics. Which best describes the difference?",
    options: [
      "Bandwidth is how much data can be sent per unit time (capacity); latency is how long a single piece of data takes to arrive (delay)",
      "They are two names for exactly the same thing",
      "Bandwidth measures delay; latency measures capacity",
      "Both only apply to wireless networks",
    ],
    correctIndex: 0,
    explanation: "A common analogy: bandwidth is the width of a pipe (how much can flow through at once); latency is how long it takes a single drop to travel from one end to the other. A link can have huge bandwidth and still have high latency, or vice versa.",
  },
  {
    id: "n-mcq-cs-13",
    question: "NAT (Network Address Translation) lets many devices on a private network share one public IP address — conceptually similar to which other CS idea?",
    options: [
      "Virtual memory, where a program's logical addresses are transparently translated to different physical addresses",
      "A hash collision",
      "A compiler optimization pass",
      "A binary search tree rotation",
    ],
    correctIndex: 0,
    explanation: "Both NAT and virtual memory insert a translation layer between an internal, private address space and an external, real one — hiding the internal addressing scheme from the outside world.",
  },
  {
    id: "n-mcq-cs-14",
    question: "DHCP automatically assigns IP addresses to devices as they join a network. This is analogous to which general CS concept?",
    options: [
      "Dynamic (runtime) resource allocation — handing out a free resource from a pool on request and reclaiming it when the lease expires",
      "Static, compile-time memory allocation",
      "A sorting algorithm",
      "Public-key encryption",
    ],
    correctIndex: 0,
    explanation: "DHCP is essentially a resource-pool manager: it hands out an available IP address (a resource) on demand and reclaims it after a lease expires — the same pattern as a runtime memory allocator handing out and reclaiming blocks.",
  },
  {
    id: "n-mcq-cs-15",
    question: "A firewall's rule set, which allows or blocks traffic based on source/destination address and port, is conceptually closest to:",
    options: [
      "An access control list (ACL) — a set of permission rules checked against each request",
      "A compression algorithm",
      "A routing table used purely for path-finding",
      "A load-balancing algorithm",
    ],
    correctIndex: 0,
    explanation: "A firewall ruleset is an ACL applied to network traffic: each packet is checked against an ordered list of allow/deny rules, the same underlying pattern used for file-permission and API-authorization systems.",
  },
  {
    id: "n-mcq-cs-16",
    question: "HTTP is described as a \"stateless\" protocol, meaning:",
    options: [
      "The server doesn't automatically remember anything about previous requests from the same client — each request must carry whatever context it needs (or rely on something like cookies)",
      "The server crashes after every single request",
      "Only GET requests are allowed",
      "Data cannot be transmitted more than once",
    ],
    correctIndex: 0,
    explanation: "Statelessness means each HTTP request is handled independently, with no built-in memory of earlier requests — a deliberate design choice that makes it far easier to scale web servers horizontally, since any server can handle any request.",
  },
  {
    id: "n-mcq-cs-17",
    question: "Using a binary heap priority queue, Dijkstra's shortest-path algorithm (as used inside link-state routing) runs in:",
    options: ["O((V + E) log V)", "O(V²), with no faster option possible", "O(1)", "O(V!)"],
    correctIndex: 0,
    explanation: "Each of the E edge relaxations costs O(log V) to update the priority queue, plus V extract-min operations, giving O((V + E) log V) — significantly faster than the naive O(V²) array-based implementation on sparse graphs like real router topologies.",
  },
  {
    id: "n-mcq-cs-18",
    question: "The TCP three-way handshake (SYN, SYN-ACK, ACK) is fundamentally an example of:",
    options: [
      "A finite-state protocol negotiation both sides use to reliably agree they're ready to communicate",
      "A method for encrypting the connection",
      "A way to compress data before sending it",
      "A load-balancing technique",
    ],
    correctIndex: 0,
    explanation: "The handshake is a small finite-state-machine exchange: each side moves through defined states (SYN-SENT, SYN-RECEIVED, ESTABLISHED...) and only proceeds once it has confirmation the other side is ready — a general pattern used throughout protocol design.",
  },
  {
    id: "n-mcq-cs-19",
    question: "When a packet is larger than a network link's MTU (maximum transmission unit), IP fragmentation splits it into smaller pieces — conceptually similar to:",
    options: [
      "Paging in an operating system, which breaks a large block of memory into fixed-size chunks that fit hardware constraints",
      "Encrypting the packet",
      "Sorting the packet's bytes",
      "Reversing the packet's byte order",
    ],
    correctIndex: 0,
    explanation: "Both fragmentation and paging solve the same underlying problem: a piece of data is too large for the fixed-size unit the underlying hardware/link can handle, so it gets broken into smaller, uniformly bounded pieces and reassembled later.",
  },
  {
    id: "n-mcq-cs-20",
    question: "traceroute discovers each router along a path by sending packets with a TTL that starts at 1 and increases by 1 each round. This works because:",
    options: [
      "Each router decrements TTL by 1 and drops the packet with an error reply once it reaches 0, revealing itself one hop at a time",
      "TTL directly encodes the router's IP address",
      "It only works over TCP, never any other protocol",
      "It requires disabling encryption first",
    ],
    correctIndex: 0,
    explanation: "TTL was designed to stop packets looping forever, but traceroute repurposes that exact mechanism: by sending packets that are guaranteed to \"time out\" at hop 1, then hop 2, and so on, it forces each successive router to reveal itself via the error reply.",
  },
  {
    id: "n-mcq-cs-21",
    question: "Real routers look up the correct next hop for an IP address using \"longest prefix matching.\" A trie (prefix tree) is a natural data structure for this because:",
    options: [
      "It lets the router walk bit by bit down the tree to efficiently find the most specific (longest) matching prefix",
      "A trie is only useful for sorting numbers",
      "Tries cannot represent binary data like IP addresses",
      "It requires linearly scanning the entire routing table on every lookup, which a trie is specifically built to avoid",
    ],
    correctIndex: 0,
    explanation: "A trie organizes routes by shared address prefixes, so a lookup walks down bit by bit and naturally finds the longest matching prefix without ever scanning the whole table — critical for routers that must forward packets at line speed.",
  },
  {
    id: "n-mcq-cs-22",
    question: "A pure client-server architecture with only one central server has an important weakness compared to a well-designed distributed system:",
    options: [
      "It has a single point of failure — if that one server goes down, the whole service becomes unavailable",
      "It cannot ever serve more than one client",
      "It is always faster than any distributed system",
      "It cannot be used over the Internet at all",
    ],
    correctIndex: 0,
    explanation: "Centralizing everything on one server creates one failure point that takes the whole service down with it — a core motivation behind replication, redundancy, and distributed-systems design more broadly.",
  },
  {
    id: "n-mcq-cs-23",
    question: "Why does TLS use slow asymmetric encryption only briefly during the handshake, then switch to fast symmetric encryption for the bulk of the data?",
    options: [
      "Asymmetric encryption is computationally far more expensive per byte, so it's used only to safely exchange a symmetric key, then the cheaper cipher takes over",
      "Symmetric encryption cannot be broken while asymmetric encryption can",
      "Asymmetric encryption doesn't work over the Internet",
      "Symmetric keys are always physically longer than asymmetric keys",
    ],
    correctIndex: 0,
    explanation: "Asymmetric (public-key) operations are orders of magnitude more computationally expensive than symmetric ones. Using them only to bootstrap a shared secret, then handing off to symmetric encryption, gets the security benefit of public-key crypto without paying its full cost on every byte.",
  },
  {
    id: "n-mcq-cs-24",
    question: "A device's IP address identifies the host, but a port number identifies:",
    options: [
      "Which specific process/application on that host a piece of data is meant for, letting one IP address serve many services at once",
      "The physical network cable being used",
      "The exact wall-clock time the packet was sent",
      "The manufacturer of the network card",
    ],
    correctIndex: 0,
    explanation: "Ports are a demultiplexing mechanism: the OS uses the port number to route incoming data to the correct running process — conceptually similar to how a process ID or file descriptor identifies one specific thing among many on the same machine.",
  },
  {
    id: "n-mcq-cs-25",
    question: "Compressing data before sending it over a network (e.g., gzip on an HTTP response) works because most real-world data:",
    options: [
      "Contains statistical redundancy that a compression algorithm can encode more compactly",
      "Is already in its smallest possible form and cannot shrink further",
      "Must first be decrypted before it can be sent",
      "Is always exactly the same size regardless of content",
    ],
    correctIndex: 0,
    explanation: "Lossless compression exploits redundancy and predictable patterns in data (repeated substrings, skewed symbol frequencies) — an application of information theory: the more predictable the data, the more it can be shrunk.",
  },
  {
    id: "n-mcq-cs-26",
    question: "A CDN (content delivery network) improves web performance mainly by:",
    options: [
      "Caching copies of content on servers geographically close to users, cutting the physical distance (and thus latency) data has to travel",
      "Increasing the speed of light",
      "Removing the need for any DNS lookups",
      "Encrypting content more strongly than normal",
    ],
    correctIndex: 0,
    explanation: "Since latency is fundamentally bounded by distance and the speed of light in fibre, a CDN's core trick is simply moving cached copies of content physically closer to users — a distributed-caching strategy, not a faster transmission medium.",
  },
  {
    id: "n-mcq-cs-27",
    question: "The core problem that motivated IPv6 — a fixed-width 32-bit address space eventually running out of room — is directly analogous to which other classic CS scenario?",
    options: [
      "32-bit systems running out of directly addressable memory, pushing adoption of 64-bit architectures",
      "A stack overflow from deep recursion",
      "A hash table with zero collisions",
      "A sorting algorithm reaching its best case",
    ],
    correctIndex: 0,
    explanation: "Both are the same underlying problem: a fixed number of bits caps how many distinct things (addresses, or bytes of memory) can be represented. Once real-world growth exceeds 2ⁿ, the only fix is widening the address, exactly as 32-bit memory addressing gave way to 64-bit.",
  },
  {
    id: "n-mcq-cs-28",
    question: "UDP is preferred over TCP for real-time applications like video calls or online gaming because:",
    options: [
      "UDP has lower overhead and doesn't wait to retransmit lost data, prioritizing low latency over guaranteed delivery — a late video frame is often more useless than a dropped one",
      "UDP is always more reliable than TCP",
      "UDP automatically encrypts everything it sends",
      "UDP cannot be used over Wi-Fi",
    ],
    correctIndex: 0,
    explanation: "This is a classic engineering tradeoff: TCP's reliability guarantees come at the cost of retransmission delay, which real-time applications can't afford — receiving a video frame late is often worse than not receiving it at all, so UDP's \"fire and forget\" model wins there.",
  },
  {
    id: "n-mcq-cs-29",
    question: "ARP spoofing, a classic network attack, works by:",
    options: [
      "Sending forged ARP replies so a victim's device associates the attacker's MAC address with another device's IP address, misdirecting traffic",
      "Encrypting all packets on the network so no one else can read them",
      "Physically cutting the network cable",
      "Increasing everyone's available bandwidth",
    ],
    correctIndex: 0,
    explanation: "ARP has no built-in authentication, so a malicious host can simply broadcast a forged reply claiming to own another device's IP — a security weakness that comes directly from ARP trusting whatever reply arrives, with no verification.",
  },
  {
    id: "n-mcq-cs-30",
    question: "CIDR route aggregation (\"supernetting\") — combining many small routing table entries into one larger prefix — mainly helps because:",
    options: [
      "It reduces the number of entries core routers must store and search, which matters since a routing-table lookup happens on every single packet",
      "It encrypts routing announcements",
      "It increases the total number of usable IP addresses in the world",
      "It eliminates the need for routers altogether",
    ],
    correctIndex: 0,
    explanation: "Every packet a router forwards triggers a routing-table lookup, so table size directly affects lookup speed and memory use at massive scale. Aggregating many specific routes into one summarized prefix keeps that table — and the per-packet lookup cost — manageable.",
  },
];
