import type { MCQ } from "@/lib/mcqBank";

export const networkingMcqBank: MCQ[] = [
  {
    id: "n-mcq-1",
    question: "A host has IP 192.168.10.70 with mask 255.255.255.192 (/26). What is its network address?",
    options: ["192.168.10.0", "192.168.10.64", "192.168.10.128", "192.168.10.192"],
    correctIndex: 1,
    explanation:
      "70 in binary is 01000110; ANDed with the mask's last octet 11000000 (192) gives 01000000 = 64. So the network address is 192.168.10.64.",
  },
  {
    id: "n-mcq-2",
    question: "How many usable host addresses does a /28 subnet provide?",
    options: ["16", "14", "30", "32"],
    correctIndex: 1,
    explanation:
      "/28 leaves 4 host bits, so 2^4 = 16 total addresses. Subtracting the network and broadcast addresses (never assignable to a host) leaves 14 usable.",
  },
  {
    id: "n-mcq-3",
    question: "Which IPv4 address class does 200.15.6.4 belong to?",
    options: ["Class A", "Class B", "Class C", "Class D"],
    correctIndex: 2,
    explanation: "First-octet ranges: A = 0-127, B = 128-191, C = 192-223, D = 224-239. 200 falls in the class C range.",
  },
  {
    id: "n-mcq-4",
    question: "What does the /24 in CIDR notation like 10.0.5.0/24 actually specify?",
    options: [
      "The encryption strength used on the connection",
      "How many leftmost bits of the address count as the network portion",
      "The physical length of the network cable",
      "The maximum number of packets per second",
    ],
    correctIndex: 1,
    explanation:
      "CIDR's /n is simply the prefix length — the number of leftmost bits treated as the network part, replacing the old fixed class A/B/C boundaries.",
  },
  {
    id: "n-mcq-5",
    question: "Borrowing 3 bits from a Class C network's host portion creates how many subnets?",
    options: ["4", "6", "8", "16"],
    correctIndex: 2,
    explanation: "Each borrowed bit doubles the number of subnets: 2^3 = 8 subnets.",
  },
  {
    id: "n-mcq-6",
    question: "Which protocol sits on top of IP and adds reliability — resending lost packets and keeping them in order?",
    options: ["UDP", "TCP", "ARP", "ICMP"],
    correctIndex: 1,
    explanation:
      "TCP is connection-oriented and reliable: it splits messages into packets, reassembles them in order, and resends anything lost. IP itself makes no such guarantees.",
  },
  {
    id: "n-mcq-7",
    question: "Why can't Wi-Fi detect collisions the same way wired Ethernet does?",
    options: [
      "Wi-Fi doesn't use radio waves",
      "A wireless device can't reliably transmit and listen for other signals at the same time",
      "Wireless packets are too small to collide",
      "Collisions cannot physically happen over the air",
    ],
    correctIndex: 1,
    explanation:
      "An Ethernet device can listen while it transmits, so it can notice a collision as it happens. A Wi-Fi radio's own transmission drowns out anything else, so it can't listen at the same time — hence collision avoidance (CSMA/CA) instead of detection.",
  },
  {
    id: "n-mcq-8",
    question: "Compared to a switch, a router's defining job is to:",
    options: [
      "Connect networks with different/incompatible addressing into a network of networks (an internet)",
      "Simply extend one network's signal range",
      "Only ever operate within a single LAN",
      "Encrypt all traffic that passes through it",
    ],
    correctIndex: 0,
    explanation:
      "A switch connects several compatible devices/networks. A router specifically connects networks that aren't directly compatible — wiring enough routers together is literally what \"an internet\" means.",
  },
  {
    id: "n-mcq-9",
    question: "In binary, how does a subnet's broadcast address relate to its network address?",
    options: [
      "All host bits set to 0",
      "All host bits set to 1",
      "Only the first host bit set to 1",
      "It's identical to the network address",
    ],
    correctIndex: 1,
    explanation:
      "The network address has all host bits at 0; the broadcast address is the same network prefix with every host bit flipped to 1 — the highest address in the block.",
  },
  {
    id: "n-mcq-10",
    question:
      "A network needs 3 subnets sized for 110, 45, and 50 hosts from a single Class C network. Why can't one fixed subnet mask satisfy all three?",
    options: [
      "A single fixed mask forces every subnet to be the same size, but these departments need different sizes",
      "Class C networks cannot be subnetted at all",
      "CIDR blocks are not allowed to be split further",
      "VLSM only works on Class A and B networks",
    ],
    correctIndex: 0,
    explanation:
      "One subnet mask always produces equal-sized subnets. Since the three requirements are all different sizes, no single mask can fit all of them without wasting a lot of addresses — that's exactly the problem VLSM (Variable Length Subnet Masking) solves.",
  },

  // ---------- Computer Science Foundations (networking as applied CS) ----------
  {
    id: "n-mcq-cs-1",
    question: "The OSI model's seven layers illustrate a general computer science design principle. Which one?",
    options: [
      "Abstraction/separation of concerns — each layer only needs its neighbour's interface, not how that neighbour works internally",
      "Recursion",
      "Object-oriented inheritance",
      "Dynamic programming",
    ],
    correctIndex: 0,
    explanation: "Layering is abstraction in action: the transport layer doesn't need to know how the physical layer moves bits, it just needs the interface the network layer below it exposes — the same principle behind APIs and modular software design.",
  },
  {
    id: "n-mcq-cs-2",
    question: "Link-state routing protocols like OSPF compute shortest paths using an algorithm most similar to:",
    options: ["Dijkstra's shortest-path algorithm", "Bubble sort", "Binary search", "Depth-first search for cycle detection only"],
    correctIndex: 0,
    explanation: "Each link-state router builds a full map of the network as a graph, then runs a Dijkstra-style shortest-path computation rooted at itself to build its routing table.",
  },
  {
    id: "n-mcq-cs-3",
    question: "Distance-vector routing protocols (like the original RIP) are based on which graph algorithm?",
    options: ["Bellman-Ford", "Dijkstra", "Kruskal's minimum spanning tree", "Depth-first search"],
    correctIndex: 0,
    explanation: "Distance-vector routing iteratively relaxes distance estimates using only neighbour-reported distances — the Bellman-Ford approach — unlike Dijkstra, which needs a full, globally known graph.",
  },
  {
    id: "n-mcq-cs-4",
    question: "DNS resolves domain names to IP addresses using what kind of system?",
    options: [
      "A distributed, hierarchical database queried top-down from root servers to authoritative servers",
      "A single centralized server that every request in the world goes to",
      "A blockchain ledger",
      "A local file only, never queried over the network",
    ],
    correctIndex: 0,
    explanation: "DNS is deliberately distributed and hierarchical (root → TLD → authoritative servers) — exactly the kind of design a single global system needs to scale without one server being a bottleneck or a single point of failure.",
  },
  {
    id: "n-mcq-cs-5",
    question: "A DNS record's TTL (time to live) exists for the same fundamental reason a cache entry expires in any computer system:",
    options: [
      "To balance staleness (serving outdated cached data) against the cost/latency of repeatedly fetching fresh data",
      "To encrypt the record",
      "To count how many network hops a packet has taken",
      "To limit how many bits the record can use",
    ],
    correctIndex: 0,
    explanation: "This is the classic caching tradeoff in computer science: cache too long and you risk staleness; refetch too often and you lose the whole performance benefit of caching. DNS TTLs are that same tradeoff applied to name resolution.",
  },
  {
    id: "n-mcq-cs-6",
    question: "Packet switching (used by the Internet) differs from circuit switching (used by the traditional telephone network) mainly in that:",
    options: [
      "Packet switching dynamically shares link capacity among many flows (statistical multiplexing) instead of reserving one dedicated path for a whole session",
      "Packet switching requires establishing a dedicated end-to-end circuit before any data can move",
      "Circuit switching is what splits messages into small packets",
      "Packet switching cannot be used for real-time traffic under any circumstances",
    ],
    correctIndex: 0,
    explanation: "Circuit switching reserves fixed capacity for the whole call's duration, even during silence. Packet switching instead statistically multiplexes many flows' packets over the same shared links — far more efficient use of capacity, at the cost of variable delay.",
  },
  {
    id: "n-mcq-cs-7",
    question: "TCP congestion control (slow start, additive increase/multiplicative decrease) is best described in computer-science terms as:",
    options: [
      "A feedback control loop that adapts the sending rate based on observed network conditions like packet loss",
      "A fixed, unchanging transmission rate agreed once at connection start",
      "A purely random retransmission strategy",
      "A method for compressing data before sending it",
    ],
    correctIndex: 0,
    explanation: "TCP congestion control continuously measures signals like packet loss and adjusts its sending rate in response — a textbook feedback control loop, the same kind of adaptive-system idea that shows up throughout CS (thermostat-style control, adaptive algorithms, etc.).",
  },
  {
    id: "n-mcq-cs-8",
    question: "A checksum or CRC (cyclic redundancy check) attached to a packet exists to:",
    options: [
      "Let the receiver detect (though not usually correct) whether the data was corrupted in transit",
      "Encrypt the payload so no one else can read it",
      "Compress the packet down to a smaller size",
      "Guarantee the packet arrives faster",
    ],
    correctIndex: 0,
    explanation: "A CRC is an error-detecting code: the sender computes a value from the data and attaches it; the receiver recomputes it and compares. A mismatch reveals corruption — but detection is not correction, and it says nothing about confidentiality.",
  },
  {
    id: "n-mcq-cs-9",
    question: "HTTPS uses TLS, which typically works by:",
    options: [
      "Using asymmetric (public-key) cryptography to securely agree on a shared secret, then switching to fast symmetric encryption for the rest of the session",
      "Using one shared static password for every website in the world",
      "Sending all data in plain text but over a different port number",
      "Compressing data instead of encrypting it",
    ],
    correctIndex: 0,
    explanation: "TLS combines both cryptographic families: slow-but-key-exchange-friendly asymmetric crypto during the handshake, then fast symmetric crypto (which needs a shared key) for the bulk of the actual data — the standard hybrid approach used across applied cryptography.",
  },
  {
    id: "n-mcq-cs-10",
    question: "In a peer-to-peer (P2P) architecture, compared to a classic client-server architecture:",
    options: [
      "Every node can act as both a client and a server, sharing resources directly with other peers instead of relying on one central server",
      "Only one designated server may ever exist",
      "All communication must first pass through a central authority",
      "There is no such thing as a peer-to-peer network on the modern Internet",
    ],
    correctIndex: 0,
    explanation: "P2P systems decentralize the client/server roles — every participant can serve data to, and request data from, any other peer, removing the single central bottleneck a pure client-server model relies on.",
  },
  {
    id: "n-mcq-cs-11",
    question: "A load balancer distributing incoming requests across backend servers using \"round robin\" means:",
    options: [
      "It sends each new request to the next server in a fixed rotating order, cycling back to the start",
      "It always sends every request to the single fastest server",
      "It randomly drops half of all incoming requests",
      "It merges all the backend servers into a single machine",
    ],
    correctIndex: 0,
    explanation: "Round robin is one of the simplest load-balancing algorithms: cycle through the list of servers in order, one request each, wrapping back to the first server once the list is exhausted.",
  },
  {
    id: "n-mcq-cs-12",
    question: "Bandwidth and latency are different network performance metrics. Which best describes the difference?",
    options: [
      "Bandwidth is how much data can be sent per unit time (capacity); latency is how long a single piece of data takes to arrive (delay)",
      "They are two names for exactly the same thing",
      "Bandwidth measures delay; latency measures capacity",
      "Both only apply to wireless networks",
    ],
    correctIndex: 0,
    explanation: "A common analogy: bandwidth is the width of a pipe (how much can flow through at once); latency is how long it takes a single drop to travel from one end to the other. A link can have huge bandwidth and still have high latency, or vice versa.",
  },
  {
    id: "n-mcq-cs-13",
    question: "NAT (Network Address Translation) lets many devices on a private network share one public IP address — conceptually similar to which other CS idea?",
    options: [
      "Virtual memory, where a program's logical addresses are transparently translated to different physical addresses",
      "A hash collision",
      "A compiler optimization pass",
      "A binary search tree rotation",
    ],
    correctIndex: 0,
    explanation: "Both NAT and virtual memory insert a translation layer between an internal, private address space and an external, real one — hiding the internal addressing scheme from the outside world.",
  },
  {
    id: "n-mcq-cs-14",
    question: "DHCP automatically assigns IP addresses to devices as they join a network. This is analogous to which general CS concept?",
    options: [
      "Dynamic (runtime) resource allocation — handing out a free resource from a pool on request and reclaiming it when the lease expires",
      "Static, compile-time memory allocation",
      "A sorting algorithm",
      "Public-key encryption",
    ],
    correctIndex: 0,
    explanation: "DHCP is essentially a resource-pool manager: it hands out an available IP address (a resource) on demand and reclaims it after a lease expires — the same pattern as a runtime memory allocator handing out and reclaiming blocks.",
  },
  {
    id: "n-mcq-cs-15",
    question: "A firewall's rule set, which allows or blocks traffic based on source/destination address and port, is conceptually closest to:",
    options: [
      "An access control list (ACL) — a set of permission rules checked against each request",
      "A compression algorithm",
      "A routing table used purely for path-finding",
      "A load-balancing algorithm",
    ],
    correctIndex: 0,
    explanation: "A firewall ruleset is an ACL applied to network traffic: each packet is checked against an ordered list of allow/deny rules, the same underlying pattern used for file-permission and API-authorization systems.",
  },
  {
    id: "n-mcq-cs-16",
    question: "HTTP is described as a \"stateless\" protocol, meaning:",
    options: [
      "The server doesn't automatically remember anything about previous requests from the same client — each request must carry whatever context it needs (or rely on something like cookies)",
      "The server crashes after every single request",
      "Only GET requests are allowed",
      "Data cannot be transmitted more than once",
    ],
    correctIndex: 0,
    explanation: "Statelessness means each HTTP request is handled independently, with no built-in memory of earlier requests — a deliberate design choice that makes it far easier to scale web servers horizontally, since any server can handle any request.",
  },
  {
    id: "n-mcq-cs-17",
    question: "Using a binary heap priority queue, Dijkstra's shortest-path algorithm (as used inside link-state routing) runs in:",
    options: ["O((V + E) log V)", "O(V²), with no faster option possible", "O(1)", "O(V!)"],
    correctIndex: 0,
    explanation: "Each of the E edge relaxations costs O(log V) to update the priority queue, plus V extract-min operations, giving O((V + E) log V) — significantly faster than the naive O(V²) array-based implementation on sparse graphs like real router topologies.",
  },
  {
    id: "n-mcq-cs-18",
    question: "The TCP three-way handshake (SYN, SYN-ACK, ACK) is fundamentally an example of:",
    options: [
      "A finite-state protocol negotiation both sides use to reliably agree they're ready to communicate",
      "A method for encrypting the connection",
      "A way to compress data before sending it",
      "A load-balancing technique",
    ],
    correctIndex: 0,
    explanation: "The handshake is a small finite-state-machine exchange: each side moves through defined states (SYN-SENT, SYN-RECEIVED, ESTABLISHED...) and only proceeds once it has confirmation the other side is ready — a general pattern used throughout protocol design.",
  },
  {
    id: "n-mcq-cs-19",
    question: "When a packet is larger than a network link's MTU (maximum transmission unit), IP fragmentation splits it into smaller pieces — conceptually similar to:",
    options: [
      "Paging in an operating system, which breaks a large block of memory into fixed-size chunks that fit hardware constraints",
      "Encrypting the packet",
      "Sorting the packet's bytes",
      "Reversing the packet's byte order",
    ],
    correctIndex: 0,
    explanation: "Both fragmentation and paging solve the same underlying problem: a piece of data is too large for the fixed-size unit the underlying hardware/link can handle, so it gets broken into smaller, uniformly bounded pieces and reassembled later.",
  },
  {
    id: "n-mcq-cs-20",
    question: "traceroute discovers each router along a path by sending packets with a TTL that starts at 1 and increases by 1 each round. This works because:",
    options: [
      "Each router decrements TTL by 1 and drops the packet with an error reply once it reaches 0, revealing itself one hop at a time",
      "TTL directly encodes the router's IP address",
      "It only works over TCP, never any other protocol",
      "It requires disabling encryption first",
    ],
    correctIndex: 0,
    explanation: "TTL was designed to stop packets looping forever, but traceroute repurposes that exact mechanism: by sending packets that are guaranteed to \"time out\" at hop 1, then hop 2, and so on, it forces each successive router to reveal itself via the error reply.",
  },
  {
    id: "n-mcq-cs-21",
    question: "Real routers look up the correct next hop for an IP address using \"longest prefix matching.\" A trie (prefix tree) is a natural data structure for this because:",
    options: [
      "It lets the router walk bit by bit down the tree to efficiently find the most specific (longest) matching prefix",
      "A trie is only useful for sorting numbers",
      "Tries cannot represent binary data like IP addresses",
      "It requires linearly scanning the entire routing table on every lookup, which a trie is specifically built to avoid",
    ],
    correctIndex: 0,
    explanation: "A trie organizes routes by shared address prefixes, so a lookup walks down bit by bit and naturally finds the longest matching prefix without ever scanning the whole table — critical for routers that must forward packets at line speed.",
  },
  {
    id: "n-mcq-cs-22",
    question: "A pure client-server architecture with only one central server has an important weakness compared to a well-designed distributed system:",
    options: [
      "It has a single point of failure — if that one server goes down, the whole service becomes unavailable",
      "It cannot ever serve more than one client",
      "It is always faster than any distributed system",
      "It cannot be used over the Internet at all",
    ],
    correctIndex: 0,
    explanation: "Centralizing everything on one server creates one failure point that takes the whole service down with it — a core motivation behind replication, redundancy, and distributed-systems design more broadly.",
  },
  {
    id: "n-mcq-cs-23",
    question: "Why does TLS use slow asymmetric encryption only briefly during the handshake, then switch to fast symmetric encryption for the bulk of the data?",
    options: [
      "Asymmetric encryption is computationally far more expensive per byte, so it's used only to safely exchange a symmetric key, then the cheaper cipher takes over",
      "Symmetric encryption cannot be broken while asymmetric encryption can",
      "Asymmetric encryption doesn't work over the Internet",
      "Symmetric keys are always physically longer than asymmetric keys",
    ],
    correctIndex: 0,
    explanation: "Asymmetric (public-key) operations are orders of magnitude more computationally expensive than symmetric ones. Using them only to bootstrap a shared secret, then handing off to symmetric encryption, gets the security benefit of public-key crypto without paying its full cost on every byte.",
  },
  {
    id: "n-mcq-cs-24",
    question: "A device's IP address identifies the host, but a port number identifies:",
    options: [
      "Which specific process/application on that host a piece of data is meant for, letting one IP address serve many services at once",
      "The physical network cable being used",
      "The exact wall-clock time the packet was sent",
      "The manufacturer of the network card",
    ],
    correctIndex: 0,
    explanation: "Ports are a demultiplexing mechanism: the OS uses the port number to route incoming data to the correct running process — conceptually similar to how a process ID or file descriptor identifies one specific thing among many on the same machine.",
  },
  {
    id: "n-mcq-cs-25",
    question: "Compressing data before sending it over a network (e.g., gzip on an HTTP response) works because most real-world data:",
    options: [
      "Contains statistical redundancy that a compression algorithm can encode more compactly",
      "Is already in its smallest possible form and cannot shrink further",
      "Must first be decrypted before it can be sent",
      "Is always exactly the same size regardless of content",
    ],
    correctIndex: 0,
    explanation: "Lossless compression exploits redundancy and predictable patterns in data (repeated substrings, skewed symbol frequencies) — an application of information theory: the more predictable the data, the more it can be shrunk.",
  },
  {
    id: "n-mcq-cs-26",
    question: "A CDN (content delivery network) improves web performance mainly by:",
    options: [
      "Caching copies of content on servers geographically close to users, cutting the physical distance (and thus latency) data has to travel",
      "Increasing the speed of light",
      "Removing the need for any DNS lookups",
      "Encrypting content more strongly than normal",
    ],
    correctIndex: 0,
    explanation: "Since latency is fundamentally bounded by distance and the speed of light in fibre, a CDN's core trick is simply moving cached copies of content physically closer to users — a distributed-caching strategy, not a faster transmission medium.",
  },
  {
    id: "n-mcq-cs-27",
    question: "The core problem that motivated IPv6 — a fixed-width 32-bit address space eventually running out of room — is directly analogous to which other classic CS scenario?",
    options: [
      "32-bit systems running out of directly addressable memory, pushing adoption of 64-bit architectures",
      "A stack overflow from deep recursion",
      "A hash table with zero collisions",
      "A sorting algorithm reaching its best case",
    ],
    correctIndex: 0,
    explanation: "Both are the same underlying problem: a fixed number of bits caps how many distinct things (addresses, or bytes of memory) can be represented. Once real-world growth exceeds 2ⁿ, the only fix is widening the address, exactly as 32-bit memory addressing gave way to 64-bit.",
  },
  {
    id: "n-mcq-cs-28",
    question: "UDP is preferred over TCP for real-time applications like video calls or online gaming because:",
    options: [
      "UDP has lower overhead and doesn't wait to retransmit lost data, prioritizing low latency over guaranteed delivery — a late video frame is often more useless than a dropped one",
      "UDP is always more reliable than TCP",
      "UDP automatically encrypts everything it sends",
      "UDP cannot be used over Wi-Fi",
    ],
    correctIndex: 0,
    explanation: "This is a classic engineering tradeoff: TCP's reliability guarantees come at the cost of retransmission delay, which real-time applications can't afford — receiving a video frame late is often worse than not receiving it at all, so UDP's \"fire and forget\" model wins there.",
  },
  {
    id: "n-mcq-cs-29",
    question: "ARP spoofing, a classic network attack, works by:",
    options: [
      "Sending forged ARP replies so a victim's device associates the attacker's MAC address with another device's IP address, misdirecting traffic",
      "Encrypting all packets on the network so no one else can read them",
      "Physically cutting the network cable",
      "Increasing everyone's available bandwidth",
    ],
    correctIndex: 0,
    explanation: "ARP has no built-in authentication, so a malicious host can simply broadcast a forged reply claiming to own another device's IP — a security weakness that comes directly from ARP trusting whatever reply arrives, with no verification.",
  },
  {
    id: "n-mcq-cs-30",
    question: "CIDR route aggregation (\"supernetting\") — combining many small routing table entries into one larger prefix — mainly helps because:",
    options: [
      "It reduces the number of entries core routers must store and search, which matters since a routing-table lookup happens on every single packet",
      "It encrypts routing announcements",
      "It increases the total number of usable IP addresses in the world",
      "It eliminates the need for routers altogether",
    ],
    correctIndex: 0,
    explanation: "Every packet a router forwards triggers a routing-table lookup, so table size directly affects lookup speed and memory use at massive scale. Aggregating many specific routes into one summarized prefix keeps that table — and the per-packet lookup cost — manageable.",
  },

  // ---------- Network Systems: Components, Topologies, Design & Internet Connectivity ----------
  {
    id: "n-mcq-ns-1",
    question: "Which is the best definition of a computer network?",
    options: [
      "A collection of computers and other devices connected together so they can communicate and share resources",
      "Any group of computers located in the same room",
      "A single computer with many programs installed on it",
      "A list of computer names stored in a directory",
    ],
    correctIndex: 0,
    explanation: "A network is specifically a collection of devices connected together so they can communicate and share resources — being in the same room isn't enough on its own.",
  },
  {
    id: "n-mcq-ns-2",
    question: "Twenty computers sit in the same laboratory but are not connected to one another in any way. Do they form a computer network?",
    options: [
      "No — a network requires the devices to be connected so they can communicate or share resources, not just be physically nearby",
      "Yes — any computers in the same room automatically form a network",
      "Yes, but only if they are all switched on at the same time",
      "No, because a network must always include a printer",
    ],
    correctIndex: 0,
    explanation: "The key idea from the handout: a network is not simply a collection of computers — they must actually be connected in a way that allows communication or resource sharing.",
  },
  {
    id: "n-mcq-ns-3",
    question: "Which of the following is NOT typically listed as a resource shared over a network?",
    options: ["The electricity bill for the building", "Files", "Printers", "Internet connections"],
    correctIndex: 0,
    explanation: "Files, printers, applications, storage, Internet connections, and other network services are the resources networks share — an electricity bill isn't a network resource at all.",
  },
  {
    id: "n-mcq-ns-4",
    question: "A computer laboratory with 40 computers is connected so that students can access the Internet, share files, and use one common printer. This is best described as:",
    options: ["A computer network", "A server farm only", "A single end device", "A topology, not a network"],
    correctIndex: 0,
    explanation: "This is the handout's own worked example of a computer network — devices connected together to communicate and share resources.",
  },
  {
    id: "n-mcq-ns-5",
    question: "Which of these is an end device?",
    options: ["A laptop being used to access a university website", "A switch connecting computers in a lab", "A router forwarding packets to the Internet", "An access point providing Wi-Fi"],
    correctIndex: 0,
    explanation: "An end device sends or receives information over a network — desktops, laptops, smartphones, tablets, printers, servers, and IoT devices all count. Switches, routers, and access points are intermediary networking devices, not end devices.",
  },
  {
    id: "n-mcq-ns-6",
    question: "A Network Interface Card (NIC) is best described as:",
    options: [
      "Hardware that enables a computer or device to connect to a network, wired or wireless",
      "Software that blocks unwanted network traffic",
      "A device that connects two entirely different networks",
      "A protocol used to translate domain names into IP addresses",
    ],
    correctIndex: 0,
    explanation: "A NIC is the hardware that lets a device physically join a network, whether via wired Ethernet or wireless connectivity.",
  },
  {
    id: "n-mcq-ns-7",
    question: "The unique hardware address burned into a network interface is called its:",
    options: ["MAC address", "IP address", "DNS address", "Port number"],
    correctIndex: 0,
    explanation: "Every NIC normally has a hardware address called a MAC address — distinct from the IP address, which is assigned logically rather than burned into the hardware.",
  },
  {
    id: "n-mcq-ns-8",
    question: "A desktop computer connects to a network switch using an Ethernet NIC and a cable. In this setup, the desktop computer is acting as the:",
    options: ["End device", "Switch", "Router", "ISP"],
    correctIndex: 0,
    explanation: "The desktop is the device generating/receiving data — the end device — while the NIC is simply what lets it physically join the network.",
  },
  {
    id: "n-mcq-ns-9",
    question: "A computer laboratory contains 30 computers connected to a switch. What is the main purpose of the switch?",
    options: ["To connect the devices within the LAN so they can communicate with one another", "To connect the laboratory to a different network entirely", "To provide wireless Wi-Fi access", "To translate domain names into IP addresses"],
    correctIndex: 0,
    explanation: "A switch connects devices within a single Local Area Network — exactly the job it does for the 30 lab computers.",
  },
  {
    id: "n-mcq-ns-10",
    question: "What type of address does a switch primarily use when deciding where to forward a frame?",
    options: ["MAC address", "IP address", "Port number", "Domain name"],
    correctIndex: 0,
    explanation: "A switch primarily uses MAC addresses to determine where frames should be forwarded within the LAN.",
  },
  {
    id: "n-mcq-ns-11",
    question: "If another computer is added to a laboratory that already uses a switch, to which device would it normally be connected?",
    options: ["The switch", "The ISP directly", "The DNS server", "The modem/ONT"],
    correctIndex: 0,
    explanation: "New devices within the same LAN are added by connecting them to the switch, which is exactly what a switch is designed to make easy.",
  },
  {
    id: "n-mcq-ns-12",
    question: "A router's defining job is to:",
    options: ["Connect different networks and forward packets between them", "Connect devices only within a single LAN", "Provide wireless connectivity to laptops and phones", "Store and share files for other computers"],
    correctIndex: 0,
    explanation: "A router connects different networks together and forwards packets between them — the device that enables computers on a LAN to reach devices outside it.",
  },
  {
    id: "n-mcq-ns-13",
    question: "What type of address does a router primarily use to make forwarding decisions?",
    options: ["IP address", "MAC address", "MAC address of the destination switch", "The device's serial number"],
    correctIndex: 0,
    explanation: "Routers primarily use IP addresses to make forwarding decisions, in contrast to switches, which primarily use MAC addresses.",
  },
  {
    id: "n-mcq-ns-14",
    question: "Which pairing correctly matches each device to its scope of communication?",
    options: ["Switch → communication within a LAN; Router → communication between networks", "Switch → communication between networks; Router → communication within a LAN", "Both switch and router only ever work within a single LAN", "Neither switch nor router affects how devices communicate"],
    correctIndex: 0,
    explanation: "This is the handout's own memory aid: switch = communication within a LAN, router = communication between networks.",
  },
  {
    id: "n-mcq-ns-15",
    question: "A Wireless Access Point (AP) is best described as a device that:",
    options: ["Enables wireless devices to connect to a network using Wi-Fi", "Connects two entirely separate networks together using IP addresses", "Stores files so other computers can download them", "Translates domain names into IP addresses"],
    correctIndex: 0,
    explanation: "A wireless access point provides wireless connectivity to devices such as laptops, smartphones, and tablets, typically feeding their traffic into a switch.",
  },
  {
    id: "n-mcq-ns-16",
    question: "Students want to connect their smartphones and tablets to the university network without any cables. Which device makes this possible?",
    options: ["A wireless access point", "A modem", "A DNS server", "A repeater only"],
    correctIndex: 0,
    explanation: "An access point is specifically the device that lets wireless devices like smartphones and tablets join a network over Wi-Fi.",
  },
  {
    id: "n-mcq-ns-17",
    question: "A server is best described as:",
    options: ["A computer or program that provides a service to other computers on a network", "Any computer connected to the Internet", "A device that only stores backups", "A type of transmission medium"],
    correctIndex: 0,
    explanation: "A server is a computer or program that provides a service; the computers requesting that service are called clients.",
  },
  {
    id: "n-mcq-ns-18",
    question: "In the exchange \"Your Laptop --- Request ---> Web Server\" followed by \"Your Laptop <--- Response --- Web Server,\" your laptop is acting as the:",
    options: ["Client", "Server", "Router", "Access point"],
    correctIndex: 0,
    explanation: "Your laptop is requesting the service (a webpage), which makes it the client; the web server is the one providing the requested service.",
  },
  {
    id: "n-mcq-ns-19",
    question: "Which server type provides webpages to clients?",
    options: ["Web server", "File server", "Mail server", "DHCP server"],
    correctIndex: 0,
    explanation: "A web server's role is specifically to provide webpages.",
  },
  {
    id: "n-mcq-ns-20",
    question: "Which server type stores and shares files?",
    options: ["File server", "Web server", "DNS server", "Mail server"],
    correctIndex: 0,
    explanation: "A file server's role is to store and share files across the network.",
  },
  {
    id: "n-mcq-ns-21",
    question: "Which server type helps translate domain names into IP addresses?",
    options: ["DNS server", "Mail server", "File server", "DHCP server"],
    correctIndex: 0,
    explanation: "A DNS server's role is to help translate domain names into the IP addresses computers actually need to communicate.",
  },
  {
    id: "n-mcq-ns-22",
    question: "Which server type provides IP configuration information to devices automatically?",
    options: ["DHCP server", "Web server", "DNS server", "Mail server"],
    correctIndex: 0,
    explanation: "A DHCP server's role is to provide IP configuration information — address, subnet mask, gateway, DNS servers — automatically.",
  },
  {
    id: "n-mcq-ns-23",
    question: "Which server type provides email services?",
    options: ["Mail server", "Web server", "File server", "DHCP server"],
    correctIndex: 0,
    explanation: "A mail server's role is to provide email services.",
  },
  {
    id: "n-mcq-ns-24",
    question: "An Internet Service Provider (ISP) is best described as an organisation that:",
    options: ["Provides connectivity between an organisation and the Internet", "Only manufactures network cables", "Only sells computers to universities", "Only writes network security software"],
    correctIndex: 0,
    explanation: "An ISP provides connectivity between an organisation (or individual) and the wider Internet.",
  },
  {
    id: "n-mcq-ns-25",
    question: "Depending on the access technology used, which piece of equipment terminates the ISP's connection into a building?",
    options: ["A modem or an Optical Network Terminal (ONT)", "A wireless access point only", "A file server", "A DNS server"],
    correctIndex: 0,
    explanation: "Equipment such as a modem or an ONT terminates the ISP's connection, depending on the underlying access technology (e.g. cable/DSL vs fibre).",
  },
  {
    id: "n-mcq-ns-26",
    question: "An ONT (Optical Network Terminal) specifically terminates which type of connection?",
    options: ["A fibre-optic connection", "A satellite connection only", "A Wi-Fi connection", "A Bluetooth connection"],
    correctIndex: 0,
    explanation: "An ONT terminates a fibre-optic connection and provides an interface the customer's own networking equipment (typically a router) can use.",
  },
  {
    id: "n-mcq-ns-27",
    question: "Following the chain Internet → ISP → Modem/ONT → Router → Switch → Computers, which device is the FIRST piece of customer-side equipment the ISP's own connection reaches?",
    options: ["The modem/ONT", "The switch", "The router", "The computer"],
    correctIndex: 0,
    explanation: "The modem/ONT is what directly terminates the ISP's incoming connection, before it ever reaches the router or switch.",
  },
  {
    id: "n-mcq-ns-28",
    question: "In the full component chain Computer → Switch → Router → Modem/ONT → ISP → Internet, which device's role is to \"connect the LAN to other networks\"?",
    options: ["Router", "Switch", "Modem/ONT", "Computer"],
    correctIndex: 0,
    explanation: "The router's role in this chain is precisely to connect the LAN to other networks — the switch's role, by contrast, is to connect devices within the LAN.",
  },
  {
    id: "n-mcq-ns-29",
    question: "What is the very first step in the sequence of what happens when you access the Internet?",
    options: ["Your computer generates a request", "The destination server responds", "The ISP provides connectivity to other networks", "Routers across interconnected networks forward the packet"],
    correctIndex: 0,
    explanation: "The sequence begins with your computer generating a request — everything else (carrying it to the router, forwarding it via the ISP, reaching the destination) happens afterward.",
  },
  {
    id: "n-mcq-ns-30",
    question: "After your computer generates a request, what happens next in the standard sequence?",
    options: ["The local network carries the request towards the router", "The response immediately arrives", "The request is deleted", "The ISP creates a new IP address for your computer"],
    correctIndex: 0,
    explanation: "Immediately after the request is generated, the local network (via the switch) carries it towards the router, which then forwards it outside the local network.",
  },
  {
    id: "n-mcq-ns-31",
    question: "Which statement best captures why the Internet is described as \"a network of interconnected networks\"?",
    options: [
      "Routers across many separate networks forward packets between each other, so no single network needs to reach every destination directly",
      "There is only one giant network that everyone in the world connects to directly",
      "Every computer on Earth is directly wired to every other computer",
      "The Internet is just one very large local area network",
    ],
    correctIndex: 0,
    explanation: "The handout's key idea: the Internet is a network of interconnected networks — packets are forwarded hop by hop across many separate networks via routers, not delivered over one single giant network.",
  },
  {
    id: "n-mcq-ns-32",
    question: "A transmission medium is best defined as:",
    options: ["The path through which data travels from one network device to another", "A device that translates domain names into IP addresses", "The software that manages network security", "A type of server that stores files"],
    correctIndex: 0,
    explanation: "A transmission medium is simply the physical (or wireless) path data actually travels along between devices.",
  },
  {
    id: "n-mcq-ns-33",
    question: "Which of these is a guided (wired) transmission medium?",
    options: ["Fibre-optic cable", "Wi-Fi radio waves", "Satellite communication", "Microwave communication"],
    correctIndex: 0,
    explanation: "Twisted-pair, coaxial, and fibre-optic cable are all guided/wired media — the signal is physically guided along a cable. Wi-Fi, microwave, and satellite are all unguided/wireless.",
  },
  {
    id: "n-mcq-ns-34",
    question: "Which of these is an unguided (wireless) transmission medium?",
    options: ["Satellite communication", "Twisted-pair cable", "Coaxial cable", "Fibre-optic cable"],
    correctIndex: 0,
    explanation: "Wi-Fi radio waves, microwave communication, and satellite communication are unguided/wireless media, in contrast to the three guided/wired cable types.",
  },
  {
    id: "n-mcq-ns-35",
    question: "You need to connect 30 desktop computers to a switch within a single laboratory. Which transmission medium is most appropriate, and why?",
    options: [
      "Twisted-pair Ethernet cable — it's relatively inexpensive, easy to install, and well suited to this kind of LAN environment",
      "Satellite communication — it provides the highest possible bandwidth for a single room",
      "Fibre-optic cable — it is always the cheapest option for connecting nearby desktops",
      "Microwave communication — it requires no cabling infrastructure at all",
    ],
    correctIndex: 0,
    explanation: "For connecting desktop computers to a switch within one lab, twisted-pair Ethernet cable is the textbook answer: inexpensive, easy to install, and suitable for many LAN environments.",
  },
  {
    id: "n-mcq-ns-36",
    question: "You need to connect two university buildings located some distance apart. Which transmission medium is most appropriate, and why?",
    options: [
      "Fibre-optic cable — it supports high bandwidth, longer distances, and resists electromagnetic interference",
      "Twisted-pair cable — it is the best choice whenever long distances are involved",
      "Coaxial cable — it is now the standard choice for all inter-building links",
      "There is no appropriate wired option for this distance",
    ],
    correctIndex: 0,
    explanation: "Fibre-optic cable is specifically recommended when high bandwidth is required, longer distances must be covered, or resistance to electromagnetic interference matters — exactly the inter-building scenario.",
  },
  {
    id: "n-mcq-ns-37",
    question: "You need to provide network access to students using smartphones as they move around a lecture block. Which transmission medium is most appropriate?",
    options: [
      "Wireless (Wi-Fi) via access points — it lets mobile devices connect without physical cables as students move around",
      "Twisted-pair cable run to each seat in the lecture block",
      "Fibre-optic cable connected directly to each smartphone",
      "Coaxial cable strung between each student's phone",
    ],
    correctIndex: 0,
    explanation: "Wireless networking is the appropriate choice specifically because it lets mobile devices like smartphones connect without physical cables, which matters when students are moving around rather than sitting at fixed desks.",
  },
  {
    id: "n-mcq-ns-38",
    question: "Bandwidth is best defined as:",
    options: ["The amount of data a communication link can carry within a given period", "The physical length of a network cable", "The number of devices connected to a switch", "The number of hops a packet takes to reach its destination"],
    correctIndex: 0,
    explanation: "Bandwidth measures capacity over time — how much data a link can carry within a given period — commonly expressed in bps, Kbps, Mbps, and Gbps.",
  },
  {
    id: "n-mcq-ns-39",
    question: "Connection A runs at 10 Mbps and Connection B runs at 100 Mbps. Which statement is correct?",
    options: ["Connection B has greater bandwidth", "Connection A has greater bandwidth", "Both connections have identical bandwidth", "Bandwidth cannot be compared between two different connections"],
    correctIndex: 0,
    explanation: "100 Mbps is ten times the capacity of 10 Mbps, so Connection B clearly has the greater bandwidth.",
  },
  {
    id: "n-mcq-ns-40",
    question: "When deciding how much bandwidth a network needs, the most important factors are:",
    options: ["The number of users and the applications they will use", "Only the price of the cheapest available connection", "Only the colour of the networking equipment", "The number of printers on the network"],
    correctIndex: 0,
    explanation: "Network bandwidth should be selected according to the number of users and the applications they'll actually use — some applications need far more capacity than others.",
  },
  {
    id: "n-mcq-ns-41",
    question: "Which of these applications is most likely to require significant network bandwidth?",
    options: ["Video conferencing and streaming", "Reading a single plain-text email", "Checking the time on a device's clock", "Typing a short document with no images"],
    correctIndex: 0,
    explanation: "Video conferencing, cloud services, video streaming, and large file transfers are all specifically called out as bandwidth-hungry applications, unlike simple text-based tasks.",
  },
  {
    id: "n-mcq-ns-42",
    question: "A network topology describes:",
    options: ["How network devices and communication links are arranged", "How fast a network's Internet connection is", "How many users a network can support", "What programming language a network's software is written in"],
    correctIndex: 0,
    explanation: "A network topology is purely about arrangement — how devices and the links between them are laid out — not about speed, capacity, or software.",
  },
  {
    id: "n-mcq-ns-43",
    question: "In a bus topology, devices share:",
    options: ["A common communication cable called a backbone", "A separate cable to a central switch each", "A closed loop connecting each device to its two neighbours", "No physical connection at all"],
    correctIndex: 0,
    explanation: "In a bus topology, every device taps into one shared backbone cable rather than having an individual connection to a central device.",
  },
  {
    id: "n-mcq-ns-44",
    question: "Which of these is an advantage of bus topology?",
    options: ["Requires relatively little cable", "Failure of one device never affects the network", "It is the most common topology in modern LANs", "Troubleshooting is always straightforward"],
    correctIndex: 0,
    explanation: "Bus topology's advantages are that it requires relatively little cable, can be inexpensive for small networks, and is conceptually simple — troubleshooting is actually a listed disadvantage, and modern LANs rarely use it.",
  },
  {
    id: "n-mcq-ns-45",
    question: "Which of these is a disadvantage of bus topology?",
    options: ["Failure of the backbone can affect the entire network", "It requires more cabling than a star topology", "Adding a device is always easy", "It requires a central networking device"],
    correctIndex: 0,
    explanation: "Because every device shares the same single backbone, a backbone failure can take down communication for the entire network — the topology's defining weakness.",
  },
  {
    id: "n-mcq-ns-46",
    question: "Traditional bus Ethernet networks are:",
    options: ["Uncommon in modern LAN installations", "The default choice for every new computer laboratory", "Required for connecting to fibre-optic backbones", "Always faster than a star topology"],
    correctIndex: 0,
    explanation: "The handout states plainly that traditional bus Ethernet networks are uncommon in modern LAN installations, having largely been replaced by star topologies built around switches.",
  },
  {
    id: "n-mcq-ns-47",
    question: "In a star topology, every device connects to:",
    options: ["A central networking device, commonly a switch", "Every other device directly, with no central point", "A shared backbone cable", "Only its two nearest neighbours"],
    correctIndex: 0,
    explanation: "The defining feature of star topology is that every device has its own individual connection to one central device — typically a switch.",
  },
  {
    id: "n-mcq-ns-48",
    question: "Which of these is an advantage of star topology?",
    options: ["Failure of one device's connection normally affects only that device", "It requires the least cable of any topology", "There is no single point of failure at all", "It was the standard choice before switches existed"],
    correctIndex: 0,
    explanation: "Because each device has its own independent connection to the switch, one device's cable failing doesn't affect anyone else — a key advantage over bus topology.",
  },
  {
    id: "n-mcq-ns-49",
    question: "Which of these is a disadvantage of star topology?",
    options: ["Failure of the central switch can affect the entire network", "It is difficult to add new devices", "It requires less cabling than a bus topology", "It cannot be used with Ethernet switches"],
    correctIndex: 0,
    explanation: "Because every device depends on the same central switch, a failure there can bring down the whole network — the topology's one significant weak point.",
  },
  {
    id: "n-mcq-ns-50",
    question: "Which topology is very common in modern Ethernet LANs?",
    options: ["Star topology", "Bus topology", "Ring topology", "None of the classic topologies are used today"],
    correctIndex: 0,
    explanation: "Modern Ethernet LANs commonly use a star topology, built around switches, unlike bus and ring which are both uncommon today.",
  },
  {
    id: "n-mcq-ns-51",
    question: "In a ring topology, each device connects to:",
    options: ["Its neighbouring devices, forming a closed loop", "A single shared backbone", "A central switch only", "Every other device on the network directly"],
    correctIndex: 0,
    explanation: "A ring topology connects each device to its immediate neighbours on either side, forming a continuous loop.",
  },
  {
    id: "n-mcq-ns-52",
    question: "Which of these is an advantage sometimes attributed to ring topology?",
    options: ["Some ring technologies provide predictable access to the transmission medium", "It always uses less cable than a bus topology", "Adding devices is always trivially easy", "A device failure never disrupts the network"],
    correctIndex: 0,
    explanation: "Because communication can be organised systematically around the loop, some ring technologies provide predictable, orderly access to the shared medium — unlike the contention-based access of some other topologies.",
  },
  {
    id: "n-mcq-ns-53",
    question: "Which of these is a disadvantage of ring topology?",
    options: ["Failure of a device or connection can disrupt some simple ring networks", "It is the most common topology in modern LAN installations", "It requires a central switch to function at all", "It is impossible to add new devices to a ring"],
    correctIndex: 0,
    explanation: "In a simple ring, a broken device or link can disrupt the whole loop's ability to function — one of the reasons ring topologies are less common in modern LAN installations.",
  },
  {
    id: "n-mcq-ns-54",
    question: "Which topology uses a central switch?",
    options: ["Star", "Bus", "Ring", "None of them"],
    correctIndex: 0,
    explanation: "Star topology is specifically defined by every device connecting to one central device, commonly a switch.",
  },
  {
    id: "n-mcq-ns-55",
    question: "In which topology do devices share a common backbone?",
    options: ["Bus", "Star", "Ring", "None of them"],
    correctIndex: 0,
    explanation: "Bus topology is specifically defined by devices sharing one common backbone cable.",
  },
  {
    id: "n-mcq-ns-56",
    question: "Comparing cable requirements across the three topologies, which is generally true?",
    options: ["Bus needs relatively little cable; star needs relatively more; ring falls in between", "Star always needs the least cable of the three", "Ring always needs the most cable of the three", "All three topologies need exactly the same amount of cable"],
    correctIndex: 0,
    explanation: "Per the handout's comparison table: bus has a relatively low cable requirement, star a relatively high one (an individual run to every device), and ring a moderate requirement.",
  },
  {
    id: "n-mcq-ns-57",
    question: "According to the topology comparison, which is generally easiest to troubleshoot?",
    options: ["Star", "Bus", "Ring", "They are all equally easy to troubleshoot"],
    correctIndex: 0,
    explanation: "Star is the easiest to troubleshoot because each device has its own independent connection, making it straightforward to isolate a fault to one link; bus and ring are both listed as more difficult.",
  },
  {
    id: "n-mcq-ns-58",
    question: "What is the important failure point of a star topology?",
    options: ["The central device (e.g. the switch)", "The backbone cable", "Any single individual device's own cable", "There is no meaningful failure point in a star topology"],
    correctIndex: 0,
    explanation: "In star topology, the central device is the single point whose failure affects the entire network — individual device cables failing only affect that one device.",
  },
  {
    id: "n-mcq-ns-59",
    question: "A network administrator is setting up a modern computer laboratory and must choose between bus and star topology. Why might they choose star instead of bus?",
    options: [
      "A device's connection can be added or fail independently, and switches provide good performance, whereas a bus's shared backbone is a single point of failure for the whole network",
      "Star topology always requires less cable than bus topology",
      "Bus topology cannot physically be built using Ethernet cable",
      "Star topology was invented more recently, so it must always be the better choice",
    ],
    correctIndex: 0,
    explanation: "The real justification is about fault isolation and performance: a star's per-device connections mean one fault doesn't take down the network, and switches provide good performance — not simply that star is newer or uses less cable (it actually uses more).",
  },
  {
    id: "n-mcq-ns-60",
    question: "A university wants a laboratory containing 50 computers and expects to add another 20 computers later. Which topology is most appropriate, and why?",
    options: [
      "Star — computers can be added relatively easily, and individual connection faults are easier to isolate",
      "Bus — it is conceptually simple and that outweighs every other consideration",
      "Ring — it is the most scalable topology available",
      "The topology choice makes no difference to this scenario",
    ],
    correctIndex: 0,
    explanation: "This is the handout's own worked scenario: star topology is appropriate because computers can be added relatively easily and individual connection faults are easier to isolate — directly relevant given the planned expansion.",
  },
  {
    id: "n-mcq-ns-61",
    question: "Scalability, in network design, refers to:",
    options: ["The ability of a network to accommodate growth without requiring a complete redesign", "The physical size of the building housing the network", "The total number of protocols a network supports", "How quickly a network can be physically relocated"],
    correctIndex: 0,
    explanation: "Scalability specifically means growth can be accommodated without tearing the whole design up and starting over.",
  },
  {
    id: "n-mcq-ns-62",
    question: "A network currently needs to support 30 computers but is expected to need 60 within three years. Which of these best reflects good scalable design practice?",
    options: [
      "Provide sufficient switch capacity, room for additional switches, adequate IP addressing capacity, sufficient bandwidth, and appropriate cabling now",
      "Wait until the network actually reaches 60 computers before making any changes",
      "Design the network only for exactly 30 computers to save money",
      "Ignore future growth entirely, since it hasn't happened yet",
    ],
    correctIndex: 0,
    explanation: "A good designer plans ahead for known future growth — providing headroom in switch capacity, addressing, bandwidth, and cabling now, rather than waiting until the network is already overwhelmed.",
  },
  {
    id: "n-mcq-ns-63",
    question: "Good network design considers:",
    options: ["Both present requirements and future requirements", "Only the requirements that exist on the very first day", "Only requirements the vendor recommends", "Only the requirements of the network administrator personally"],
    correctIndex: 0,
    explanation: "The handout's key reminder: good network design considers both present requirements and future requirements — designing only for today risks an expensive redesign later.",
  },
  {
    id: "n-mcq-ns-64",
    question: "When justifying a network design decision in an exam answer, which structure does the handout recommend?",
    options: ["Choice + Reason + Relationship to the requirement", "Choice only, with no explanation needed", "A list of every topology that was NOT chosen", "A description of the hardware's manufacturer"],
    correctIndex: 0,
    explanation: "The recommended structure is Choice + Reason + Relationship to Requirement — stating the technology alone is only part of a complete answer.",
  },
  {
    id: "n-mcq-ns-65",
    question: "Which of these is the stronger exam answer, in the style the handout recommends?",
    options: [
      "\"I will use a star topology because each computer can have an independent connection to the central switch, making individual connection faults easier to isolate and allowing additional computers to be added relatively easily.\"",
      "\"I will use star topology.\"",
      "\"I will use whichever topology is cheapest, regardless of the requirements.\"",
      "\"I will use star topology because it is the only topology that exists.\"",
    ],
    correctIndex: 0,
    explanation: "This answer follows Choice + Reason + Relationship to Requirement: it names the topology, gives a specific reason, and ties that reason back to the actual requirement (adding devices, isolating faults) — far stronger than simply naming the technology.",
  },
  {
    id: "n-mcq-ns-66",
    question: "According to the handout's final takeaway, what question should a network designer ask FIRST?",
    options: ["\"What does this network need to achieve?\"", "\"Which topology do I already know?\"", "\"Which vendor offers the cheapest hardware?\"", "\"Which topology is newest?\""],
    correctIndex: 0,
    explanation: "The handout's explicit final takeaway warns against starting from familiarity (\"which topology do I know?\") and instead starting from requirements (\"what does this network need to achieve?\").",
  },
  {
    id: "n-mcq-ns-67",
    question: "In the recommended network design flow, what comes immediately after Requirements?",
    options: ["Topology", "Security", "Scalability", "Internet Connectivity"],
    correctIndex: 0,
    explanation: "The design flow is: Requirements → Topology → Network Devices → Transmission Media → Bandwidth → Internet Connectivity → Scalability → Security — topology is the very next decision after requirements are understood.",
  },
  {
    id: "n-mcq-ns-68",
    question: "In the worked network design example (40 desktop computers, one printer, one server, Internet access, future expansion expected), which topology was recommended, and for what stated reasons?",
    options: [
      "Star — easy to add computers, individual connection faults can be isolated, and modern Ethernet switches support efficient communication",
      "Bus — it requires the least cable of any topology available",
      "Ring — it provides the most predictable access to the transmission medium",
      "No topology was recommended in the worked example",
    ],
    correctIndex: 0,
    explanation: "The worked example recommends star topology specifically because it's easy to add computers, individual connection faults can be isolated, and modern Ethernet switches support efficient communication.",
  },
  {
    id: "n-mcq-ns-69",
    question: "In the same worked example, which transmission medium connects the desktop computers to the switch?",
    options: ["Twisted-pair Ethernet cable", "Fibre-optic cable exclusively", "Satellite communication", "Coaxial cable exclusively"],
    correctIndex: 0,
    explanation: "The worked example uses twisted-pair Ethernet cable to connect the desktop computers to the switch, consistent with it being inexpensive, easy to install, and well suited to LAN environments.",
  },
  {
    id: "n-mcq-ns-70",
    question: "Which of these is a recommended good password practice?",
    options: ["Using different passwords for important services", "Reusing one memorable password across every important service", "Choosing a password based on your date of birth so you never forget it", "Sharing your password with a trusted friend for convenience"],
    correctIndex: 0,
    explanation: "Using different passwords for important services limits the damage if any single password is ever leaked — one of several good password practices, alongside sufficient length, avoiding personal information, keeping passwords private, and using multi-factor authentication.",
  },
  {
    id: "n-mcq-ns-71",
    question: "Multi-factor authentication is best described as:",
    options: ["An additional layer of verification beyond just a password, used where available to strengthen account security", "A way to make a password shorter and easier to type", "A method for sharing one password safely among a group", "A type of network topology"],
    correctIndex: 0,
    explanation: "Multi-factor authentication adds a second (or further) verification step beyond the password alone, and the handout specifically recommends using it where available.",
  },
  {
    id: "n-mcq-ns-72",
    question: "Which of these is good practice for staying safe on the Internet?",
    options: ["Verifying a website before providing sensitive information", "Clicking any link that arrives by email, regardless of the sender", "Reusing the same password everywhere for convenience", "Ignoring software update notifications"],
    correctIndex: 0,
    explanation: "Verifying a website before entering sensitive information is one of the handout's core Internet safety habits, alongside avoiding suspicious sites, unknown links/attachments, and recognising phishing attempts.",
  },
  {
    id: "n-mcq-ns-73",
    question: "Recognising phishing attempts is important because phishing typically involves:",
    options: [
      "Messages designed to trick a user into revealing credentials or sensitive personal information",
      "A network topology with a shared backbone cable",
      "A legitimate request from a known, verified system administrator",
      "A type of transmission medium used for long-distance links",
    ],
    correctIndex: 0,
    explanation: "Phishing attempts are deceptive messages engineered to trick users into handing over credentials or other sensitive data — recognising them is one of the handout's listed Internet safety skills.",
  },
  {
    id: "n-mcq-ns-74",
    question: "Malware is best defined as:",
    options: [
      "Malicious software designed to damage, disrupt, spy on, or gain unauthorised access to computer systems",
      "Any software that requires an Internet connection to run",
      "A hardware fault in a network switch",
      "A type of network topology",
    ],
    correctIndex: 0,
    explanation: "Malware is specifically malicious software with harmful intent — damage, disruption, spying, or unauthorised access — distinct from ordinary software or hardware issues.",
  },
  {
    id: "n-mcq-ns-75",
    question: "Which of these is an example of malware?",
    options: ["Ransomware", "A firewall", "A DHCP server", "A network switch"],
    correctIndex: 0,
    explanation: "Viruses, worms, Trojan horses, spyware, and ransomware are all examples of malware — a firewall, DHCP server, and switch are all legitimate networking components, not malicious software.",
  },
  {
    id: "n-mcq-ns-76",
    question: "Keeping software updated is an important malware-prevention practice mainly because:",
    options: [
      "Updates often patch known security vulnerabilities that malware is designed to exploit",
      "Updates always make software run faster, which is unrelated to security",
      "Old software is illegal to keep installed",
      "Updates automatically delete all files on the device",
    ],
    correctIndex: 0,
    explanation: "Many attacks specifically target known, already-patched vulnerabilities in outdated software — keeping software updated closes those doors.",
  },
  {
    id: "n-mcq-ns-77",
    question: "A backup is best defined as:",
    options: [
      "An additional copy of data kept so information can be recovered if the original is lost or damaged",
      "The original, only copy of a set of important files",
      "A type of network topology used for redundancy only",
      "A device that terminates an ISP's fibre-optic connection",
    ],
    correctIndex: 0,
    explanation: "A backup is specifically an extra copy, kept precisely so information can be recovered if the original copy is lost or damaged.",
  },
  {
    id: "n-mcq-ns-78",
    question: "Which of these is NOT listed as a typical cause of data loss?",
    options: ["Regularly scheduled backups", "Hardware failure", "Malware", "Accidental deletion"],
    correctIndex: 0,
    explanation: "Hardware failure, malware, theft, accidental deletion, and disasters are all listed causes of data loss. Regularly scheduled backups are the defence against data loss, not a cause of it.",
  },
  {
    id: "n-mcq-ns-79",
    question: "Which of these is a recommended practice for securing a personal laptop, smartphone, or tablet?",
    options: ["Lock the device when unattended", "Disable all software updates permanently", "Install any software regardless of its source", "Avoid ever backing up personal files"],
    correctIndex: 0,
    explanation: "Locking a device when unattended is one of several recommended personal-device security practices, alongside using passwords/PINs/biometrics, installing updates, avoiding untrusted software, enabling security features, and backing up important information.",
  },
  {
    id: "n-mcq-ns-80",
    question: "Personal devices such as laptops and smartphones should be backed up:",
    options: ["Just like any server, since important information on them can also be lost", "Never, because personal devices cannot lose data", "Only if the device is more than five years old", "Only if it is also used as a file server"],
    correctIndex: 0,
    explanation: "The handout explicitly extends the data-backup principle to personal devices — important information on a personal laptop or phone can be lost just as easily as data on a server, so it needs backing up too.",
  },
];
