import type { MCQ } from "@/lib/mcqBank";

// CSM 152 - Information Technology II, KNUST, Second Semester Mid-Semester
// Examination 2023/2024 (June 2024). Transcribed from the real exam paper;
// answers independently verified against IPv4/TCP-IP semantics since the
// source paper (a photographed answer script) did not include an answer key.
export const midsemBank: MCQ[] = [
  {
    id: "midsem-1",
    question: "What is a network?",
    options: ["Two or more computers connected to each other", "Computers in a circle", "Clients receiving data from servers", "Spiders doing a job"],
    correctIndex: 0,
    explanation: "A network is simply two or more computers (or other devices) connected together so they can communicate and share resources.",
  },
  {
    id: "midsem-2",
    question: "Why are IP addresses needed?",
    options: ["So the user knows how to send emails", "So the router can speak to WiFi", "So the Internet knows where to send information", "So the header can see the control information"],
    correctIndex: 2,
    explanation: "An IP address is a unique address that identifies a device on a network, letting data be routed to the correct destination.",
  },
  {
    id: "midsem-3",
    question: "The communication links in a Metropolitan Area Network (MAN) are generally owned by:",
    options: ["ISPs", "Private Organisation", "Online Information Services", "Military Organization"],
    correctIndex: 1,
    explanation: "Unlike a LAN (owned by the organisation using it) or a WAN (often built on ISP/carrier infrastructure), a MAN's links are typically owned by a private organisation (e.g. a cable or utility company) that provides service across a city.",
  },
  {
    id: "midsem-4",
    question: "Which of the following is a valid IP address?",
    options: ["984.12.787.76", "192.168.321.10", "1.888.234.3456", "192.168.56.115"],
    correctIndex: 3,
    explanation: "Every octet of an IPv4 address must be 0-255. The other three options all contain at least one octet well outside that range.",
  },
  {
    id: "midsem-5",
    question: "How many bits are there in the IP address?",
    options: ["8", "16", "32", "48"],
    correctIndex: 2,
    explanation: "An IPv4 address is 32 bits, written as four 8-bit octets.",
  },
  {
    id: "midsem-6",
    question: "How many bits are there in an Ethernet (MAC) address?",
    options: ["8", "16", "32", "48"],
    correctIndex: 3,
    explanation: "A MAC address is 48 bits, usually written as six pairs of hex digits.",
  },
  {
    id: "midsem-7",
    question: "A device operating at the network layer is called a ___.",
    options: ["Router", "Equalizer", "Bridge", "Repeater"],
    correctIndex: 0,
    explanation: "Routers make forwarding decisions based on network-layer (IP) addresses. Bridges and repeaters operate lower down, at the data-link/physical layers.",
  },
  {
    id: "midsem-8",
    question: "In a bus network based on the Ethernet standards, the right to transmit messages is controlled by the protocol known as:",
    options: ["Carrier Sense, Multiple Access with Collision Detection (CSMA/CD)", "Carrier Sense, Multiple Access with Collision Avoidance (CSMA/CA)", "HyperText Transfer Protocol (HTTP)", "File Transfer Protocol (FTP)"],
    correctIndex: 0,
    explanation: "Classic wired Ethernet uses CSMA/CD — a device can listen while transmitting, so it can detect a collision as it happens. CSMA/CA (avoidance) is the Wi-Fi equivalent, used because wireless devices can't listen and transmit at once.",
  },
  {
    id: "midsem-9",
    question: "IP Address 14.23.120.8 lies in which class?",
    options: ["Class A", "Class B", "Class C", "Class D"],
    correctIndex: 0,
    explanation: "Class A covers first-octet values 1-126. 14 falls in that range.",
  },
  {
    id: "midsem-10",
    question: "Addresses of classes A, B and C are:",
    options: ["Multicast", "Reserved", "Unicast", "All of the above"],
    correctIndex: 2,
    explanation: "Classes A, B and C are all unicast (one destination host). Class D is multicast and Class E is reserved/experimental.",
  },
  {
    id: "midsem-11",
    question: "Which one of the following is NOT true?",
    options: [
      "Multiple hostnames may correspond to a single IP address",
      "Multiple hostnames may correspond to a multiple IP address",
      "A single hostname may correspond to many IP addresses",
      "A single hostname may correspond to a single IP address",
    ],
    correctIndex: 1,
    explanation: "Virtual hosting (many hostnames → one IP), DNS load-balancing (one hostname → many IPs), and the simple direct case (one hostname → one IP) are all standard, well-established DNS realities. \"Multiple hostnames to multiple IPs\" isn't a real standard DNS mapping pattern in the same sense — this is the odd one out. (This item is genuinely one of the more debatable ones on the paper; treat it as testing DNS name-resolution flexibility in general.)",
  },
  {
    id: "midsem-12",
    question: "Which class of IP address provides a maximum of only 254 host addresses per network ID?",
    options: ["Class A", "Class B", "Class C", "Class D"],
    correctIndex: 2,
    explanation: "Class C leaves 8 host bits: 2^8 - 2 = 254 usable host addresses (subtracting the network and broadcast addresses).",
  },
  {
    id: "midsem-13",
    question: "The Application layer provides the basis for:",
    options: ["Email services", "Frame Division", "File Making", "Packet forwarding"],
    correctIndex: 0,
    explanation: "Application-layer protocols like SMTP directly support services such as email. Frame division and packet forwarding happen lower in the stack.",
  },
  {
    id: "midsem-14",
    question: "Which of the following is NOT part of the Host-to-Host (Transport) layer discussion in the TCP/IP model?",
    options: ["Application", "Presentation", "Transport", "Network"],
    correctIndex: 1,
    explanation: "\"Presentation\" is an OSI-only layer — it doesn't exist as a separate layer in the 4-layer TCP/IP model (Application, Transport, Network/Internet, Link), where its responsibilities are folded into the Application layer.",
  },
  {
    id: "midsem-15",
    question: "Which of the TCP/IP model layers is responsible for breaking down the message into packets?",
    options: ["Network", "Application", "Transport", "Internet"],
    correctIndex: 2,
    explanation: "The Transport layer (TCP) segments a message into packets for delivery and reassembles them at the other end.",
  },
  {
    id: "midsem-16",
    question: "Which is the first layer of the TCP/IP model?",
    options: ["Network", "Application", "Transport", "Internet"],
    correctIndex: 1,
    explanation: "Presented top-down (matching how this course's own material lists it: Application → Transport → Network → Link), Application is the first/topmost layer.",
  },
  {
    id: "midsem-17",
    question: "What does TCP stand for?",
    options: ["Transfer Control Protocol", "Transmission Control Protocol", "Transfer Character Protocol", "Transmission Character Protocol"],
    correctIndex: 1,
    explanation: "TCP = Transmission Control Protocol.",
  },
  {
    id: "midsem-18",
    question: "Which protocol is used to send packets?",
    options: ["IP", "FTP", "SMTP", "TCP"],
    correctIndex: 0,
    explanation: "IP (Internet Protocol) handles addressing and routing of packets (datagrams) across networks — it's the namesake \"packet\" layer. TCP rides on top of it to add reliability.",
  },
  {
    id: "midsem-19",
    question: "What is a protocol?",
    options: ["Any peripheral device", "A person that uses a client", "Rules for networks and communications", "A circuit board with the components to send/receive data"],
    correctIndex: 2,
    explanation: "A protocol is a set of agreed-upon rules that govern how devices communicate.",
  },
  {
    id: "midsem-20",
    question: "What is TCP used for?",
    options: ["To send information across the internet in packets", "To ensure that information is sent to the correct computer", "To send mail across the internet", "To transmit webpages across the internet"],
    correctIndex: 0,
    explanation: "TCP's job is to break data into packets and manage their reliable, ordered delivery. Getting data to the correct computer is really IP's addressing job; mail and webpages are handled by specific application protocols (SMTP, HTTP) built on top of TCP.",
  },
  {
    id: "midsem-21",
    question: "Which of the following is NOT a layer of the TCP/IP protocol?",
    options: ["Physical layer", "Link layer", "Network layer", "Transport layer"],
    correctIndex: 0,
    explanation: "The 4-layer TCP/IP model is Application, Transport, Network, and Link — \"Physical\" is an OSI-only term, absorbed into the Link layer in the TCP/IP model.",
  },
  {
    id: "midsem-22",
    question: "The ___ of the TCP/IP protocol is responsible for figuring out how to get data to its destination.",
    options: ["Application layer", "Link layer", "Network layer", "Transport layer"],
    correctIndex: 2,
    explanation: "The Network (Internet) layer handles addressing and routing — figuring out the path data takes to its destination.",
  },
  {
    id: "midsem-23",
    question: "UDP needs the ___ address to deliver the user datagram to the correct application process.",
    options: ["Port", "Application", "Internet", "none of the above"],
    correctIndex: 0,
    explanation: "A port number identifies which specific application/process on a host should receive the datagram.",
  },
  {
    id: "midsem-24",
    question: "IP: 192.168.1.2, Subnet mask: 255.255.255.0. What class is the IP address?",
    options: ["A", "B", "C", "D"],
    correctIndex: 2,
    explanation: "Classful addressing is determined by the leading bits of the first octet, not the mask in use. 192 falls in the 192-223 range, which is Class C — consistent with the /24 mask shown, which happens to be Class C's default.",
  },
  {
    id: "midsem-25",
    question: "When using the IPv4 Class System, which of the following would be the subnet mask of a Class C address?",
    options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"],
    correctIndex: 2,
    explanation: "Class C's default mask is 255.255.255.0 (/24) — 24 network bits, 8 host bits.",
  },
  {
    id: "midsem-26",
    question: "What is the Network address for the following IP?\n172.16.32.19/28",
    options: ["172.16.32.16", "172.16.32.1", "172.16.32.255", "172.16.32.128"],
    correctIndex: 0,
    explanation: "/28 leaves a block size of 16 in the last octet. 19 falls in the block starting at 16 (0, 16, 32...), so the network address is 172.16.32.16.",
  },
  {
    id: "midsem-27",
    question: "The subnet mask for a /30 is?",
    options: ["255.255.255.252", "255.255.255.248", "255.255.255.128", "255.0.255.0"],
    correctIndex: 0,
    explanation: "/30 leaves 2 host bits, so the last octet is 11111100 = 252.",
  },
  {
    id: "midsem-28",
    question: "Which of the following is the broadcast address for a Class B network ID using the default subnet mask?",
    options: ["172.16.10.255", "172.16.255.255", "172.255.255.255", "255.255.255.255"],
    correctIndex: 1,
    explanation: "Class B's default mask is 255.255.0.0, so both of the last two octets are host bits — the broadcast address sets both to 255: 172.16.255.255.",
  },
  {
    id: "midsem-29",
    question:
      "What are the network address and the broadcast address for a host with the IP Address 167.36.150.41 /20?\nI. Network Address: 167.36.156.0\nII. Network Address: 167.36.144.0\nIII. Broadcast Address: 167.36.159.255\nIV. Broadcast Address: 167.36.171.255",
    options: ["I, II", "II, III", "I, III", "I, IV"],
    correctIndex: 1,
    explanation: "/20 gives a block size of 16 in the 3rd octet. 150 falls in the block starting at 144 (9×16), so network = 167.36.144.0 and broadcast = 167.36.159.255 (144+16-1) — that's II and III.",
  },
  {
    id: "midsem-30",
    question:
      "What are the network address and the broadcast address for a host with the IP Address 92.52.63.123 /14?\nI. Network Address: 92.52.0.0\nII. Network Address: 92.48.0.0\nIII. Broadcast Address: 92.46.255.255\nIV. Broadcast Address: 92.55.255.255",
    options: ["I, II", "II, III", "I, III", "I, IV"],
    correctIndex: 3,
    explanation: "/14 gives a block size of 4 in the 2nd octet. 52 is exactly divisible by 4 (13×4), so network = 92.52.0.0 and broadcast = 92.55.255.255 (52+4-1) — that's I and IV.",
  },
  {
    id: "midsem-31",
    question:
      "Practical scenario: you are the network administrator for a company assigned the IP address 192.168.10.0/24. The company needs to divide this into 4 equal-sized subnets for four departments (HR, Finance, Sales, IT).\n\nDetermine the new subnet mask required to create 4 subnets of equal size.",
    options: ["/26 (255.255.255.192)", "/27 (255.255.255.224)", "/25 (255.255.255.128)", "/28 (255.255.255.240)", "/24 (255.255.255.0)"],
    correctIndex: 0,
    explanation: "4 equal subnets need 2 borrowed bits (2^2 = 4), so /24 + 2 = /26 (255.255.255.192).",
  },
  {
    id: "midsem-32",
    question: "For the same 192.168.10.0/24 → 4-subnet scenario: calculate the network addresses for each of the 4 subnets.",
    options: [
      "Subnet 1: .0/27, Subnet 2: .32/27, Subnet 3: .64/27, Subnet 4: .96/27",
      "Subnet 1: .0/26, Subnet 2: .32/26, Subnet 3: .64/26, Subnet 4: .96/26",
      "Subnet 1: .0/26, Subnet 2: .64/26, Subnet 3: .128/26, Subnet 4: .192/26",
      "Subnet 1: .0/28, Subnet 2: .16/28, Subnet 3: .32/28, Subnet 4: .48/28",
    ],
    correctIndex: 2,
    explanation: "With a /26 mask the block size is 64, so the four subnets start at .0, .64, .128, and .192.",
  },
  {
    id: "midsem-33",
    question: "For the same scenario: determine the range of usable IP addresses for each subnet.",
    options: [
      "Subnet 1: .0-.63, Subnet 2: .64-.127, Subnet 3: .128-.191, Subnet 4: .192-.255",
      "Subnet 1: .1-.63, Subnet 2: .64-.126, Subnet 3: .128-.190, Subnet 4: .192-.254",
      "Subnet 1: .0-.62, Subnet 2: .64-.126, Subnet 3: .128-.190, Subnet 4: .192-.254",
      "Subnet 1: .1-.62, Subnet 2: .65-.126, Subnet 3: .129-.190, Subnet 4: .193-.254",
    ],
    correctIndex: 3,
    explanation: "Usable addresses exclude both the network address and the broadcast address of each /26 block: .1-.62, .65-.126, .129-.190, .193-.254.",
  },
  {
    id: "midsem-34",
    question: "For the same scenario: identify the broadcast address for each subnet.",
    options: [
      "Subnet 1: .63, Subnet 2: .127, Subnet 3: .191, Subnet 4: .255",
      "Subnet 1: .64, Subnet 2: .128, Subnet 3: .192, Subnet 4: .0",
      "Subnet 1: .62, Subnet 2: .126, Subnet 3: .190, Subnet 4: .254",
      "Subnet 1: .32, Subnet 2: .96, Subnet 3: .160, Subnet 4: .224",
    ],
    correctIndex: 0,
    explanation: "The broadcast address is the last address in each /26 block, one below the next subnet's start: .63, .127, .191, .255.",
  },
  {
    id: "midsem-35",
    question: "For the same scenario: assign each subnet to the respective department (HR, Finance, Sales, IT in that order).",
    options: [
      "HR: .0/26, Finance: .64/26, Sales: .128/26, IT: .192/26",
      "HR: .0/24, Finance: .128/24, Sales: .0/24, IT: .192/24",
      "HR: .0/25, Finance: .128/25, Sales: .0/25, IT: .192/25",
      "HR: .0/27, Finance: .64/27, Sales: .128/27, IT: .192/27",
    ],
    correctIndex: 0,
    explanation: "Assigning the four /26 subnets in order: HR gets 192.168.10.0/26, Finance 192.168.10.64/26, Sales 192.168.10.128/26, and IT 192.168.10.192/26.",
  },
];
