export type StatisticsTopic =
  | "variables-data"
  | "frequency-distributions"
  | "central-tendency"
  | "dispersion"
  | "position"
  | "shape-eda"
  | "empirical-rule";

export type QuestionType = "concept" | "code-analysis" | "debugging" | "best-practice";

export interface StatisticsExamQuestion {
  id: string;
  topic: StatisticsTopic;
  subtopic: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
  type: QuestionType;
  code?: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  misconception?: string;
  relatedPartId: string;
}

export const STATISTICS_EXAM_TOPICS: { id: StatisticsTopic; label: string }[] = [
  { id: "variables-data", label: "Variables & Data Collection" },
  { id: "frequency-distributions", label: "Frequency Distributions & Graphs" },
  { id: "central-tendency", label: "Measures of Central Tendency" },
  { id: "dispersion", label: "Measures of Dispersion" },
  { id: "position", label: "Measures of Position" },
  { id: "shape-eda", label: "Measures of Shape & EDA" },
  { id: "empirical-rule", label: "The Empirical Rule" },
];

export const statisticsExamBank: StatisticsExamQuestion[] = [
  // ---------- Variables & Data Collection (12) ----------
  {
    id: "stats-ex-1",
    topic: "variables-data",
    subtopic: "IVPPSS",
    difficulty: 1,
    type: "concept",
    question: "In statistics, a 'parameter' is best described as:",
    options: ["A number computed from the population", "A number computed from the sample", "Another name for the mean only", "A type of graph"],
    correctIndex: 0,
    explanation: "A parameter summarizes the entire population; a statistic is the equivalent summary computed from just a sample.",
    relatedPartId: "stats-part-0",
  },
  {
    id: "stats-ex-2",
    topic: "variables-data",
    subtopic: "IVPPSS",
    difficulty: 1,
    type: "concept",
    question: "A 'statistic' (as opposed to a parameter) is computed from:",
    options: ["The sample", "The population", "A single individual", "A hypothesis"],
    correctIndex: 0,
    explanation: "A statistic is a summary number computed from the sample — it's used to estimate the corresponding (usually unknown) population parameter.",
    relatedPartId: "stats-part-0",
  },
  {
    id: "stats-ex-3",
    topic: "variables-data",
    subtopic: "Qualitative vs quantitative",
    difficulty: 1,
    type: "concept",
    question: "Which of these is a qualitative (categorical) variable?",
    options: ["Marital status", "Height in cm", "Number of children", "Annual income"],
    correctIndex: 0,
    explanation: "Marital status sorts individuals into categories (single/married/divorced) rather than assigning a numeric measurement.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-4",
    topic: "variables-data",
    subtopic: "Nominal vs ordinal",
    difficulty: 2,
    type: "concept",
    question: "'Customer satisfaction rating (very dissatisfied ... very satisfied)' is best classified as:",
    options: ["Nominal", "Ordinal", "Discrete", "Continuous"],
    correctIndex: 1,
    explanation: "There is a genuine rank/order to the categories (dissatisfied is 'less' than satisfied), which makes it ordinal, not nominal.",
    misconception: "Students sometimes call any category-based variable 'nominal' without checking whether the categories have a natural order.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-5",
    topic: "variables-data",
    subtopic: "Discrete vs continuous",
    difficulty: 1,
    type: "concept",
    question: "'Number of cars in a parking lot' is:",
    options: ["Discrete", "Continuous", "Nominal", "Ordinal"],
    correctIndex: 0,
    explanation: "It's a countable whole number — you can't have 4.5 cars — so it's discrete, even though it's quantitative.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-6",
    topic: "variables-data",
    subtopic: "Discrete vs continuous",
    difficulty: 2,
    type: "concept",
    question: "Which of these is the defining test for a continuous variable?",
    options: [
      "A potential value exists between any two values",
      "It can only take positive values",
      "It is always measured in metric units",
      "It always has a natural zero",
    ],
    correctIndex: 0,
    explanation: "Continuous variables allow (at least in principle) infinitely many values between any two given values — e.g. between 1.2cm and 1.3cm there's 1.25cm, 1.27cm, and so on.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-7",
    topic: "variables-data",
    subtopic: "Scales of measurement",
    difficulty: 2,
    type: "concept",
    question: "Temperature in Celsius is an example of which scale of measurement?",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"],
    correctIndex: 2,
    explanation: "Celsius has equal intervals (the gap from 10° to 20° equals the gap from 20° to 30°) but 0°C does not mean 'no temperature at all' — so it's interval, not ratio.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-8",
    topic: "variables-data",
    subtopic: "Scales of measurement",
    difficulty: 2,
    type: "concept",
    question: "Which scale of measurement has order, equal intervals, AND a true zero?",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"],
    correctIndex: 3,
    explanation: "Ratio scales (like weight, distance, or age) have all three properties — a true zero means '0' genuinely represents the absence of the quantity.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-9",
    topic: "variables-data",
    subtopic: "Primary vs secondary data",
    difficulty: 1,
    type: "concept",
    question: "Data collected by the researcher themselves, for their own specific study, is called:",
    options: ["Primary data", "Secondary data", "Population data", "Categorical data"],
    correctIndex: 0,
    explanation: "Primary data is collected first-hand for the exact purpose at hand; secondary data was collected by someone else for a different original purpose.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-10",
    topic: "variables-data",
    subtopic: "Primary vs secondary data",
    difficulty: 2,
    type: "concept",
    question: "A key LIMITATION of using secondary data is that it:",
    options: ["May not be exactly what you need", "Is always more expensive to obtain", "Cannot be numeric", "Is illegal to use"],
    correctIndex: 0,
    explanation: "Since secondary data was collected for someone else's purpose, it may be incomplete, outdated, or not quite match what the current research question needs.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-11",
    topic: "variables-data",
    subtopic: "Univariate/bivariate/multivariate",
    difficulty: 2,
    type: "concept",
    question: "A study recording both a patient's blood pressure AND their age is:",
    options: ["Bivariate", "Univariate", "Multivariate", "Nominal"],
    correctIndex: 0,
    explanation: "Exactly two variables are being recorded per individual, which makes this a bivariate study.",
    relatedPartId: "stats-part-1",
  },
  {
    id: "stats-ex-12",
    topic: "variables-data",
    subtopic: "Data collection methods",
    difficulty: 1,
    type: "concept",
    question: "Which of these is NOT one of the three most common methods of collecting primary data?",
    options: ["Experiment", "Observation", "Survey", "Literature review"],
    correctIndex: 3,
    explanation: "A literature review draws on other people's already-published (secondary) data — experiment, observation, and survey are the standard primary-data collection methods.",
    relatedPartId: "stats-part-1",
  },

  // ---------- Frequency Distributions & Graphs (14) ----------
  {
    id: "stats-ex-13",
    topic: "frequency-distributions",
    subtopic: "Class count rule",
    difficulty: 2,
    type: "concept",
    question: "Using the 2^k ≥ n rule, how many classes should a frequency table have for n = 100 observations?",
    options: ["6", "7", "8", "9"],
    correctIndex: 1,
    explanation: "2⁶=64 < 100, but 2⁷=128 ≥ 100, so the smallest valid k is 7.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-14",
    topic: "frequency-distributions",
    subtopic: "Class width",
    difficulty: 2,
    type: "concept",
    question: "A dataset ranges from 10 to 94 and needs 7 classes. What class width should be used?",
    options: ["10", "11", "12", "13"],
    correctIndex: 2,
    explanation: "Width = (94−10)/7 = 84/7 = 12 exactly — no rounding needed here since it divides evenly.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-15",
    topic: "frequency-distributions",
    subtopic: "Class width rounding",
    difficulty: 3,
    type: "concept",
    question: "A dataset ranges from 5 to 100 and needs 6 classes. What class width should be used?",
    options: ["15", "15.83 (leave as a decimal)", "16", "17"],
    correctIndex: 2,
    explanation: "(100−5)/6 = 15.83, which must be ROUNDED UP (not down or left as a decimal) to 16, so that 6 classes of width 16 are guaranteed to cover the full range.",
    misconception: "Rounding down or truncating the decimal leaves the last few data points with no class to belong to.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-16",
    topic: "frequency-distributions",
    subtopic: "Class boundaries",
    difficulty: 2,
    type: "concept",
    question: "For the class limits 20-29 and 30-39, the class boundary between them is:",
    options: ["29.5", "30", "29", "30.5"],
    correctIndex: 0,
    explanation: "The gap between 29 (upper limit) and 30 (next lower limit) is 1; half of that gap is 0.5, so the boundary sits at 29.5 — closing the gap between the two classes.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-17",
    topic: "frequency-distributions",
    subtopic: "Class midpoint",
    difficulty: 1,
    type: "concept",
    question: "The midpoint of the class 40-49 is:",
    options: ["44", "44.5", "45", "40"],
    correctIndex: 1,
    explanation: "Midpoint = (lower + upper)/2 = (40+49)/2 = 44.5.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-18",
    topic: "frequency-distributions",
    subtopic: "Relative frequency",
    difficulty: 1,
    type: "concept",
    question: "A class has frequency 18 out of a total of n = 60 observations. Its relative frequency is:",
    options: ["0.3", "18", "3.33", "0.6"],
    correctIndex: 0,
    explanation: "Relative frequency = frequency / n = 18/60 = 0.3.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-19",
    topic: "frequency-distributions",
    subtopic: "Cumulative frequency",
    difficulty: 1,
    type: "concept",
    question: "Class frequencies are 5, 8, 12, 7 (in order). What is the cumulative frequency of the THIRD class?",
    options: ["12", "20", "25", "32"],
    correctIndex: 2,
    explanation: "Cumulative frequency sums the class's own frequency with every class before it: 5 + 8 + 12 = 25.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-20",
    topic: "frequency-distributions",
    subtopic: "Rules for FD tables",
    difficulty: 2,
    type: "concept",
    question: "Why must classes in a frequency distribution be mutually exclusive?",
    options: [
      "So no single observation can be placed into two classes at once",
      "So the table looks neater",
      "So the mean can be calculated",
      "It's not actually required",
    ],
    correctIndex: 0,
    explanation: "If classes overlapped, some values could be double-counted, inflating the total frequency beyond n.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-21",
    topic: "frequency-distributions",
    subtopic: "Histogram",
    difficulty: 1,
    type: "concept",
    question: "A histogram represents class frequencies using:",
    options: ["Contiguous (touching) vertical bars", "Separated vertical bars with gaps", "A single continuous curve", "Sectors of a circle"],
    correctIndex: 0,
    explanation: "Histogram bars touch each other (using class boundaries) because the underlying data is continuous with no real gaps between classes — unlike a bar graph for categorical data.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-22",
    topic: "frequency-distributions",
    subtopic: "Ogive",
    difficulty: 2,
    type: "concept",
    question: "An ogive (cumulative frequency curve) should always be:",
    options: ["Non-decreasing (never goes down)", "A straight line", "Symmetric", "Bell-shaped"],
    correctIndex: 0,
    explanation: "Since cumulative frequency only ever adds more observations as you move along the x-axis, the curve can never decrease.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-23",
    topic: "frequency-distributions",
    subtopic: "Pie chart",
    difficulty: 2,
    type: "concept",
    question: "A category makes up 15% of a dataset. What angle (in degrees) should its pie chart sector have?",
    options: ["15°", "36°", "54°", "150°"],
    correctIndex: 2,
    explanation: "A circle has 360°, so 15% of 360° = 0.15 × 360 = 54°.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-24",
    topic: "frequency-distributions",
    subtopic: "Categorical frequency distribution",
    difficulty: 1,
    type: "concept",
    question: "A categorical frequency distribution is used when the data is:",
    options: ["Nominal or ordinal", "Only continuous", "Only from a survey", "Impossible to graph"],
    correctIndex: 0,
    explanation: "Categorical data (nominal or ordinal) just needs a tally per category — no class limits or boundaries are needed, unlike numeric grouped data.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-25",
    topic: "frequency-distributions",
    subtopic: "Class count rule",
    difficulty: 2,
    type: "concept",
    question: "Using the 2^k ≥ n rule, how many classes should be used for n = 30 observations?",
    options: ["4", "5", "6", "7"],
    correctIndex: 1,
    explanation: "2⁴=16 < 30, but 2⁵=32 ≥ 30, so the smallest valid k is 5.",
    relatedPartId: "stats-part-2",
  },
  {
    id: "stats-ex-26",
    topic: "frequency-distributions",
    subtopic: "Scatter plot",
    difficulty: 1,
    type: "concept",
    question: "A scatter plot is most appropriate for:",
    options: [
      "Showing the relationship between two quantitative variables",
      "Showing the frequency of a single categorical variable",
      "Showing cumulative frequency",
      "Showing percentages as pie slices",
    ],
    correctIndex: 0,
    explanation: "Scatter plots specifically show how two quantitative variables relate to each other (e.g. whether they trend together).",
    relatedPartId: "stats-part-2",
  },

  // ---------- Measures of Central Tendency (16) ----------
  {
    id: "stats-ex-27",
    topic: "central-tendency",
    subtopic: "Mean sensitivity",
    difficulty: 2,
    type: "concept",
    question: "Which measure of central tendency is MOST affected by a single extreme outlier?",
    options: ["Arithmetic mean", "Median", "Mode", "None of these — they're all equally affected"],
    correctIndex: 0,
    explanation: "The arithmetic mean uses every value's actual magnitude, so one extreme value can pull it substantially; the median only depends on rank order.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-28",
    topic: "central-tendency",
    subtopic: "Trimmed mean",
    difficulty: 2,
    type: "concept",
    question: "The purpose of a trimmed mean is to:",
    options: [
      "Reduce the influence of extreme values by dropping the most extreme few percent from each end",
      "Make the mean always equal the median",
      "Only use the largest half of the data",
      "Replace the need for a standard deviation",
    ],
    correctIndex: 0,
    explanation: "Trimming removes a set percentage of the most extreme values from each end before averaging, protecting the result from being distorted by outliers.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-29",
    topic: "central-tendency",
    subtopic: "Geometric mean",
    difficulty: 2,
    type: "concept",
    question: "The geometric mean is most appropriate for averaging:",
    options: ["Growth rates or percentages", "Any dataset with negative numbers", "Categorical data", "Data with many ties"],
    correctIndex: 0,
    explanation: "Geometric mean handles multiplicative quantities (rates, ratios, percentage changes) correctly, and requires all values to be positive.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-30",
    topic: "central-tendency",
    subtopic: "Mode",
    difficulty: 1,
    type: "concept",
    question: "A dataset with two values tied for 'most frequent' is called:",
    options: ["Bimodal", "Unimodal", "Skewed", "Trimmed"],
    correctIndex: 0,
    explanation: "Bimodal means the dataset has exactly two modes; a dataset can even be multimodal with more than two.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-31",
    topic: "central-tendency",
    subtopic: "Weighted mean",
    difficulty: 2,
    type: "concept",
    question: "A weighted mean differs from a simple arithmetic mean because it:",
    options: [
      "Multiplies each value by its own weight before averaging",
      "Only uses the largest value",
      "Ignores repeated values",
      "Can only be used on grouped data",
    ],
    correctIndex: 0,
    explanation: "Weighted mean = Σ(value × weight) / Σ(weight) — values with a larger weight (like more credit hours) count proportionally more.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-32",
    topic: "central-tendency",
    subtopic: "Computing the mean",
    difficulty: 2,
    type: "concept",
    question: "For the dataset 10, 12, 12, 15, 18, the arithmetic mean is:",
    options: ["12", "13.4", "14", "15"],
    correctIndex: 1,
    explanation: "Sum = 10+12+12+15+18 = 67. Mean = 67/5 = 13.4.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-33",
    topic: "central-tendency",
    subtopic: "Computing the median",
    difficulty: 2,
    type: "concept",
    question: "For the dataset 10, 12, 12, 15, 18, the median is:",
    options: ["10", "12", "13.4", "15"],
    correctIndex: 1,
    explanation: "The data is already sorted; with n=5 (odd), the median is the middle (3rd) value: 12.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-34",
    topic: "central-tendency",
    subtopic: "Computing the mode",
    difficulty: 1,
    type: "concept",
    question: "For the dataset 10, 12, 12, 15, 18, the mode is:",
    options: ["10", "12", "13.4", "18"],
    correctIndex: 1,
    explanation: "12 appears twice — more often than any other value — making it the mode.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-35",
    topic: "central-tendency",
    subtopic: "Median for even n",
    difficulty: 2,
    type: "concept",
    question: "For the dataset 4, 7, 9, 12 (n = 4), the median is:",
    options: ["7", "8", "9", "9.5"],
    correctIndex: 1,
    explanation: "With an even number of values, the median is the average of the two middle values: (7+9)/2 = 8.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-36",
    topic: "central-tendency",
    subtopic: "Choosing the right measure",
    difficulty: 3,
    type: "best-practice",
    question: "A dataset of household incomes is heavily right-skewed (a few very high earners). Which measure best represents the 'typical' household?",
    options: ["Median", "Arithmetic mean", "Range", "Standard deviation"],
    correctIndex: 0,
    explanation: "The mean would be dragged upward by the few very high incomes; the median stays closer to where most households actually sit — this is exactly why income statistics are usually reported as medians.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-37",
    topic: "central-tendency",
    subtopic: "Assumed mean method",
    difficulty: 3,
    type: "concept",
    question: "In the assumed-mean method for grouped data, the deviation d for a class is calculated as:",
    options: ["d = x − A (class midpoint minus assumed mean)", "d = x + A", "d = A / x", "d = f × x"],
    correctIndex: 0,
    explanation: "d is the deviation of each class midpoint (x) from the assumed mean (A); the true mean is then recovered as A + (Σfd/Σf).",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-38",
    topic: "central-tendency",
    subtopic: "Coding method",
    difficulty: 3,
    type: "concept",
    question: "In the coding method for grouped data with equal class width c, the coded value u equals:",
    options: ["(x − A) / c", "x × c", "A / c", "x + A"],
    correctIndex: 0,
    explanation: "u = (x − A)/c rescales the deviation by the class width, simplifying the arithmetic before multiplying back by c at the end.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-39",
    topic: "central-tendency",
    subtopic: "Trimmed mean computation",
    difficulty: 3,
    type: "concept",
    question: "For a 10-value dataset, a 10% trimmed mean removes how many values from EACH end?",
    options: ["0", "1", "2", "5"],
    correctIndex: 1,
    explanation: "10% of 10 = 1, so exactly 1 value is removed from the bottom and 1 from the top before averaging the remaining 8.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-40",
    topic: "central-tendency",
    subtopic: "Weighted mean computation",
    difficulty: 3,
    type: "concept",
    question: "A student scores 80 (weight 2) and 90 (weight 3) in two courses. The weighted mean is:",
    options: ["85", "86", "84", "87"],
    correctIndex: 1,
    explanation: "Weighted mean = (80×2 + 90×3) / (2+3) = (160+270)/5 = 430/5 = 86.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-41",
    topic: "central-tendency",
    subtopic: "Mode of grouped data",
    difficulty: 3,
    type: "concept",
    question: "In the grouped-data mode formula, Δ1 represents the difference between:",
    options: [
      "The modal class frequency and the PRECEDING class frequency",
      "The modal class frequency and the SUCCEEDING class frequency",
      "The upper and lower class limits",
      "The class width and 1",
    ],
    correctIndex: 0,
    explanation: "Δ1 = (modal frequency − preceding class frequency); Δ2 = (modal frequency − succeeding class frequency). Mode = L + [Δ1/(Δ1+Δ2)] × c.",
    relatedPartId: "stats-part-3",
  },
  {
    id: "stats-ex-42",
    topic: "central-tendency",
    subtopic: "Geometric mean vs arithmetic mean",
    difficulty: 3,
    type: "concept",
    question: "For any dataset of positive numbers that aren't all identical, the geometric mean is:",
    options: ["Always less than the arithmetic mean", "Always greater than the arithmetic mean", "Always equal to the arithmetic mean", "Unpredictable relative to the arithmetic mean"],
    correctIndex: 0,
    explanation: "The geometric mean is always ≤ the arithmetic mean (with equality only when all values are identical) — a general mathematical fact (AM-GM inequality).",
    relatedPartId: "stats-part-3",
  },

  // ---------- Measures of Dispersion (16) ----------
  {
    id: "stats-ex-43",
    topic: "dispersion",
    subtopic: "Range",
    difficulty: 1,
    type: "concept",
    question: "For the dataset 14, 22, 9, 31, 18, the range is:",
    options: ["18", "20", "22", "31"],
    correctIndex: 2,
    explanation: "Range = highest − lowest = 31 − 9 = 22.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-44",
    topic: "dispersion",
    subtopic: "Range limitation",
    difficulty: 2,
    type: "concept",
    question: "The main limitation of using the range as a measure of dispersion is that it:",
    options: [
      "Only uses the two extreme values and ignores everything in between",
      "Cannot be computed for small datasets",
      "Is always negative",
      "Requires a computer to calculate",
    ],
    correctIndex: 0,
    explanation: "Because the range only looks at the max and min, it's blind to how the rest of the data is distributed — and very sensitive to a single outlier.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-45",
    topic: "dispersion",
    subtopic: "Mean deviation",
    difficulty: 2,
    type: "concept",
    question: "The mean deviation is calculated using:",
    options: [
      "The average of the ABSOLUTE deviations from the mean",
      "The average of the squared deviations from the mean",
      "The largest deviation from the mean",
      "The deviation of the mean from the median",
    ],
    correctIndex: 0,
    explanation: "Mean deviation = Σ|x − mean| / n — absolute values are used so that positive and negative deviations don't cancel out to zero.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-46",
    topic: "dispersion",
    subtopic: "Population vs sample variance",
    difficulty: 2,
    type: "concept",
    question: "Population variance divides the sum of squared deviations by n, while sample variance divides by:",
    options: ["n − 1", "n + 1", "n", "√n"],
    correctIndex: 0,
    explanation: "Sample variance uses (n−1) — Bessel's correction — to compensate for the sample mean fitting its own sample slightly too well.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-47",
    topic: "dispersion",
    subtopic: "SD vs variance",
    difficulty: 1,
    type: "concept",
    question: "Standard deviation is related to variance by:",
    options: ["SD is the square root of variance", "SD is the square of variance", "They are unrelated", "SD is always larger than variance"],
    correctIndex: 0,
    explanation: "SD = √variance — this puts the spread measure back into the same units as the original data.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-48",
    topic: "dispersion",
    subtopic: "Coefficient of variation",
    difficulty: 2,
    type: "concept",
    question: "The coefficient of variation (CV) is most useful for:",
    options: [
      "Comparing variability between two datasets with different units or very different means",
      "Replacing the need to compute a mean",
      "Only measuring symmetric distributions",
      "Converting variance into range",
    ],
    correctIndex: 0,
    explanation: "CV = (SD/mean) × 100% is unit-free, so it lets you fairly compare 'relative spread' even across very different scales.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-49",
    topic: "dispersion",
    subtopic: "Computing variance",
    difficulty: 3,
    type: "concept",
    question: "For the dataset 2, 4, 4, 4, 5, 5, 7, 9 (mean = 5), the POPULATION variance is:",
    options: ["2", "4", "5", "8"],
    correctIndex: 1,
    explanation: "Squared deviations from 5 are 9,1,1,1,0,0,4,16, summing to 32. Population variance = 32/8 = 4.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-50",
    topic: "dispersion",
    subtopic: "Computing SD",
    difficulty: 3,
    type: "concept",
    question: "For the dataset 2, 4, 4, 4, 5, 5, 7, 9 (mean = 5, population variance = 4), the POPULATION standard deviation is:",
    options: ["1", "2", "4", "16"],
    correctIndex: 1,
    explanation: "Population SD = √(population variance) = √4 = 2.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-51",
    topic: "dispersion",
    subtopic: "Computing sample variance",
    difficulty: 3,
    type: "concept",
    question: "For the dataset 2, 4, 4, 4, 5, 5, 7, 9 (sum of squared deviations = 32), the SAMPLE variance is closest to:",
    options: ["4.00", "4.57", "5.33", "6.40"],
    correctIndex: 1,
    explanation: "Sample variance = 32/(n−1) = 32/7 ≈ 4.57 — larger than the population variance of 4 because it divides by a smaller number.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-52",
    topic: "dispersion",
    subtopic: "Why deviations are squared",
    difficulty: 3,
    type: "concept",
    question: "Deviations from the mean are squared (rather than just summed) when computing variance mainly because:",
    options: [
      "The raw deviations always sum to zero, and squaring also penalizes larger deviations more heavily",
      "Squaring is required to make the units match the original data",
      "It makes the calculation shorter",
      "Negative numbers cannot exist in statistics",
    ],
    correctIndex: 0,
    explanation: "Σ(x − mean) is always exactly 0 by definition of the mean, so squaring is needed to get a meaningful, non-cancelling measure of spread — and it also weights bigger deviations more than smaller ones.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-53",
    topic: "dispersion",
    subtopic: "Sample vs population SD",
    difficulty: 3,
    type: "concept",
    question: "For the SAME dataset, the sample standard deviation (divided by n−1) compared to the population standard deviation (divided by n) will always be:",
    options: ["Greater than or equal to the population SD", "Less than or equal to the population SD", "Always exactly equal", "Impossible to compare"],
    correctIndex: 0,
    explanation: "Since (n−1) < n, dividing the same sum of squared deviations by a smaller number always produces a variance (and thus SD) that is greater than or equal to the population version.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-54",
    topic: "dispersion",
    subtopic: "Computing mean deviation",
    difficulty: 3,
    type: "concept",
    question: "For the dataset 2, 4, 4, 4, 5, 5, 7, 9 (mean = 5), the mean deviation is:",
    options: ["1.0", "1.5", "2.0", "4.0"],
    correctIndex: 1,
    explanation: "Absolute deviations from 5 are 3,1,1,1,0,0,2,4, summing to 12. Mean deviation = 12/8 = 1.5.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-55",
    topic: "dispersion",
    subtopic: "Comparing CV",
    difficulty: 3,
    type: "best-practice",
    question: "Dataset A has mean 200, SD 20. Dataset B has mean 50, SD 10. Which is MORE variable relative to its own mean?",
    options: ["Dataset B (CV = 20%) is more variable than Dataset A (CV = 10%)", "Dataset A is more variable because its SD is larger", "They are equally variable", "Cannot be determined"],
    correctIndex: 0,
    explanation: "CV_A = 20/200×100 = 10%. CV_B = 10/50×100 = 20%. Even though A's raw SD is bigger, B is more variable RELATIVE to its own mean.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-56",
    topic: "dispersion",
    subtopic: "Units of variance vs SD",
    difficulty: 2,
    type: "concept",
    question: "If a dataset of exam scores is measured in points, the variance is measured in:",
    options: ["Points squared", "Points", "Percent", "No units at all"],
    correctIndex: 0,
    explanation: "Squaring the deviations also squares the units — this is exactly why SD (which un-squares it via the square root) is usually easier to interpret.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-57",
    topic: "dispersion",
    subtopic: "Population vs sample formulas",
    difficulty: 2,
    type: "best-practice",
    question: "If you have data on every single employee at a small company (not a sample), which formula should you use to compute variance?",
    options: ["The population variance formula (divide by n)", "The sample variance formula (divide by n−1)", "Either — they always give the same answer", "Neither — variance requires a sample"],
    correctIndex: 0,
    explanation: "Since the data covers the entire population of interest (all employees), the population formula is correct — the n−1 correction is only needed when generalizing FROM a sample TO an unknown population.",
    relatedPartId: "stats-part-4",
  },
  {
    id: "stats-ex-58",
    topic: "dispersion",
    subtopic: "Computing CV",
    difficulty: 2,
    type: "concept",
    question: "A dataset has mean 50 and standard deviation 10. Its coefficient of variation is:",
    options: ["5%", "10%", "20%", "50%"],
    correctIndex: 2,
    explanation: "CV = (SD/mean) × 100% = (10/50) × 100% = 20%.",
    relatedPartId: "stats-part-4",
  },

  // ---------- Measures of Position (14) ----------
  {
    id: "stats-ex-59",
    topic: "position",
    subtopic: "Quartiles",
    difficulty: 1,
    type: "concept",
    question: "Quartiles divide an ordered dataset into:",
    options: ["4 equal parts", "10 equal parts", "100 equal parts", "2 equal parts"],
    correctIndex: 0,
    explanation: "Q1, Q2, and Q3 split the data into four groups of roughly equal size.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-60",
    topic: "position",
    subtopic: "Q2 = median",
    difficulty: 1,
    type: "concept",
    question: "The second quartile (Q2) is always the same value as:",
    options: ["The median", "The mean", "The mode", "The range"],
    correctIndex: 0,
    explanation: "Q2 marks the 50th percentile — exactly the middle of the sorted data — which is the definition of the median.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-61",
    topic: "position",
    subtopic: "Percentiles",
    difficulty: 1,
    type: "concept",
    question: "Percentiles divide an ordered dataset into:",
    options: ["100 equal parts", "4 equal parts", "10 equal parts", "50 equal parts"],
    correctIndex: 0,
    explanation: "The k-th percentile is the value below which k% of the data falls, so there are 99 percentile cut-points dividing the data into 100 parts.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-62",
    topic: "position",
    subtopic: "IQR",
    difficulty: 2,
    type: "concept",
    question: "The interquartile range (IQR) is calculated as:",
    options: ["Q3 − Q1", "Q3 + Q1", "Q3 − Q2", "Max − Min"],
    correctIndex: 0,
    explanation: "IQR spans the middle 50% of the data — from the top of the first quarter (Q1) to the top of the third quarter (Q3).",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-63",
    topic: "position",
    subtopic: "Grouped percentile formula",
    difficulty: 3,
    type: "concept",
    question: "In the grouped-data percentile formula P_k = l + (c/f)(nk − F), 'l' represents:",
    options: ["The lower boundary of the class containing the percentile", "The total number of observations", "The class width", "The frequency of the target class"],
    correctIndex: 0,
    explanation: "l is the lower boundary of the target class — the starting point that the formula then adjusts by how far INTO that class the percentile position falls.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-64",
    topic: "position",
    subtopic: "Grouped percentile formula",
    difficulty: 3,
    type: "concept",
    question: "In the grouped-data percentile formula P_k = l + (c/f)(nk − F), the term 'nk' represents:",
    options: [
      "The target cumulative position (n × k, where k is the percentile as a decimal)",
      "The class width multiplied by frequency",
      "The number of classes",
      "The total frequency",
    ],
    correctIndex: 0,
    explanation: "nk is how many observations should fall at or below the target percentile (e.g. for P90 with n=40, nk = 40×0.90 = 36) — this position is then located within the cumulative frequency column.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-65",
    topic: "position",
    subtopic: "Deciles",
    difficulty: 1,
    type: "concept",
    question: "Deciles divide an ordered dataset into:",
    options: ["10 equal parts", "4 equal parts", "100 equal parts", "5 equal parts"],
    correctIndex: 0,
    explanation: "D1 through D9 split the data into ten equally-sized groups.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-66",
    topic: "position",
    subtopic: "Ungrouped quartile position",
    difficulty: 2,
    type: "concept",
    question: "For ungrouped data, the position of Q1 is found using the formula:",
    options: ["(n + 1) / 4", "n / 4", "(n − 1) / 4", "n × 0.25"],
    correctIndex: 0,
    explanation: "Q1's position = (n+1)/4; if this isn't a whole number, interpolate between the two nearest ranked values.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-67",
    topic: "position",
    subtopic: "Computing Q1",
    difficulty: 3,
    type: "concept",
    question: "For the sorted dataset 5, 7, 7, 9, 12, 15, 20 (n = 7), Q1 is:",
    options: ["5", "7", "9", "12"],
    correctIndex: 1,
    explanation: "Q1 position = (7+1)/4 = 2, so Q1 is exactly the 2nd value: 7.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-68",
    topic: "position",
    subtopic: "Computing Q3",
    difficulty: 3,
    type: "concept",
    question: "For the sorted dataset 5, 7, 7, 9, 12, 15, 20 (n = 7), Q3 is:",
    options: ["9", "12", "15", "20"],
    correctIndex: 2,
    explanation: "Q3 position = 3(7+1)/4 = 6, so Q3 is exactly the 6th value: 15.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-69",
    topic: "position",
    subtopic: "Computing IQR",
    difficulty: 3,
    type: "concept",
    question: "For the sorted dataset 5, 7, 7, 9, 12, 15, 20 (Q1 = 7, Q3 = 15), the IQR is:",
    options: ["6", "8", "15", "20"],
    correctIndex: 1,
    explanation: "IQR = Q3 − Q1 = 15 − 7 = 8.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-70",
    topic: "position",
    subtopic: "Interpolated quartile",
    difficulty: 4,
    type: "concept",
    question: "For the sorted dataset 3, 6, 7, 8, 10, 13, 15, 18 (n = 8), Q1 is:",
    options: ["6", "6.25", "6.5", "7"],
    correctIndex: 1,
    explanation: "Q1 position = (8+1)/4 = 2.25, i.e. 0.25 of the way from the 2nd value (6) to the 3rd value (7): 6 + 0.25×(7−6) = 6.25.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-71",
    topic: "position",
    subtopic: "Boxplot components",
    difficulty: 2,
    type: "concept",
    question: "A boxplot's five-number summary is built from:",
    options: ["Minimum, Q1, median, Q3, maximum", "Mean, mode, median, range, SD", "Q1, Q2, Q3, Q4, Q5", "Minimum, mean, maximum, SD, variance"],
    correctIndex: 0,
    explanation: "The five-number summary is exactly the set of position measures needed to draw a boxplot: min, Q1, median (Q2), Q3, max.",
    relatedPartId: "stats-part-5",
  },
  {
    id: "stats-ex-72",
    topic: "position",
    subtopic: "Why interpolation is needed",
    difficulty: 3,
    type: "concept",
    question: "Interpolation is often required when computing a quartile or percentile because:",
    options: [
      "The calculated position frequently falls BETWEEN two ranked observations, not exactly on one",
      "Data must always be rounded to the nearest whole number",
      "It's only needed for grouped data, never ungrouped",
      "Percentiles cannot be computed without a computer",
    ],
    correctIndex: 0,
    explanation: "Formulas like (n+1)k/4 rarely land on a whole number, so the value is estimated by interpolating a proportional distance between the two nearest actual data points.",
    relatedPartId: "stats-part-5",
  },

  // ---------- Measures of Shape & EDA (14) ----------
  {
    id: "stats-ex-73",
    topic: "shape-eda",
    subtopic: "Skewness definition",
    difficulty: 1,
    type: "concept",
    question: "Skewness measures:",
    options: ["The asymmetry of a distribution", "The center of a distribution", "The spread of a distribution", "The sample size"],
    correctIndex: 0,
    explanation: "Skewness quantifies how lopsided a distribution is — whether it leans with a longer tail to one side.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-74",
    topic: "shape-eda",
    subtopic: "Positive skew",
    difficulty: 2,
    type: "concept",
    question: "In a positively (right) skewed distribution, the relationship between mean and median is typically:",
    options: ["Mean > median", "Mean < median", "Mean = median", "No relationship exists"],
    correctIndex: 0,
    explanation: "A long right tail pulls the mean upward more than the median, since the mean (unlike the median) is sensitive to the magnitude of extreme values.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-75",
    topic: "shape-eda",
    subtopic: "Negative skew",
    difficulty: 2,
    type: "concept",
    question: "In a negatively (left) skewed distribution, the relationship between mean and median is typically:",
    options: ["Mean < median", "Mean > median", "Mean = median", "No relationship exists"],
    correctIndex: 0,
    explanation: "A long left tail pulls the mean downward below the median.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-76",
    topic: "shape-eda",
    subtopic: "Symmetric distributions",
    difficulty: 1,
    type: "concept",
    question: "In a perfectly symmetric, unimodal distribution:",
    options: ["Mean = median = mode", "Mean is always largest", "Mode is always largest", "Median is always largest"],
    correctIndex: 0,
    explanation: "With no skew pulling any measure away from the center, all three measures of central tendency coincide at the same value.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-77",
    topic: "shape-eda",
    subtopic: "Kurtosis definition",
    difficulty: 2,
    type: "concept",
    question: "Kurtosis measures:",
    options: ["The 'peakedness' and tail-heaviness of a distribution", "The center of a distribution", "The skewness of a distribution", "The sample size needed"],
    correctIndex: 0,
    explanation: "Kurtosis describes how sharply peaked the center is and how heavy/light the tails are, compared to a normal distribution.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-78",
    topic: "shape-eda",
    subtopic: "Mesokurtic",
    difficulty: 2,
    type: "concept",
    question: "A distribution described as 'mesokurtic' has:",
    options: ["The same peakedness/tail-weight as a normal distribution", "A much sharper peak than normal", "A much flatter peak than normal", "No peak at all"],
    correctIndex: 0,
    explanation: "Mesokurtic (kurtosis ≈ 3) is the 'baseline' shape — matching the normal distribution's peak and tails.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-79",
    topic: "shape-eda",
    subtopic: "Leptokurtic",
    difficulty: 2,
    type: "concept",
    question: "A leptokurtic distribution (kurtosis > 3) has:",
    options: ["A sharper peak and fatter (heavier) tails than normal", "A flatter peak and thinner tails than normal", "Exactly the same shape as normal", "Always negative values"],
    correctIndex: 0,
    explanation: "Leptokurtic distributions concentrate more data near the mean AND have more extreme outliers than a normal distribution would predict.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-80",
    topic: "shape-eda",
    subtopic: "Platykurtic",
    difficulty: 2,
    type: "concept",
    question: "A platykurtic distribution (kurtosis < 3) has:",
    options: ["A flatter peak and thinner tails than normal", "A sharper peak and fatter tails than normal", "Exactly the same shape as normal", "Always positive skew"],
    correctIndex: 0,
    explanation: "Platykurtic distributions are more spread out and 'flat-topped' with fewer extreme outliers than a normal distribution.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-81",
    topic: "shape-eda",
    subtopic: "Five-number summary",
    difficulty: 1,
    type: "concept",
    question: "The five-number summary consists of:",
    options: ["Minimum, Q1, median, Q3, maximum", "Mean, median, mode, range, SD", "Q1, Q2, Q3, IQR, CV", "Minimum, mean, maximum, mode, variance"],
    correctIndex: 0,
    explanation: "These five values give a compact picture of both the center and the spread of a dataset, and are exactly what a boxplot displays.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-82",
    topic: "shape-eda",
    subtopic: "Boxplot whiskers",
    difficulty: 2,
    type: "concept",
    question: "On a boxplot, a noticeably longer whisker on the right side (compared to the left) suggests:",
    options: ["The data likely has a positive (right) skew", "The data likely has a negative (left) skew", "The data is perfectly symmetric", "The sample size is too small"],
    correctIndex: 0,
    explanation: "A longer right whisker means the top 25% of the data is more spread out — consistent with a longer right tail, i.e. positive skew.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-83",
    topic: "shape-eda",
    subtopic: "Computing skewness",
    difficulty: 3,
    type: "concept",
    question: "Using Sk = 3(mean − median)/SD, for a dataset with mean = 28, median = 25, SD = 4.2, the skewness coefficient is closest to:",
    options: ["0.71", "1.43", "2.14", "3.00"],
    correctIndex: 2,
    explanation: "Sk = 3×(28−25)/4.2 = 3×3/4.2 = 9/4.2 ≈ 2.14 — a fairly strong positive skew.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-84",
    topic: "shape-eda",
    subtopic: "Boxplot median position",
    difficulty: 3,
    type: "concept",
    question: "On a boxplot, if the median line sits noticeably closer to Q1 than to Q3, this suggests:",
    options: [
      "The lower half of the data is more tightly packed, consistent with positive skew",
      "The distribution must be exactly normal",
      "The data has no outliers",
      "The sample size is even",
    ],
    correctIndex: 0,
    explanation: "The median being pushed toward Q1 means the bottom 50% of the data is compressed into a smaller range than the top 50% — a visual sign of a right-skewed shape.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-85",
    topic: "shape-eda",
    subtopic: "EDA purpose",
    difficulty: 2,
    type: "concept",
    question: "The main purpose of Exploratory Data Analysis (EDA) is to:",
    options: [
      "Investigate a dataset's patterns, shape, and possible outliers before formal analysis",
      "Replace the need for any formal statistical test",
      "Only produce a single final summary number",
      "Only be used on categorical data",
    ],
    correctIndex: 0,
    explanation: "EDA is about understanding the data first — its shape, spread, and anomalies — which then informs what formal methods are appropriate.",
    relatedPartId: "stats-part-6",
  },
  {
    id: "stats-ex-86",
    topic: "shape-eda",
    subtopic: "Median in EDA",
    difficulty: 2,
    type: "best-practice",
    question: "In EDA and boxplots, the median (rather than the mean) is typically used to summarize the center because it is:",
    options: ["Resistant to outliers and skewed data", "Easier to calculate by hand", "The only measure that always exists", "Required by definition of a boxplot"],
    correctIndex: 0,
    explanation: "The median is a 'robust' statistic — a few extreme values or a skewed shape barely move it, making it a more reliable summary for exploratory work.",
    relatedPartId: "stats-part-6",
  },

  // ---------- The Empirical Rule (14) ----------
  {
    id: "stats-ex-87",
    topic: "empirical-rule",
    subtopic: "The rule statement",
    difficulty: 1,
    type: "concept",
    question: "According to the Empirical Rule, approximately what percentage of data falls within 1 standard deviation of the mean?",
    options: ["68%", "95%", "99.7%", "50%"],
    correctIndex: 0,
    explanation: "The Empirical Rule states roughly 68% of data falls within ±1 SD, 95% within ±2 SD, and 99.7% within ±3 SD, for a bell-shaped distribution.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-88",
    topic: "empirical-rule",
    subtopic: "Applicability",
    difficulty: 2,
    type: "concept",
    question: "The Empirical Rule reliably applies to distributions that are:",
    options: ["Approximately bell-shaped (normal)", "Heavily skewed", "Bimodal", "Any shape whatsoever"],
    correctIndex: 0,
    explanation: "The 68/95/99.7% figures come directly from the mathematics of the normal distribution — they don't hold for strongly skewed or multimodal data.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-89",
    topic: "empirical-rule",
    subtopic: "Computing ±1 SD range",
    difficulty: 2,
    type: "concept",
    question: "For a bell-shaped distribution with mean = 150 and SD = 20, the range covering approximately 68% of the data is:",
    options: ["130 to 170", "110 to 190", "90 to 210", "150 to 170"],
    correctIndex: 0,
    explanation: "±1 SD from the mean: 150 − 20 = 130, and 150 + 20 = 170.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-90",
    topic: "empirical-rule",
    subtopic: "Computing ±2 SD range",
    difficulty: 2,
    type: "concept",
    question: "For a bell-shaped distribution with mean = 150 and SD = 20, the range covering approximately 95% of the data is:",
    options: ["130 to 170", "110 to 190", "90 to 210", "120 to 180"],
    correctIndex: 1,
    explanation: "±2 SD from the mean: 150 − 40 = 110, and 150 + 40 = 190.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-91",
    topic: "empirical-rule",
    subtopic: "Computing ±3 SD range",
    difficulty: 2,
    type: "concept",
    question: "For a bell-shaped distribution with mean = 150 and SD = 20, the range covering approximately 99.7% of the data is:",
    options: ["110 to 190", "130 to 170", "90 to 210", "70 to 230"],
    correctIndex: 2,
    explanation: "±3 SD from the mean: 150 − 60 = 90, and 150 + 60 = 210.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-92",
    topic: "empirical-rule",
    subtopic: "Percentage outside a range",
    difficulty: 2,
    type: "concept",
    question: "According to the Empirical Rule, approximately what percentage of data falls OUTSIDE ±2 SD of the mean?",
    options: ["5%", "32%", "68%", "0.3%"],
    correctIndex: 0,
    explanation: "Since ~95% falls within ±2 SD, the remaining 100% − 95% = 5% falls outside that range (split between both tails).",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-93",
    topic: "empirical-rule",
    subtopic: "Half-interval percentage",
    difficulty: 3,
    type: "concept",
    question: "According to the Empirical Rule, approximately what percentage of data falls between the mean and 1 SD ABOVE the mean?",
    options: ["34%", "68%", "50%", "16%"],
    correctIndex: 0,
    explanation: "The 68% within ±1 SD is split symmetrically around the mean, so exactly half — 34% — lies between the mean and +1 SD.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-94",
    topic: "empirical-rule",
    subtopic: "Rule requirements",
    difficulty: 2,
    type: "concept",
    question: "Before applying the Empirical Rule to a real dataset, you should first check that the data is:",
    options: ["Roughly symmetric and bell-shaped", "Entirely positive", "Discrete", "Collected from a survey"],
    correctIndex: 0,
    explanation: "Applying the 68/95/99.7% figures to a skewed or oddly-shaped distribution would give misleading results — the shape assumption must hold first.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-95",
    topic: "empirical-rule",
    subtopic: "Distance from mean in SDs",
    difficulty: 2,
    type: "concept",
    question: "For a distribution with mean = 150 and SD = 20, the value 190 is how many standard deviations from the mean?",
    options: ["1", "2", "3", "4"],
    correctIndex: 1,
    explanation: "(190 − 150) / 20 = 40/20 = 2 standard deviations above the mean.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-96",
    topic: "empirical-rule",
    subtopic: "Interpreting a good fit",
    difficulty: 3,
    type: "concept",
    question: "If a real dataset's actual percentages within ±1, ±2, and ±3 SD closely match 68%, 95%, and 99.7%, this is evidence that:",
    options: [
      "The distribution is approximately normal (bell-shaped)",
      "The dataset has no variability",
      "The dataset must be categorical",
      "The mean and median are definitely different",
    ],
    correctIndex: 0,
    explanation: "A close match to the Empirical Rule's predicted percentages is itself a diagnostic clue that the data resembles a normal distribution.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-97",
    topic: "empirical-rule",
    subtopic: "Percentage beyond 3 SD",
    difficulty: 2,
    type: "concept",
    question: "According to the Empirical Rule, approximately what percentage of data falls OUTSIDE ±3 SD of the mean (combined, both tails)?",
    options: ["0.3%", "5%", "32%", "1%"],
    correctIndex: 0,
    explanation: "Since ~99.7% falls within ±3 SD, only 100% − 99.7% = 0.3% falls beyond it — an extremely rare region for a normal distribution.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-98",
    topic: "empirical-rule",
    subtopic: "Comparing spread",
    difficulty: 2,
    type: "concept",
    question: "Two bell-shaped distributions share the same mean, but Distribution X has SD = 5 and Distribution Y has SD = 15. Which is more spread out?",
    options: ["Distribution Y", "Distribution X", "They are equally spread out", "Cannot be determined from SD alone"],
    correctIndex: 0,
    explanation: "A larger standard deviation directly means the data is more spread out around the mean — Y's ±1 SD interval is three times as wide as X's.",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-99",
    topic: "empirical-rule",
    subtopic: "Alternative names",
    difficulty: 1,
    type: "concept",
    question: "The Empirical Rule is also commonly known as the:",
    options: ["68-95-99.7 rule (or three-sigma rule)", "Central Limit Theorem", "Law of Large Numbers", "Bayes' Rule"],
    correctIndex: 0,
    explanation: "It's often referred to by its three key percentages, or as the 'three-sigma rule' since it describes coverage out to 3 standard deviations (sigma).",
    relatedPartId: "stats-part-7",
  },
  {
    id: "stats-ex-100",
    topic: "empirical-rule",
    subtopic: "Limitations",
    difficulty: 2,
    type: "best-practice",
    question: "The main limitation of the Empirical Rule is that it:",
    options: [
      "Does not reliably apply to skewed or non-normal distributions",
      "Only works for datasets with fewer than 30 values",
      "Cannot be used with negative numbers",
      "Requires the mean to equal zero",
    ],
    correctIndex: 0,
    explanation: "The 68/95/99.7% figures are derived specifically from the normal distribution's shape — applying them to a skewed dataset would give inaccurate estimates.",
    relatedPartId: "stats-part-7",
  },
];
