import type { MCQ } from "@/lib/mcqBank";

export const statisticsMcqBank: MCQ[] = [
  {
    id: "stats-mcq-1",
    question: "A parameter is best described as:",
    options: ["A summary computed from the sample", "A summary computed from the population", "The same thing as a statistic", "An individual observation"],
    correctIndex: 1,
    explanation: "A parameter is a number computed from the ENTIRE population; a statistic is the same kind of summary computed from just the sample.",
  },
  {
    id: "stats-mcq-2",
    question: "Which scale of measurement has a true zero point?",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"],
    correctIndex: 3,
    explanation: "Only the ratio scale has a genuine zero meaning 'none at all' — interval scales (like temperature in °C) have an arbitrary zero.",
  },
  {
    id: "stats-mcq-3",
    question: "\"Number of siblings\" is what type of variable?",
    options: ["Continuous", "Discrete", "Nominal", "Ordinal"],
    correctIndex: 1,
    explanation: "It's a countable whole-number quantity — you can't have 2.5 siblings — which makes it discrete, not continuous.",
  },
  {
    id: "stats-mcq-4",
    question: "According to the 2^k ≥ n rule, how many classes (k) should a frequency table have for n = 50 observations?",
    options: ["4", "5", "6", "7"],
    correctIndex: 2,
    explanation: "2⁵=32 < 50, but 2⁶=64 ≥ 50, so the smallest valid k is 6.",
  },
  {
    id: "stats-mcq-5",
    question: "A class boundary, compared to a class limit, is:",
    options: ["Exactly the same number", "Always a whole number", "Adjusted to close the gap between consecutive classes", "Only used for categorical data"],
    correctIndex: 2,
    explanation: "Class boundaries shift the limits by half the gap between classes, so consecutive classes touch with no gaps — needed for accurate histograms.",
  },
  {
    id: "stats-mcq-6",
    question: "Which chart is most appropriate for showing cumulative frequency?",
    options: ["Pie chart", "Bar graph", "Ogive", "Scatter plot"],
    correctIndex: 2,
    explanation: "An ogive (cumulative frequency curve) is specifically built to show running totals as data accumulates across classes.",
  },
  {
    id: "stats-mcq-7",
    question: "A trimmed mean is most useful when:",
    options: ["The data has extreme outliers", "The data is perfectly symmetric", "You need the exact middle value", "You're averaging percentages"],
    correctIndex: 0,
    explanation: "Trimming removes the most extreme values from each end before averaging, protecting the mean from being dragged around by outliers.",
  },
  {
    id: "stats-mcq-8",
    question: "The geometric mean is the right choice for averaging:",
    options: ["Test scores", "Ages", "Growth rates or percentages", "Heights"],
    correctIndex: 2,
    explanation: "Geometric mean is specifically designed for multiplicative quantities like growth rates, percentages, and ratios — not raw additive amounts.",
  },
  {
    id: "stats-mcq-9",
    question: "Which measure of central tendency is completely unaffected by extreme outliers?",
    options: ["Arithmetic mean", "Median", "Geometric mean", "Weighted mean"],
    correctIndex: 1,
    explanation: "The median only cares about rank position, not magnitude — an outlier of 1,000,000 shifts it no more than an outlier of 1,000.",
  },
  {
    id: "stats-mcq-10",
    question: "Population variance divides the sum of squared deviations by:",
    options: ["n", "n − 1", "n + 1", "√n"],
    correctIndex: 0,
    explanation: "Population variance divides by n; sample variance divides by n−1 to correct for the sample mean being a slightly-too-good fit to its own data.",
  },
  {
    id: "stats-mcq-11",
    question: "Why is sample variance divided by (n−1) instead of n?",
    options: [
      "It's just a convention with no real reason",
      "To correct for the sample mean fitting the sample data slightly too well",
      "Because samples always have one fewer data point",
      "To make the answer smaller",
    ],
    correctIndex: 1,
    explanation: "Using n−1 (Bessel's correction) compensates for the fact that a sample's own mean minimizes the sum of squared deviations for THAT sample, which would otherwise make sample variance a biased (too-small) estimate of the population variance.",
  },
  {
    id: "stats-mcq-12",
    question: "The coefficient of variation is useful because it:",
    options: ["Removes units, allowing fair comparison across different scales", "Is always smaller than the standard deviation", "Only works for symmetric data", "Replaces the need for a mean"],
    correctIndex: 0,
    explanation: "CV = SD/mean × 100% is a unit-free percentage, making it possible to fairly compare variability across datasets with different units or very different means.",
  },
  {
    id: "stats-mcq-13",
    question: "Q2 (the second quartile) is the same as:",
    options: ["The mode", "The median", "The mean", "The range"],
    correctIndex: 1,
    explanation: "Q2 marks the 50th percentile — exactly the same position as the median.",
  },
  {
    id: "stats-mcq-14",
    question: "In the grouped-data percentile formula P_k = l + (c/f)(nk − F), what does F represent?",
    options: [
      "The frequency of the target class",
      "The cumulative frequency of the class BEFORE the target class",
      "The total sample size",
      "The class width",
    ],
    correctIndex: 1,
    explanation: "F is how many observations were already accounted for before reaching the target class — needed to figure out how far INTO that class the percentile falls.",
  },
  {
    id: "stats-mcq-15",
    question: "If a distribution's mean is much larger than its median, the distribution is:",
    options: ["Symmetric", "Positively skewed", "Negatively skewed", "Impossible to determine"],
    correctIndex: 1,
    explanation: "A mean pulled above the median means a few unusually large values are dragging it upward — a right-stretching tail, i.e. positive skew.",
  },
  {
    id: "stats-mcq-16",
    question: "On a boxplot, what does the line inside the box represent?",
    options: ["The mean", "The mode", "The median", "The range"],
    correctIndex: 2,
    explanation: "The line inside the box marks the median (Q2); the box itself spans from Q1 to Q3.",
  },
  {
    id: "stats-mcq-17",
    question: "According to the Empirical Rule, about what percentage of a bell-shaped distribution's data falls within 2 standard deviations of the mean?",
    options: ["68%", "90%", "95%", "99.7%"],
    correctIndex: 2,
    explanation: "68% falls within ±1 SD, 95% within ±2 SD, and 99.7% (almost all) within ±3 SD.",
  },
  {
    id: "stats-mcq-18",
    question: "A leptokurtic distribution, compared to a normal distribution, has:",
    options: ["A flatter peak and thinner tails", "A sharper peak and fatter tails", "Exactly the same shape", "No tails at all"],
    correctIndex: 1,
    explanation: "Leptokurtic means kurtosis > 3 (or a positive excess kurtosis): a sharper central peak plus more extreme values out in the tails than a normal distribution.",
  },
  {
    id: "stats-mcq-19",
    question: "Two events A and B are mutually exclusive if:",
    options: ["P(A ∩ B) = 0", "P(A ∩ B) = P(A)P(B)", "P(A) = P(B)", "P(A ∪ B) = 1"],
    correctIndex: 0,
    explanation: "Mutually exclusive means A and B can never both happen at once — their intersection has probability zero.",
  },
  {
    id: "stats-mcq-20",
    question: "If A and B are independent events, then P(A ∩ B) equals:",
    options: ["P(A) + P(B)", "P(A) − P(B)", "P(A) × P(B)", "P(A) / P(B)"],
    correctIndex: 2,
    explanation: "Independence means one event has no effect on the other, which mathematically means their probabilities simply multiply.",
  },
  {
    id: "stats-mcq-21",
    question: "For any events A and B, P(A ∪ B) equals:",
    options: ["P(A) + P(B)", "P(A) + P(B) − P(A ∩ B)", "P(A) × P(B)", "P(A) − P(B)"],
    correctIndex: 1,
    explanation: "The overlap P(A ∩ B) is counted once in P(A) and once in P(B), so it must be subtracted once to avoid double-counting.",
  },
  {
    id: "stats-mcq-22",
    question: "The conditional probability P(B | A) is defined as:",
    options: ["P(A ∩ B) / P(A)", "P(A ∩ B) / P(B)", "P(A) × P(B)", "P(A) + P(B)"],
    correctIndex: 0,
    explanation: "P(B|A) re-measures B's probability within the shrunken sample space where A is already known to have occurred.",
  },
  {
    id: "stats-mcq-23",
    question: "In the Total Probability Rule, the events A₁, A₂, ..., Aₙ must:",
    options: [
      "Partition the sample space (mutually exclusive and cover all of S)",
      "All have equal probability",
      "Be independent of event B",
      "Sum their conditional probabilities to 1",
    ],
    correctIndex: 0,
    explanation: "The rule only works if every outcome in S belongs to exactly one Ai — that's what 'partition' means.",
  },
  {
    id: "stats-mcq-24",
    question: "Bayes' Theorem is best described as a way to:",
    options: [
      "Compute a prior probability from a posterior",
      "Reverse a conditional probability, from P(B|A) to P(A|B)",
      "Prove two events are independent",
      "Find the mean of a probability distribution",
    ],
    correctIndex: 1,
    explanation: "Bayes' Theorem takes what you know about P(B|Ai) for each cause and works backward to P(Ai|B) once B has actually been observed.",
  },
  {
    id: "stats-mcq-25",
    question: "P(5,3) — the number of ways to arrange 3 items chosen from 5 — equals:",
    options: ["10", "15", "60", "120"],
    correctIndex: 2,
    explanation: "5P3 = 5!/(5−3)! = 5×4×3 = 60. Order matters, so this is a permutation, not a combination.",
  },
  {
    id: "stats-mcq-26",
    question: "The key difference between a permutation and a combination is:",
    options: [
      "Permutations count ordered arrangements; combinations count unordered selections",
      "Permutations only work with numbers; combinations only work with letters",
      "Combinations always produce a larger count than permutations",
      "There is no real difference — they're two names for the same formula",
    ],
    correctIndex: 0,
    explanation: "ab and ba are different permutations but the SAME combination — combinations only care about which objects were selected, not their order.",
  },
  {
    id: "stats-mcq-27",
    question: "Why does the word MAMMAL (M×3, A×2, L×1) have only 60 distinct letter arrangements instead of 6! = 720?",
    options: [
      "Because dividing by the factorial of each repeated letter's count removes the identical-looking duplicate arrangements",
      "Because M, A, and L are not real English letters",
      "Because 6! was calculated incorrectly",
      "Because permutations always undercount by a factor of 12",
    ],
    correctIndex: 0,
    explanation: "6!/(3!×2!×1!) = 720/12 = 60 — swapping identical letters among themselves produces arrangements that look the same, so those duplicates must be divided out.",
  },
  {
    id: "stats-mcq-28",
    question: "A discrete random variable's probability mass function f(x) must satisfy:",
    options: [
      "f(x) ≥ 0 for all x, and Σf(x) = 1",
      "f(x) = 1 for exactly one value of x",
      "f(x) can be negative as long as the average is positive",
      "Σf(x) must equal the number of possible values of x",
    ],
    correctIndex: 0,
    explanation: "Every valid PMF has non-negative probabilities that sum to exactly 1 across all possible values.",
  },
  {
    id: "stats-mcq-29",
    question: "For a continuous random variable X, P(X = 5) is:",
    options: ["Always exactly 0", "Equal to f(5)", "Undefined", "Always exactly 1"],
    correctIndex: 0,
    explanation: "Probability for a continuous random variable comes from AREA under the curve — a single point has zero width, so its probability is always exactly 0.",
  },
  {
    id: "stats-mcq-30",
    question: "The cumulative distribution function F(x) of a random variable represents:",
    options: ["P(X ≤ x)", "P(X = x)", "P(X ≥ x)", "The variance of X up to x"],
    correctIndex: 0,
    explanation: "F(x) = P(X ≤ x) is the running total of probability accumulated from the smallest possible value up through x.",
  },
  {
    id: "stats-mcq-31",
    question: "If Y = 5X, how does Var(Y) relate to Var(X)?",
    options: ["Var(Y) = 5·Var(X)", "Var(Y) = 25·Var(X)", "Var(Y) = Var(X)", "Var(Y) = √5·Var(X)"],
    correctIndex: 1,
    explanation: "Var(aX) = a²Var(X), so scaling X by 5 scales its variance by 5² = 25 — variance scales by the SQUARE of the constant, unlike the mean which scales linearly.",
  },
  {
    id: "stats-mcq-32",
    question: "Which condition is NOT required for a Binomial distribution?",
    options: [
      "The probability of success changes from trial to trial",
      "A fixed number of trials n",
      "Each trial has exactly two possible outcomes",
      "The trials are independent",
    ],
    correctIndex: 0,
    explanation: "The probability of success p must stay CONSTANT across all trials for a Binomial distribution — if it changes, the trials aren't identical and the binomial formula no longer applies.",
  },
  {
    id: "stats-mcq-33",
    question: "For a Poisson distribution, which statement is always true?",
    options: [
      "The mean and variance are equal",
      "The mean is always larger than the variance",
      "There must be a fixed number of trials n",
      "p must be exactly 0.5",
    ],
    correctIndex: 0,
    explanation: "A defining signature of the Poisson distribution is that E(X) = Var(X) = μ — both equal the same rate parameter.",
  },
  {
    id: "stats-mcq-34",
    question: "The Geometric distribution's 'lack of memory' property means:",
    options: [
      "Knowing you've already failed s trials doesn't change the probability distribution of how many MORE trials are needed",
      "The distribution forgets its own parameter p after each trial",
      "Past failures make success more likely on the next trial",
      "The distribution only applies to the first trial",
    ],
    correctIndex: 0,
    explanation: "P(X > s+t | X > s) = P(X > t) — the process genuinely 'resets' after every failure, with no memory of how long you've already been waiting.",
  },
  {
    id: "stats-mcq-35",
    question: "A discrete uniform distribution is characterized by:",
    options: [
      "Every possible outcome having exactly the same probability",
      "Outcomes that increase in probability as x increases",
      "Exactly two possible outcomes",
      "A probability that depends on an average rate μ",
    ],
    correctIndex: 0,
    explanation: "Discrete uniform means f(x) = 1/n for every one of the n equally likely values — a fair die or coin is the classic example.",
  },
  {
    id: "stats-mcq-36",
    question: "A continuous uniform distribution's probability density function over (a,b) is:",
    options: ["1/(b−a)", "1/(b+a)", "(b−a)", "1/n"],
    correctIndex: 0,
    explanation: "The density is flat at height 1/(b−a) across the whole interval, so the total area (1/(b−a))×(b−a) correctly equals 1.",
  },
  {
    id: "stats-mcq-37",
    question: "The Exponential distribution is most naturally used to model:",
    options: ["Waiting time until the next event in a Poisson process", "A fixed number of successes in n trials", "Every outcome being equally likely", "A bell-shaped, symmetric measurement"],
    correctIndex: 0,
    explanation: "Exponential models the GAP between events in a Poisson process — like time until the next customer arrival or machine failure.",
  },
  {
    id: "stats-mcq-38",
    question: "Which of these is NOT a property of the Normal distribution?",
    options: ["It is skewed to the right", "It is symmetric about the mean", "Mean, median, and mode are all equal", "The total area under the curve is 1"],
    correctIndex: 0,
    explanation: "The normal distribution is perfectly symmetric, not skewed — skewness is zero for a true normal curve.",
  },
  {
    id: "stats-mcq-39",
    question: "The z-score transform Z = (X−μ)/σ converts a normal random variable X into:",
    options: ["The standard normal distribution, N(0,1)", "A discrete uniform distribution", "A Poisson distribution with rate σ", "A distribution with mean σ and variance μ"],
    correctIndex: 0,
    explanation: "Z always has mean 0 and standard deviation 1, regardless of the original X's mean and SD — this is what lets one table work for every normal distribution.",
  },
  {
    id: "stats-mcq-40",
    question: "For X ~ N(40.5, 5.5²), the z-score of X=48.75 is:",
    options: ["1.5", "8.25", "0.67", "−1.5"],
    correctIndex: 0,
    explanation: "z = (48.75−40.5)/5.5 = 8.25/5.5 = 1.5.",
  },
  {
    id: "stats-mcq-41",
    question: "By the symmetry of the standard normal distribution, P(Z < −k) equals:",
    options: ["P(Z > k)", "P(Z < k)", "1 + Φ(k)", "−Φ(k)"],
    correctIndex: 0,
    explanation: "The left tail beyond −k has exactly the same area as the right tail beyond k, by the curve's symmetry about 0.",
  },
  {
    id: "stats-mcq-42",
    question: "The Normal Approximation to the Binomial distribution is considered appropriate when:",
    options: ["np > 5 AND nq > 5", "n > 5 only", "p = 0.5 exactly", "n < 30"],
    correctIndex: 0,
    explanation: "Both conditions must hold together to ensure the binomial distribution is symmetric enough for a normal curve to approximate it well.",
  },
  {
    id: "stats-mcq-43",
    question: "When applying the normal approximation to find P(X = k) for a Binomial random variable, the continuity correction requires computing:",
    options: ["P(k−0.5 < X < k+0.5)", "P(X = k) directly, no correction needed", "P(X < k)", "P(X > k)"],
    correctIndex: 0,
    explanation: "Since X is discrete but the normal curve is continuous, the single point k must be widened into the small interval (k−0.5, k+0.5) to have any area at all.",
  },
  {
    id: "stats-mcq-44",
    question: "150 fair coins are tossed (X=number of heads, n=150, p=0.5). What are μ and σ for the normal approximation?",
    options: ["μ=75, σ≈6.12", "μ=75, σ=150", "μ=0.5, σ≈6.12", "μ=150, σ=75"],
    correctIndex: 0,
    explanation: "μ=np=150(0.5)=75, and σ=√(npq)=√(150×0.5×0.5)=√37.5≈6.12.",
  },
];
