import type { MCQ } from "@/lib/mcqBank";

export const statisticsMcqBank: MCQ[] = [
  {
    id: "stats-mcq-1",
    question: "A parameter is best described as:",
    options: ["A summary computed from the sample", "A summary computed from the population", "The same thing as a statistic", "An individual observation"],
    correctIndex: 1,
    explanation: "A parameter is a number computed from the ENTIRE population; a statistic is the same kind of summary computed from just the sample.",
  },
  {
    id: "stats-mcq-2",
    question: "Which scale of measurement has a true zero point?",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"],
    correctIndex: 3,
    explanation: "Only the ratio scale has a genuine zero meaning 'none at all' — interval scales (like temperature in °C) have an arbitrary zero.",
  },
  {
    id: "stats-mcq-3",
    question: "\"Number of siblings\" is what type of variable?",
    options: ["Continuous", "Discrete", "Nominal", "Ordinal"],
    correctIndex: 1,
    explanation: "It's a countable whole-number quantity — you can't have 2.5 siblings — which makes it discrete, not continuous.",
  },
  {
    id: "stats-mcq-4",
    question: "According to the 2^k ≥ n rule, how many classes (k) should a frequency table have for n = 50 observations?",
    options: ["4", "5", "6", "7"],
    correctIndex: 2,
    explanation: "2⁵=32 < 50, but 2⁶=64 ≥ 50, so the smallest valid k is 6.",
  },
  {
    id: "stats-mcq-5",
    question: "A class boundary, compared to a class limit, is:",
    options: ["Exactly the same number", "Always a whole number", "Adjusted to close the gap between consecutive classes", "Only used for categorical data"],
    correctIndex: 2,
    explanation: "Class boundaries shift the limits by half the gap between classes, so consecutive classes touch with no gaps — needed for accurate histograms.",
  },
  {
    id: "stats-mcq-6",
    question: "Which chart is most appropriate for showing cumulative frequency?",
    options: ["Pie chart", "Bar graph", "Ogive", "Scatter plot"],
    correctIndex: 2,
    explanation: "An ogive (cumulative frequency curve) is specifically built to show running totals as data accumulates across classes.",
  },
  {
    id: "stats-mcq-7",
    question: "A trimmed mean is most useful when:",
    options: ["The data has extreme outliers", "The data is perfectly symmetric", "You need the exact middle value", "You're averaging percentages"],
    correctIndex: 0,
    explanation: "Trimming removes the most extreme values from each end before averaging, protecting the mean from being dragged around by outliers.",
  },
  {
    id: "stats-mcq-8",
    question: "The geometric mean is the right choice for averaging:",
    options: ["Test scores", "Ages", "Growth rates or percentages", "Heights"],
    correctIndex: 2,
    explanation: "Geometric mean is specifically designed for multiplicative quantities like growth rates, percentages, and ratios — not raw additive amounts.",
  },
  {
    id: "stats-mcq-9",
    question: "Which measure of central tendency is completely unaffected by extreme outliers?",
    options: ["Arithmetic mean", "Median", "Geometric mean", "Weighted mean"],
    correctIndex: 1,
    explanation: "The median only cares about rank position, not magnitude — an outlier of 1,000,000 shifts it no more than an outlier of 1,000.",
  },
  {
    id: "stats-mcq-10",
    question: "Population variance divides the sum of squared deviations by:",
    options: ["n", "n − 1", "n + 1", "√n"],
    correctIndex: 0,
    explanation: "Population variance divides by n; sample variance divides by n−1 to correct for the sample mean being a slightly-too-good fit to its own data.",
  },
  {
    id: "stats-mcq-11",
    question: "Why is sample variance divided by (n−1) instead of n?",
    options: [
      "It's just a convention with no real reason",
      "To correct for the sample mean fitting the sample data slightly too well",
      "Because samples always have one fewer data point",
      "To make the answer smaller",
    ],
    correctIndex: 1,
    explanation: "Using n−1 (Bessel's correction) compensates for the fact that a sample's own mean minimizes the sum of squared deviations for THAT sample, which would otherwise make sample variance a biased (too-small) estimate of the population variance.",
  },
  {
    id: "stats-mcq-12",
    question: "The coefficient of variation is useful because it:",
    options: ["Removes units, allowing fair comparison across different scales", "Is always smaller than the standard deviation", "Only works for symmetric data", "Replaces the need for a mean"],
    correctIndex: 0,
    explanation: "CV = SD/mean × 100% is a unit-free percentage, making it possible to fairly compare variability across datasets with different units or very different means.",
  },
  {
    id: "stats-mcq-13",
    question: "Q2 (the second quartile) is the same as:",
    options: ["The mode", "The median", "The mean", "The range"],
    correctIndex: 1,
    explanation: "Q2 marks the 50th percentile — exactly the same position as the median.",
  },
  {
    id: "stats-mcq-14",
    question: "In the grouped-data percentile formula P_k = l + (c/f)(nk − F), what does F represent?",
    options: [
      "The frequency of the target class",
      "The cumulative frequency of the class BEFORE the target class",
      "The total sample size",
      "The class width",
    ],
    correctIndex: 1,
    explanation: "F is how many observations were already accounted for before reaching the target class — needed to figure out how far INTO that class the percentile falls.",
  },
  {
    id: "stats-mcq-15",
    question: "If a distribution's mean is much larger than its median, the distribution is:",
    options: ["Symmetric", "Positively skewed", "Negatively skewed", "Impossible to determine"],
    correctIndex: 1,
    explanation: "A mean pulled above the median means a few unusually large values are dragging it upward — a right-stretching tail, i.e. positive skew.",
  },
  {
    id: "stats-mcq-16",
    question: "On a boxplot, what does the line inside the box represent?",
    options: ["The mean", "The mode", "The median", "The range"],
    correctIndex: 2,
    explanation: "The line inside the box marks the median (Q2); the box itself spans from Q1 to Q3.",
  },
  {
    id: "stats-mcq-17",
    question: "According to the Empirical Rule, about what percentage of a bell-shaped distribution's data falls within 2 standard deviations of the mean?",
    options: ["68%", "90%", "95%", "99.7%"],
    correctIndex: 2,
    explanation: "68% falls within ±1 SD, 95% within ±2 SD, and 99.7% (almost all) within ±3 SD.",
  },
  {
    id: "stats-mcq-18",
    question: "A leptokurtic distribution, compared to a normal distribution, has:",
    options: ["A flatter peak and thinner tails", "A sharper peak and fatter tails", "Exactly the same shape", "No tails at all"],
    correctIndex: 1,
    explanation: "Leptokurtic means kurtosis > 3 (or a positive excess kurtosis): a sharper central peak plus more extreme values out in the tails than a normal distribution.",
  },
];
