import type { MCQ } from "@/lib/mcqBank";

export const statisticsMcqBank: MCQ[] = [
  {
    id: "stats-mcq-1",
    question: "A parameter is best described as:",
    options: ["A summary computed from the sample", "A summary computed from the population", "The same thing as a statistic", "An individual observation"],
    correctIndex: 1,
    explanation: "A parameter is a number computed from the ENTIRE population; a statistic is the same kind of summary computed from just the sample.",
  },
  {
    id: "stats-mcq-2",
    question: "Which scale of measurement has a true zero point?",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"],
    correctIndex: 3,
    explanation: "Only the ratio scale has a genuine zero meaning 'none at all' — interval scales (like temperature in °C) have an arbitrary zero.",
  },
  {
    id: "stats-mcq-3",
    question: "\"Number of siblings\" is what type of variable?",
    options: ["Continuous", "Discrete", "Nominal", "Ordinal"],
    correctIndex: 1,
    explanation: "It's a countable whole-number quantity — you can't have 2.5 siblings — which makes it discrete, not continuous.",
  },
  {
    id: "stats-mcq-4",
    question: "According to the 2^k ≥ n rule, how many classes (k) should a frequency table have for n = 50 observations?",
    options: ["4", "5", "6", "7"],
    correctIndex: 2,
    explanation: "2⁵=32 < 50, but 2⁶=64 ≥ 50, so the smallest valid k is 6.",
  },
  {
    id: "stats-mcq-5",
    question: "A class boundary, compared to a class limit, is:",
    options: ["Exactly the same number", "Always a whole number", "Adjusted to close the gap between consecutive classes", "Only used for categorical data"],
    correctIndex: 2,
    explanation: "Class boundaries shift the limits by half the gap between classes, so consecutive classes touch with no gaps — needed for accurate histograms.",
  },
  {
    id: "stats-mcq-6",
    question: "Which chart is most appropriate for showing cumulative frequency?",
    options: ["Pie chart", "Bar graph", "Ogive", "Scatter plot"],
    correctIndex: 2,
    explanation: "An ogive (cumulative frequency curve) is specifically built to show running totals as data accumulates across classes.",
  },
  {
    id: "stats-mcq-7",
    question: "A trimmed mean is most useful when:",
    options: ["The data has extreme outliers", "The data is perfectly symmetric", "You need the exact middle value", "You're averaging percentages"],
    correctIndex: 0,
    explanation: "Trimming removes the most extreme values from each end before averaging, protecting the mean from being dragged around by outliers.",
  },
  {
    id: "stats-mcq-8",
    question: "The geometric mean is the right choice for averaging:",
    options: ["Test scores", "Ages", "Growth rates or percentages", "Heights"],
    correctIndex: 2,
    explanation: "Geometric mean is specifically designed for multiplicative quantities like growth rates, percentages, and ratios — not raw additive amounts.",
  },
  {
    id: "stats-mcq-9",
    question: "Which measure of central tendency is completely unaffected by extreme outliers?",
    options: ["Arithmetic mean", "Median", "Geometric mean", "Weighted mean"],
    correctIndex: 1,
    explanation: "The median only cares about rank position, not magnitude — an outlier of 1,000,000 shifts it no more than an outlier of 1,000.",
  },
  {
    id: "stats-mcq-10",
    question: "Population variance divides the sum of squared deviations by:",
    options: ["n", "n − 1", "n + 1", "√n"],
    correctIndex: 0,
    explanation: "Population variance divides by n; sample variance divides by n−1 to correct for the sample mean being a slightly-too-good fit to its own data.",
  },
  {
    id: "stats-mcq-11",
    question: "Why is sample variance divided by (n−1) instead of n?",
    options: [
      "It's just a convention with no real reason",
      "To correct for the sample mean fitting the sample data slightly too well",
      "Because samples always have one fewer data point",
      "To make the answer smaller",
    ],
    correctIndex: 1,
    explanation: "Using n−1 (Bessel's correction) compensates for the fact that a sample's own mean minimizes the sum of squared deviations for THAT sample, which would otherwise make sample variance a biased (too-small) estimate of the population variance.",
  },
  {
    id: "stats-mcq-12",
    question: "The coefficient of variation is useful because it:",
    options: ["Removes units, allowing fair comparison across different scales", "Is always smaller than the standard deviation", "Only works for symmetric data", "Replaces the need for a mean"],
    correctIndex: 0,
    explanation: "CV = SD/mean × 100% is a unit-free percentage, making it possible to fairly compare variability across datasets with different units or very different means.",
  },
  {
    id: "stats-mcq-13",
    question: "Q2 (the second quartile) is the same as:",
    options: ["The mode", "The median", "The mean", "The range"],
    correctIndex: 1,
    explanation: "Q2 marks the 50th percentile — exactly the same position as the median.",
  },
  {
    id: "stats-mcq-14",
    question: "In the grouped-data percentile formula P_k = l + (c/f)(nk − F), what does F represent?",
    options: [
      "The frequency of the target class",
      "The cumulative frequency of the class BEFORE the target class",
      "The total sample size",
      "The class width",
    ],
    correctIndex: 1,
    explanation: "F is how many observations were already accounted for before reaching the target class — needed to figure out how far INTO that class the percentile falls.",
  },
  {
    id: "stats-mcq-15",
    question: "If a distribution's mean is much larger than its median, the distribution is:",
    options: ["Symmetric", "Positively skewed", "Negatively skewed", "Impossible to determine"],
    correctIndex: 1,
    explanation: "A mean pulled above the median means a few unusually large values are dragging it upward — a right-stretching tail, i.e. positive skew.",
  },
  {
    id: "stats-mcq-16",
    question: "On a boxplot, what does the line inside the box represent?",
    options: ["The mean", "The mode", "The median", "The range"],
    correctIndex: 2,
    explanation: "The line inside the box marks the median (Q2); the box itself spans from Q1 to Q3.",
  },
  {
    id: "stats-mcq-17",
    question: "According to the Empirical Rule, about what percentage of a bell-shaped distribution's data falls within 2 standard deviations of the mean?",
    options: ["68%", "90%", "95%", "99.7%"],
    correctIndex: 2,
    explanation: "68% falls within ±1 SD, 95% within ±2 SD, and 99.7% (almost all) within ±3 SD.",
  },
  {
    id: "stats-mcq-18",
    question: "A leptokurtic distribution, compared to a normal distribution, has:",
    options: ["A flatter peak and thinner tails", "A sharper peak and fatter tails", "Exactly the same shape", "No tails at all"],
    correctIndex: 1,
    explanation: "Leptokurtic means kurtosis > 3 (or a positive excess kurtosis): a sharper central peak plus more extreme values out in the tails than a normal distribution.",
  },
  {
    id: "stats-mcq-19",
    question: "Two events A and B are mutually exclusive if:",
    options: ["P(A ∩ B) = 0", "P(A ∩ B) = P(A)P(B)", "P(A) = P(B)", "P(A ∪ B) = 1"],
    correctIndex: 0,
    explanation: "Mutually exclusive means A and B can never both happen at once — their intersection has probability zero.",
  },
  {
    id: "stats-mcq-20",
    question: "If A and B are independent events, then P(A ∩ B) equals:",
    options: ["P(A) + P(B)", "P(A) − P(B)", "P(A) × P(B)", "P(A) / P(B)"],
    correctIndex: 2,
    explanation: "Independence means one event has no effect on the other, which mathematically means their probabilities simply multiply.",
  },
  {
    id: "stats-mcq-21",
    question: "For any events A and B, P(A ∪ B) equals:",
    options: ["P(A) + P(B)", "P(A) + P(B) − P(A ∩ B)", "P(A) × P(B)", "P(A) − P(B)"],
    correctIndex: 1,
    explanation: "The overlap P(A ∩ B) is counted once in P(A) and once in P(B), so it must be subtracted once to avoid double-counting.",
  },
  {
    id: "stats-mcq-22",
    question: "The conditional probability P(B | A) is defined as:",
    options: ["P(A ∩ B) / P(A)", "P(A ∩ B) / P(B)", "P(A) × P(B)", "P(A) + P(B)"],
    correctIndex: 0,
    explanation: "P(B|A) re-measures B's probability within the shrunken sample space where A is already known to have occurred.",
  },
  {
    id: "stats-mcq-23",
    question: "In the Total Probability Rule, the events A₁, A₂, ..., Aₙ must:",
    options: [
      "Partition the sample space (mutually exclusive and cover all of S)",
      "All have equal probability",
      "Be independent of event B",
      "Sum their conditional probabilities to 1",
    ],
    correctIndex: 0,
    explanation: "The rule only works if every outcome in S belongs to exactly one Ai — that's what 'partition' means.",
  },
  {
    id: "stats-mcq-24",
    question: "Bayes' Theorem is best described as a way to:",
    options: [
      "Compute a prior probability from a posterior",
      "Reverse a conditional probability, from P(B|A) to P(A|B)",
      "Prove two events are independent",
      "Find the mean of a probability distribution",
    ],
    correctIndex: 1,
    explanation: "Bayes' Theorem takes what you know about P(B|Ai) for each cause and works backward to P(Ai|B) once B has actually been observed.",
  },
  {
    id: "stats-mcq-25",
    question: "P(5,3) — the number of ways to arrange 3 items chosen from 5 — equals:",
    options: ["10", "15", "60", "120"],
    correctIndex: 2,
    explanation: "5P3 = 5!/(5−3)! = 5×4×3 = 60. Order matters, so this is a permutation, not a combination.",
  },
  {
    id: "stats-mcq-26",
    question: "The key difference between a permutation and a combination is:",
    options: [
      "Permutations count ordered arrangements; combinations count unordered selections",
      "Permutations only work with numbers; combinations only work with letters",
      "Combinations always produce a larger count than permutations",
      "There is no real difference — they're two names for the same formula",
    ],
    correctIndex: 0,
    explanation: "ab and ba are different permutations but the SAME combination — combinations only care about which objects were selected, not their order.",
  },
  {
    id: "stats-mcq-27",
    question: "Why does the word MAMMAL (M×3, A×2, L×1) have only 60 distinct letter arrangements instead of 6! = 720?",
    options: [
      "Because dividing by the factorial of each repeated letter's count removes the identical-looking duplicate arrangements",
      "Because M, A, and L are not real English letters",
      "Because 6! was calculated incorrectly",
      "Because permutations always undercount by a factor of 12",
    ],
    correctIndex: 0,
    explanation: "6!/(3!×2!×1!) = 720/12 = 60 — swapping identical letters among themselves produces arrangements that look the same, so those duplicates must be divided out.",
  },
  {
    id: "stats-mcq-28",
    question: "A discrete random variable's probability mass function f(x) must satisfy:",
    options: [
      "f(x) ≥ 0 for all x, and Σf(x) = 1",
      "f(x) = 1 for exactly one value of x",
      "f(x) can be negative as long as the average is positive",
      "Σf(x) must equal the number of possible values of x",
    ],
    correctIndex: 0,
    explanation: "Every valid PMF has non-negative probabilities that sum to exactly 1 across all possible values.",
  },
  {
    id: "stats-mcq-29",
    question: "For a continuous random variable X, P(X = 5) is:",
    options: ["Always exactly 0", "Equal to f(5)", "Undefined", "Always exactly 1"],
    correctIndex: 0,
    explanation: "Probability for a continuous random variable comes from AREA under the curve — a single point has zero width, so its probability is always exactly 0.",
  },
  {
    id: "stats-mcq-30",
    question: "The cumulative distribution function F(x) of a random variable represents:",
    options: ["P(X ≤ x)", "P(X = x)", "P(X ≥ x)", "The variance of X up to x"],
    correctIndex: 0,
    explanation: "F(x) = P(X ≤ x) is the running total of probability accumulated from the smallest possible value up through x.",
  },
  {
    id: "stats-mcq-31",
    question: "If Y = 5X, how does Var(Y) relate to Var(X)?",
    options: ["Var(Y) = 5·Var(X)", "Var(Y) = 25·Var(X)", "Var(Y) = Var(X)", "Var(Y) = √5·Var(X)"],
    correctIndex: 1,
    explanation: "Var(aX) = a²Var(X), so scaling X by 5 scales its variance by 5² = 25 — variance scales by the SQUARE of the constant, unlike the mean which scales linearly.",
  },
  {
    id: "stats-mcq-32",
    question: "Which condition is NOT required for a Binomial distribution?",
    options: [
      "The probability of success changes from trial to trial",
      "A fixed number of trials n",
      "Each trial has exactly two possible outcomes",
      "The trials are independent",
    ],
    correctIndex: 0,
    explanation: "The probability of success p must stay CONSTANT across all trials for a Binomial distribution — if it changes, the trials aren't identical and the binomial formula no longer applies.",
  },
  {
    id: "stats-mcq-33",
    question: "For a Poisson distribution, which statement is always true?",
    options: [
      "The mean and variance are equal",
      "The mean is always larger than the variance",
      "There must be a fixed number of trials n",
      "p must be exactly 0.5",
    ],
    correctIndex: 0,
    explanation: "A defining signature of the Poisson distribution is that E(X) = Var(X) = μ — both equal the same rate parameter.",
  },
  {
    id: "stats-mcq-34",
    question: "The Geometric distribution's 'lack of memory' property means:",
    options: [
      "Knowing you've already failed s trials doesn't change the probability distribution of how many MORE trials are needed",
      "The distribution forgets its own parameter p after each trial",
      "Past failures make success more likely on the next trial",
      "The distribution only applies to the first trial",
    ],
    correctIndex: 0,
    explanation: "P(X > s+t | X > s) = P(X > t) — the process genuinely 'resets' after every failure, with no memory of how long you've already been waiting.",
  },
  {
    id: "stats-mcq-35",
    question: "A discrete uniform distribution is characterized by:",
    options: [
      "Every possible outcome having exactly the same probability",
      "Outcomes that increase in probability as x increases",
      "Exactly two possible outcomes",
      "A probability that depends on an average rate μ",
    ],
    correctIndex: 0,
    explanation: "Discrete uniform means f(x) = 1/n for every one of the n equally likely values — a fair die or coin is the classic example.",
  },
  {
    id: "stats-mcq-36",
    question: "A continuous uniform distribution's probability density function over (a,b) is:",
    options: ["1/(b−a)", "1/(b+a)", "(b−a)", "1/n"],
    correctIndex: 0,
    explanation: "The density is flat at height 1/(b−a) across the whole interval, so the total area (1/(b−a))×(b−a) correctly equals 1.",
  },
  {
    id: "stats-mcq-37",
    question: "The Exponential distribution is most naturally used to model:",
    options: ["Waiting time until the next event in a Poisson process", "A fixed number of successes in n trials", "Every outcome being equally likely", "A bell-shaped, symmetric measurement"],
    correctIndex: 0,
    explanation: "Exponential models the GAP between events in a Poisson process — like time until the next customer arrival or machine failure.",
  },
  {
    id: "stats-mcq-38",
    question: "Which of these is NOT a property of the Normal distribution?",
    options: ["It is skewed to the right", "It is symmetric about the mean", "Mean, median, and mode are all equal", "The total area under the curve is 1"],
    correctIndex: 0,
    explanation: "The normal distribution is perfectly symmetric, not skewed — skewness is zero for a true normal curve.",
  },
  {
    id: "stats-mcq-39",
    question: "The z-score transform Z = (X−μ)/σ converts a normal random variable X into:",
    options: ["The standard normal distribution, N(0,1)", "A discrete uniform distribution", "A Poisson distribution with rate σ", "A distribution with mean σ and variance μ"],
    correctIndex: 0,
    explanation: "Z always has mean 0 and standard deviation 1, regardless of the original X's mean and SD — this is what lets one table work for every normal distribution.",
  },
  {
    id: "stats-mcq-40",
    question: "For X ~ N(40.5, 5.5²), the z-score of X=48.75 is:",
    options: ["1.5", "8.25", "0.67", "−1.5"],
    correctIndex: 0,
    explanation: "z = (48.75−40.5)/5.5 = 8.25/5.5 = 1.5.",
  },
  {
    id: "stats-mcq-41",
    question: "By the symmetry of the standard normal distribution, P(Z < −k) equals:",
    options: ["P(Z > k)", "P(Z < k)", "1 + Φ(k)", "−Φ(k)"],
    correctIndex: 0,
    explanation: "The left tail beyond −k has exactly the same area as the right tail beyond k, by the curve's symmetry about 0.",
  },
  {
    id: "stats-mcq-42",
    question: "The Normal Approximation to the Binomial distribution is considered appropriate when:",
    options: ["np > 5 AND nq > 5", "n > 5 only", "p = 0.5 exactly", "n < 30"],
    correctIndex: 0,
    explanation: "Both conditions must hold together to ensure the binomial distribution is symmetric enough for a normal curve to approximate it well.",
  },
  {
    id: "stats-mcq-43",
    question: "When applying the normal approximation to find P(X = k) for a Binomial random variable, the continuity correction requires computing:",
    options: ["P(k−0.5 < X < k+0.5)", "P(X = k) directly, no correction needed", "P(X < k)", "P(X > k)"],
    correctIndex: 0,
    explanation: "Since X is discrete but the normal curve is continuous, the single point k must be widened into the small interval (k−0.5, k+0.5) to have any area at all.",
  },
  {
    id: "stats-mcq-44",
    question: "150 fair coins are tossed (X=number of heads, n=150, p=0.5). What are μ and σ for the normal approximation?",
    options: ["μ=75, σ≈6.12", "μ=75, σ=150", "μ=0.5, σ≈6.12", "μ=150, σ=75"],
    correctIndex: 0,
    explanation: "μ=np=150(0.5)=75, and σ=√(npq)=√(150×0.5×0.5)=√37.5≈6.12.",
  },

  // ---------- Computer Science Foundations (statistics as the theory behind CS/ML) ----------
  {
    id: "stats-mcq-cs-1",
    question: "When benchmarking software performance, why is it standard practice to run a program many times and average the results rather than trusting a single run?",
    options: [
      "By the Central Limit Theorem, the average of many runs is approximately Normally distributed with lower variance than any single run",
      "A single run is always exactly correct",
      "Averaging multiple runs always doubles the program's speed",
      "It has nothing to do with statistics",
    ],
    correctIndex: 0,
    explanation: "A single run is one noisy sample. Averaging many independent runs shrinks the variance of the estimate (variance of the mean falls as σ²/n), giving a far more trustworthy number.",
  },
  {
    id: "stats-mcq-cs-2",
    question: "A Naive Bayes spam filter classifies an email as spam or not spam by directly applying:",
    options: ["Bayes' theorem — updating the probability an email is spam given the words it contains", "Standard deviation of the message length", "The pigeonhole principle", "Linear regression"],
    correctIndex: 0,
    explanation: "Naive Bayes classifiers compute P(spam | words) from P(words | spam), P(spam), and P(words) using Bayes' theorem, treating each word's presence as (naively) independent evidence.",
  },
  {
    id: "stats-mcq-cs-3",
    question: "The Poisson distribution is commonly used in computer science to model:",
    options: ["The number of requests arriving at a server (or packets on a network) in a fixed time interval", "The exact execution time of one specific line of code", "The size of a hard drive", "The number of lines in a source file"],
    correctIndex: 0,
    explanation: "Poisson is the standard model for counting rare, independent events over a fixed interval at a constant average rate — exactly the pattern of requests hitting a server or packets arriving on a link.",
  },
  {
    id: "stats-mcq-cs-4",
    question: "A data center has 100 independent hard drives, each with a 2% chance of failing this year. The number of drives that fail this year is best modeled by:",
    options: ["A Binomial distribution with n=100, p=0.02", "A Normal distribution only", "A Poisson distribution with λ=100", "A uniform distribution"],
    correctIndex: 0,
    explanation: "This is exactly the Binomial setup: a fixed number (n=100) of independent trials, each with the same success (failure) probability p=0.02 — the textbook definition of a Binomial random variable.",
  },
  {
    id: "stats-mcq-cs-5",
    question: "Analyzing the 'expected' (average-case) running time of randomized quicksort uses which statistical concept?",
    options: [
      "Expected value (mean) of a random variable — here, the number of comparisons averaged over all random pivot choices",
      "The mode of the dataset",
      "The range of the dataset",
      "Standard deviation only",
    ],
    correctIndex: 0,
    explanation: "Average-case analysis of a randomized algorithm computes E[running time], the probability-weighted average over all the randomness in the algorithm (here, the random choice of pivot) — precisely the definition of expected value.",
  },
  {
    id: "stats-mcq-cs-6",
    question: "In machine learning, a model that fits its training data almost perfectly but performs poorly on new data has:",
    options: ["Low bias but high variance — it has 'overfit', memorizing noise specific to the training set", "High bias but low variance", "Zero variance and zero bias", "No relationship to statistics at all"],
    correctIndex: 0,
    explanation: "This is the bias-variance tradeoff: an overfit model is so flexible it captures the training set's random noise (high variance across different training samples) rather than the true underlying pattern.",
  },
  {
    id: "stats-mcq-cs-7",
    question: "A system with low average latency but very high standard deviation in response times is best described as:",
    options: ["Fast on average but unpredictable — occasional very slow ('tail latency') responses", "Always exactly as fast as its average", "Guaranteed to never be slow", "Impossible to measure"],
    correctIndex: 0,
    explanation: "Standard deviation measures spread around the mean. A low mean with high spread means most requests are fast, but some are far slower — the classic 'tail latency' problem engineers track with metrics like p99.",
  },
  {
    id: "stats-mcq-cs-8",
    question: "The 'birthday paradox' — with just 23 random people, there's already a better-than-50% chance two share a birthday — is directly relevant to computer science because it explains why:",
    options: [
      "Hash collisions become likely much sooner than intuition suggests, even with a huge number of possible hash values",
      "Passwords should always be exactly 23 characters long",
      "Hash tables never have collisions",
      "Only 23 hash values ever need to be checked",
    ],
    correctIndex: 0,
    explanation: "The same combinatorial effect behind the birthday paradox means, for example, hash collisions become likely once roughly √(number of possible hash values) items have been hashed — far sooner than naive intuition suggests, which matters for both hash table design and cryptographic hash security.",
  },
  {
    id: "stats-mcq-cs-9",
    question: "A Monte Carlo method estimates a mathematical quantity (e.g., the value of π) by:",
    options: [
      "Running many random trials/simulations and using the statistical average of the outcomes as an estimate",
      "Solving the exact equation analytically with no randomness involved",
      "Sorting a dataset first",
      "Always requiring an infinite amount of memory",
    ],
    correctIndex: 0,
    explanation: "Monte Carlo methods deliberately use repeated random sampling to approximate a result that may be hard to compute exactly — e.g., randomly throwing darts at a square containing a circle and using the fraction that land inside the circle to estimate π.",
  },
  {
    id: "stats-mcq-cs-10",
    question: "In information theory, a data source's entropy (based on the probability distribution of its symbols) sets a theoretical limit on:",
    options: ["The best possible lossless compression ratio achievable for that data", "The maximum clock speed of a CPU", "The number of hash functions needed", "The size of a binary search tree"],
    correctIndex: 0,
    explanation: "Shannon's source coding theorem states that a source's entropy is the theoretical lower bound on the average number of bits needed per symbol for lossless compression — data with lower entropy (more predictable/skewed probabilities) can be compressed further.",
  },
  {
    id: "stats-mcq-cs-11",
    question: "Reservoir sampling is a technique for:",
    options: [
      "Selecting a uniformly random sample of k items from a data stream whose total size isn't known in advance",
      "Sorting a list in O(n log n) time",
      "Compressing a file losslessly",
      "Finding the shortest path in a graph",
    ],
    correctIndex: 0,
    explanation: "Reservoir sampling processes a stream one item at a time, using randomized replacement probabilities so that at any point — even without knowing the final stream length — every item seen so far has had an equal chance of ending up in the sample.",
  },
  {
    id: "stats-mcq-cs-12",
    question: "Google's original PageRank algorithm models a random web surfer clicking links, and computes each page's importance using:",
    options: [
      "A Markov chain — the long-run probability distribution over pages the surfer ends up visiting",
      "A sorting algorithm applied to page titles",
      "A hash function applied to URLs",
      "A single fixed formula with no probability involved",
    ],
    correctIndex: 0,
    explanation: "PageRank models browsing as a Markov chain: the surfer's next page depends only on the current page's outgoing links (with some random-jump probability), and a page's rank is its steady-state visit probability in that chain.",
  },
  {
    id: "stats-mcq-cs-13",
    question: "Chebyshev's inequality, P(|X−μ| ≥ kσ) ≤ 1/k², is useful in computer science for analyzing randomized algorithms because it:",
    options: [
      "Bounds the probability of a large deviation from the mean without needing to know the random variable's exact distribution",
      "Only applies to the Normal distribution",
      "Requires an infinite sample size to be valid",
      "Proves an algorithm is always correct",
    ],
    correctIndex: 0,
    explanation: "Unlike results that assume Normality, Chebyshev's inequality holds for any distribution with a finite mean and variance — exactly the kind of distribution-free worst-case guarantee needed when analyzing a randomized algorithm's behavior.",
  },
  {
    id: "stats-mcq-cs-14",
    question: "A 'good' hash function is one whose outputs are approximately:",
    options: [
      "Uniformly distributed across the possible output values, so keys spread evenly across hash table buckets",
      "Normally distributed with a large standard deviation",
      "Always equal to the same single value",
      "Poisson distributed with a very small λ",
    ],
    correctIndex: 0,
    explanation: "A hash function that maps keys uniformly across the output range minimizes the chance of many keys landing in the same bucket — non-uniform hashing directly causes uneven bucket loads and worse average-case lookup performance.",
  },
  {
    id: "stats-mcq-cs-15",
    question: "In evaluating a machine-learning classifier, 'recall' measures:",
    options: [
      "Of all the actual positive cases, what fraction the model correctly identified",
      "Of all cases the model labelled positive, what fraction were actually positive",
      "How fast the model runs",
      "How much memory the model uses",
    ],
    correctIndex: 0,
    explanation: "Recall = TP / (TP + FN) — out of everything that's truly positive, how much did the model catch. (The second option describes precision, a related but distinct metric — mixing the two up is a very common mistake.)",
  },
  {
    id: "stats-mcq-cs-16",
    question: "Splitting a dataset into separate 'training' and 'test' sets before building a machine-learning model exists mainly to:",
    options: [
      "Get an honest estimate of how the model performs on data it has never seen, rather than data it was fit to",
      "Make the training process run faster",
      "Reduce the total amount of data needed",
      "Guarantee the model will never make mistakes",
    ],
    correctIndex: 0,
    explanation: "A model evaluated on the same data it was trained on will look artificially good (it can simply memorize that data). A held-out test set gives an unbiased estimate of real-world generalization performance.",
  },
  {
    id: "stats-mcq-cs-17",
    question: "A data analyst notices ice cream sales and traffic to a weather app are strongly correlated. The most statistically sound conclusion is:",
    options: [
      "Correlation alone doesn't establish that one causes the other — both may be driven by a third factor, like hot weather",
      "Ice cream sales must be causing more people to check the weather app",
      "The website traffic must be causing more ice cream sales",
      "The correlation must be a bug in the data pipeline",
    ],
    correctIndex: 0,
    explanation: "\"Correlation is not causation\" — a classic confounding variable (hot weather) can drive both quantities up together without either one causing the other. This distinction matters constantly in data-driven product decisions.",
  },
  {
    id: "stats-mcq-cs-18",
    question: "In queueing theory used for server capacity planning, request arrivals are commonly modelled as a Poisson process. The time between consecutive arrivals then follows:",
    options: ["An Exponential distribution", "A Binomial distribution", "A Normal distribution only", "There is no relationship between the two"],
    correctIndex: 0,
    explanation: "This is a well-known pairing: if the number of arrivals per interval is Poisson, the waiting time between successive arrivals is Exponentially distributed — the discrete-count and continuous-waiting-time views of the very same random process.",
  },
  {
    id: "stats-mcq-cs-19",
    question: "A Bloom filter, a probabilistic data structure used to test set membership space-efficiently, can produce:",
    options: [
      "False positives (saying an item might be in the set when it isn't), but never false negatives",
      "False negatives, but never false positives",
      "Neither false positives nor false negatives, ever",
      "Both, with equal probability, always",
    ],
    correctIndex: 0,
    explanation: "A Bloom filter only ever sets bits, never unsets them, so if an item was actually inserted, its bits are guaranteed to still be set (no false negatives) — but unrelated items can coincidentally have all their bits set too, causing false positives.",
  },
  {
    id: "stats-mcq-cs-20",
    question: "A random forest combines many individual decision trees and averages their predictions. This reduces the model's overall:",
    options: [
      "Variance — averaging many noisy but roughly unbiased predictors smooths out each individual tree's errors",
      "Bias only, never variance",
      "Accuracy",
      "The number of features available",
    ],
    correctIndex: 0,
    explanation: "This is the same statistical fact behind averaging benchmark runs: averaging many independent (or weakly correlated) noisy estimates reduces variance, since the individual errors tend to cancel out.",
  },
  {
    id: "stats-mcq-cs-21",
    question: "If a facial recognition model is trained mostly on photos of one demographic group and performs poorly on others, this is fundamentally a problem of:",
    options: [
      "Sampling bias — the training data isn't representative of the population the model will actually be used on",
      "Insufficient RAM on the training server",
      "A syntax error in the code",
      "The programming language being too slow",
    ],
    correctIndex: 0,
    explanation: "A model can only learn patterns present in its training data. If that sample systematically under-represents part of the real-world population, the model's performance on that group will be unreliable — a statistics problem, not a coding one.",
  },
  {
    id: "stats-mcq-cs-22",
    question: "In an A/B test comparing two website versions, a 95% confidence interval for the difference in conversion rate that does NOT include zero suggests:",
    options: [
      "The observed difference is unlikely to be due to random chance alone, at the 95% confidence level",
      "The two versions are definitely, 100% identical",
      "The test must be re-run with fewer users",
      "Confidence intervals are irrelevant to A/B testing",
    ],
    correctIndex: 0,
    explanation: "If the interval excludes zero, zero (\"no difference\") is not a plausible value at that confidence level — evidence the observed gap likely reflects a real effect, not just sampling noise.",
  },
  {
    id: "stats-mcq-cs-23",
    question: "The Law of Large Numbers explains why running a load-test simulation for a very large number of requests gives a more reliable estimate of average response time than running just a handful:",
    options: [
      "As the number of trials grows, the sample average converges to the true expected value",
      "More trials always take less total time to run",
      "It guarantees zero variance after enough trials",
      "It only applies to Normally distributed data",
    ],
    correctIndex: 0,
    explanation: "The Law of Large Numbers guarantees that as sample size grows, the sample mean converges toward the true population mean — it applies regardless of the underlying distribution's shape, which is exactly why bigger load tests are more trustworthy.",
  },
  {
    id: "stats-mcq-cs-24",
    question: "Calling a function like random.randint(1, 6), which returns each integer 1 through 6 with equal probability, is modelling which distribution?",
    options: ["Discrete uniform distribution", "Poisson distribution", "Normal distribution", "Geometric distribution"],
    correctIndex: 0,
    explanation: "Every outcome in the range is equally likely — the defining property of a discrete uniform distribution, the same model used for a fair die roll.",
  },
  {
    id: "stats-mcq-cs-25",
    question: "If each network packet independently has probability p of successfully getting through, the number of attempts needed until the first success follows:",
    options: ["A Geometric distribution", "A Binomial distribution", "A Poisson distribution", "A Normal distribution"],
    correctIndex: 0,
    explanation: "\"Number of independent trials until the first success\" is precisely the Geometric distribution — the same model used for expected number of hash probes until an empty slot, or retransmissions until a packet gets through.",
  },
  {
    id: "stats-mcq-cs-26",
    question: "Computing the probability that a specific 5-card poker hand is dealt from a standard 52-card deck relies most directly on which topic from this room?",
    options: ["Counting techniques — permutations and combinations, to count both favourable outcomes and the total sample space", "Hypothesis testing", "Regression analysis", "The empirical rule"],
    correctIndex: 0,
    explanation: "This is a classic combinatorics problem: count the number of ways to form the specific hand (favourable outcomes) and divide by C(52,5), the total number of possible 5-card hands — exactly the counting-techniques machinery covered earlier in this room.",
  },
  {
    id: "stats-mcq-cs-27",
    question: "Why do so many aggregated real-world metrics (like the average of many independent measurements) tend to approximate a Normal distribution, even when the individual underlying values don't?",
    options: [
      "The Central Limit Theorem — the distribution of a sum/average of many independent random variables tends toward Normal as the number of variables grows",
      "All data in the real world is inherently Normal to begin with",
      "It only happens for data measured in seconds",
      "It's a coincidence with no theoretical explanation",
    ],
    correctIndex: 0,
    explanation: "The Central Limit Theorem is exactly this guarantee: regardless of the shape of the individual distribution, sums/averages of many independent, identically distributed random variables converge toward a Normal distribution as the sample size grows.",
  },
  {
    id: "stats-mcq-cs-28",
    question: "A cache eviction strategy that estimates each cached item's 'expected future value' before deciding what to evict is directly applying which statistical concept?",
    options: ["Expected value — the probability-weighted average outcome of a random variable", "The mode of a dataset", "The interquartile range", "Bayes' theorem exclusively"],
    correctIndex: 0,
    explanation: "Estimating an item's expected future value (e.g., probability-weighted benefit of keeping it cached) is a direct application of the expected-value concept — using probabilities to weigh uncertain future outcomes into a single decision score.",
  },
  {
    id: "stats-mcq-cs-29",
    question: "A software A/B test produces a p-value of 0.03 for the difference between two button colours' click-through rates. The correct interpretation is:",
    options: [
      "If there were truly no real difference, there'd only be a 3% chance of seeing a difference this large or larger purely by random chance",
      "There is a 97% chance the new button colour is better",
      "The new button colour is definitely better",
      "The p-value tells you the size of the improvement",
    ],
    correctIndex: 0,
    explanation: "A p-value is P(data this extreme or more extreme | null hypothesis is true) — it says nothing directly about the probability the alternative is true, nor about effect size, which is one of the most common misreadings of hypothesis-testing results.",
  },
  {
    id: "stats-mcq-cs-30",
    question: "Machine learning is often described as fundamentally an applied statistics discipline because:",
    options: [
      "Most ML techniques (regression, classification, clustering) are built directly on estimating probability distributions and parameters from data",
      "ML never involves any uncertainty or randomness",
      "Statistics and machine learning share no common concepts",
      "ML models never need any data to be trained",
    ],
    correctIndex: 0,
    explanation: "Linear/logistic regression, Naive Bayes, Gaussian mixture models, and even neural network training (maximum likelihood estimation) all rest on statistical machinery — estimating parameters and distributions from observed data — which is why a strong statistics foundation transfers directly into ML.",
  },
];
